sktime/transformers/compose.py
sktime/transformers/tests/test_compose.py

modified rowwise transformer to try faster apply first before explici…

reworked tsf 

---

sktime/forecasters/base.py
sktime/forecasters/forecasters.py
sktime/forecasters/tests/test_DummyForecaster.py
sktime/forecasters/tests/test_EnsembleForecaster.py
sktime/forecasters/tests/test_forecasters.py
sktime/highlevel/tasks.py
sktime/highlevel/tests/test_tasks.py
sktime/utils/validation/forecasting.py
sktime/utils/validation/tests/test_validation_forecasting.py

Fixes forecasting horizon default arg problem

---

documentation/Makefile
documentation/source/conf.py
documentation/source/examples.rst
documentation/source/examples/experiment_orchestration.ipynb
documentation/source/examples/forecasting.ipynb
documentation/source/examples/loading_data.ipynb
documentation/source/examples/multivariate_time_series_classification.ipynb
documentation/source/examples/plateau_finder.ipynb
documentation/source/examples/shapelet_transform.ipynb
documentation/source/examples/univariate_time_series_classification.ipynb
documentation/update_documentation.sh

* fixed missing example notebooks on website
* added helper function to update symbolic link to example notebooks for online documentation

Updated online documentation

---

examples/experiment_orchestration.ipynb
examples/multivariate_time_series_classification.ipynb
sktime/experiments/data.py

Fixes broken example notebooks
* orchestration
* multivariate time series

fixing examples

---

sktime/classifiers/compose/ensemble.py

* assign params to class, otherwise `clone` won't work

fix for cloning

---

setup.py
sktime/contrib/experiments.py

Resampling

---

documentation/source/installation.rst
sktime/transformers/shapelets.py

Fixes #191 
The fix makes sure that the time limit in the constructor of the `ContractedShapeletTransformer` is set in a way that ensures correct behaviour when cloned by a sklearn class.
This also changes `ShapeletTransfomer`, as the time limit is now in minutes and needs to be handled differently.

Change constructor of ContractedShapeletTransformer to conform with sklearn

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTIONS.md
ESTIMATOR_OVERVIEW.md

* implements new contribution guidelines
* updates PR templates with checklist 
* adds table for overview linking estimators to contributors/maintainers and literature

New contributions guidelines

---

sktime/tests/config.py
sktime/transformers/series_as_features/pca.py

Fixes part of #257: `PCATransformer`
Ensure `PCATransformer` is compatible with `check_estimator()` and include it in standardised unit tests for estimators

Refactor PCATransformer

---

examples/time_series_classification_with_mrseql.ipynb
sktime/classification/shapelet_based/mrseql/mrseql.pyx
sktime/classification/shapelet_based/mrseql/sax_converter.h
sktime/classification/shapelet_based/tests/test_mrseql.py
sktime/tests/config.py

See #257 
Refactor Mr-SEQL to pass all the tests for estimators.
Add multivariate time series support. MrSEQLClassifier can classify multivariate time series now.
Update notebook example.

Refactor mrseql

---

sktime/tests/config.py
sktime/transformers/series_as_features/rocket.py

Fix estimators (#257)
Change self.seed to self.random_state to pass check_constructor and test_estimator.

Change self.seed to self.random_state to pass check_constructor.

---

sktime/classification/compose/_ensemble.py
sktime/regression/compose/_ensemble.py
sktime/series_as_features/base/estimators/__init__.py
sktime/series_as_features/base/estimators/_ensemble.py

Work on #212 
Refactors Time Series Forest Classifier to Regressor and creates a hierarchical structure for Forest-based estimators
1. Check if the utility method `_set_oob_score` will be replaced by a custom implementation.
2. `predict` methods for Regressor and Classifier are different - need to find a way to combine them into BaseEnsemble

added BaseTimeSeriesForest

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Adds GitHub workflow to automatically update release notes from merged PRs.

added release drafter workflow

---

README.rst

The link for the classification notebook was broken on the README :+1: 
[estimator overview](https://github.com/alan-turing-institute/sktime/blob/master/ESTIMATOR_OVERVIEW.md) and I'm
committed to maintain my contribution and provide bug fixes if necessary.

Fix univariate classification notebook link

---

sktime/utils/data_container.py

[estimator overview](https://github.com/alan-turing-institute/sktime/blob/master/ESTIMATOR_OVERVIEW.md) and I'm
committed to maintain my contribution and provide bug fixes if necessary.

typo in the code

---

README.rst

No specific issue. Test first PR
Found a typo with a dead link in README file.
No

README: simple typo correction

---

sktime/classification/distance_based/_time_series_neighbors.py

Fixes #289 
Added a workaround for check_array that is not wrapped with a decorator.
Change the _check_array_ts to accept any other not used arguments and keyword arguments.
Nope
No test added but it passes all test before. Have tried on examples/02_classification_univariate.ipynb with sci-kit learn 0.22.1 and passes the knn fit.

make knn compatible with sci-kit learn below 0.23

---

.github/workflows/assign.yml

Assign an issue to the person who comments "take".
No
Not sure how to test workflow

add github workflow to assign tasks to people commenting 'take'

---

sktime/transformers/series_as_features/tests/test_Truncate.py
sktime/transformers/series_as_features/truncation.py

#6 
Implements the Truncate Transformer
no
This is in response to the list on PR's for beginners,
Thanks for contributing!
-->

Truncate Transformer

---

examples/dictionary_based_classification.ipynb

Uses ItalyPowerDemand dataset with 50 test instances.

Dictionary notebook speed up

---

.all-contributorsrc

https://github.com/all-contributors/all-contributors/issues/362
Changes config `.all-contributorsrc` from CLI usage to bot usage

Fix all-contributor bot config

---

GOVERNANCE.rst
docs/source/installation.rst
examples/dictionary_based_classification.ipynb
examples/interpolation.ipynb
examples/loading_data.ipynb
sktime/benchmarking/evaluation.py
sktime/benchmarking/strategies.py
sktime/benchmarking/tasks.py
sktime/classification/dictionary_based/_tde.py
sktime/classification/dictionary_based/_weasel.py
sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/distance_based/_proximity_forest.py
sktime/classification/frequency_based/_rise.py
sktime/contrib/distance_based/elastic_ensemble_from_file.py
sktime/datasets/base.py
sktime/forecasting/arima.py
sktime/forecasting/base/_sktime.py
sktime/forecasting/compose/_ensemble.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/_stack.py
sktime/forecasting/theta.py
sktime/series_as_features/model_selection/_split.py
sktime/transformers/series_as_features/compose.py
sktime/transformers/series_as_features/dictionary_based/_sax.py
sktime/transformers/series_as_features/interpolate.py
sktime/transformers/series_as_features/segment.py
sktime/transformers/series_as_features/shapelets.py
sktime/transformers/single_series/base.py
sktime/transformers/single_series/detrend/_deseasonalise.py
sktime/transformers/single_series/detrend/_detrend.py

docs: minor spelling tweaks

---

examples/01_forecasting.ipynb
examples/02_classification_univariate.ipynb
examples/03_classification_multivariate.ipynb
examples/feature_extraction_with_tsfresh.ipynb
examples/loading_data.ipynb
examples/shapelet_transform.ipynb

Fixed small typos in ipynb files I noticed when reading through. Otherwise they looked great!
N/A

Fixed typos in example ipynb

---

docs/source/api_reference.rst

Add ForecastingHorizon class to docs

---

azure-pipelines.yml
build_tools/azure/build_wheels.sh

Remove manylinux1

---

docs/source/api_reference.rst
sktime/datasets/base.py

fix in doc string - before was a copy paste error

update basic motion description

---

sktime/benchmarking/data.py

Fixes #484 
Documented multiple classes and methods
No

[DOC] Update docs in benchmarking/data.py

---

docs/source/related_software.rst

Adds scikit-fda to the list of related software.
scikit-fda is a package to perform Functional Data Analysis (FDA). Real valued time series can be considered as univariate functions, and can benefit from FDA methods in some tasks, such as clustering or classification. Thus, I think this package could be useful also for the time series community.
Some of the methods available are:
- Classes for representing functions, either discreticed in a grid/set of times or in a basis expansion (Fourier, BSplines...)
- Preprocessing methods: smoothing, registration (alignment of curves) and dimensionality reduction (such as FPCA)
- Exploratory analysis: visualization tools (functional boxplot, magnitude-shape plot), outlier detection, depth functions...
- Functional ANOVA
- Machine learning tools: …

Add scikit-fda to the list of related software

---

sktime/forecasting/base/_adapters.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/hcrystalball.py
sktime/forecasting/model_selection/_split.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/model_selection/tests/test_split.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/forecasting/tests/test_naive.py
sktime/forecasting/theta.py
sktime/forecasting/trend.py
sktime/transformers/series/detrend/_deseasonalize.py
sktime/utils/_testing/__init__.py
sktime/utils/_testing/forecasting.py
sktime/utils/validation/forecasting.py

Add tests for forecasting with exogenous variables

---

.all-contributorsrc
sktime/forecasting/model_selection/_split.py

Example: Fixes #516
Fixed default argument in docstring
No
Simple change, should not require detailed review

Fixed default argument in docstring in SlidingWindowSplitter

---

examples/02_classification_univariate.ipynb

Fixes #605 
To fix the ModuleNotFoundError.
I guess this `.ipynb` hasn't been updated for a long time, so the function `RandomIntervalSpectralForest` has been moved from `frequency_based`(this module is deleted) to `interval_based `, but nobody found.
None
Whether or not it can generate the correct result. I have already tested it so no worries.
This is a bug fix, so I guess the following PR checklist's most content is not applicable.

[MRG] fix sktime.classification.frequency_based not found error

---

examples/shapelet_transform.ipynb

Fixes #611.
Instead of such fine-grained import, we can avoid this issue by a little more coarse-grained import.
None
Nothing
None

bugfix: fix ModuleNotFoundError issue

---

CODEOWNERS
docs/source/api_reference/transformations.rst
sktime/tests/_config.py
sktime/transformations/series/impute.py

#69 #603 
Transformation of `pd.Series` to impute missing values (`np.nan`) with different imputation strategies.
No
The imputation with `method="drift"` might be renamed to `"trend"`, however I adopted this naming from `sktime.NaiveForecaster`, so maybe we can rename it there also?
1. I might implement further imputation  strategies, if s.o. has more ideas of other methods. 
2. I might also add an example to the notebook. 
3. What about imputation of `pd.DataFrame`, should this also be considered?
Example:
```python
from sktime.datasets import load_airline
from sktime.transformations.series.impute import Imputer
y[0] = np.nan
y[4] = np.nan
y[5] = np.nan
y[8] = np.nan
imputer = Imputer(method="drift")
imputer.fit_transform(y)
imputer = Imputer(method="forecaster", …
```

Added Imputer for missing values

---

sktime/transformations/panel/dictionary_based/_sfa.py

Partially fixes Bug #640
Removes Numba-signatures to add compatibility for PLAID, ASCF1, etc datasets with variable-length data

Address Bug #640

---

.all-contributorsrc
docs/source/api_reference/forecasting.rst
sktime/forecasting/all/__init__.py
sktime/forecasting/model_selection/__init__.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/model_selection/tests/test_tune.py
sktime/forecasting/tests/_config.py
sktime/tests/_config.py

Feature #597
Implements a randomized search equivalent of the fixed grid search option (similar to what is present in scikit-learn)
No new dependencies
Any and all feedback is welcome - this is my first pull request :)

Feature ForecastingRandomizedSearchCV

---

sktime/forecasting/model_selection/tests/test_tune.py

Something went wrong with merging #635 - I might have merged without syncing with master. Fixing the broken reference here.

Fix reduced regression forecaster reference

---

sktime/datasets/tsc_dataset_names.py

update dataset names

---

sktime/classification/distance_based/tests/test_time_series_neighbors.py

quick fix for error in unit test for MSM

remove MSM from unit tests for now

---

sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/distance_based/_time_series_neighbors.py

Fixed bug mentioned in #694 for Elastic Ensemble. Also fixed other bugs caused by recent changes to KNN classifiers.
Removed the double transposing issue, and removed coercion to pandas for ElasticEnsemble. Also removed algorithm parameter from classifiers used in cross validation parameter searches, and fixed some naming issues regarding usage of the term distance rather than metric.
No
Checking if I accidentally missed anything
Ive compared the current elastic ensemble implementation to that from tsml for a few datasets and found they matched, but there may still be some issues regarding distance parameters being set through cross validation.

Fixed bugs mentioned in #694 

---

sktime/classification/distance_based/tests/test_time_series_neighbors.py
sktime/distances/elastic.py
sktime/distances/elastic_cython.pyx
sktime/distances/mpdist.py

unit tests on ArrowHead for 1-NN classifier with euclidean, dtw, wdtw, msm and erp

Knn unit tests

---

sktime/forecasting/base/adapters/_fbprophet.py

Fixes #696 
Use .loc as suggested in the warning and by @muhlbach so that warning is no longer raised.
No
This is my first time creating a pull request so I hope I've done everything correctly.

SettingWithCopyWarning in Prophet with exogenous data

---

sktime/transformations/series/detrend/_deseasonalize.py

Fixes https://github.com/alan-turing-institute/sktime/issues/539

Fix Deseasonalizer docstring

---

.appveyor.yml
build_tools/requirements.txt

Fixes PyStan version to fix failing builds.

Pin PyStan version

---

docs/source/api_reference/regression.rst
sktime/classification/interval_based/_tsf.py
sktime/regression/all/__init__.py
sktime/regression/interval_based/__init__.py
sktime/regression/interval_based/_tsf.py
sktime/series_as_features/base/estimators/interval_based/__init__.py
sktime/series_as_features/base/estimators/interval_based/_tsf.py

#693
`TimeSeriesForestRegressor` wasn't added to a public file and hence tests didn't run. That was my oversight.

Fix TimeSeriesForestRegressor

---

sktime/forecasting/compose/_ensemble.py

fixes the issue #583
The agg argument adds aggregate options for ensembling forecasters.
No
The changes on the __init__ of the EnsembleForecaster and it predict method.

Added the agg argument to EnsembleForecaster

---

sktime/forecasting/arima.py
sktime/forecasting/bats.py
sktime/forecasting/ets.py
sktime/forecasting/exp_smoothing.py
sktime/forecasting/fbprophet.py
sktime/forecasting/naive.py
sktime/forecasting/tbats.py
sktime/forecasting/theta.py
sktime/forecasting/trend.py

Added some docstring examples for the forecasting module
___

Added forecasting docstring examples

---

.pre-commit-config.yaml

Hey @mloning - hope you're well!
Am just upgrading the nbqa version here, are there's been a number of fixes/improvements recently
As an aside, I'd suggest using [pre-commit-ci](https://pre-commit.ci/), which autoupdates all hooks each week!

Upgrade nbqa

---

sktime/transformations/panel/rocket/_rocket.py

Remove soft dependency check for numba

---

.binder/requirements.txt
build_tools/hard_dependencies.txt
build_tools/requirements.txt
setup.py
sktime/contrib/distance_based/elastic_ensemble_from_file.py

Update sklearn version

---

.gitattributes
sktime/forecasting/compose/tests/test_reduce.py

resolves #809
* Update config in `.gitattributes` for Github Linguist to conduct language discovery more appropriately

Fix counting for Github's automatic language discovery

---

.binder/requirements.txt
build_tools/requirements.txt
setup.py

Fix import error from `pmdarima==1.8.1`, see here:
https://github.com/alkaline-ml/pmdarima/issues/423
Hotfix should be reverted once there is a new release of `pmdarima`.
___

Hotfix pmdarima version

---

.pre-commit-config.yaml
build_tools/check_install_from_test_pypi.sh

* updates pre-commit versions
* minor changes

Update maintenance tools

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/model_selection/_tune.py
sktime/transformations/series/acf.py
sktime/transformations/series/adapt.py
sktime/transformations/series/boxcox.py
sktime/transformations/series/cos.py
sktime/transformations/series/detrend/_deseasonalize.py
sktime/transformations/series/detrend/_detrend.py
sktime/transformations/series/impute.py
sktime/transformations/series/matrix_profile.py
sktime/transformations/series/outlier_detection.py
sktime/transformations/series/summarize.py

Added several docstring examples
___

Added several docstring examples

---

sktime/transformations/series/impute.py
sktime/transformations/series/outlier_detection.py

Added `pd.DataFrame` transformation for `Imputer` and `HampelFilter`.
___

Added pd.DataFrame transformation for Imputer and HampelFilter

---

sktime/forecasting/compose/tests/test_reduce.py

Fixes import error after merging #779 and #801

Fix smape import

---

sktime/datasets/base.py

Fixes #881 
Adds a link to where the datasets can be found.
No.

update docs on loading data

---

azure-pipelines.yml
build_tools/azure/build_manylinux_wheels.yml
build_tools/azure/build_wheels.sh

#196 
* excludes failing PyPy version 
* changes specification from excluding versions to including them

Fix manylinux CI

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py
sktime/tests/_config.py
sktime/utils/_testing/estimator_checks.py

Suggested changes to PR 912

---

sktime/forecasting/base/adapters/_tbats.py

Refactors TbatAdapter

---

CONTRIBUTING.md

This fixes a broken link related to soft dependencies in the documentation.

fixing soft dependencies link

---

sktime/clustering/_k_means.py
sktime/clustering/_k_medoids.py
sktime/clustering/base/__init__.py
sktime/clustering/base/base.py
sktime/clustering/evaluation/_plot_clustering.py
sktime/clustering/partitioning/_lloyds_partitioning.py
sktime/clustering/tests/_clustering_tests.py
sktime/tests/_config.py
sktime/utils/_testing/estimator_checks.py

Addresses #1065
Changes to the BaseCluster class suggested by @fkiraly 
No
sktime/clustering/base/base.py file is where the changes are rest are just refactors updating imports.

BaseCluster class issues resolved

---

sktime/transformations/series/impute.py
sktime/transformations/series/outlier_detection.py

Fix side effect on input for Imputer and HampelFilter

---

extension_templates/clustering.py
sktime/clustering/base/base.py

@chrisholder, for clustering:
* I've cleaned up the docstrings in the base class
* I've added an extension template
I also noticed that you didn't have a `get_fitted_params` in the base class, I added that.

Clustering extension templates, docstrings & get_fitted_params

---

sktime/forecasting/model_selection/_tune.py

Suggestions for PR #1088

---

sktime/forecasting/compose/_pipeline.py

#967 
* Fixes import error from merging into main without first updating from main

Fix ForecastingPipeline import

---

build_tools/check_install_from_test_pypi.sh
build_tools/make_release.py

#1131 
* fixes typos
* push single tag instead of all tags

Update release script

---

docs/source/roadmap.rst

Updates the roadmap based on the discussion from the 2021 sktime dev days.

Add roadmap 

---

setup.cfg

* fixes an error in the pydocstyle config

Fix pydocstyle config

---

sktime/classification/distance_based/_time_series_neighbors.py

Partial fix of issue #1148.
In the docstring of `KNeighborsTimeSeriesClassifier`: added example and modified description of `weights` in `Parameters`.

adding example in docstring of KNeighborsTimeSeriesClassifier

---

docs/source/_static/js/dynamic_table.js
docs/source/conf.py
docs/source/estimator_overview.rst

Hello from SciPy 2021 sprints! 👋🏽 Continuation of #1138, gets the filtering working both locally and on Read the Docs 🎉  Thanks @mloning for the guidance!

Add JavaScript and HTML to filter estimator overview

---

.all-contributorsrc
sktime/classification/dictionary_based/_boss.py
sktime/classification/dictionary_based/_cboss.py
sktime/classification/dictionary_based/_muse.py
sktime/classification/dictionary_based/_tde.py
sktime/classification/dictionary_based/_weasel.py

Fixes partially  #932, #1147.
Added examples in docstrings in `classification/dictionary_based`.
For some examples the `pytest` was a bit slow on my machine (took 54 seconds to test `_weasel.py`). Is that ok?
Let me known if the current PR is ok before merging. Then I can add more examples for the other classifiers by next Saturday.

add examples in docstrings in classification

---

.github/FUNDING.yml
README.md

* adds funding button to repo page with links to my user page and sktime's Open Collective page 
* adds link to Open Collective in readme

Add funding

---

docs/source/api_reference.rst
docs/source/api_reference/annotation.rst

#1021 
* adds PyODSeriesAnnotator to docs

Add annotation to docs

---

setup.py
sktime/setup.py

Demonstrates setup fails the tests

Format setup files

---

README.md

This PR adds a binder link to the readme (landing page).
Thanks to @corvusrabus for fixing our binder!

adding binder link to readme (landing page)

---

docs/source/developer_guide/documentation.rst
docs/source/reviewer_guide.rst

#1245
This includes content in the developer guide's documentation section (and a tweak to the reviewer guide) to clarify our docstring expectations ahead of the docsprint.
No.
Is there anything you don't agree with in the documentation guide? 
Should we expect reviewers to ensure documentation meets our standards (I think we need to in order to ensure quality of sktime documentation post docsprint)

Add content to documentation guide for use in docsprint

---

docs/source/api_reference/transformations.rst

Typo in transformations.rst fixed

---

sktime/transformations/series/cos.py

Added link to numpy cosine description 
#

Description and link to cosine added

---

docs/source/glossary.rst
sktime/transformations/series/adapt.py
sktime/transformations/series/compose.py

References #1245.
Updates the docstrings for `TabularToSeriesAdaptor` and `ColumnwiseTransformer` to satisfy the documentation requirements.
No
Are there other sections that can be added?

Update ColumnwiseTransformer and TabularToSeriesAdaptor docstrings

---

sktime/transformations/series/theta.py

References #1245.
Updates the docstring for it to satisfy the documentation requirements.
No
Are there other sections that can be added?

Update ThetaLinesTransformer's docstring

---

.all-contributorsrc
sktime/registry/_lookup.py

Did not open an issue for this.
sktime.registry.all_estimators() crashes if the user does not have all the extra modules installed.
This change instead outputs warnings for them, allowing the user to continue.
No.
This is intended to be a clear, simple, quick-to-merge contribution that makes the code easier
to use.  Please let me know if that is not the case.
- n/a Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- n/a I've added unit tests and made sure they pass locally.
- n/a I've added the estimator to the online documentation.
- n/a I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

Fix all_estimators when extras are missing.

---

.codecov.yml

Excludes some files from code coverage metrics.

[MNT] Update codecov config

---

docs/source/get_involved/contributing.rst

[DOC] Correct typo in contributing guidelines

---

docs/source/governance.rst

https://github.com/sktime/community-org/pull/18
* changes link to new repo

[DOC] Fix community repo link

---

CONTRIBUTING.md

Example: Fixes #1427 
The link in CONTRIBUTING.md has been updated to the correct link.
No

updated the link in CONTRIBUTING.md

---

README.md
docs/source/changelog.rst
docs/source/get_started.rst
sktime/__init__.py

Release v0.8.0

---

CONTRIBUTING.md
README.md

Fixes #1427 
Related #1428
Updated the link for "contribute" in README.md
No

Update doc link

---

.all-contributorsrc
sktime/annotation/base/_base.py
sktime/base/_base.py
sktime/base/tests/test_base.py
sktime/classification/base.py
sktime/datatypes/_check.py
sktime/datatypes/_convert.py
sktime/datatypes/_examples.py
sktime/datatypes/_registry.py
sktime/dists_kernels/_base.py
sktime/forecasting/base/_base.py
sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/tests/test_column_ensemble.py
sktime/forecasting/compose/tests/test_ensemble.py
sktime/registry/_lookup.py
sktime/transformations/series/tests/test_theta.py
sktime/transformations/series/theta.py

Fixes #1433.
Moved any copyrights inside a docstring to a comment above.
N/A
N/A
N/A

Remove license info from docstrings

---

docs/source/about/showcase.rst

Add DataChef.co blog post
No
Not so much to feedback :)
Thanks

[DOC] Add DataChef blog post to community showcase

---

.all-contributorsrc
docs/source/about/showcase.rst
sktime/datasets/_data_io.py

Fixes #1466
Added missing extract_path in line 178 in sktime/datasets/_data_io.py to fix the bug

fixed missing extract_path

---

sktime/classification/feature_based/_tsfresh_classifier.py

Partially handles #1146. TSC refactoring for `tsfreshclassifier`
- Made public methods into private
- Changed the name of the capabilities dictionary to _tags.
- Removed the checks from the private version
- Checked that all tags already were already in the _tag registry
No
Please look at the changes and let me know if I should make any other edits.
No

Refactors tsfresh classifier

---

docs/source/_static/css/custom.css
docs/source/_templates/layout.html
docs/source/conf.py
docs/source/get_started.rst

#1565 
It adds  a layout.html template to extend the pydata-sphinx-theme when building our docs. We need to run a javascript script after the content of pages is loaded. This script will identify example code blocks (e.g. blocks with python highlighting) and add a toggle button so we can turn on/off the text that makes the examples difficult to copy (e.g. >>>, ...,  example output, etc). 
It also adds css styling for the new button. Changes to the conf.py should just be to add the css styling file.

Add toggle button to make examples easy to copy

---

sktime/performance_metrics/base/_base.py
sktime/performance_metrics/forecasting/_classes.py

Fixes #1422
Stores the `func` param in the `func` attribute instead of the `_func` attribute. This ensure compliance with underlying expectation of sktime's `BaseObject`
None.

Fix Performance metric bug that affects repr

---

docs/source/api_reference/forecasting.rst
docs/source/api_reference/transformations.rst
sktime/transformations/series/difference.py

Add missing classes to API reference

---

sktime/transformations/panel/signature_based/_signature_method.py

Removes unused _assertions method in signatures module.

Fixes #1234

---

.all-contributorsrc
sktime/forecasting/ets.py

Fixes #1387
If a time series is not strictly positive, ETS models with multiplicative components will raise the error. I've add conditions to omit multiplicative models for not strictly positive models.
No

Ets strictly pos mul models

---

sktime/classification/base.py

Updated the types in the classification base class for np.array to the type np.ndarray (np.array is a method np.ndarray is the type of a numpy array).

Updated classification base class typing.

---

sktime/series_as_features/compose/_pipeline.py

Fixes #1662
Failing test for `FeatureUnion`
nope

Fix `FeatureUnion` test failure

---

examples/loading_data.ipynb

What I got from the explanation,
The sparse vector
2,5,?,?,?,?,?,5,?,?,?,?,4
Should be wrote as
(0,2),(*1*,5),(7,5),(12,4)
not as 
(0,2),(*0*,5),(7,5),(12,4)

Misstyping

---

sktime/forecasting/model_evaluation/_functions.py

Related to #1614
Added clone for the refit case and for the first iteration of the update case.

Add clone in evaluate

---

sktime/transformations/series/impute.py
sktime/transformations/series/tests/test_imputer.py

Fix Imputer. Added Imputer tests

---

sktime/transformations/series/compose.py

* fix example of ColumnwiseTransformer

Fix ColumnwiseTransformer example

---

sktime/forecasting/model_evaluation/_functions.py

Fixes https://github.com/alan-turing-institute/sktime/issues/1194
* replaces `time.time` with `time.perf_counter`

Replace time.time with time.perf_counter

---

README.md

Fixes https://github.com/alan-turing-institute/sktime/issues/1430

Add links to estimator overview to README

---

examples/AA_datatypes_and_datasets.ipynb
sktime/alignment/utils/utils_align.py
sktime/datatypes/__init__.py
sktime/datatypes/_check.py
sktime/datatypes/_series_as_panel/_convert.py
sktime/datatypes/tests/test_check.py
sktime/transformations/base.py

Rename check_is to check_is_mtype

---

docs/source/about/team.rst

Updating docs after Slack announcement.

Remove myself from CC and CoC committee

---

sktime/tests/_config.py
sktime/tests/test_all_estimators.py

- replace legacy `check_` with `test_` in test configuration
- exclude `test_fit_does_not_overwrite_hyper_params` for `FeatureUnion`
- small refactoring of the tests
No.
Check if all the test are running.

[MNT] Refactor legacy test config

---

examples/catch22.ipynb

fixes #1783 
Correct the method name call that was causing an error.

Correct the `examples/catch22.ipynb` call to `transform_single_feature`

---

CODEOWNERS

This PR updates overall codeowners to @aiwalter, @fkiraly, @TonyBagnall (current CC mebmers)

[MNT] updated codeowners

---

build_tools/run_examples.sh

Update the bash script parameters to fail when one of the subcommands fails.

Correct the bash error propagation for running notebook examples

---

docs/source/about/team.rst

Add lmmentel to the team page :tada: 

---

sktime/contrib/data_io.py
sktime/contrib/tests/test_data_io.py

moved the polymorphic data loader to contrib due to reviewer objections to its presence in main

polymorphic data loader in contrib

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/forecasting/tests/test_theta.py
sktime/forecasting/theta.py

Related to https://github.com/alan-turing-institute/sktime/issues/984
Implements a function to test predict_quantiles
No
Implemented these checks:
Modified extension docs to account for base forecasters class:
Changes in the Theta classifier:

Implement predict_quantiles and predict_intervals in theta forecasters, tests in base class

---

sktime/datasets/_data_io.py

fixes a bug in _load_provided_datasets when concatenating the target variable y.

fix error when concatenating train and test

---

docs/source/api_reference/forecasting.rst

Added VAR to API docs

---

sktime/transformations/series/scaledlogit.py
sktime/transformations/series/tests/test_scaledlogit.py

Added `get_test_params` method for `ScaledLogitTransformer` with parameter combinations that cover all cases.

Scaled logit test params

---

docs/source/installation.rst

Fix wrong instructions for `conda` command line usage.

[DOC] Fix wrong conda command to install packages.

---

sktime/datasets/data/UnitTest/UnitTest_Tsf_Loader.tsf

Related to https://github.com/alan-turing-institute/sktime/issues/1933
Added a .tsf dataset for unit testing.

[ENH] Added tsf dataset for unit testing

---

sktime/classification/dictionary_based/_tde.py
sktime/classification/interval_based/_drcif.py
sktime/classification/kernel_based/_arsenal.py
sktime/contrib/vector_classifiers/_rotation_forest.py

Reverts alan-turing-institute/sktime#2020
See #2020 for a discussion.
This is aimed at restoring a situation on main where tests pass.

Revert "HC2 component bugfixes"

---

README.md

Removed gitter from README

---

.all-contributorsrc
docs/source/developer_guide/continuous_integration.rst
sktime/series_as_features/model_selection/_split.py
sktime/tests/test_all_estimators.py

I didn't create a new issue because the changes are minor :)
- The docstring of `SingleSplit.split()` had a missing description and a missing "-". 
- The docstring of `SingleSplit.get_n_splits()` was missing.
- The spaces in the table in `continuous_integration.rst` were weirdly placed.
Before:
Now: 
Before:
Now:
No
I have modified/added a couple of docstrings. I'd be happy to change them if someone could let me know what the method exactly does.
--

Fix minor documentation issues

---

sktime/datatypes/_alignment/_check.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_series/_check.py
sktime/datatypes/_table/_check.py

Tries to fix Issues #1817 
The pull request changes the names of the functions in datatypes to `lower_snake_case.`
No it doesn't.
Please check whether the deprecation has been done properly. If there are any changes needed to be done for the same.
--

[ENH] Changing function names in datatypes check to lower_snake_case

---

sktime/forecasting/base/_fh.py

https://github.com/alan-turing-institute/sktime/issues/2038
Added TODO item regarding pandas bug and the corresponding workaround.

Add TODO about pandas bug

---

.github/release-drafter.yml

[MNT] Update release drafter

---

.github/release-drafter.yml

Reverts alan-turing-institute/sktime#2096
Auto-generation seems not to work, reverting

Revert "[MNT] Update release drafter"

---

.github/release-drafter.yml

Reverts alan-turing-institute/sktime#2098

Revert "Revert "[MNT] Update release drafter""

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release 0.10.1

---

CODE_OF_CONDUCT.md

Hi, this is a great project. I just wanted to fix the CoC link that appears in GitHub which currently is broken to point to the current CoC link on your website. This is a minor change.
No new dependencies. This is a minor documentation change only.
Can you please check that the CoC link is correct? Thanks!
I've crossed out the checklist b/c they don't seem to apply, okay? Also if alright, I'm fine with anonymously making this PR, so no need to add to CONTRIBUTORS. Thanks!
_DISCLAIMER: I am part of the NF APSC_

[DOC] fix broken link to CoC

---

sktime/classification/compose/_column_ensemble.py
sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/distance_based/tests/test_elastic_ensemble.py

testing time creeping up again, this will speed up EE tests and examples by giving minimal config

speed up EE tests and ColumnEnsemble example

---

sktime/classification/kernel_based/_rocket_classifier.py
sktime/tests/_config.py

[ENH] test parameter refactor: `RocketClassifier`

---

sktime/transformations/panel/rocket/tests/test_MiniRocket.py
sktime/transformations/panel/rocket/tests/test_MiniRocketMultivariate.py
sktime/transformations/panel/rocket/tests/test_MultiRocket.py
sktime/transformations/panel/rocket/tests/test_MultiRocketMultivariate.py
sktime/transformations/panel/rocket/tests/test_Rocket.py

Normalize' will be removed in the version 1.2 release
of sklearn. Adding Pipeline with a StandardScaler as
a preprocessing stage.
Fixes half of [#2143](https://github.com/alan-turing-institute/sktime/issues/2143)
Normalize' will be removed in the version 1.2 release
of sklearn. Adding Pipeline with a StandardScaler as
a preprocessing stage.
Clarity of git commit message

Replacing normalize by use of StandardScaler

---

.readthedocs.yml
docs/source/developer_guide/documentation.rst
sktime/forecasting/fbprophet.py

Fixes #2013
There are missing docs due to missing soft-dependency installation when building docs. So readthedocs was not able to build the docs for all classes that are based on soft-dependencies.

[DOC] Fix minor doc issues

---

sktime/utils/_testing/hierarchical.py

Fixes #2195 issue
"_make_hierachical" is renamed to "_make_hierarchical" to avoid typo, it is renamed after the name of the file "hierarchical.py"
No new dependency is introduced
Just the name of the function

_make_hierachical is renamed to _make_hierarchical (typo/bug) issue #2195

---

docs/source/get_started.rst
sktime/utils/_testing/hierarchical.py

Not related to any fixe/issue, just updating the environments for python versions (sktime), added 3.9
just updating compatible python versions for sktime
No dependency is introduced
cross-check that sktime works with python 3.9

updated the environments with python version for sktime, added python 3.9

---

sktime/transformations/series/func_transform.py

Minimal change: changes signature of `FunctionTransformer._fit` from `_fit(Z, y)` to `_fit(X, y)`

[ENH] changed `FunctionTransformer._fit` to common signature

---

docs/source/get_involved/contributing.rst

This PR updates `contributing.rst` with the concrete first steps from pinned issue #1147.

[DOC] contributing page: concrete initial steps

---

docs/source/about/team.rst

Adding myself to the core developers list!

adding ltsaprounis to core developer list

---

sktime/classification/tests/test_sklearn_compatability.py

fixes #2240 by simply commenting out the test for  StratifiedGroupKFold, we can put it back when sktime updates to latest scikit learn.

[BUG] remove test for StratifiedGroupKFold

---

docs/source/developer_guide/coding_standards.rst

Fixes #2280 by adding the pre-commit link
Grammatical Update to the Coding Style docs

Updated pre-commit link and also grammatically updated Coding Style docs

---

docs/source/api_reference/forecasting.rst
examples/01_forecasting.ipynb
sktime/forecasting/statsforecast.py

#2251
The PR renames AutoARIMA from StatsForecast to StatsForecastAutoARIMA. 
No.

[ENH] Rename AutoARIMA from StatsForecast to StatsForecastAutoARIMA

---

docs/source/developer_guide/testing_framework.rst

Fixes  #2283
fixed the bullet issue.
hopefully it'll work, otherwise if any changes required let me know.

fixed the issue with 'docs/source/developer_guide/testing_framework.rst'

---

sktime/forecasting/base/_base.py

This PR enables automatic vectorization for probabilistic forecasting methods that return `pd.DataFrame`, i.e., `predict_interval`, `predict_quantiles`, and `predict_var`.
This makes the (non-tensorflow) probabilistic forecasting interface compatible with the hierarchical forecasting interface, allowing to use them jointly.

[ENH] vectorization for probabilistic forecasting methods that return `pd.DataFrame`

---

sktime/contrib/datasets/_single_problem_loaders.py
sktime/datasets/_single_problem_loaders.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_proba/_check.py
sktime/datatypes/_series/_check.py
sktime/forecasting/base/tests/test_fh.py
sktime/utils/tests/test_plotting.py
sktime/utils/validation/series.py

Closes https://github.com/alan-turing-institute/sktime/issues/2332
- Replace `pd.Int64Index` with `pd.Index(..., dtype=int)`
- Remove unused objects like `VALID_INDEX_TYPES` and `VALID_MULTIINDEX_TYPES`
No

[ENH] Get rid of `pd.Int64Index`

---

sktime/forecasting/model_selection/_tune.py

This PR fixes a bug in the grid search estimators, which prevented from calling probabilistic prediction methods directly on the composite.
The bug is resolved by simply patching through all the methods using the existing delegator decorator.

[BUG] fixing proba predict methods of forecasting tuning estimators

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release v0.11.2

---

docs/source/installation.rst

Fixes #2365
This fix resolved the `Error: Invalid requirement: 'dev]'` I got while running the installation on the command line 
No
None
Okay

[DOC] fix typo in sktime install instructions, causes "invalid requirement error" if followed verbatim

---

sktime/classification/tests/test_all_classifiers.py
sktime/classification/tests/test_base.py
sktime/datasets/tests/test_data_processing.py
sktime/forecasting/base/tests/test_base.py
sktime/utils/_testing/panel.py
sktime/utils/_testing/tests/test_panel.py

Reverts alan-turing-institute/sktime#2508

Revert "[ENH] Tests for multiple classifier input mtypes"

---

docs/source/events/gsoc_2022.md
docs/source/index.rst

Fixes #2510.
Delete the GSoC announcement from the landing page.
No.

[DOC] fix: delete gsoc announcement from landing page

---

sktime/forecasting/theta.py

Partial revert of #2529, fixing inheritance issue which led to nonsensical prediction intervals

[BUG] fix problem in ThetaForecaster proba prediction introduced by #2529

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Changelog and version bump.
@lmmentel, kindly review.

Release v0.11.3

---

sktime/distances/_twe.py

TWE distance was running slow for large datasets due to an implementation of a numpy function in numba running slow. This pr removes those numpy functions and uses raw python to get performance desired.

[BUG] Twe distance running slow due to numpy and numba interaction

---

sktime/transformations/series/boxcox.py

Fixes a typo in the author variable of the boxcox module.

[BUG] fix typo in author variable for boxcox module

---

sktime/forecasting/model_selection/_split.py

Minor fixes in class description 'ExpandingWindowSplitter'. No code changes.
No
- [ x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

[DOC] Fixes in class description ExpandingWindowSplitter

---

docs/source/get_involved/contributing.rst
docs/source/get_involved/mentoring.rst

This pull request seeks to resolve broken links for both the Developer Guide and Mentorship Program under the "How to Contribute" page. It also fixes the broken Code of Conduct link under the "Mentorship Program" page.

[DOC] Fixed A Few Links on the Website

---

sktime/forecasting/tests/test_all_forecasters.py
sktime/utils/_testing/forecasting.py

fixes #2700
Replaced `SlidingWindowSplitter` with `ExpandingWindowSlicer` as described in #2700 and made the appropriate changes in the corresponding util function.

[ENH] test_update_predict _predicted_index continuous data

---

sktime/transformations/series/adapt.py
sktime/transformations/series/tests/test_adapt.py

This PR adds a transformer adaptor for `pandas` native methods.
This exposes applications of pandas methods as an `sktime` transformer.

[ENH] transformer adaptor for `pandas` native methods

---

.github/PULL_REQUEST_TEMPLATE.md

[MNT] Add [MNT] tag to PR template

---

docs/source/about/team.rst

[DOC] Add `khrapovs` to core devs

---

sktime/regression/distance_based/_time_series_neighbors.py

Part of a fix for #2733, for `KNeighborsRegressor`.

[BUG] fixing constructor non-compliance with sklearn: `KNeighborsRegressor`

---

sktime/transformations/panel/pca.py

Part of a fix for #2733, for `PCATransformer`.

[BUG] fixing constructor non-compliance with sklearn: `PCATransformer`

---

GOVERNANCE.md

Fix a broken link
(I didn't add myself to contributors as it is such a minor change)

[DOC] Fix link to governance website page

---

sktime/forecasting/conformal.py
sktime/forecasting/naive.py
sktime/forecasting/tests/test_interval_wrappers.py

Alternative fix for #2814, implements "alternative" option discussed in #2814 = option 2 in #2767
See linked PR for details
No

[BUG] Fixing type conversion for proba interval wrappers - option 2, convert for computing residuals logic

---

docs/source/about/team.rst
sktime/benchmarking/strategies.py

@sajaysurya was missing as a former core dev.
Also replaces instances where his name was in the author field and not the GitHub ID.
Also lints the files where he appears.

[DOC] add missing Sajay references

---

.gitignore
docs/source/installation.rst

Adds to the documentation according to #2770 
Added the solution to the troubleshoot section of ```installation.rst```.

[DOC] adds solution to "no matches found" to troubleshoot section of install guide

---

sktime/transformations/tests/test_multiplexer.py

- Replace `pd.np.nan` with `np.nan`
- Add `numeric_only=True` to `.mean()`

[MNT] Address future warnings

---

sktime/transformations/series/theta.py

flake8 pre commit check: "B020 Found for loop that reassigns the iterable it is iterating with each iterable value"

[MNT] Fix loop reassignment

---

docs/source/related_software.rst

[DOC] Added diviner by Databricks and statsforecast by Nixtla to related software

---

.all-contributorsrc
sktime/forecasting/naive.py

Added missing/incorrect credits in the `naive.py` module's `__authors__` variable:
* `Piyush Gade` was changed to GitHub id @Piyush1729, full name moved to `all-contributorsrc`
* @bethrice44 added, for work on `NaiveVariance`
* @sri1419 added, for work on the `drift` strategy

[DOC] added missing credits in `naive.py`

---

sktime/classification/deep_learning/cnn.py

minor typo in cnn model (fix verbose mode)

[BUG] fix bug in verbose mode in CNN TSC models

---

sktime/_contrib/set_classifier.py
sktime/classification/ds/__init__.py
sktime/classification/ds/_ds_pipeline.py
sktime/transformations/panel/cs.py

Adding Elbow class pairwise methods to branch elbow_class_pairwise

---

.all-contributorsrc
docs/source/related_software.rst
sktime/forecasting/reconcile.py
sktime/forecasting/tests/test_reconcile.py
sktime/transformations/base.py
sktime/transformations/tests/test_all_transformers.py
sktime/transformations/tests/test_base.py
sktime/utils/_testing/scenarios_transformers.py

Reverts alan-turing-institute/sktime#2867
Accidentally deleted reconcilers, emergency revert

Revert "[ENH] auto-vectorization over columns for univariate estimators - transformers"

---

sktime/classification/compose/_ensemble.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/tests/test_reduce.py
sktime/regression/compose/_ensemble.py
sktime/transformations/panel/tsfresh.py

This PR replaces @AyushmaanSeth's name with his GitHub ID in the authors' fields.

[DOC] replace AyushmaanSeth name with GitHub ID

---

sktime/forecasting/model_selection/_tune.py

This PR attempts to fix grid/random search issues in #2943, #2944.
A refactor is carried out that replaces manual delegation with `_DelegatedForecaster` inheritance.
The problem was likely coming from patching through underscore methods `_fit` etc rather than non-underscore methods such as  `_DelegatedForecaster`.
Adds the failure cases from #2943, #2944 for testing.

[BUG] fixing grid/random search broken delegation

---

.github/workflows/wheels.yml

Updates wheels to 3.10, adds verson 3.10 to wheels matrix

[MNT] update wheels to 3.10

---

.github/workflows/wheels.yml

Fixes merge accident in `wheels.yml`

[MNT] fix merge accident in wheels.yml

---

docs/source/about/team.rst

remove Tony from code of conduct

[DOC] remove Tony Bagnall from code of conduct committee

---

examples/02a_classification_multivariate_cnn.ipynb

Adds the corresponding jupyter notebook with minor changes to work within sktime.
Don't know if you have plans to port everything from sktime-dl one-by-one or in a single big effort.
In the latter case, please just discard my PR.

[ENH] Add multivariate CNN example (from sktime-dl)

---

sktime/forecasting/compose/_reduce.py

Added docstring example for `make_reduction`

[ENH] Added docstring example for make_reduction

---

.github/workflows/test.yml

Just trying some stuff out.  Will ping if it works.

[MNT] Update codecov github action from v2 to v3

---

examples/01b_forecasting_proba.ipynb
sktime/utils/plotting.py

This adds the probabilistic forecasting notebook from pydata Berlin 2022 to the `examples` folder.

[DOC] proba forecasting notebook from pydata Berlin 2022

---

examples/segmentation_with_clasp.ipynb

Its just a very minor typo fix

[DOC] fix typo in segmentation_with_clasp.ipynb

---

setup.cfg

[MNT] Reduce test verbosity

---

.all-contributorsrc
sktime/forecasting/base/adapters/_tbats.py

…r BATS and TBATS wrappers
Fixes #3063. See also https://github.com/intive-DataScience/tbats/issues/35 for discussion. 
Implements update method for tbats, which allows users to update state fo the model with new observations (fast) without refitting model parameters (slow). Particualrly, useful for walk-forward prediction and validation.
No new dependencies were introduced.
There are a number of potential places I could implement this change. I thought the _tbats.py file with the adapter class was the most natural but let me know if this was not the intended design / pattern. 
This is my first contribution to a public code base. Would appreciate any feedback and, if happy, would be interested in contributing more (eg. related issues #3064 and #3065).

[ENH] dedicated `_update` for `BATS` and `TBATS`

---

docs/source/installation.rst

Added Python 3.10 to installation docs

[MNT] Added Python 3.10 to installation docs

---

.github/workflows/test.yml
.github/workflows/wheels.yml

This PR simplifies the CI by consolidating the test workflow since there are no longer any platform dependent differences between mac and linux, i.e. merging mac/linux via a matrix.

[MNT] cleaning up CI workflow

---

docs/source/developer_guide/coding_standards.rst

[DOC] Fixing improvements on local linting/precommit setup developer documentation

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/model_evaluation/_functions.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/model_selection/tests/test_tune.py
sktime/utils/_testing/deep_equals.py

#2891 
Enable better UX for grid search by avoiding exceptions. This is really important for bigger grids with multiple transformers.

[ENH] Added error_score to evaluate and grid searches

---

sktime/forecasting/var.py

Adds `predict_intervals` to the VAR module.
Adds `predict_intervals` to the VAR module.

[ENH] Adding `VAR._predict_intervals`

---

sktime/utils/profiling.py

This adds a utility to profile fit/predict runtime of time series classifiers, `utils.profiling.profile_classifier`.

[ENH] classifier runtime profiling utility

---

.all-contributorsrc
sktime/utils/validation/series.py
sktime/utils/validation/tests/test_series.py

Fixes #3159 
* The 'y_index' is set to 'range(len(y))' instead of being 'y'. This mitigates that it is checked if the values of y are part of the index of the second array.
* Add a new test file for the series file.
No
I am unsure about the testing because I could figure out where the tests for this specific method are. Thus, I created a new file.

[BUG] Fix check_equal_time_index with numpy arrays as input.

---

pyproject.toml

closes #2766
Added `pytest-randomly`
New dev dependency `pytest-randomly`

[MNT] Added pytest-randomly

---

README.md

[MNT] Changed sktime logo on README

---

sktime/forecasting/model_selection/_split.py

Next step in #1737 
This PR is a simple refactoring. Use `sktime.datatypes._utilities.get_window` in `sktime.forecasting.model_selection._split.SingleWindowSplitter._split`.
No

[ENH] Refactor `SingleWindowSplitter` using `get_window` function

---

sktime/forecasting/trend.py

Improved `STLForeceaster` docstring, with a proper description of the algorithm and complete parameter strings.
FYI @ckwan48

[DOC] improved `STLForecaster` docstring

---

sktime/forecasting/model_selection/_split.py

Next step in #1737 
This PR is a simple refactoring. Use `sktime.datatypes._utilities.get_window` in `sktime.forecasting.model_selection._split.CutoffSplitter._split`.
No

[ENH] Refactor `CutoffSplitter` using `get_window` function

---

sktime/transformations/series/detrend/_deseasonalize.py

Adds some clarifications in the docstring of `Deseasonalizer`.

[DOC] clarifications in the `Deseasonalizer` docstring

---

sktime/transformations/series/tests/test_optional_passthrough.py

[ENH] Added test for OptionalPassthrough

---

.all-contributorsrc
CODEOWNERS
examples/channel_selection.ipynb
sktime/transformations/panel/channel_selection.py
sktime/transformations/panel/tests/test_channel_selection.py

#2934
Partially related to mentioned PR. The methods are implemented from [this](https://link.springer.com/chapter/10.1007/978-3-030-91445-5_3) paper.

[ENH] Channel selection for multivariate time series classification.

---

sktime/annotation/clasp.py
sktime/annotation/plotting/utils.py
sktime/transformations/series/clasp.py

This PR fixes:
- Plotting issue with ClaSP when list of change points is not sorted
- Adds exclusion zone as a parameter to segmentation.

[END][BUG] ClaSP Segmentation

---

sktime/classification/deep_learning/cnn.py

adds missing soft dependency tag to `CNNClassifier`

[MNT] add soft dependency tag to `CNNClassifier`

---

sktime/utils/_testing/scenarios_forecasting.py

Reverts alan-turing-institute/sktime#3297

Revert "[ENH] test `pd.Series` with name attribute in forecasters"

---

README.md
docs/source/changelog.rst
sktime/__init__.py

Release v0.13.2

---

sktime/classification/deep_learning/mlp.py
sktime/networks/mlp.py
sktime/registry/_base_classes.py
sktime/registry/tests/test_lookup.py
sktime/tests/_config.py

Fixes #3192 
Migrating MLPClassifier from sktime-dl to sktime

[ENH] Adding MLPClassifier

---

docs/source/installation.rst

I recently ran into some import issues with sktime using jupyter notebooks that essentially stemmed from not having my virtual environment properly linked as a kernel!
Moving forward I plan to just use jupyter notebooks in VScode (and recommend others do too), but figured I would add some tips to the docs (as well as some general resources for using virtual environments) to perhaps save some time for future contributors. :)

[DOC] Some tips on getting virtual environments to work

---

sktime/clustering/base.py
sktime/clustering/k_means.py
sktime/clustering/k_medoids.py
sktime/clustering/k_shapes.py
sktime/clustering/kernel_k_means.py
sktime/transformations/series/outlier_detection.py

Various small refactoring I spotted while browsing the code.

[MNT] Small refactoring changes

---

sktime/transformations/compose.py

Fix docstring of TransformerPipeline

[DOC] Fix docstring of TransformerPipeline

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release v0.13.3

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

maintenance release 0.13.4 - version increase and changelog only

release 0.13.4

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/tests/test_base.py
sktime/forecasting/compose/_pipeline.py

[BUG] Fix side-effect of predict_residuals

---

docs/source/developer_guide/release.rst

Update docs on releasing conda packages

---

pyproject.toml
sktime/networks/tapnet.py
sktime/regression/deep_learning/tapnet.py
sktime/tests/_config.py

Fixes #3474
Migrate TapNet Regressor from `sktime-dl` into `sktime`.
Yes, introduces `keras-self-attention` as a soft dependency.

[ENH] TapNet DL Model for regression from sktime-dl

---

sktime/annotation/hmm_learn/base.py
sktime/annotation/tests/test_all_annotators.py

Many thanks to @GuzalBulatova for detecting this issue! :)

[BUG] Fixing the tags typo that was causing issues with all estimators

---

.github/workflows/test.yml

[MNT] Bump pre-commit action from 2 to 3

---

.github/workflows/test.yml
.github/workflows/wheels.yml

[MNT] Bump setup-python action from 2 to 4

---

sktime/base/_base.py
sktime/dists_kernels/compose_tab_to_panel.py

Fix typo in method `set_tags()`

[BUG] Fix typo in `set_tags` call in `AggrDist.__init__`

---

docs/source/about/team.rst

Thank you team! Just adding the change to the docs as per @fkiraly 's suggestion! :)

[DOCS] Adding myself to list of core developers

---

docs/source/conf.py
docs/source/index.rst

Adding an invite to the sktime website for people to register for the upcoming dev days.

[DOCS] Adding invite to fall dev days to website landing page.

---

sktime/forecasting/base/tests/test_fh.py
sktime/utils/validation/__init__.py

Closes #3619 
Checking `np.timedelta64` with `is_int` function returns `True` since
```
>>> import numpy as np
>>> isinstance(np.timedelta64(1, "D"), np.integer)
True
```
This PR checks that the object is not `np.timedelta64`.
No

[BUG] Exclude `np.timedelta64` from `is_int` check

---

docs/source/conf.py
docs/source/developers.rst
docs/source/get_involved.rst
docs/source/get_involved/contributing.rst
docs/source/index.rst
docs/source/tutorials.rst
docs/source/users.rst
pyproject.toml

Replaces the `sphinx-panels` dependency with `sphinx-design` #3370.
The cards/panels are slightly smaller than before, and the button colour has changed since the default grey bugged out on darkmode for me with the new package.

[DOC] Replace `sphinx-panels` with `sphinx-design`

---

sktime/forecasting/compose/_ensemble.py

Fixes https://github.com/sktime/sktime/issues/3640 with the fix suggested therein.
Test is in https://github.com/sktime/sktime/pull/3637 which adds the test, and depends on this fix.

[ENH] fix conditional `requires-fh-in-fit` tag in `EnsembleForecaster`

---

docs/source/get_involved/governance.rst

Clarification on lazy consensus approval for GOV PRs.

[GOV] Lazy consensus on GOV PRs

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/early_classification.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This adds two important recommendation when adding parameter set for `get_test_params()` in classification template. See #3633 for further information.
No.
I could copy-paste it to other relevant templates but I was wondering if there was a better way. Since this recommendation is important for only classification at the moment, so I want to at least add it there.

[ENH] Add important information about `get_test_params()` in the extension template

---

sktime/forecasting/base/_fh.py
sktime/utils/datetime.py

* from `pandas` `freq` deprecation: replace warning with exception in `_coerce_to_period`
* from `pandas` `freq` deprecation: replace warning with exception in `_shift`

[MNT] 0.14.0 deprecation actions

---

sktime/forecasting/model_evaluation/_functions.py

Closes #3698
Documents all columns in DataFrame of results returned by `evaluate`
Np.
Docstring.

[DOC] Document `evaluate` output DataFrame schema 

---

docs/source/about/team.rst

Fixes #3732.
- CC list had a typo that made it disappear from the docs - fixed that
- Martina resigned from CoC - deleted her name from there
- moved RNKuhns back to active core-devs
Is the team page https://sktime--3733.org.readthedocs.build/en/3733/about/team.html rendered correctly now?

[DOC] Update CC and CoC and active core-devs lists in team.rst

---

docs/source/api_reference/classification.rst

Adds classification package classes to the classification API page.

[DOC] Add missing estimators to classification API page

---

docs/source/conf.py
docs/source/index.rst

Reverts sktime/sktime#3607
The dev days will be over after today, so we can remove that ad then :)

Revert "[DOCS] Adding invite to fall dev days to website landing page."

---

sktime/classification/tests/test_base.py

Quick fix for #3743 by moving the import inside the test.

keras import quick-fix

---

sktime/classification/kernel_based/_rocket_classifier.py

Fixed doc typo in Rocket Classifier

---

docs/source/get_involved/contributing.rst

[DOC] added new slack link

---

sktime/datasets/_single_problem_loaders.py
sktime/datasets/tests/test_data_io.py

Fixes #3758 and #3663 
Removes test of `load_solar` and instead prints a warning from the `load_solar` function if a HTTP or URL error is detected
No
Wasn't sure whether to keep the backoff decorator or just raise a user warning like i've changed it to. Happy to revert it back if you all think that's more user friendly

[BUG] remove test and add warning to load solar

---

docs/source/api_reference/transformations.rst

[DOC] Updates documentation for channel selection

---

.all-contributorsrc
docs/source/api_reference/data_format.rst

Fixes #3772
The problem was in `toctree` part of the `.rst` file. It has been updated and now `.ts` format is visible (in the local build).
No
Feedback on whether the resulting page (`API Reference/File Format Specifications`) look good.

[BUG] Update File Format Specifications page to show list of hyperlinked formats

---

pyproject.toml
sktime/_contrib/data_io.py

fix typo in string introduced in https://github.com/sktime/sktime/commit/0ce1b838bd9837b7f80f8e6ddce2fa912059b881

[MNT] fix pyproject.toml broken string

---

.all-contributorsrc
docs/source/developer_guide/add_dataset.rst

Fixes #2019 
* Corrected the layout
* Detailed the steps
* Added the reference to the list of supported file formats
* Clarity and comprehensiveness of the instructions
**IMPORTANT**
The former doc contained an instruction about commenting out the `.gitignore` file:
`#downloaded datasets sktime/datasets/data/`
The current `.gitignore` only refers to
`#downloaded datasets
sktime/datasets/local_data/`
a folder not even in the current file tree...
Is this issue with `.gitignore` obsolete?

[DOC] documentation on workflow of adding a new dataset loader

---

docs/source/api_reference/forecasting.rst

Added ForecastByLevel to API docs

[DOC] Added ForecastByLevel to API docs

---

docs/source/about/team.rst

I'm glad to join the team, thanks all!
Thank you @fkiraly for suggesting me as a core dev.

[DOC] Add achieveordie as a core developer

---

sktime/classification/deep_learning/base.py
sktime/classification/tests/test_base.py
sktime/regression/deep_learning/base.py

Fixes #3816
Replacing `keras.optimizers` with `tf.keras.optimizers` along with few other API-related changes. Also reformatted `save` to check for model presence first, must have gone unnoticed in the original PR.
No
Tested for the latest tensorflow version (2.11.0)

[BUG] Update `test_deep_estimator_full` to incorporate new versions of tf/keras

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.14.1.
* changelog

Release v0.14.1

---

examples/03_transformers.ipynb

This PR updates the transformers extension section in the transformers tutorial which was outdated.

[DOC] update transformers extension section in transformers tutorial

---

examples/01_forecasting.ipynb
sktime/datatypes/_proba/_check.py
sktime/utils/plotting.py
sktime/utils/validation/forecasting.py

This would close [Issue-3824](https://github.com/sktime/sktime/issues/3824) as well as [Issue-541](https://github.com/sktime/sktime/issues/541). There have been multiple other PRs for the original issue but as far as I can see they're all closed ([545](https://github.com/sktime/sktime/pull/545), [802](https://github.com/sktime/sktime/pull/802)).
Allows user to pass `pred_interval` to `plot_series()` and plot the confidence interval provided in that argument.
No
Any other edge cases I need to check for? So far there is pretty rigorous check of the schema of the interval DataFrame, and there's a check to ensure the index matches that of the final series passed to the function.
Once there's some buy in for this approach I'll add at least one test case.
I'm not sure what killed the other …

[ENH] Add support for plotting intervals in `plot_series()`

---

.all-contributorsrc
sktime/classification/deep_learning/resnet.py
sktime/networks/resnet.py
sktime/tests/_config.py

Part of #3351. See also #3365 
Migrating dl estimators from sktime_dl to sktime
No
tests

[ENH] Migrate `ResNetClassifier` from `sktime-dl` to `sktime` 

---

docs/source/get_involved/governance.rst

#3865 
Propose change in nomination of CC and CoC members. This PR removes the gate keeping sections

 [GOV] Appointment of CC and CoC members

---

docs/source/get_involved/governance.rst

Revert " [GOV] Appointment of CC and CoC members"

---

pyproject.toml

Add links to **api reference** and **release notes**.

[MNT] Additional project urls in `pyproject.toml`

---

.all-contributorsrc

This maintenance PR moves @badrmarani in the `allcontributors` file to chronological order.

[MNT] move `badrmarani` contrib to chronological order

---

docs/source/api_reference/transformations.rst
sktime/transformations/series/binning.py

Fixes https://github.com/sktime/sktime/issues/242
Implements a transformer `TimeBinAggregate` which transforms a series to a series by aggregating in time bins as specified in a hyper-parameter (description in the docstring).

[ENH] time bin aggregation transformer

---

sktime/utils/validation/_dependencies.py

This PR extends `_check_estimator_deps` so it also allows a list or tuple of `BaseObject`-s as input.
When a tuple or list is passed, iterates through it and returns the conjunction condition (all estimators must be supported).

[ENH] `_check_estimator_deps` to also allows list or tuple of `BaseObject`-s

---

docs/source/about/team.rst

Updates the list of core devs to be current.

[DOC] update list of core devs

---

sktime/forecasting/model_evaluation/_functions.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py

Function `from sktime.forecasting.model_evaluation import evaluate` to accept list of scorers, this is then added as new columns to the output data.

[ENG] Evaluate function to accept list of scorers

---

sktime/forecasting/tests/test_structural.py

Isolates some remaining instances of `statsmodels`, in preparation of PR https://github.com/sktime/sktime/pull/3516

[MNT] isolate `statsmodels`, recent instances

---

docs/source/developer_guide/continuous_integration.rst
docs/source/get_involved/contributing.rst

I feel like many new contributors struggle with the linting checks, so I was hoping that adding some more detail to this section of the developer docs would help with that.  Also the link to pre-commit was broken (making it even more difficult to get it setup!). 
Feel free to add other suggestions.  This has just been on my mind with all the new contributors, so wanted to get the ball rolling.

[DOC] More details on Code Quality and Linting

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.15.1.
* changelog

Release 0.15.1

---

.all-contributorsrc
sktime/forecasting/model_selection/_split.py

Resolves #2695
* Refactor the `sktime.forecasting.model_selection._split.BaseSplitter._split_vectorized` method to improve readability.
* Simplify other small fragments of code in the same module.
Are there any concerns regarding the new implementation of the `_split_vectorized` method? @fkiraly would be great to hear your thoughts on this, since you wrote the original code.
No, I just checked that previous tests still pass.

[ENH] Refactor/simplify `sktime.forecasting.model_selection._split.BaseSplitter._split_vectorized`

---

docs/source/glossary.rst

Fixes #4117 
`user_guide_forecasting` is an orphaned reference, so it needs to be replaced. The suggested change links to the user guide introduction page. I would have linked it to the forecasting-specific page, but it wasn't obvious how to do that since it gets generated from `.ipynb`.
No
It's just 1 line 🙂 
Not applicable.

[DOC] Fix broken link to the user guide in the glossary

---

sktime/datatypes/_utilities.py
sktime/forecasting/compose/_reduce.py

https://github.com/sktime/sktime/issues/4139
Reworked get_time_index to run faster and be less frequently called

[ENH] get time index rework to get faster run times for grouped data

---

sktime/forecasting/compose/_hierarchy_ensemble.py

Missing commit from https://github.com/sktime/sktime/pull/4166

[MNT] isolate `statsmodels` in `HierarchyEnsembleForecaster` docstring - accidentally missing commit

---

sktime/transformations/series/subset.py

This PR allows ColumnSelect to transform multi-index dataframes directly instead using an expensive iterative instance wise 
transformation.

[ENH] Add panel support to column select transformer

---

.all-contributorsrc
sktime/transformations/base.py

This addresses one of the problems mentioned in #4158 but it doesn't fix all of them, so it should probably remain open.
This PR converts the table format from md to rst. This renders as follows on my machine:
no

[DOC] fix tables in transformer `transform` docstrings - change md to rst

---

examples/02_classification.ipynb

Fixes #4189 
Removes the unnecessary gap between `pandas` and the class names. This only applies in these cases from what I can tell, since in other cases like `sktime` `make_pipeline` we'd need to add the in-between modules. If that is ever desired I suggest switching to `intersphinx` since it will also validate all those references, so in case there's a typo or anything changes you'll know immediately.
no

[DOC] remove gap between pandas and DataFrame | Series in classification notebook (#4200)

---

.all-contributorsrc

This fixes some merge conflicts and formatting in `.all-contributorsrc`.
Includes contributors from https://github.com/sktime/sktime/pull/2977 to remove conflicts with main, of #2977

[DOC] Fix merge conflicts and formatting in `.all-contributorsrc`

---

.all-contributorsrc

#2977 cannot be pushed to due to branch lock, but has conflicts on `all-contributorsrc`. Therefore we will carry out the merge as follows:
1. overwrite main with `all-contributorc` from #2977
2. merge #2977
3. revert 1

[MNT] temp MR to remove 2977 conflicts

---

.all-contributorsrc

Reverts sktime/sktime#4206, see there for explanation of the strategy to resolve the merge conflict with #2977

[MNT] temp MR to remove 2977 conflicts - part 3

---

sktime/transformations/series/impute.py
sktime/transformations/series/tests/test_imputer.py

This PR allows Imputer to transform multi-index dataframes directly instead using an expensive iterative instance wise
transformation for some imputation strategies.

[ENH] add native multi-index/hierarchical data support to `Imputer`

---

sktime/datasets/tsc_dataset_names.py

[BUG] Correct 'StarlightCurves' data set identifier string, to 'StarLightCurves'

---

pyproject.toml
sktime/param_est/seasonality.py

Fixes #3835
Interfaces welch/seasonal package as seasonality param_est
Introduces soft dependancey: [Seasonal](https://github.com/welch/seasonal)

 [ENH] interface the seasonal package as a parameter estimator for seasonality

---

docs/source/about/team.rst

Moves myself from core devs to former core devs

Remove myself from core devs

---

sktime/performance_metrics/forecasting/_classes.py

Towards https://github.com/sktime/sktime/issues/3429, test parameter sets for performance metrics.

[ENH] additional test parameter sets for performance metrics

---

sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/tests/test_reduce_global.py

[BUG] Small docstring fixes in reducer module and tests

---

.all-contributorsrc
sktime/transformations/panel/summarize/tests/test_PlateauFinder.py
sktime/transformations/tests/__init__.py

#4182
Fixed (D103 & D100: Missing docstring in public function)
No.
*Fixed the missing docstring for public function `test_PlateauFinder` at line 11.
*Fixed the missing docstring for public function `test_PlateauFinder` at line 1,
No.

[ENH] add missing docstrings in `PlateauFinder` module

---

docs/source/api_reference/transformations.rst
sktime/transformations/series/kinematic.py
sktime/transformations/series/tests/test_kinematic.py

Fixes https://github.com/sktime/sktime/issues/4256
Simple implementation of the kinematic feature transformer based on finite differences. Does not do smoothing, but can be pipeliend with smoothers.

[ENH] kinematic feature transformer

---

sktime/transformations/__init__.py
sktime/transformations/panel/__init__.py
sktime/transformations/panel/catch22.py
sktime/transformations/panel/dictionary_based/tests/__init__.py
sktime/transformations/panel/dictionary_based/tests/test_paa.py
sktime/transformations/panel/reduce.py
sktime/transformations/panel/rocket/_minirocket_multivariate_variable.py
sktime/transformations/panel/shapelet_transform.py
sktime/transformations/panel/signature_based/__init__.py
sktime/transformations/panel/signature_based/_window.py
sktime/transformations/panel/signature_based/tests/__init__.py
sktime/transformations/panel/summarize/tests/__init__.py
sktime/transformations/panel/tests/__init__.py
sktime/transformations/panel/tests/test_ColumnConcatenator.py
sktime/transformations/panel/tests/test_Padder.py
sktime/transformations/panel/tests/test_dwt.py
sktime/transformations/panel/tests/test_hog1d_transformer.py
sktime/transformations/panel/tests/test_slope_transformer.py
sktime/transformations/series/binning.py
sktime/transformations/series/date.py
sktime/transformations/series/dobin.py
sktime/transformations/series/outlier_detection.py
sktime/transformations/series/tests/__init__.py
sktime/transformations/series/tests/test_exponent.py
sktime/transformations/series/time_since.py

#4182
- Fix B028 No explicit stacklevel keyword argument found
- Fix pydocstyle errors (D103, D100, D200, D403, D205, D400, D401, D410, D411)
No
No
No

[MNT] Fix linting issues in transformations module

---

extension_templates/param_est.py

This PR adds an extension template for parameter estimators.

[DOC] extension template for parameter estimators

---

sktime/clustering/partitioning/_lloyds.py

#4182
- Fix flake8 issue (T201 print found)
No
- flake8 issue (T201 print found)
No
No

[MNT] Fix linting issues in `clustering` module

---

sktime/annotation/eagglo.py
sktime/annotation/hmm.py
sktime/annotation/stray.py
sktime/annotation/tests/__init__.py

#4182 
- Fix B028 No explicit stacklevel keyword argument found
- Fix pydocstyle error (D104)
No
No
No

[MNT] Fixes linting issues in `annotation` module

---

sktime/benchmarking/__init__.py
sktime/benchmarking/tests/__init__.py
sktime/dists_kernels/tests/__init__.py
sktime/dists_kernels/tests/test_compose_tab_to_panel.py
sktime/dists_kernels/tests/test_scipy_dist.py
sktime/series_as_features/base/__init__.py
sktime/series_as_features/base/estimators/__init__.py
sktime/series_as_features/base/estimators/tests/__init__.py
sktime/tests/__init__.py

#4182
- isort auto-fixes
- Fix series_as_features pydocstyle issues (D104)
- Fix tests pydocstyle issues (D104)
- Fix dists_kernels pydocstyle issues (D100, D103, D104)
- Fix benchmarking pydocstyle issues (D104)
No
- isort auto-fixes
- series_as_features pydocstyle issues (D104)
- tests pydocstyle issues (D104)
- dists_kernels pydocstyle issues (D100, D103, D104)
- benchmarking pydocstyle issues (D104)
No
No

[MNT] Fix linting issues in `series_as_features`, `tests`, `dist_kernels`, `benchmarking` modules

---

sktime/classification/compose/tests/__init__.py
sktime/classification/dictionary_based/_cboss.py
sktime/classification/dictionary_based/_muse.py
sktime/classification/dictionary_based/_tde.py
sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/feature_based/_tsfresh_classifier.py

#4182 
- Fix B028 No explicit stacklevel keyword argument found
- Fix noqa code T001 to T201
- Fix pydocstyle error (D104)
No
No
No

[MNT] Fixes linting issues in `classification` module

---

.github/workflows/update_contributors.yml

Reference PR #4257 and issue #4103
We're simply removing the restriction on branches which would enable the workflow to be triggered whenever changes are detected to `.all-contributorsrc` regardless of the branch name. Please see the discussion in #4257 and #4103 for the complete context.
None
After we merge this PR, I will be able to resume testing the workflow via #4257 and we can decide if we want to keep this workflow since it only reduces manual work with no apparent cons.

[MNT] Remove restrictions on branch for workflow that autodetect and updates `CONTRIBUTORS.md`

---

sktime/distances/_distance.py

Adds to #4264
I updated the `dtw_distance` example to include the actual import.  This way someone can copy and paste the example given on the website and re-use it.
No
Make sure the example in the docstring can be re-used if copied and pasted directly into a python file.
Since it's just an example I didn't add a test.
This fixes a small pet peeve of mine with the current documentation, which is that the actual import for the technique is often not listed in the example, so you can't just copy and paste from the API reference to see how it works.  This inconvenience is compounded by the fact that the actual imports you need to use are often irregular and can't be easily inferred from the way different methods are listed in the API docs.  So you often have to go on a bit of a chase just to …

[DOC] updated `dtw_distance` docstring example to include import

---

.all-contributorsrc
sktime/utils/estimators/_forecasters.py

See also #4394  ([relevant comment](https://github.com/sktime/sktime/pull/4394#issuecomment-1484120463))
`MockForecaster` predicts by a constant value, and for negative values of the constant, the quantile predictions were monotonically decreasing instead of monotonically increasing. As suggested by @fkiraly in the [comment](https://github.com/sktime/sktime/pull/4394#issuecomment-1484149023), this PR addresses this by handling positive and negative cases separately.
No.
No.

[BUG] Fix `MockForecaster._predict_quantiles` to ensure monotonicity of quantiles

---

docs/source/get_involved.rst

I have changed few lines to make it more grammatically correct and more appealing . Hope it helps.

[DOC] improvements to "invitation to contribute" paragraph in documentation

---

docs/source/related_software.rst

Fixes #4418
Hey! this is my first open source contribution. I am a beginner in machine learning and found your projects very interesting and would like to contribute to your projects.

[DOC] timeseers added to the related_software.rst page

---

docs/source/api_reference/transformations.rst
sktime/transformations/compose/__init__.py
sktime/transformations/compose/_ixtox.py

Resolves #4343, by adding a transformer that creates features from time or hierarchy index.
The user can select which hierarchy levels to use (if a hierarchical time series), and can control type coercion.

[ENH] transformer that creates features from time index or hierarchy label

---

docs/source/api_reference/transformations.rst
sktime/transformations/bootstrap/__init__.py
sktime/transformations/bootstrap/_mbb.py
sktime/transformations/bootstrap/_splitterboot.py

This implements a splitter based bootstrap transformer to which any splitter can be passed.
It then bootstraps sub-series based on train and/or test sets produced by the splitter.
Resolves https://github.com/sktime/sktime/issues/4454

[ENH] splitter bootstrap transformer

---

sktime/transformations/panel/rocket/_minirocket.py

Error in MiniRocket example code
Fixes error in MiniRocket example code
No new dependencies

[BUG] Fix error in `MiniRocket` example code - wrong transformer

---

sktime/classification/deep_learning/rnn.py
sktime/networks/rnn.py
sktime/regression/deep_learning/rnn.py

migrates simple RNN regressor from sktime-dl, see https://github.com/sktime/sktime/issues/3351

[ENH] Add SimpleRNN DL Estimator

---

sktime/forecasting/dynamic_factor.py

Fixed few typos in `DynamicFactor` docstrings.

[DOC] fix typos in `DynamicFactor` docstring

---

sktime/dists_kernels/algebra.py
sktime/dists_kernels/compose.py
sktime/dists_kernels/dtw.py
sktime/dists_kernels/edit_dist.py

Improves the docstrings in the distances/kernels module:
* added and expanded examples
* corrected typos and mistakes

[DOC] improved docstrings in distances/kernels module

---

sktime/classification/deep_learning/rnn.py
sktime/forecasting/base/_base.py
sktime/forecasting/dynamic_factor.py
sktime/networks/rnn.py
sktime/regression/deep_learning/rnn.py
sktime/tests/_config.py

This PR turns on the tests for RNN classifier and regressor, post https://github.com/sktime/sktime/pull/4530

achievordie [BUG] fix RNN classifier and regressor

---

docs/source/index.rst

Adds references to the sktime internship on the docs page.

[DOC} adds sktime internship link on the docs page

---

examples/minirocket.ipynb

N/A
One of the links in the MiniRocket notebook was pointing at a file that doesn't seem to exist, and I found one that is similarly named and seems to have relevant content.
No.
Does this link seem right?
N/A
No.

[DOC] Update link in minirocket.ipynb

---

docs/source/api_reference/dists_kernels.rst

Correcting module name and path in dists_kernels.rst

[ENH] correcting module path in dists_kernels.rst

---

docs/source/api_reference/classification.rst
sktime/classification/deep_learning/macnn.py
sktime/networks/macnn.py
sktime/tests/_config.py

Fixes #3294 
Part of #3351
Add `MACNNNetwork` and `MACNNClassifier`.
None …

[ENH] Add MACNN classifier and network

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/statsforecast.py
sktime/forecasting/theta.py

Depends on #4629
Part of #4643 
This PR adds and interface to the `AutoTheta` model provided in `statsforecast`. It's exposed to users as `StatsForecastAutoTheta`.
No.
No.

[ENH] `statsforecast` `AutoTheta` direct interface estimator

---

README.md
extension_templates/alignment.py

This PR adds an extension template for sequence alignerse.
Reference: #1634

[DOC] extension template for sequence aligners

---

docs/source/glossary.rst

I have added a few common glossary terms. Please double-check the additions and merge them accordingly.

[DOC] additional glossary terms

---

docs/source/changelog.rst

PR with some minor changes to the 0.18.1 changelog where some PR were miscategorized.

[DOC] fixing miscategorizations in 0.18.1 changelog

---

sktime/classification/interval_based/_stsf.py
sktime/classification/interval_based/_tsf.py

In some cases while using doctest, the expected outputs for certain items were incorrect, resulting in the failure of the corresponding doctests.

[DOC] correct some failing doctests

---

README.md
docs/source/about/_mission.rst
docs/source/changelog.rst
docs/source/index.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.19.2
* changelog
* updated mission statement as per council decision May 27

Release 0.19.2

---

sktime/networks/inceptiontime.py

Fixes a misformatted author line for the `InceptionTime` estimator

[DOC] fix author line in InceptionTime

---

pyproject.toml

https://numpy.org/doc/stable/release/1.25.0-notes.html

[MNT] 0.20.0 release action - support for numpy 1.25

---

docs/source/developer_guide/continuous_integration.rst

[DOC] adding ellipsis flag to doctest command

---

.all-contributorsrc
sktime/regression/deep_learning/resnet.py
sktime/regression/dummy/_dummy.py
sktime/regression/interval_based/_tsf.py

Additions #4264 
Added examples to docstrings in _tsf.py and _dummy.py. Fixed a typo in docstring for ResNetRegressor example.
No
No
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers) …

[DOC] Examples added to docstrings for Time Series Forest Regressor and Dummy Regressor

---

sktime/forecasting/dynamic_factor.py
sktime/forecasting/tests/test_dynamic_factor.py

Closes #4744.
Main Changes
* passes exogeneous variables always (`None` causes no problem) for prediction
* adds tests
Extra Changes
* fix type hinting

[BUG] allows probabilistic predictions in `DynamicFactor` in presence of exogenous variables

---

README.md

Fixes #4755 
Some Spell Changes and Enhancements
No
Readme section
No …

[DOC] Improvements to formulations in the README

---

docs/source/developer_guide/dependencies.rst
sktime/base/_base.py

A quick PR to be merged with #4860

 [ENH] suggested change to PR #4860 - placing `_tag` for sklearn dependecy alias in `BaseEstimator`

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py
sktime/classification/early_classification/_probability_threshold.py
sktime/forecasting/base/_fh.py
sktime/forecasting/compose/_bagging.py
sktime/forecasting/model_evaluation/_functions.py

Release PR for 0.21.0
* changelog
* minor typo fixes

Release 0.21.0

---

docs/source/developer_guide/dependencies.rst

This PR makes some minor improvements to the dependencies guide:
* fixing of typos
* improving formulations and specificity of instructions

[DOC] minor improvements to the dependencies guide

---

.all-contributorsrc
docs/source/installation.rst
sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py

Fixes #4933 
The developer documentation was hard to read, because it didn't mention the git workflow. Added the link.
Moreover there were two small sections regarding the build requirements. These were removed here.
no
Readability and logic
no

[DOC] clarifications to different installations in install documentation

---

docs/source/conf.py
pyproject.toml

[ENH] Adds copy clipboard button for Example section

---

docs/source/conf.py

[MNT] updated sphinx intersphinx links for other libraries

---

.github/workflows/test.yml
docs/source/conf.py
pyproject.toml
sktime/classification/distance_based/_elastic_ensemble.py
sktime/forecasting/reconcile.py
sktime/forecasting/statsforecast.py
sktime/transformations/series/adapt.py
sktime/transformations/series/difference.py
sktime/transformations/series/tests/test_differencer.py
sktime/utils/_testing/hierarchical.py
sktime/utils/tests/test_check_estimator.py

Test only modified changes in CI

---

sktime/clustering/k_means.py
sktime/clustering/k_medoids.py
sktime/clustering/partitioning/_lloyds.py

Closes #4863.
Allows numpy arrays representing the initial centroid guesses to be passed into `init_algorithm` for `TimeSeriesLoyds`.
No
Not yet
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm- …

[ENH] Handle array centroid guesses for TimeSeriesLloyds

---

sktime/forecasting/model_evaluation/_functions.py
sktime/forecasting/tests/test_reconcile.py

This PR speeds up various non-suite tests:
* doctest of `evaluate` by making the data set smaller
* tests in `test_reconcile` by making the data set smaller

[MNT] speed up various non-suite tests

---

sktime/alignment/base.py

This extends `BaseAligner.fit` to allow any `Panel` mtype as input.
Such an input is then convnerted to the `X_inner_mtype`, which is a newly introduced tag similar to `BaseForecaster` etc, with a default of the current `"df-list"` type.

[ENH] extend `BaseAligner.fit` with input conversion

---

pyproject.toml

[MNT] update sphinx upper bound after skipping 7.2.0

---

.pre-commit-config.yaml
sktime/forecasting/base/_base.py
sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/base/tests/test_base_bugs.py
sktime/transformations/panel/dictionary_based/_sfa_fast.py

1. updated versions with `pre-commit autoupdate`
2. ran all hooks on all files using `pre-commit run --all-files`
3. modified `if type(object_1) == type(object_2)` to `if type(object_1) is type(object_2)`
4. modified `if type(object) == Type` to `if isinstance(object, Type)`

[MNT] Update versions of pre commit hooks and fix `E721` issues pointed out by `flake8`

---

sktime/forecasting/naive.py

[BUG] Fix tag to indicate support of exogenous features by `NaiveForecaster`

---

sktime/registry/tests/test_tags.py

This PR adds a test for specification conformance of the tag register.

[ENH] test for specification conformance of tag register

---

.all-contributorsrc

Adds @alexfilothodoros as a contributor for #5169

[DOC] add alexfilothodoros to contributors

---

sktime/proba/laplace.py

Adds the Laplace distribution to the `proba` module.
Towards https://github.com/sktime/sktime/issues/4518
Mirror of https://github.com/sktime/skpro/pull/19

[ENH] Laplace distribution

---

.all-contributorsrc
sktime/forecasting/compose/tests/test_reduce_global.py

This PR fixes a missing `return` statement in the `y_dict` fixture used for testing composite forecasters.

[BUG] Add `return` statement for `y_dict`

---

docs/source/installation.rst

I wanted to get started with sktime and was going through it's documentation when I came across a couple of typos that I wished to fix.

[DOC] Fixing typos in installation.rst

---

sktime/forecasting/dummy.py

Fix ForecastKnownValues support for pd-multiindex with 2 index levels …

[BUG] Fix ForecastKnownValues not supporting pd-multiindex

---

.github/workflows/wheels.yml

Reverts sktime/sktime#5262, see https://github.com/sktime/sktime/pull/5262#issuecomment-1722439214 - was to ensure release of 0.22.1 without too long a wait.

[MNT] Revert "instant release action"

---

pyproject.toml

Reverts sktime/sktime#5285 - the `numba` estimators are incompatible with 0.58

[MNT] revert update numba requirement from <0.58,>=0.53 to >=0.53,<0.59"

---

extension_templates/forecasting.py

This adds the insample capability tags in the long forecasting extension template.

[DOC] forecasting extension template - add insample capability tags

---

examples/02_classification.ipynb

I was going through our [User Guide Documentation](https://www.sktime.net/en/stable/user_guide.html) and found that the second notebook(`sktime/examples/02_classification`) has the name "Overview of this notebook". This led to improving only the readability aspect of the notebook since it was initially written to be presented at a conference. I've also added some examples where necessary, reworded a few sentences for clarity, and corrected typos.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus …

[DOC] Improve Readability of Notebook 2 - Classification, Regression & Clustering

---

sktime/alignment/naive.py

This PR contains several minor fixes to `NaiveAligner`:
* corrections to docstrings
* correct setting of the tags indicating partial alignment and multiple alignment

[ENH] minor fixes to `NaiveAligner`

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py

[ENH] Skip unnecessary fit in `ForecastX` if inner `forecaster_y` ignores `X`

---

.all-contributorsrc
examples/02_classification.ipynb

Fixing a typo in the classification notebook …

[DOC] fix typo in classification notebook

---

.github/PULL_REQUEST_TEMPLATE.md

This PR makes the PR post template hopefully more informative and welcoming to new contributors:
* more and corrected links to contributing guide, soft dependencies guide, discord
* restructured PR review guide to make it less apologetic and more welcoming as well as instructive

[DOC] Improved PR template for new contributors

---

.pre-commit-config.yaml
pyproject.toml

1. Introduces two new `pre-commit` hooks to auto-format and validate `pyproject.toml`
2. Formats existing `pyproject.toml`

[MNT] Auto format pyproject

---

.pre-commit-config.yaml

[BUG] [MNT] removed two recently added hooks

---

.github/workflows/test_all.yml

Fixes https://github.com/sktime/sktime/actions/runs/6600462700
Note: can not test `test_all` workflow without running on `main`, but this should be enough based on my understanding.

[BUG] [MNT] added missing checkout steps

---

pyproject.toml

I added comments for readability of `pyproject.toml`, in the file:
* semantic ordering and commenting of dependency sets
* comments in headers re contributor credits and governance
* explanations for core dep set

[DOC] comments for readability of `pyproject.toml`

---

.codecov.yml
docs/source/developer_guide/add_estimators.rst
docs/source/events/gsoc_2022.md
examples/01a_forecasting_sklearn.ipynb
examples/03_transformers.ipynb
sktime/benchmarking/benchmarks.py
sktime/datasets/data/ACSF1/ACSF1_TEST.ts
sktime/datasets/data/ACSF1/ACSF1_TRAIN.ts
sktime/datatypes/tests/test_convert_to.py
sktime/forecasting/compose/_hierarchy_ensemble.py
sktime/forecasting/sarimax.py
sktime/performance_metrics/forecasting/_classes.py
sktime/transformations/panel/tests/test_timebinner.py
sktime/transformations/series/exponent.py

Follow-up #5424
Thank you @kianmeng
Found few more misspellings.

[DOC] Fix more typos

---

docs/source/conf.py
pyproject.toml

Reverts #4681 - see discussion in https://github.com/sktime/sktime/issues/5495

[MNT] revert PR #4681

---

sktime/base/_meta.py

Diagnosing #5498
Depends #5498

[MNT] rename variables in base

---

.pre-commit-config.yaml
examples/mlflow.ipynb
sktime/datasets/_readers_writers/arff.py
sktime/datasets/_readers_writers/utils.py
sktime/transformations/panel/catch22.py

1. updated versions of configured hooks
2. removed deprecated flags
3. removed unnecessary hadcoded outdated pins
4. used consistent array specification style
5. ran all hooks over all files

[MNT] Update pre commit hooks

---

sktime/forecasting/croston.py

Adds another test parameter set for `Croston` - integer typed smoothing

[ENH] `Croston` test parameters - integer smoothing parameter

---

sktime/forecasting/model_evaluation/_functions.py

Improves the algorithm description in the docstring of the `evaluate` forecasting utility.

[DOC] forecasting `evaluate` utility - improved algorithm description in docstring

---

.github/workflows/wheels.yml

This PR changes the release action back to release after testing wheels.
Reverts sktime/sktime#5660.

Revert "[MNT] instant release action"

---

sktime/base/_base_panel.py

This PR simplifies internals of `BasePanelMixin._vectorize` - this is a plain refactor to make the logic simpler, more readable, and idiomatic across base classes.

[ENH] refactor-simplify `BasePanelMixin._vectorize`

---

sktime/utils/_testing/estimator_checks.py
sktime/utils/_testing/scenarios_classification.py
sktime/utils/_testing/scenarios_forecasting.py

Without an issue.
Discussed in #5656
Replace `isinstance` or `issubclass` based checks by `object_type` tag.
No
No

[ENH] Replace `isinstance` by `object_type` tag based checks

---

sktime/pipeline/pipeline.py
sktime/tests/test_all_estimators.py

Fixes #5653 
dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependen …

[BUG] Enable pipeline.fit without X

---

examples/01c_forecasting_hierarchical_global.ipynb
examples/partition_based_clustering.ipynb
pyproject.toml
sktime/_contrib/notebooks/windows_installation.ipynb
sktime/annotation/clasp.py
sktime/base/_base_panel.py
sktime/classification/early_classification/base.py
sktime/datasets/_readers_writers/arff.py
sktime/datasets/_readers_writers/long.py
sktime/datasets/_readers_writers/tsf.py
sktime/datasets/_readers_writers/tsv.py
sktime/forecasting/trend/_pwl_trend_forecaster.py
sktime/forecasting/trend/tests/test_pwl_trend.py
sktime/param_est/compose/_func_fitter.py
sktime/transformations/base.py
sktime/transformations/bootstrap/_mbb.py
sktime/transformations/panel/rocket/_minirocket_multivariate.py
sktime/transformations/panel/rocket/_minirocket_multivariate_variable.py
sktime/transformations/panel/rocket/_multirocket.py
sktime/transformations/panel/rocket/_multirocket_multivariate.py
sktime/transformations/panel/rocket/_rocket.py
sktime/transformations/panel/signature_based/_augmentations.py
sktime/transformations/panel/signature_based/_signature_method.py
sktime/transformations/series/scaledasinh.py
sktime/utils/mlflow_sktime.py

Diagnoses #5638 
Depends on #5638

[MNT] fix several spelling mistakes

---

sktime/forecasting/tbats.py

Towards #3429
dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/depende …

[ENH] adding second test parameters for `TBATS`

---

sktime/forecasting/compose/_reduce.py

This PR simplifies a few conditional statements in the direct reducer, without changing the logic - this is a pure refactor.

[ENH] Simplify conditional statements in direct reducer

---

sktime/transformations/panel/rocket/_multirocket_multivariate.py

Fixes #5696.
Sets the random state.
No
N/A
N/A
Have not yet added myself to the list/file (which one?), will do later.

[BUG] Ensure `MultiRocketMultivariate` uses `random_state`

---

sktime/alignment/dtw_numba.py
sktime/alignment/dtw_python.py
sktime/alignment/edit_numba.py
sktime/alignment/lucky.py
sktime/alignment/naive.py
sktime/dists_kernels/algebra.py
sktime/dists_kernels/base/adapters/_tslearn.py
sktime/dists_kernels/compose.py
sktime/dists_kernels/compose_from_align.py
sktime/dists_kernels/compose_tab_to_panel.py
sktime/dists_kernels/ctw.py
sktime/dists_kernels/dist_to_kern.py
sktime/dists_kernels/dtw/_dtw_python.py
sktime/dists_kernels/dtw/_dtw_sktime.py
sktime/dists_kernels/dtw/_dtw_tslearn.py
sktime/dists_kernels/dummy.py
sktime/dists_kernels/edit_dist.py
sktime/dists_kernels/gak.py
sktime/dists_kernels/indep.py
sktime/dists_kernels/lcss.py
sktime/dists_kernels/lucky.py
sktime/dists_kernels/scipy_dist.py
sktime/dists_kernels/signature_kernel.py

Adds author and maintainer tags to all estimators in the alignment and distances modules.

[ENH] author and maintainer tags for alignment and distances modules

---

sktime/param_est/compose/_func_fitter.py
sktime/param_est/compose/_pipeline.py
sktime/param_est/fixed.py
sktime/param_est/plugin/_forecaster.py
sktime/param_est/plugin/_transformer.py
sktime/param_est/seasonality.py
sktime/param_est/stationarity/_arch.py
sktime/param_est/stationarity/_statsmodels.py
sktime/proba/empirical.py
sktime/proba/laplace.py
sktime/proba/normal.py
sktime/proba/t.py
sktime/proba/tfp.py

Adds author and maintainer tags to all estimators in the distributions and parameter fitting modules.

[ENH] author and maintainer tags for distributions and parameter fitting module

---

.pre-commit-config.yaml
examples/interpolation.ipynb
sktime/classification/distance_based/_shape_dtw.py
sktime/classification/tests/_classification_test_reproduction.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/adapters/_pytorch.py
sktime/networks/base.py
sktime/pipeline/step.py
sktime/utils/_testing/scenarios_classification.py

Automated changes from code quality tools, no manual changes.
1. updated version of pre-commit hooks (`pre-commit autoupdate`)
2. ran ruff with default settings (`ruff sktime`) -> ignored changes in `sktime/_contrib`
3. ran all hooks on all files (`pre-commit run --all-files`) -> ignored changes in `examples/blog_posts`

[MNT] Code quality updates

---

docs/source/api_reference/split.rst
sktime/split/compose/__init__.py
sktime/split/compose/_repeat.py

This PR adds a compositor for splitters which adds an n-times repeat.
This is useful to construct repeated versions of any splitter.

[ENH] Repeat splitter composition

---

sktime/forecasting/compose/_fallback.py

Fixes https://github.com/sktime/sktime/pull/5779#discussion_r1466764459

[BUG] fix wrong setting of `failed_at_step` in `FallbackForecaster`

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.26.0
* changelog

Release 0.26.0

---

.github/workflows/test_main.yml

[MNT] Reactivate new CI after temporary deactivation for 0.25.1 and 0.26.0 releases

---

sktime/performance_metrics/forecasting/_functions.py

[MNT] addressed future warning for RMSE by using newer `root_mean_absolute_error` function

---

sktime/transformations/panel/interpolate.py

Added Second test parameter set for `TSInterpolator`, towards #3429 
To begin with, I have updated it with a minor enhancement. If everything works well, will add more test sets and work on next `mid-to-longer term tasks`.

[ENH] second set of test parameters for `TSInterpolator`

---

docs/source/conf.py

Adds a "maintainers" column to the estimator overview, to facilitate pinging of maintainers

[DOC] add "maintainers" column to estimator overview

---

sktime/forecasting/base/adapters/_pytorch.py

fixes #5885 
I ensured that no varied `_fh`is set to self. This lead to several smaller changes to ensure that the fh is relative wherever needed.
No
No, this needs a more general discussing where we can create this test that it is tested for all forecasters!

[BUG] Avoid setting `_fh` and `_y` in _fit of `_pytorch.py`

---

.all-contributorsrc
sktime/annotation/hmm_learn/gmm.py

Added second test parameter set for `GMMHMM` and included myself in the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
#3429

[ENH] second set of test parameters for `GMMHMM`

---

.github/workflows/test.yml
.github/workflows/test_base.yml
.github/workflows/test_module.yml
.github/workflows/test_other.yml

This PR attempts the fix proposed by @yarnabrina, adding a checkout action to detect steps, to fix CI failures on main.
Fixes https://github.com/sktime/sktime/issues/5940

[MNT] CI on main fix: add checkout step to detect steps in CI

---

.github/workflows/test.yml
.github/workflows/test_all.yml
.github/workflows/test_base.yml
.github/workflows/test_datasets.yml
.github/workflows/test_module.yml
.github/workflows/test_other.yml

[MNT] Add codecov token to coverage uploads

---

sktime/classification/interval_based/_tsf.py

- Fixed typo identified by `codespell`
- Creating PR from branch in `sktime` repo to debug `codecov` upload issues

[MNT] fixed typo in docstring

---

docs/source/api_reference/regression.rst
sktime/regression/deep_learning/__init__.py
sktime/regression/deep_learning/fcn.py
sktime/regression/deep_learning/lstmfcn.py
sktime/regression/deep_learning/mlp.py
sktime/tests/_config.py

Part of https://github.com/sktime/sktime/issues/3351. See also https://github.com/sktime/sktime/pull/3365
Migrated FCN, MLP and LSTMFCN regressors to sktime from sktime-dl
No
None yet …

[ENH] Migrate DL regressors from `sktime-dl`: FCN, LSTMFCN, MLP

---

sktime/forecasting/compose/_hierarchy_ensemble.py

This PR improves formatting of the `HierarchyEnsembleForecaster` docstring.

[DOC] improved formatting of `HierarchyEnsembleForecaster` docstring

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.27.0
* changelog

Release 0.27.0

---

sktime/proba/t.py

@ivarzap forgot to add author credits in #5942, fixed.

[DOC] add missing author credits of @ivarzap

---

.github/workflows/wheels.yml

Instant release action - for quick release.
Temporary, should be reverted after 0.27.1

[MNT] instant release action

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.28.0
* changelog

Release 0.28.0

---

sktime/forecasting/tests/test_naive.py

Issue #3177 seems to be fixed. This PR is just adding a test. 
closes #3177
Adds a new test.
No
New test 

[BUG] Add regression test for bug 3177

---

.all-contributorsrc
sktime/transformations/series/augmenter.py

Adds to #4264 and partly addresses #4400
I added import statements to the `InvertAugmenter` example in the docstrings to improve copy-paste experience of a user.
No
Copy and paste property of the updated docstring example
No
None
See here for further details on the [algorithm …

[DOC] add import statements to the InvertAugmenter docstring

---

examples/02_classification.ipynb

[DOC] Redundant Code in tutorial section 2.2.4

---

sktime/classification/deep_learning/inceptiontime.py

Adding usage example to estimator  
In PR #6187 I had  added multiple  usage example, but due to some reason I'm not able to understand where test failing. so on this Pr I will added usage example one by one

[DOC] Adding Usage Example in docstring

---

sktime/performance_metrics/forecasting/probabilistic/_classes.py

This PR improves docstring formatting in some probabilistic metrics.

[DOC] improve docstring formatting in probabilistic metrics

---

README.md

This PR updates the time of Friday meetups in the readme.

[ENH] Update README.md - time of Friday meetups

---

sktime/forecasting/base/adapters/_neuralforecast.py
sktime/forecasting/neuralforecast.py

This PR is pure refactoring with no logic change.
1. created type alias for supported scaling methods
2. updated documented link to all optimisers instead of just Adam
3. added @geetu040 and @pranavvp16 in author section of the adapter
4. simplified `auto=True` logic by reducing nesting (requesting @geetu040 for a review)
5. changed variable names for readability and avoided unnecessary variables and conversions (requesting @pranavvp16 to take a look)

[MNT] Minor neuralforecast changes

---

.github/workflows/wheels.yml

Revert "[MNT] instant release action - temporary"

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.29.0
* changelog

Release 0.29.0

---

.github/actions/test-component/action.yml

Fixes #6352
This PR adds coverage of `sktime/tests` for per module CI workflows.

[MNT] include unit tests in `sktime/tests` in per module tests

---

sktime/datatypes/_adapter/dask_to_pd.py

[DOC] Correct docstring for conversion functions of dask_to_pd.py

---

docs/source/api_reference/forecasting.rst

Fast fix for documentation of hf forecaster that is not showing up on readthedocs
It fixes the HF documentation, that was not showing up on readthedocs
No

[BUG] Fix hf transformers documentation

---

.all-contributorsrc
docs/source/api_reference/transformations.rst
sktime/transformations/series/bollinger.py
sktime/transformations/series/tests/test_bollinger.py

closes #6320.
Implements the Bollinger Bands for a time series
No
- Code structure
- Code Location
- Do we need an "inv_transform" for this? When would we use that? …

[ENH] Bollinger Bands

---

sktime/transformations/series/adapt.py

This fixes #5867 .
Made changes to the TabularToSeriesAdaptor to check the case when transformer accepts only y(like LabelEncoder) and set tag accordingly. And a minor indexing fix on line 203.
No.
Yes.

[BUG] fix to make LabelEncoder compatible

---

sktime/utils/plotting.py

Reverts sktime/sktime#6416 - seems to fail the notebooks

Revert "[ENH], [BUG] utils/plotting.py: change plot_series() to use matplotlib conventions; enhance plot_interval()"

---

README.md
docs/source/about/team.rst
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py
sktime/forecasting/squaring_residuals.py

Release PR for 0.29.1
* changelog
* updated team: new core developer @Alex-JG3

Release 0.29.1

---

.github/workflows/wheels.yml

Revert "[MNT] fast release"

---

.github/workflows/test.yml
.github/workflows/test_all.yml
.github/workflows/test_base.yml
.github/workflows/test_datasets.yml
.github/workflows/test_module.yml
.github/workflows/test_other.yml
.github/workflows/wheels.yml

[MNT] drop test coverage on python 3.8 in CI

---

.all-contributorsrc
sktime/forecasting/model_selection/_tune.py

Fixes #6507  
- Fixes an error caused by dictionary unpacking on a list
- Removes numpy restriction on ForecastingSkoptSearchCV which was causing tests to be skipped
No
No, as bug already captured by existing tests (they were just skipped)

[BUG] Remove dict unpacking on list in tuning skopt

---

docs/source/changelog.rst

Adds the fix #6521 to the changelog for the 0.30.0 release.

[DOC] Update changelog for 0.30.0

---

docs/source/changelog.rst

Further changelog updates for release 0.30.0 to include dependabot updates

[MNT] further changelog updates for 0.30.0

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.30.1
* changelog
Intended to primarily contain https://github.com/sktime/sktime/pull/6535

Release 0.30.1

---

sktime/classification/sklearn/tests/test_all_classifiers.py
sktime/classification/tests/test_base.py
sktime/classification/tests/test_sklearn_compatibility.py
sktime/dists_kernels/tests/test_dist_kernels_dunders.py
sktime/tests/test_softdeps.py

Decorates tests in some base modules with differential testing switches.
Towards #2890.

[MNT] differential testing for base functionality in various modules

---

sktime/networks/fcn.py

Added two parameter sets for FCNNetwork. 
This is my first small contribution to sktime.
Hope to contribute more.

[ENH] added two test params sets to `FCNNetwork` on #3429 

---

sktime/datatypes/tests/test_convert_bugfixes.py
sktime/utils/tests/test_check_estimator.py
sktime/utils/tests/test_plotting.py

* adds a missed differential testing decorator in `datatypes`
* refactors `test_check_estimator` test, add conditional execution
* refactor tests for `plotting` module to fixtures, simplify skip conditions

[ENH] minor improvements to test efficiency

---

docs/source/developer_guide/dependencies.rst

Small PR. 
PR #6354 moved the location of the `_dependencies.py` file. This PR adjusts sources to changes.
dependency isolation, …

[DOC] update dependencies reference

---

sktime/transformations/base.py

Fixes https://github.com/sktime/sktime/issues/6687
Fixes a minor typo in a developer comment.

[DOC] fix minor typo in developer comment in `BaseTransformer`

---

sktime/benchmarking/forecasting.py

fixes #6559
add backend options to benchmarking and passes them to evaluate

[ENH] Parallelize ForecastingBenchmark

---

sktime/transformations/panel/rocket/_rocket_numba.py

PR with further `numpy 2` compatibility fixes in estimators
* deprecation of `npNINF` in rocket classifiers

[MNT] further `numpy 2` compatibility fixes in estimators

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.30.2, 0.31.0"

---

.all-contributorsrc
sktime/transformations/series/matrix_profile.py

#5938 
Adds authorship credit for Stumpy to MatrixProfileTransformer class
Nope :)
Did I spell the names right?
No
dependency …

[DOC] Add authorship credits to MatrixProfileTransformer for Stumpy authors

---

sktime/forecasting/arch/_statsforecast_arch.py

None
Add example sections to StatsForecastGARCH and StatsForecastARCH
No
No …

[DOC] add examples to `StatsForecastGARCH` docstring

---

docs/source/examples.rst
examples/06_distances_kernels_alignment.ipynb

None
Adds a notebook example for distancse, alignment, from pydata london 2023
Also creates a new example category: `Introduction` and moves the "Introduction to `sktime`" notebook to this category (top of page).
Negative.
Something requiring more attention
No
See here for …

[DOC] Add alignment notebook example

---

sktime/transformations/panel/dwt.py

docstring example for `DWTTransformer`

[DOC] improved docstring of `DWTTransformer`

---

docs/source/api_reference/tags.rst
docs/source/conf.py
sktime/registry/_tags.py

Reference umbrella issue : #6109 
Added a tag to identify capability of estimator to natively support categorical in X.
No.
No.

[ENH] Adding tag for categorical support in `X`

---

pyproject.toml
sktime/forecasting/pykan_forecaster.py

fixes #6784 
It adapts to the changes in `pykan`and set a lower version bounds. 
No

[BUG] Fix pykan dependency and set lower bound

---

pyproject.toml
sktime/alignment/edit_numba.py
sktime/annotation/ggs.py
sktime/classification/feature_based/_fresh_prince.py
sktime/classification/feature_based/_tsfresh_classifier.py
sktime/datasets/_single_problem_loaders.py
sktime/datasets/tsc_dataset_names.py
sktime/distances/_distance.py
sktime/distances/_dtw.py
sktime/distances/_msm.py
sktime/distances/_twe.py
sktime/distances/_wdtw.py
sktime/dists_kernels/edit_dist.py
sktime/forecasting/arima/_pmdarima.py
sktime/forecasting/croston.py
sktime/forecasting/ets.py
sktime/forecasting/exp_smoothing.py
sktime/forecasting/structural.py
sktime/forecasting/var.py
sktime/transformations/panel/_catch22_numba.py
sktime/transformations/series/outlier_detection.py
sktime/transformations/series/paa.py
sktime/transformations/series/sax.py

This PR adds the rule to check for non-unicode characters for the linting tool and run the pre-commit against all the files.

[ENH] add non-unicode characters check to the linter

---

sktime/datatypes/_check.py
sktime/datatypes/_convert.py

Also added a input checker for `to_type` inside the `convert` function inside `_convert`.
Relates to https://github.com/sktime/skpro/pull/432/

[DOC] updated docstring for `check_is_mtype` to match skpro `check_is_mtype` function

---

docs/source/developer_guide/git_workflow.rst

added recommendations about contribution from forks
1. avoid modifying `main`
2. use dedicated branches from `main` for separate tasks
3. delete merged local and remote branches in forks
4. use new branch from existing branch only if the new task depends on old task and old task PR is not merged yet

[DOC] added fork usage recommendations

---

sktime/utils/dependencies/_dependencies.py

This PR syncs the docstring and code formatting of the dependency checker module with the same module in `skbase`.

[MNT] sync docstring and code formatting of dependency checker module with `skbase`

---

.github/workflows/wheels.yml

Copy of https://github.com/sktime/skbase/pull/349

[MNT] release workflow: Upgrade deprecated pypa action parameter

---

sktime/utils/validation/forecasting.py

This PR makes minor improvements to the `check_scoring` docstring in terms of formatting.

[DOC] minor improvements to `check_scoring` docstring

---

build_tools/changelog.py

Makes small improvements to changelog generator utility:
* proper docstrings for parts of the module
* isolates imports to the functions

[ENH] small improvements to changelog generator utility

---

.github/actions/test-component/action.yml
.github/workflows/test.yml
.github/workflows/test_all.yml
.github/workflows/test_other.yml

Reverts changes from https://github.com/sktime/sktime/pull/6926 until we have diagnosed the issues.

[MNT] revert OSX install script changes #6926

---

.github/actions/test-component/action.yml
.github/workflows/test.yml
.github/workflows/test_all.yml
.github/workflows/test_other.yml

Combination of https://github.com/sktime/sktime/pull/6926 and https://github.com/sktime/sktime/pull/6933
Also same as revert of sktime/sktime#6935.

[MNT] Updating the GHA dependencies to install OSX dependencies and setting the compiler flags

---

sktime/forecasting/pytorchforecasting.py

[BUG] Reduce model size of pytorch-forecasting models

---

sktime/tests/_config.py

Updates "only 1 test param set" exception list, as that property may depend on soft dependencies present.

[MNT] update "only 1 test param set" exception list

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.31.1"

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py
sktime/forecasting/model_selection/_tune.py
sktime/utils/dependencies/_dependencies.py

Release PR for 0.32.1
* changelog

Release 0.32.1

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.32.1"

---

docs/source/changelog.rst

Added missing entry for `0.31.2` release in changelog of `main`.

[MNT] sync changelog with hotfix branch `anirban-sktime-0.31.2`

---

sktime/transformations/series/bollinger.py

This PR makes minor improvements to the docstring of the `Bollinger` (bands) transformation.

[DOC] minor improvements to docstring of `Bollinger` (bands)

---

sktime/datasets/_single_problem_loaders.py

converts the “date” column to a period with daily frequency in load_m5() function.

[ENH] Convert the “date” column to a period with daily frequency in `load_m5`

---

sktime/classification/base.py
sktime/clustering/base.py
sktime/clustering/utils/plotting/_plot_partitions.py
sktime/regression/base.py

This PR improves the docstrings for panel tasks - time series classification, regression, clustering:
* better formatting
* glossary links
* cross-reference to the new tags API
Fixes https://github.com/sktime/sktime/issues/6989

[DOC] improvements to docstrings for panel tasks - time series classification, regression, clustering

---

sktime/forecasting/enbpi.py

Fixes the incorrect import in the `EnbPIForecaster` docstring

[DOC] fix incorrect import in `EnbPIForecaster` docstring

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.32.2"

---

.github/workflows/wheels.yml

[MNT] insta-release action for 0.32.3

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.32.3
* changelog

Release 0.32.3

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.32.3"

---

sktime/forecasting/ttm.py

Update the docstring for parameter `model_path` to more informative info.

[DOC] Improve documentation for TinyTimeMixer

---

docs/source/developer_guide/continuous_integration.rst

This PR fixes all the broken links in continuos integration docs.

[DOC] fix broken links in continous integration docs

---

.github/workflows/wheels.yml

insta-release action for 0.32.4

[MNT] insta-release action for 0.32.4

---

README.md
docs/source/changelog.rst
docs/source/get_involved/governance.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.32.4
* changelog
* updated governance page with pointers to elections repo

Release 0.32.4

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.32.4"

---

.all-contributorsrc

this adds my profile to all_contributors file

[DOC] Updating all_contributors

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.33.0
* changelog

Release 0.33.0

---

.github/workflows/wheels.yml

Instant release action for 0.33.0

[MNT] insta-release action for 0.33.0

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.33.0"

---

.all-contributorsrc
sktime/clustering/kernel_k_means.py

Adds to #4264
Adds one docstring example to TimeSeriesKernelKMeans
No
No

[DOC] Added a docstring example to TimeSeriesKernelKMeans

---

docs/source/api_reference/clustering.rst
docs/source/developer_guide/git_workflow.rst

PR with minor documentation fixes.
* fixes formatting in git/GH workflow guide
* fixes API reference name of renamed `BaseTimeseriesLloyds`

[DOC] minor documentation fixes

---

pyproject.toml
sktime/forecasting/pykan_forecaster.py

fixes #7116 
* set the lower bound of pykan
* set the device only in initialization not during fit.
No

[BUG] Fix pykan forecaster

---

sktime/datasets/_fpp3_loaders.py

Quick fix for #7162, but does not resolve it since this PR does not resolve the stability and downwards compatibility problem.

[MNT] fix FPP3 download link

---

.github/workflows/wheels.yml

insta-release action for 0.33.1

[MNT] insta-release action for 0.33.1

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.33.1"

---

sktime/transformations/panel/hog1d.py

This PR adds an example to the class `HOG1DTransformer`.
Issue: https://github.com/sktime/sktime/issues/4264#issuecomment-2365029875

[DOC] Add example to `HOG1DTransformer`

---

sktime/transformations/series/filter.py

Added second parameters example to get_test_params of Filter.
#3429

[ENH] Added second parameters example to get_test_params of Filter

---

sktime/transformations/series/hurst.py

dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#add …

[DOC] Added docstring example for `HurstExponentTransformer`

---

README.md

#7262
Fixed minor grammatical errors in README.md
No, I did not add any tests as my changes are primarily focused on documentation and do not affect the codebase functionality. However, I have ensured that existing tests pass.
See here for further details on the [algorithm …

[DOC] Fixed minor grammatical errors in README.md

---

sktime/datatypes/_adapter/dask_to_pd.py
sktime/datatypes/_adapter/tests/test_dask_pd.py

Closes #7250 by adding missing import statement in `check_dask_frame`.

[BUG] fixed `dask.dataframe` import error in dask_to_pd.py script

---

sktime/split/slidingwindow.py

This PR clarifies the docstring of `SlidingWindowSplitter` by providing a proper mathematical description.

[DOC] `SlidingWindowSplitter` - proper mathematical description

---

.github/workflows/wheels.yml

insta-release action for 0.33.2

[MNT] insta-release action for 0.33.2

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.33.2"

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.34.0
* changelog

Release 0.34.0

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.34.0"

---

.all-contributorsrc
sktime/classification/kernel_based/_arsenal.py

#3429 
Added a second set of parameters to `get_test_params` in `_arsenal.py`.
No.
Whether the second set of test params make sense.
No.

[ENH] Added second test parameter to Arsenal classifier 

---

README.md

Fixed the position of the image which overlaps with the line.
earlier it was like this 
Now it is fixed like this 
dependency …

[DOC] Fixed sktime logo positioning in the README

---

sktime/tests/_config.py
sktime/transformations/panel/rocket/_multirocket_multivariate.py

Related #3429 
dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/depend …

[ENH] Adds parameter set in `_multirocket_multivariate`

---

.all-contributorsrc
examples/02_classification.ipynb

The description seemed copy-pasted from that of classification. Updated a couple of words
The description seemed copy-pasted from that of classification. Updated a couple of words
No
The 3 words I changed in the text
Not needed, only docs.

 [DOC] Small typo on explanation of regression

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/boxcox_bias_adjusted_forecaster.py

I have added adjust_bias parameter in BoxCox transformation in accordance with issue #2391 
Closes #2391 by following option 1 in #7287.

& talat-khattatov [ENH] box-cox bias adjustment for forecasters

---

sktime/split/singlewindow.py

Towards #7196 
I wrote a better documentation for this splitter.
No.
Making sure that the documentation is written correctly.
No. …

[DOC] provide proper mathematical description in docstring of sliding window splitter.

---

sktime/forecasting/neuralforecast.py
sktime/forecasting/tests/test_neuralforecast.py

Interfaced GRU, DilatedRNN and TCN estimators from `neuralforecast`.
Note: these have been added in same pull request to avoid conflict due to multiple pull requests modifying same file simultanneously.

[ENH] Interface new neuralforecast estimators

---

sktime/forecasting/base/adapters/_statsmodels.py

Fixes #7405
Discussion #6914
The bigger issue: #7416
It's not necessary to save all of `_y` and `_X`, but if memory conscious and using `set_config(remember_data=False)` prediction methods will not work. So saving only the necessary info to allow prediction.
- Saving the `_y` and `_X` info the way I am seems kind of arbitrary. Should everything go in `_y_metadata` (or the respective attribute for `_X` (if there is one)?
- Haven't but open to suggestions
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this …

[ENH] Reduce memory footprint of `statsmodels` adapter - save necessary `_y` info to remove need for `_y`

---

examples/07_detection_anomaly_changepoints.ipynb

This Pr fixes a few failing cells in detection notebook after the recent `skchange` update.

[DOC] fix failing cells in detection notebook after `skchange` update

---

README.md
docs/source/about/team.rst
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.35.0
* changelog
* update to core developers: @felipeangelimvieira joined (elected), @achieveordie left (inactivity)

Release 0.35.0

---

CODEOWNERS
docs/source/changelog.rst

* updates CODEOWNERS with new frequently active core devs
* adds the Chinese encoding codec fix in the css/read to the changelog

[MNT] release 0.35.0 - various minor additions

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release action for 0.34.1"

---

sktime/datatypes/_series/_check.py
sktime/datatypes/_series/_examples.py

Towards #7386 for `SeriesXarray`

[DOC] API reference documentation for `SeriesXarray` mtype

---

sktime/performance_metrics/forecasting/_classes.py

This PR reduces the requested metadata in forecasting metric input checks, making the input checks faster.

[ENH] reduce requested metadata in forecasting metric input check

---

sktime/datatypes/_series/_base.py
sktime/datatypes/_table/_check.py

Fixed docstring for TableNp1D class (https://github.com/sktime/sktime/issues/7386)
Added docstring for TableNp1D class.
No …

[DOC] API reference for `TableNp1D` mtype

---

docs/source/api_reference/detection.rst
sktime/detection/_datatypes/_examples.py
sktime/detection/dummy/_zero_seg.py
sktime/detection/naive/__init__.py
sktime/detection/naive/_threshold.py
sktime/detection/utils/_arr_to_seg.py
sktime/detection/utils/_seg_middle.py

This PR adds a naive thresholding anomaly detector, for testing and use in pipelines.
Very simple and different from `StatThresholdAnomalyDetector` as no aggregation is carried out, only a threshold is applied.
Also contains some fixes to logic and docstrings of utilities, and adds some private utilities to handling segmentations.

[ENH] naive thresholding detector

---

sktime/detection/base/_base.py
sktime/detection/clasp.py
sktime/detection/hmm.py

This PR adds input checks and conversions to the detection base class.

[ENH] detection base class input checks and conversions

---

sktime/detection/clasp.py
sktime/tests/_config.py

Fixes https://github.com/sktime/sktime/issues/7409

[ENH] `ClaSPSegmentation` fixes for new detection interface

---

sktime/detection/adapters/_pyod.py
sktime/tests/_config.py

Fixes https://github.com/sktime/sktime/issues/7413.

[ENH] `PyODDetector` fixes for new detector interface

---

sktime/benchmarking/forecasting.py

Fixes #6646
It exposes parameters from `evaluate` to `add_task` of forecastingBenchmark. 
Note `return_data` will probably exposed by #6718
No
* Does it makes sense to expose also strategy in 'add_task'. In the Issue we discussed to expose it via `__init__`. However, I think it makes more sense in `add_task`, since I might imagine that we want to vary it taskwise not for all tasks in one benchmark!
* I haven't exposed `cv_X`. Should I, I do not really see a use-case for this in benchmarking.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - …

[ENH] Expose `evaluate` params to `add_task` of forecasting benchmark

---

docs/source/conf.py

Fixes #7623 
Fixes invalid links on [https://www.sktime.net/en/stable/estimator_overview.html](https://www.sktime.net/en/stable/estimator_overview.html) for _sktime_developers_ tags

[DOC] Fixes #7623 Invalid Link 

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/_functions.py

Towards #4304 
Implemented efficient `_evaluate_by_index` for MedianSquaredError

[ENH] Implement efficient `_evaluate_by_index` for MedianSquaredError

---

sktime/forecasting/hf_transformers_forecaster.py

This makes minor formatting improvements to `hf_transformers_forecaster`, ensuring that the bullet points are rendered properly.

[DOC] minor formatting improvement in `hf_transformers_forecaster`

---

.all-contributorsrc
docs/source/about/team.rst

- Fixes #7630.
Previously, the link was interpreted as a relative path, leading to an incorrect redirection (https://www.sktime.net/en/stable/about/www.github.com/sktime/elections).
Updated the URL in the documentation (`docs/source/about/team.rst`) to include the full protocol (`https://`), ensuring the link is interpreted as an absolute URL.
https://github.com/sktime/elections
N/A
I verified that the link now correctly redirects to the [elections repository](https://github.com/sktime/elections)
N/A
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. …

[DOC] Fix invalid link to elections repository in sktime's website

---

sktime/datasets/_single_problem_loaders.py

This PR makes minor formatting improvements in the data loader docs.

[DOC] minor improvements in data loader docs

---

sktime/datatypes/_table/_check.py

Part of #7386 
Made the following changes for the datatype `TablePolarsEager`  -
- Added Short & Long Description for `TablePolarsEager`. 
- Added its capabilitites .

[DOC] Added Description for `TablePolarsEager`

---

sktime/base/_base.py
sktime/datatypes/_table/_check.py

@fkiraly 
As you pointed out, I fixed the rendering issues and fixed some from the base classes.

[DOC] Fixed `TablePolarsEager ` rendering issues related to recent merged PR #7666

---

docs/source/developer_guide/release.rst

Improves some formatting and formulations in the release manager guide - only minor changes.

[DOC] improved formatting and clarity in release manager guide

---

docs/source/developer_guide/git_workflow.rst

This PR makes a few small improvements to the git workflow guide:
* fix formatting for the bullet points at the start
* mention of GUI-based tools
* clarifying even more which parts are first-time vs every-time
* added note on when parts of first-time setup need to be repeated
* add note about avoiding a rebase

[DOC] improvements to git workflow guide, note about avoiding rebase

---

sktime/forecasting/pytorchforecasting.py

This is the same bugfix as PR #7639, except this is for the PytorchForecastingDeepAR class. That one was for the PytorchForecastingTFT class.
Bugfix similar to PR #7639, except this is for DeepAR. 
This simply fixes a bug in the example code in the documentation which couldn't be run if copy-pasting the code directly. The old code was attempting to slice a dataframe with two columns using only single brackets `[]`, but double brackets are required `[[]]`
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get …

[BUG] Fix typo in example code in documentation requiring double brackets to slice dataframe. DeepAR

---

.github/workflows/wheels.yml

instant release action for 0.35.1

[MNT] insta-release for 0.35.1

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release for 0.35.1"

---

sktime/forecasting/compose/_bagging.py

Fixes `BaggingForecaster.predict_proba`, a bug masked through https://github.com/sktime/sktime/issues/7787

[BUG] fix `BaggingForecaster.predict_proba`

---

sktime/datasets/_readers_writers/tsf.py
sktime/datasets/tests/test_datadownload.py

Closes #6388 
* adds missing frequencies to the load_forecastingdata.
* ensures that the frequency information is not removed if the multi index is created.
* adds tests for the fixed issues.
No
Yes

[BUG] Add missing frequencies to `load_forecastingdata`

---

sktime/datatypes/__init__.py
sktime/datatypes/_alignment/__init__.py
sktime/datatypes/_alignment/_check.py
sktime/datatypes/_alignment/_registry.py
sktime/datatypes/_check.py
sktime/datatypes/_hierarchical/__init__.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_hierarchical/_convert.py
sktime/datatypes/_hierarchical/_registry.py
sktime/datatypes/_panel/__init__.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_panel/_convert.py
sktime/datatypes/_panel/_registry.py
sktime/datatypes/_proba/__init__.py
sktime/datatypes/_proba/_check.py
sktime/datatypes/_proba/_convert.py
sktime/datatypes/_proba/_registry.py
sktime/datatypes/_registry.py
sktime/datatypes/_series/__init__.py
sktime/datatypes/_series/_check.py
sktime/datatypes/_series/_convert.py
sktime/datatypes/_series/_registry.py
sktime/datatypes/_table/__init__.py
sktime/datatypes/_table/_check.py
sktime/datatypes/_table/_convert.py
sktime/datatypes/_table/_registry.py
sktime/datatypes/tests/test_lookup.py

Revert "[ENH] refactor `datatypes` registry to `scikit-base` records"

---

sktime/tests/_config.py
sktime/transformations/panel/rocket/_minirocket.py

Towards https://github.com/sktime/sktime/issues/3429 - `MiniRocket`

[ENH] param sets for `MiniRocket`

---

docs/source/get_involved/contributing.rst

The link to the developer guide in the new contributor instructions was broken - this PR fixes that.

&yarnabrina [DOC] fix link to developer guide in new contributor instructions

---

sktime/tests/_config.py

Fixes #7859
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/sktime/sktime/pull/7860?shareId=e804b183-2a75-4d9a-b907-0732960ed114).

[BUG] Removes MiniRocket from EXCLUDED_TESTS_BY_TEST list to fix CI failures

---

pyproject.toml

replaced 3.12 with 3.13 in pyrpject.toml for tensorflow's max python version requirement
Fixes #7858 
Changed `'tensorflow<2.17,>=2; python_version < "3.12"'` to `'tensorflow<2.17,>=2; python_version < "3.13"'` everywhere in `pyproject.toml`
No
Referenced [Tensorflow's Release Notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1)
See here for …

[BUG] Update pyproject.toml to install tensorflow in uptil python 3.12

---

pyproject.toml
sktime/tests/_config.py

[MNT] Avoid skipping of unit tests of several forecasters

---

examples/transformation/fracdiff/example_prado.ipynb

Attempt to fix the examples link, fixes https://github.com/sktime/sktime/issues/7894

[DOC] fixing examples link

---

sktime/tests/_config.py

minor linting fix in `tests._config`

[ENH] minor linting fix in `tests._config`

---

sktime/classification/deep_learning/fcn.py
sktime/classification/deep_learning/mlp.py
sktime/classification/deep_learning/resnet.py
sktime/regression/deep_learning/mlp.py
sktime/regression/deep_learning/resnet.py

Fixes #7862 
Adds Wang et al. as in the references for the FCN classifier docs 
As pointed out by @fkiraly for checking for the FCN Regressor, I was unable to see their contribution towards it, so I have not added it there.

[DOC] `FCNClassifier` - add Wang et al reference

---

sktime/param_est/base.py
sktime/param_est/tests/test_all_param_est.py

This PR adds test suite coverage for the `update` method of parameter fitters.
This PR also fixes some bugs uncovered by adding the tests.

[ENH] test parameter estimator `update` in suite tests

---

.github/workflows/test.yml

Removes the compromised `tj-actions` GH action.
See https://github.com/sktime/sktime/issues/7988

[MNT] remove `tj-actions`

---

sktime/forecasting/model_evaluation/_functions.py

Minor linting improvement, deletes superfluous newline

[DOC] minor linting improvement

---

sktime/forecasting/base/adapters/_generalised_statsforecast.py
sktime/forecasting/tests/test_statsforecast.py

[BUG] ensure `statsforecast` adapter keeps track of trained forecaster

---

sktime/base/_panel/forest/tests/test_feature_importances_.py
sktime/base/_panel/forest/tests/test_tsf.py
sktime/classification/compose/tests/test_pipeline.py
sktime/forecasting/compose/tests/test_multiplex.py

This PR adds some missing adds some missing differential test skips

[ENH] add some missing differential test skips

---

sktime/transformations/series/tests/test_kalman_filter.py

Lints `test_kalman_filter` which accidentaly was merged unlinted.

[MNT] lint `test_kalman_filter`

---

.all-contributorsrc
CONTRIBUTORS.md
sktime/classification/deep_learning/fcn.py

Fix #8035 
Fix FCN as short for "Fully Convolutional Networks" …

[DOC] fix `FCNClassifier` docstring

---

sktime/tests/_config.py

This PR adds a temporary skip for `DistanceFeatures` until known failures https://github.com/sktime/sktime/issues/8077 are fixed.

[MNT] temporary skip for `DistanceFeatures` until fix of known failures

---

sktime/tests/test_all_estimators.py

This PR adds test case handling for a case missed in https://github.com/sktime/sktime/pull/8023

[ENH] catch `test_fit_idempotent` `predict_proba` soft dependency error

---

sktime/tests/test_all_estimators.py

Fixes a bug accidentally introduced in https://github.com/sktime/sktime/pull/8076

[BUG] catch `test_fit_idempotent` `predict_proba` soft dependency error - secondary fix

---

sktime/forecasting/base/_fh.py
sktime/forecasting/base/tests/test_fh.py

[BUG] fix timestamp format change in fh.to_absolute

---

sktime/forecasting/base/_fh.py
sktime/forecasting/base/tests/test_fh.py

Reverts sktime/sktime#7914 until https://github.com/sktime/sktime/issues/8087 is fixed

Revert "[BUG] fix timestamp format change in fh.to_absolute"

---

sktime/alignment/utils/utils_align.py
sktime/base/_meta.py
sktime/datasets/_single_problem_loaders.py
sktime/detection/lof.py
sktime/distances/_distance.py
sktime/forecasting/compose/_fhplex.py
sktime/forecasting/model_selection/_tune.py
sktime/libs/fracdiff/fdiff.py
sktime/libs/fracdiff/sklearn/tol.py
sktime/performance_metrics/detection/utils/_closest.py
sktime/performance_metrics/forecasting/_functions.py
sktime/utils/dependencies/_safe_import.py

Further fixes in docstring examples - functions

[DOC] docstring example fixes - functions

---

sktime/alignment/dtw_python.py
sktime/detection/clust.py
sktime/detection/lof.py
sktime/forecasting/enbpi.py
sktime/forecasting/model_selection/_tune.py
sktime/tests/_config.py
sktime/transformations/series/kalman_filter/_kalman_filter.py

This PR contains further fixes and skips of failing docstring examples.

[DOC] more docstring example fixes

---

.github/workflows/wheels.yml

instant release action for 0.36.1

[MNT] insta-release for 0.36.1

---

sktime/forecasting/compose/_fhplex.py

Fixes the `FhPlexForecaster` docstring example

[DOC] fix `FhPlexForecaster` docstring example

---

docs/source/changelog.rst

add missing contributor ot 0.36.1 release changelog

[DOC] add missing contributor ot 0.36.1 release changelog

---

sktime/forecasting/arch/_statsforecast_arch.py
sktime/forecasting/compose/_fhplex.py
sktime/forecasting/enbpi.py
sktime/tests/_config.py

Adds test skips for some known failing tests.

[MNT] skip some known failing tests

---

sktime/forecasting/es_rnn.py
sktime/forecasting/model_selection/_tune.py
sktime/tests/_config.py

Adds more docstring example fixes and test skips based on CI failures.

[MNT] docstring example fixes and test skips

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release for 0.36.1"

---

sktime/forecasting/model_selection/_tune.py

Removes an unisolated soft dependency from `ForecastingOptunaSearchCV` docstring example

[MNT] remove soft dependency from `ForecastingOptunaSearchCV` docstring example

---

sktime/utils/dependencies/_safe_import.py

This PR improves the formatting of the docstring of the `_safe_import` utility.

[ENH] improve formatting of `_safe_import` docstrings

---

sktime/forecasting/var_reduce.py

Improves the `VARReduce` docstring and fixes some formatting issues.

[DOC] improve `VARReduce` docstring

---

docs/source/developer_guide/continuous_integration.rst

Fixes #8190
as suggested by @gbilleyPeco

[DOC] Improves documentation in `Testing and continuous integration` webpage

---

sktime/transformations/series/outlier_detection.py
sktime/transformations/tests/test_hampelfilter.py

Fixes #8248.
It uses sktime's tag system to handle non-univariate data.
No.
Yes, a new one. HampelFilter was untested so far. …

[ENH] Simplify HampelFilter code and add a unit test

---

sktime/forecasting/dummy.py

Fixes #8256.
Use `names` instead of `name` in `pd.MultiIndex.from_tuples`.
No
No.
dependency isolation, see the [estimator …

[BUG] fix: use names keyword instead of name

---

sktime/libs/fracdiff/__init__.py
sktime/libs/fracdiff/sklearn/tol.py

Adds missing imports in the `fracdiff` docstrings.

[DOC] add missing imports in `fracdiff` docstrings

---

sktime/classification/distance_based/_time_series_neighbors_pyts.py

Fixes a typo in the `KNeighborsTimeSeriesClassifierTslearn` docstring

[DOC] fix `KNeighborsTimeSeriesClassifierTslearn` docstring

---

sktime/classification/foundation_models/momentfm.py

Fixes formatting and imports in the `MomentFMClassifier` docstring example

[DOC] fix `MomentFMClassifier` docstring example

---

.github/workflows/wheels.yml

instant release action for 0.37.1

[MNT] insta-release for 0.37.1

---

sktime/utils/dependencies/_dependencies.py

This PR fixes the `_check_soft_dependencies` error message if the right packages are present but the version is wrong.

[BUG] fix `_check_soft_dependencies` error message if version is wrong

---

docs/source/conf.py

@mateuszkasprowicz's excellent PR https://github.com/sktime/sktime/pull/8385 fixed the doc build, though as a side effect of simplifying it also removed a few extensions:
* extension required for links in changelogs, `sphinx_issues`
* extension required for panels and buttons in overviews, `sphinx_design`
These are added back in this PR.

[BUG] fix sphinx changelog link generation and panel overview

---

.github/workflows/wheels.yml

instant release action for 0.38.0

[MNT] insta-release for 0.38.0

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release for 0.38.1"

---

.github/workflows/wheels.yml

[MNT] insta-release for 0.38.3

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.38.3
* changelog

Release 0.38.3

---

.github/workflows/wheels.yml

Revert "[MNT] insta-release for 0.38.3"

---

sktime/tests/test_switch.py

PR https://github.com/sktime/sktime/pull/7087 works, but vm are spun up even if estimators do not have the tag `tests:core`.
This PR makes behaviour of the `tests:core` tag consistent across estimators that require VM and those that do not require VM:
a test for a non-core estimator requiring a VM - on its separate VM - is triggered only if the estimator itself changes.

[ENH] do not trigger VM tests for non-core estimators on framework changes

---

sktime/tests/test_switch.py

The `run_test_for_module` usage in `tests:libs` tag was buggy - if the tag was set, it would always trigger tests for the class, even if the `ONLY_CHANGED_MODULES` flag was passed to `run_test_for_class`
The reason for this was that `run_test_for_module` was getting its parameter from the global `ONLY_CHANGED_MODULES` and not from the input of `run_test_for_class` which called it - this has been fixed.

[BUG] fix `run_test_for_module` usage in `tests:libs` tag

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py
sktime/forecasting/base/_base.py

Release PR for 0.38.4
* changelog

Release 0.38.4

---

.github/workflows/wheels.yml

Revert "insta-release for 0.38.4"

---

.pre-commit-config.yaml

updated pre-commit hook versions

[MNT] pre-commit autoupdate

---

sktime/forecasting/statsforecast.py

1. adds some minor missing docs
2. removed the positional requirement from AutoTBATS interface

[ENH] Minor statsforecast updates

---

.github/workflows/wheels.yml

From https://github.com/sktime/skpro/pull/583#pullrequestreview-3131917702

[MNT] Check versions in wheels workflow

---

sktime/datasets/_fpp3_loaders.py

fpp3 dataset was updated on CRAN; updated loader to use the latest

[ENH] fpp3 dataset was updated on CRAN; updated loader to use the latest

---

sktime/forecasting/pykan_forecaster.py

`PykanForecaster` is currently not tested when changed - this PR enables a dedicated VM for testing the forecaster.

[ENH] add testing for `PykanForecaster`

---

sktime/transformations/compose/_arithmetic.py

updates deprecated tags for recently added `CombineTransformer`

[ENH] update tags for `CombineTransformer`

---

.github/workflows/wheels.yml

Revert "insta-release for 0.39.0"

---

sktime/datasets/_dataset_downloader.py

fixes syntax errors in the `DatasetDownloader` doctest

[BUG] fix `DatasetDownloader` doctest

---

sktime/datasets/tests/test_datadownload.py

Fixes #8879 
Skips test of `test_load_fpp3_public` when soft dependency `rdata` is not available.
no
See here for [full badge reference](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintai …

[ENH] only run `test_load_fpp3_public` when `rdata` is installed

---

sktime/tests/_config.py
sktime/transformations/series/lag.py

Added the second test parameter set for the `ReducerTransform` for the issue #3429

[ENH] ReducerTransform second test parameter set
