sktime/transformers/pca.py
sktime/transformers/tests/test_PCATransformer.py

Create PCA transformer
Implement a wrapper `PCATransformer` around `sklearn.decomposition.PCA` for column-wise PCA on time series formatted data. The transformer requires a univariate, equal length time series (i.e. DataFrame with one column and the same number of elements in each cell). Independent PCA of multiple columns can be performed using ColumnTransformer.
Examples:
```python
from sktime.datasets import load_gunpoint, load_basic_motions
from sktime.transformers.compose import ColumnTransformer
from sktime.transformers.pca import PCATransformer
X, y = load_gunpoint("TRAIN", True)
pca = PCATransformer()
pca.fit_transform(X)
X, y = load_basic_motions('TRAIN', True)
pcas = [("pca" + str(c), PCATransformer(), [c]) for c in range(X.shape[1])]
ctf = ColumnTransformer(transformers=pcas) …
```

PCATransformer

---

ESTIMATOR_OVERVIEW.md

Update of ESTIMATOR_OVERVIEW.md based on taxonomy discussion 2 weeks ago. Compiled all existing estimators in dev branch into categories based on scitype.
Does not include deep learning, kernel, or forecasting modules.

compiled existing estimators in ESTIMATOR_OVERVIEW ... finally

---

sktime/classifiers/interval_based/tsf.py

Initialisation of the `self.intervals` is `np.zeros((self.n_trees, 3*self.n_intervals, 2), dtype=int)` But it should be `np.zeros((self.n_trees, self.n_intervals, 2), dtype=int)` as the range of  `j` is `range(0, self.n_intervals)`

Fix in tsf classifier

---

docs/source/installation.rst

Fix: Update macOS advanced install instructions (#306)

---

CONTRIBUTING.rst
sktime/forecasting/compose/_reduce.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/trend.py
sktime/transformers/series_as_features/summarize/_extract.py
sktime/transformers/single_series/detrend/_detrend.py

Fixes #349 
Docstrings have been created for the following classes:
-  PolynomialTrendForecaster
-  DirectRegressionForecaster
-  DirectTimeSeriesRegressionForecaster
-  RecursiveRegressionForecaster
-  RecursiveTimeSeriesRegressionForecaster
-  ForecastingGridSearchCV
-  FittedParamExtractor
-  Detrender
No new dependences
N/A

Add missing docstrings to methods

---

conftest.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py
sktime/forecasting/tests/test_theta.py
sktime/forecasting/theta.py

Most of the code in `ThetaForecaster` for computing prediction intervals is applicable to all forecasters. I've moved that code out into the base classes (`_base.py` and `_sktime.py`), leaving only the parts that are specific to the Theta algorithm in `ThetaForecaster`.
An added benefit is that all forecasters will now have a `compute_pred_int` method, allowing for a common API. If the method hasn't been implemented for a forecaster, a `NotImplementedError` will be raised.
I wasn't sure whether my changes belonged in `_base.py` or `_sktime.py`. Let me know if I've got it wrong and I can change it.
No
The old `compute_pred_int` code had a minor bug in it. It's supposed to return a list of intervals if you provide an iterable of alphas. However if you provide an iterable of length 1, …

Move prediction interval API to base classes

---

sktime/datasets/__init__.py
sktime/datasets/base.py
sktime/datasets/tests/test_data_loaders.py

Adds feature mentioned in issue #425 to resolve it
Add the ability to download and use any dataset present on timeseriesclassification.com through a single function call. Following example is for downloading and loading the 'Car' dataset
```X, y = load_dataset_proxy("Car", split=None, return_X_y=True)```
N/A
I wasn't quite sure if I should convert ``_load_dataset`` function from a 'protected function' to a public function so I made a proxy function to access it for now, also I noticed by renaming it it would break certain tests, so I thought it would be best to ask how to proceed. This currently does not delete downloaded file types that are not used by sktime, let me know if it should delete irrelevant file types. Sorry if anything looks weird, I tried to follow the code guide as best I …

Added support for downloading dataset on demand through code

---

docs/source/conf.py
docs/source/index.rst
docs/source/related_software.rst

Fixes #419 
Move the list of related software from the wiki to the online documentation/website.

Moved related software from wiki to docs

---

sktime/utils/plotting/__init__.py

The function as written produces the following warning (which will become an error)
```
/usr/local/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
FutureWarning
```
Tested with 
sktime: '0.4.3'
seaborn: ''0.11.0'

Avoid seaborn warning

---

sktime/classification/frequency_based/_rise.py

Fixes #493.
This PR overrides the `feature_importances_` property for RISE to avoid calling `feature_importances_` from its parent class in scikit-learn and raising un-recognized errors.
No.

Implement the `feature_importances_` property for RISE

---

sktime/utils/plotting/__init__.py

Fixes #519 
As the issue points out, the x-axis labels don't match with the data points plotted. It turns out that mathplotlib recommends  [a different solution](https://matplotlib.org/examples/ticks_and_spines/tick_labels_from_values.html) for dynamically assigning tick labels from a list. I tweaked this code a bit to accommodate multiple series, which gives this result:
```
y = y[:48]
fh=np.arange(1, 13)
y_train, y_test = temporal_train_test_split(y, test_size=len(fh))
plot_series(y_train, y_test, labels=["y_train", "y_test"]);
print(y.shape, y_train.shape[0], y_test.shape[0])
print(y.index)
```
> (48,) 36 12
> PeriodIndex(['1949-01', '1949-02', '1949-03', '1949-04', '1949-05', '1949-06',
> '1949-07', '1949-08', '1949-09', '1949-10', '1949-11', '1949-12',
> '1950-01', …

Fix plot-series

---

.all-contributorsrc
sktime/forecasting/arima.py

Fixes https://github.com/alan-turing-institute/sktime/issues/522
As outlined in https://github.com/alan-turing-institute/sktime/issues/522, this fix allows using AutoARIMA with the sliding window forecaster along with Grid Search. This can allow for the search of the right hyperparameters such as sp.
No. `pmdarima` is already a soft dependency and this simply uses that.
- I tested locally in a notebook and it works. I am only familiar with `unittest` and had some issues setting up `pytest` on my end so I could not add a unit test specifically for this. If you could add it for me, I would appreciate it. The code is as follows
```python
y_train, y_test = temporal_train_test_split(y, test_size=36)
forecaster_param_grid = {'sp': [3, 12]}
forecaster = …
```

Fixed issue outlined in issue 522

---

build_tools/azure/check_soft_dependencies.py
build_tools/requirements.txt
setup.py
sktime/transformers/series/matrix_profile.py
sktime/transformers/tests/test_all_transformers.py

matrix_profile.py with soft dependency check for stumpy added
https://github.com/alan-turing-institute/sktime/issues/450
Interface and wrap stumpy.stump in series-to-series transformer.
No hard dependency, but stumpy is introduced as soft dependency

Added matrix profile using stumpy 

---

sktime/forecasting/model_selection/_split.py

Partially solves [Issue 477](https://github.com/alan-turing-institute/sktime/issues/477). This PR simply adds an example of the `SlidingWindowSplitter` folds to the docstring class.

Add SlidingWindowSplitter visualization on doctrings

---

.binder/requirements.txt
build_tools/hard_dependencies.txt
build_tools/requirements.txt

On Linux (manylinux) with Python 3.7, `sktime/forecasting/tests/test_ets.py` fails with `pandas==1.2.0` for some reason, see e.g. #559 
Pin pandas to `pandas==1.1.5`

Pin pandas version to fix pandas-related AutoETS error on Linux 

---

sktime/classification/distance_based/_time_series_neighbors.py

Fixes #608 . See also #596.
scikit learn changed how KNN works in v0.24. _fit(X) was replaced by _fit(X, y=None), with a test for a _tag whether 'requires_y' is true. this is called in sklearn/neighbors/_base.py function_fit. 
y is not actually required. Fixed by implementing
def _more_tags(self):
return {'requires_y': False}
this will overwrite the base class requires_y: True, since this function _get_tags is calls all _more_tags in the inheritance hierarchy in reverse order, from base class to self, using inspect.getmro, which seems to be pythons version of reflection.

Fixes _fit(X)

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py
sktime/forecasting/compose/_ensemble.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/_stack.py
sktime/forecasting/model_selection/tests/test_tune.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/forecasting/theta.py
sktime/transformations/series/detrend/_detrend.py
sktime/utils/datetime.py

Fixes #647. See also sktime/enhancement-proposals#8
- Makes `update_params=True` by default for all `update`-related forecasting methods.
- Implements a refit in the base Forecaster class when `update_params=True`
No
The behaviour of the Forecaster w.r.t. update is as follows:
First, the Forecaster calls `fit` on a time period `y_a=y1,y2,...,yN`
Then, when we call `update`, the Forecaster uses the new information, e.g. `y_b=yN+1,...,yN+k` along with the old information to update the model. If a custom `update` routine is not implemented, then we simply fit a new model on `y=concat(y_a,y_b)`.
Original test failures have been isolated to when `step_length > 1`. In this case, when `update_params=True`, the model attempts to refit on a concatenation of the previous data (e.g. daily from …

Make update_params=true by default

---

sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/distance_based/_time_series_neighbors.py
sktime/classification/distance_based/tests/test_time_series_neighbors.py
sktime/contrib/basic_benchmarking.py
sktime/contrib/dictionary_based/bop.py
sktime/contrib/experiments.py
sktime/contrib/shape_dtw/experiments/experiments_shape_dtw.py
sktime/distances/elastic.py
sktime/distances/elastic_cython.pyx
sktime/tests/_config.py

Those goes a way to addressing issues raised in #596
1. Fix the data representation
a common framework for check_X was introduced that includes a mechanism for coercing a pandas into a numpy array. This superceded the previous conversion used in the KNeighborsTimeSeriesClassifier. However, check_X converts to data[n][d][m] (n=num cases, d = num dimensions, m = series length), whereas this is set up to use data[n][m][d] to optimise vectorisation). The first fix is to correct this with a simple transpose
2. Fix default setting for MSM
MSM distance was defaulting the cost parameter c to 0. The tsml version uses 1, and this is preferable,
3. Remove the option for algorithm, only use "brute"
the two alternatives in sklearn knn are not usable with time series, and are hard coded that way. It is …

Knn transpose fix

---

sktime/utils/validation/forecasting.py
sktime/utils/validation/series.py

See #700 
There were inconsistencies in the docstrings, e.g. referring to `y` instead of `X`. See changes in the commit below.

Correct docstrings for check_X and related functions

---

.all-contributorsrc
CONTRIBUTING.md

Making it simpler for new users to directly link to installation steps from the CONTRIBUTING.md file
Adding in a few extra lines to the CONTRIBUTING.md documentation to help new users avoid some easy bugs that they may first encounter if they don't have the environment properly set up.  
No
Seeing if the edit is well positioned or should be changed
None
- [x ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ x] I've added unit tests and made sure they pass locally.
- None needed

changes to contributing.md to include directions to installation

---

.all-contributorsrc
.github/workflows/upload-to-pypi.yml

Fixes #607 
Relates to #723 #748 (@freddyaboulton FYI)
I see sktime [was uploading a source tarball in v0.4.3](https://pypi.org/project/sktime/0.4.3/#files) and prior, but [has not done so since that version](https://pypi.org/project/sktime/0.5.3/#files).
As a result, running `pip install sktime` on platforms for which sktime has not built a wheel (like mac OS 10.14) will install that older version of sktime, v0.4.3.
Uploading a source tarball to PyPI will enable `pip`-installation of future sktime releases on platforms for which sktime didn't upload a wheel.
Nope!
Check out [the console output from the last run of the PyPI upload action](https://github.com/alan-turing-institute/sktime/runs/1844683304?check_suite_focus=true) (for the v0.5.3 release). You can see it ran `python setup.py …

Upload source tarball to PyPI during releases

---

.all-contributorsrc
.gitattributes
sktime/forecasting/compose/tests/test_reduce.py

resolves #809
Take suggestions from this [discussion](https://github.com/github/linguist/discussions/5323#discussioncomment-610376) to recursively mark all downstream directories as vendored.
As mentioned in this discussion, in order to trigger the language discovery appropriately, we have to push other changes along with this PR. Therefore, I have modified the config for all-contributors, removing my previous account that causes the duplicates in [CONTRIBUTORS.md](https://github.com/alan-turing-institute/sktime/blob/main/CONTRIBUTORS.md).

Fix counting for Github's automatic language discovery

---

.all-contributorsrc
.binder/requirements.txt
build_tools/requirements.txt
setup.py

Reverts hotfix from #828 (also see alkaline-ml/pmdarima#423) and pins so `pmdarima 1.8.1` is avoided.
Removes the need for the hotfix and keeps `numpy` compatibility.
No, just fixes an existing one 🙂 
N/A
Sorry I pushed a bad `pmdarima` version yesterday 😅

Undo pmdarima hotfix and avoid pmdarima 1.8.1

---

sktime/forecasting/tests/test_theta.py
sktime/forecasting/theta.py

Fixes #692
ThetaForecaster works when passed an initial_level, passed initialization_method parameter to ExponentialSmoothing
NA
Is this a better fix or should I receive it from the user? 
Refer: https://github.com/alan-turing-institute/sktime/issues/692#issuecomment-811197573

ThetaForecaster now works with initial_level

---

README.rst
azure-pipelines.yml

* Fix broken manylinux builds by skipping Python 3.10 which was recently added to the manylinux image. 
* Fix badge for supported Python version (thanks to discussion in #664)
I initially thought this is related to numba (hence the branch name), but it wasn't.

Exclude Python 3.10 from manylinux CI 

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py
sktime/forecasting/base/adapters/_pmdarima.py

…rizon.
I updated the docstrings of the following methods to inform that they accept `fh=ForecastingHorizon`.
```python
sktime.forecasting.base._base.BaseForecaster.fit()
sktime.forecasting.base._base.BaseForecaster.predict()
sktime.forecasting.base._base.BaseForecaster.score()
sktime.forecasting.base._sktime._SktimeForecaster._set_fh()
sktime.forecasting.base._sktime._SktimeForecaster.predict()
sktime.forecasting.base._sktime._SktimeForecaster.update_predict_single()
sktime.forecasting.base._sktime._OptionalForecastingHorizonMixin._set_fh()
sktime.forecasting.base._sktime._RequiredForecastingHorizonMixin._set_fh()
sktime.forecasting.base.adapters._pmdarima._PmdArimaAdapter.fit()
```
No.

[DOC] Updated docstrings to inform that methods accept ForecastingHorizon

---

.all-contributorsrc
sktime/forecasting/base/tests/test_fh.py
sktime/utils/datetime.py

Add support for non-unit frequencies (eg: 30 minutes) by parsing the pandas frequency and extracting the relevant values to pass on to pd.Timedelta().
This works for frequencies like `D` and `3D`, as demonstrated by the test.
This does not work with [anchored offsets](https://pandas.pydata.org/docs/user_guide/timeseries.html#anchored-offsets), like the `W-SUN` mentioned in #866, as it's not immediately obvious to me how one would construct a correct Timedelta from this. I suspect that the anchor can simply be dropped (7 days are 7 days, no matter whether they start on Sunday or Monday), but I'm not entirely sure, and I had a hard time constructing a test example.
Fixes: #868

datetime: Construct Timedelta from parsed pandas frequency

---

.all-contributorsrc
sktime/classification/shapelet_based/mrseql/SNode.h

Fixes #913
On certain OS's, installing with `pip install sktime` gives:
```
sktime/classification/shapelet_based/mrseql/SNode.cpp:89:39:
error: ‘numeric_limits’ is not a member of ‘std’
89 | totalWildcardLimit = std::numeric_limits<int>::max();
|                           ^~~~~~~~~~~~~~
sktime/classification/shapelet_based/mrseql/SNode.cpp:89:54:
error: expected primary-expression before ‘int’
89 | totalWildcardLimit = std::numeric_limits<int>::max();
|                                          ^~~
```
By "certain OS's", this happened on an up to date Arch Linux system:
python: 3.9.5
gcc: 11.1.0

Add limits.h to ensure pip install on certain OS's

---

sktime/transformations/series/boxcox.py

Fixes minor typos in `transformations/series/boxcox.py`
No.
The function `_eval_pearsonr` is an inline function, I've slightly changed the docstring, but haven't converted it to a standard function docstr. Is it ok?

Fix minor typos in docstrings

---

sktime/forecasting/compose/_reduce.py

Step length hyper-parameter is still in the code even though it cannot be set anymore after refactoring in #345

Remove step_length hyper-parameter from reduction classes

---

sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/base/adapters/_statsmodels.py
sktime/forecasting/base/adapters/_tbats.py
sktime/forecasting/compose/_ensemble.py
sktime/forecasting/compose/_multiplexer.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/_stack.py
sktime/forecasting/hcrystalball.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/naive.py
sktime/forecasting/trend.py
sktime/transformations/series/detrend/_deseasonalize.py
sktime/transformations/series/detrend/_detrend.py

This is a minuscule change which is a preemptive fix.
The change sets `self._is_fitted = False` in the first line of `fit`, of a number of forecasters, before the input checks.
This prevents some unexpected behaviour when `fit`, of the estimator, is called multiple times in sequence, e.g., in grid search (as in the tutorial notebook).
It also prevents exceptions caused by this unexpected behaviour in any future refactor (e.g., #912) where `_set_fh` uses `_is_fitted` to check whether an `fh` is expected.
This should be done in all forecasters.

minor bugfix - setting _is_fitted to False before input checks in forecasters

---

sktime/forecasting/base/_base.py
sktime/forecasting/naive.py

This is an exemplary refactor of a concrete estimator class, `NaiveForecaster`, to explore how general concrete forecaster refactors would work, along the lines discussed in #912.
This PR changes:
* `_BaseWindowForecaster` still inherits from `BaseForecaster` directly, and already looked extension spec compliant (no overrides, no tags)
* `NaiveForecaster` inherits from `_BaseWindowForecaster`, and has been made extension spec compliant by adding the `requires-fh-in-fit` tag, and moving core logic from `fit` to `_fit`, while avoiding to override `fit`
* it adds one line in `BaseForecaster.fit`, as a general change: the `cutoff` is set to the latest `y` index using `_set_cutoff`. This is done pre-`_fit`, which could override the set cut-off.

Exemplary concrete estimator refactor post interface refactor, of NaiveForecaster

---

CODEOWNERS

This minuscule PR adds me as a codeowner for anything going on in `forecasting/base`, i.e., I'll get auto-PR reviews on any changes to the forecasting base/template interface.
As discussed with @mloning (who is current codeowner).
Also FYI, @aiwalter, @TonyBagnall.

adding fkiraly as codeowner for forecasting base classes

---

sktime/forecasting/hcrystalball.py

refactors HCrystallBall Forecaster

---

sktime/forecasting/base/adapters/_fbprophet.py

Refactor Prophet

---

sktime/forecasting/base/adapters/_pmdarima.py

refactors PmdArimaAdapter

---

sktime/forecasting/compose/_ensemble.py
sktime/forecasting/online_learning/_online_ensemble.py
sktime/forecasting/online_learning/_prediction_weighted_ensembler.py

Refactors ensembler, online-ensembler-forecaster and descendants

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/_functions.py
sktime/performance_metrics/tests/test_performance_metrics_forecasting.py

Fixes #959, as well as a bug in _RelativeLossMixin that was discovered when adding docstring examples. 
Bug meant that RelativeLoss class's relative_loss_function parameter was not being passed to underlying function; therefore, default (mean_absolute_error) was always being used.
Addresses the docstring issues (with `y_true`, `y_pred`, and `y_train`) in #959. Also improves docstring formatting (see References section) and tweaks docstring explanations to improve clarity in some cases. Adds examples to docstrings that were missing examples (relative_loss, RelativeLoss, mean_asymmetric_error, MeanAsymmetricError).
In addition to docstring cleanup, a bug in _RelativeLossMixin that was identified when creating docstring examples was corrected. 
No new dependencies.

Cleanup metric docstrings and fix bug in _RelativeLossMixin

---

sktime/dists_kernels/_base.py
sktime/dists_kernels/compose_tab_to_panel.py
sktime/dists_kernels/scipy_dist.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/dists_kernels/tests/test_compose_tab_to_panel.py
sktime/dists_kernels/tests/test_scipy_dist.py
sktime/registry/_base_classes.py
sktime/tests/_config.py
sktime/utils/_testing/panel.py

Tests to go along side the PR #1071 @fkiraly 
Implements basic tests for general transformers and specific tests for the scipy_dist pairwise transformer.
Is this enough I can add more but felt for now keep it simple until we see where this goes fully.

Pairwise transformers tests

---

CODEOWNERS

@mloning, a while ago when I added myself as code owner of `forecasting/base`, I did not realize that this would overwrite your "general" code owner tag. That is, you don't receive auto-review invites for `forecasting/base` anymore.
I fixed this, and also added @aiwalter who has been closely involved with the foreasting module's design.

added mloning and aiwalter as forecasting/base code owners

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py

Some small changes to the forecasting base class and template:
* updates to docstrings, clarifications
* added `fit_predict` method which does what one would "obviously" expect, fitting & forecast in one step.

Forecasting: base/template docstring fixes, added fit_predict method

---

sktime/transformations/series/compose.py

`OptionalPassthrough` transformer was only accepting `pd.Series`. This was fixed to also accept `pd.DataFrame`
___

Make OptionalPassthrough to support multivariate input

---

sktime/base/_base.py

This is a bugfix to `BaseObject.clone_tags`.
`set_tags` was called incorrectly from `clone_tags` without the kwargs symbol.

[bugfix] `set_tags` call in `BaseObject.clone_tags` used incorrect signature

---

sktime/forecasting/base/convertIO/_convertIO.py

The pd.DataFrame->pd.Series conversion was incorrectly missing from `_convertIO` (from #980), this is fixed now.

bugfix - pd.DataFrame->pd.Series conversion missing

---

sktime/forecasting/base/convertIO/_convertIO.py

Some references in the converter module (from #980) where mistakenly to the function `np.array` instead of the array type `np.ndarray`. This is now fixed.

bugfix - convertIO broken references to np.ndarray

---

.appveyor.yml

Fixes #1252 
* Pin Python patch version for Python 3.8 builds on appveyor to Python 3.8.10 (avoiding 3.8.11 for now due to failing builds)

Fix appveyor CI

---

README.md
docs/source/installation.rst

This PR addes the new `conda-forge` recipe for maximum dependencies to installation guidelines and README, in follow-up of #1142.
It also adds the `pip` option with maximum dependences to the README.

[DOC] add conda-forge max dependency recipe to installation and readme

---

extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py

I just noticed that the `_transform` docstrings were switched around between distances/kernels on tabular data and those on time series.
Fixed that, together with some other, minor things.

[DOC] docstring fix for distances/series extension templates

---

sktime/forecasting/tests/test_all_forecasters.py

if the estimator has the tag scitype:y = multivariate, the test example should have 2 columns and should have 1 column if univariate.

checks invalid X type for y multivariate and univariate

---

.binder/prelim_requirements.txt

An attempt to address #1342 by reverting `numba` and `numpy` version bounds to pre #1266 values

bugfix - broken binder and test_examples check

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py

This updates all extension templates with a section in the constructor that explain how to set/override tags for the object (not the class).
Further changes fix the docstrings in the clustering extension template.

[DOC] updated extension templates - object tags

---

sktime/forecasting/compose/_column_ensemble.py
sktime/tests/_config.py

This extends `ColumnEnsembleForecaster` so the same forecaster is cloned across all columns if not a list of forecasters is passed, but just a single forecaster, as the `forecasters` parameter.
This is achieved by a change in the `_check_forecasters` that is called at the start of `_fit`, which, at the very start, replaced a single forecaster with clones per column in the old expected format.
We ought to merge this quickly, since the current signature of `ColumnEnsembleForecaster` prevents upgrading the forecaster tests to the multivariate case, which in turn is blocking VAR.
FYI @thayeylolu.

Updates ColumnEnsembleForecaster with "copy forecaster for all columns" functionality

---

sktime/forecasting/base/_base.py

`update_predict` was missing input checks on `y` and `X` compliant with multivariate forecasting, this has been added

forecasting: input checks in update_predict

---

sktime/utils/_testing/estimator_checks.py

The testing issue in #1347 highlighted that the tests refactor in #1361 was incomplete by oversight - `check_constructor` `test_all_estimators` suite was still referring to `ESTIMATOR_TEST_PARAMS` in `_config`.
This caused errors to be raised if a new implementation of `create_test_instance` deviated from the default parameter settings.
This should be fixed in this PR.

Fixed ESTIMATOR_TEST_PARAMS reference in `test_all_estimators`

---

sktime/datatypes/_check.py
sktime/datatypes/_series/_convert.py
sktime/forecasting/base/_base.py

This PR implements the change request from the last core developer meeting:
forecasters' `predict` will now return the forecast series in the `mtype` that is idential to the last `mtype` seen for `y`, in `fit` or `update`.
The PR also includes some clean-up of `check_is` in the `datatypes` module which is not necessary for the new feature but improves code quality. The utility `check_is` is called in the check that is changed.

Forecasting return type update: series in, series out

---

sktime/forecasting/naive.py

This fixes a bug uncovered by #1449 - the new multivariate `NaiveForecaster` from #1401 did not have an `update` method, which caused updated related tests to break.
Introduction of this bug was obscured by introduction of a bug in the tests, resolved by #1449.

[BUG] multivariate `NaiveForecaster` was missing `update`

---

sktime/forecasting/model_selection/_split.py

Bad style case distinction and variable overwrite caused the entire `DataFrame` to be passed to `check_time_index` in `_check_y` of the splitters.
This is one of the cause of undetected failures in #1449.
This is now fixed.

[BUG] model_selection/split passed the entire DataFrame as index if DataFrame was provided

---

.all-contributorsrc
sktime/datatypes/_panel/_examples.py

Fixes #1452  [#1452](https://github.com/alan-turing-institute/sktime/issues/1452)
`X.iloc[0][1] = ...` and similar assignments will raise a
SettingWithCopy error in later versions of Pandas.
Refactor the respective lines for compatibility
up to v1.3.3 while maintaining same value assignments to dataframe
No new dependency
Refactor should produce same result and behaviour as previous code intended

Refactor sktime/.../_panels/_examples.py for tsai compatibility

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py
sktime/base/_base.py
sktime/base/tests/test_base.py
sktime/classification/base.py
sktime/forecasting/base/_base.py
sktime/forecasting/model_selection/_tune.py
sktime/registry/_tags.py
sktime/transformations/base.py

This adds the possibility to raise an error when `get_tag` is used.
An error will always be raised if the function is used with parameter defaults and the tag with the specified `tag_name` does not exist, but this can be overridden by setting the new `raise_error` parameter to `False`.
This should hopefully prevent the human error that caused the bug in #1449 for the future.
FYI @aiwalter, @thayeylolu, @mloning 
This PR also contains a second test for `get_tag` to cover the behaviour if `raise_error=True`, the old test covers the behaviour if `raise_errpr=False` with minor changes.
The change has caught the following bugs which are also fixed:
* `"enforce_index_type"` tag was sometimes written `"enforce-index-type"`, this was changed to `"enforce_index_type"` consistently
* transformer …

Error handling for `get_tag`

---

.appveyor.yml
.binder/requirements.txt
build_tools/hard_dependencies.txt
build_tools/requirements.txt
setup.py

This is a temporary fix for #1478, what looks like a bug introduced with `statsmodels` 0.13.0 through an interface hange that has not yet propagated to `tsfresh`.
Besides setting a max `statsmodels` version of 0.12.1 (the latest version before 0.13.0), it adds a `MAX_REQUIREMENTS` list to the `setup.py`.

1478 statsmodels max_requirements

---

docs/source/governance.rst

This PR makes minior changes to the governance document. It adds, for all roles:
* an "eligibility" section, which explicitly states conditions on role eligibility
* an "end of tenure" section, which describes how the tenure ends
In most cases, this has been already part of the respective sections, and just moved to a new section and/or explicitly clarified.

Governance: eligibility and end of tenure clarification

---

sktime/classification/feature_based/_catch22_classifier.py
sktime/classification/feature_based/tests/test_catch22_classifier.py

See #1235.
Speeds up the catch22 test a small amount. I think it is stuck with compiling the numerous numba functions in the catch22 file causing the majority of the remaining time, however.

Classifier test speed ups

---

sktime/contrib/vector_classifiers/_rotation_forest.py
sktime/datasets/_data_io.py
sktime/utils/data_io.py

Fixes #1603 
A few minor fixes
1. corrects a bug in contracted rotation forest: this was only a problem with small contracts and should not effect testing.
2. casts the target variable to numpy strings rather than Series strings when loading the concatenated train and test using load_UCR_UEA_dataset (#1603). This is needed to fix the problem in STC with numba, and it is more consistent, since these are returned when either train or test is loaded
3. removes the deprecation warning is data.io. tbh there is a lot in here that could be improved, so I think a gradual move over, with duplication is preferable
4. change the default return_X_y in load_UCR_UEA_dataset to True. I think its a legacy of Weka conversion to append the target variable, This could conceivably break something somewhere, …

load from UCR fix

---

sktime/utils/validation/panel.py
sktime/utils/validation/tests/test_panel.py

https://github.com/alan-turing-institute/sktime/issues/1596
This is a very simple fix to allow 2D numpy input to represent univariate, equal length time series, where each row is a series. If a 2D is passed, it is just converted in check_X to 3D. All the classifiers that only accept univariate equal length simply convert any input into a 2D numpy anyway, so this is the easiest way to allow for 2D input without having to change a large number of classifiers. I believe the conversion is a constant time operation i.e. it does not clone the data, but just changes the iteration (although feel free to disabuse me). I had meant to bring this in as part of a bigger change to the base classifier, https://github.com/alan-turing-institute/sktime/pull/1594 but I have run into some testing errors that …

convert 2D to 3D rather than throw exception

---

sktime/benchmarking/experiments.py
sktime/contrib/classification_experiments.py
sktime/contrib/clustering_experiments.py
sktime/contrib/set_classifier.py
sktime/contrib/set_clusterer.py

simple change to benchmarking/experiments.py to move set classifier and set clusterer into contrib. The problem they introduce (apart from ugly code and general poor usability) is to require all soft dependencies to run experiments.py. This is a pain. Now the actual classifier/clusterer has to be passed, and the string name is only used to set the results location.

Experiments tidy

---

sktime/benchmarking/tests/test_evaluator.py

Fixes #1651 
See also: #1198 
Updated asset condition to take into account column reordering. 
no
Sorry for all the additional edits but `pre-commit` made me do it.

Fix `test_wilcoxon` compatibility between pandas versions

---

.appveyor.yml
.binder/prelim_requirements.txt
build_tools/requirements.txt
setup.py

* Fixes stumpy>=1.5.1,<=1.9.2
When comparing the last successful appveyor run (https://ci.appveyor.com/project/mloning/sktime/builds/41606163/job/66bdyvexm97h7u07?fullLog=true) with the the next run after than (type hint changes) (https://ci.appveyor.com/project/mloning/sktime/builds/41607852/job/ov25h6yajbf2ibpm?fullLog=true), they both use different stumpy versions (0.9.2 and 0.10.0). 
appveyor runs used to take around 30-40 mins, they are now timing out after 1 hour.

Fix appveyor

---

sktime/alignment/tests/__init__.py
sktime/base/tests/__init__.py
sktime/datasets/tests/__init__.py
sktime/datatypes/tests/__init__.py
sktime/distances/tests/__init__.py

Related to #1661, #1699
* add missing init files identified via: `find sktime -type d '!' -exec test -e "{}/__init__.py" ";" -not -path "**/__pycache__" -not -path "**/datasets/data*" -print`

[FIX] Add missing init files

---

sktime/datatypes/__init__.py
sktime/datatypes/_check.py
sktime/dists_kernels/_base.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/dists_kernels/tests/test_compose_tab_to_panel.py
sktime/registry/_lookup.py

This PR makes the following two changes:
* introduces `check_is_scitype`, a shorthand counterpart of `check_is_mtype`, see also recent renaming in #1692
* replaces custom check/conversion functionality in pairwise transformers with `datatypes` functionality
The above refactoring also uncovered that the input conversions for `dists_kernels` were faulty:
* `numpy`/`DataFrame` conversions were using wrong order of `numpy` dimensions
* fixtures were `X` = 4-dimensional, `X2` = 5-dimensional panel which doesn't make sense for Euclidean distance (what is the distance between 4-vector and 5-vector??). This was not caught since the input conversions were faulty, and the same conversions were used in the tests.

check_is_scitype, cleaning up dists_kernels input checks/conversions

---

sktime/forecasting/base/adapters/_fbprophet.py

Fixes https://github.com/alan-turing-institute/sktime/issues/1673
- Reproduced the error described in  https://github.com/alan-turing-institute/sktime/issues/1673
- Creates a copy of X in _Prophet_Adapter before changes are made to it.
- Verified that the code snippet int he issue document a bug doesn't throw the error after this change.
- Checks if X contained a column ds were already implemented in _merge_X, so I didn't implement a new one
No

Fixes prophet bug concerning the internal change of exogenous X

---

sktime/forecasting/model_selection/_tune.py
sktime/transformations/base.py

Fixes #1697 by introducing the following base class behaviour: returning `pd.DataFrame` output if transform output is multivariate but input was `pd.Series`.

[ENH] transformer base class to allow multivariate output if input is always univariate

---

sktime/transformations/series/boxcox.py

Currently, passing multivariate `y` to the `BoxCoxTransformer` (refactored recently) will cause an error, since series-to-series transformers like it assume a univariate `y` by default, and a conversion is attempted to univariate `pd.Series` (which is impossible). This is unexpected, since the transformer ignores `y`.
This can be problematic in a `TransformedTargetPipeline` since there the forecaster's `X` - typically multivariate - is passed to the `y` of the transformers. (slightly surprising to me, but that's the status quo).
This implements a quick workaround, where the inner mtype for the `BoxCoxtransformer` is set to multivariate, that doesn't cause an error if a multivariate one is passed.
No other transformers are impacted currently, since `BoxCoxTransformer` is the only one …

[BUG] hotfix for bug when passing multivariate `y` to boxcox transformer

---

sktime/benchmarking/evaluation.py
sktime/benchmarking/orchestration.py
sktime/classification/compose/_ensemble.py
sktime/classification/distance_based/_time_series_neighbors.py
sktime/clustering/tests/test_cluster_averaging.py
sktime/contrib/vector_classifiers/_rotation_forest.py
sktime/forecasting/base/_fh.py
sktime/forecasting/base/tests/test_fh.py
sktime/forecasting/naive.py
sktime/transformations/base.py
sktime/transformations/panel/segment.py
sktime/utils/_testing/forecasting.py
sktime/utils/data_io.py
sktime/utils/datetime.py
sktime/utils/slope_and_trend.py
sktime/utils/validation/tests/test_panel.py

Take that, deprecation warnings.
This PR does what they were begging us to do since months - replacing deprecated `np.int` by `int` and `np.float` by `float`.
The deprecation message assures it's safe to do so ... let's see.

[ENH] replace deprecated np.int, np.float

---

sktime/forecasting/compose/_pipeline.py

Update: this is not a bug, as originally thought.
Following some discussion, I've added a deprecation message that was missing in `ForecastingPipeline` and changed the `Z` kwarg to first arg, to prevent the code breaking in 0.10.0.
---
I think the transformers refactor introduced a bug:
in series-to-series transformers, the order of arguments was not changed, but the names were.
So args calls are fine since downwards compatible, but kwargs calls may break.
One reference in the `ForecastingPipeline` was kwargs, which makes pipelines with any transformers that are not yet refactored break.
This PR fixes the issue, by replacing the kwargs reference with an args reference.
I've also searched the repository, there are no other kwargs references to the sub-set of transformers that had `Z` …

Add deprecation message to ambiguous arg reference in `ForecastingPipeline`, removed `Z` kwarg

---

sktime/utils/tests/test_datetime.py

Running
```
pytest sktime/utils/tests/test_datetime.py
```
produces a warning:
```
======================================================================================================= warnings summary =======================================================================================================
sktime/utils/tests/test_datetime.py::test_get_freq
/home/skhrapov/PycharmProjects/github/sktime/sktime/utils/tests/test_datetime.py:21: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
x3 = pd.Series(
-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================================= 1 passed, 1 …
```

Fix DeprecationWarning of `pd.Series` in sktime/utils/tests/test_datetime.py:21

---

extension_templates/forecasting.py

Updates the extension template to account for changes introducing predict_quantiles.
No
This was included in another PR https://github.com/alan-turing-institute/sktime/pull/1579, but I am separating to make review easier. I have fixed some of the issues mentioned there.

Update extension template for predict_quantiles

---

sktime/datatypes/_check.py
sktime/datatypes/tests/test_check.py

In discrepancy to the docstring, by mistake, `check_is_mtype` did not actually return the scitype in its metadata dict.
This has been added.
In the future I'll probably refactor `check_is_mtype` and `check_is_scitype` to use the same internal logic and be semi-aliases, and introduce some tests - the scope of this PR is to only fix the bug (vs specification).

[BUG] `check_is_mtype` to return scitype

---

sktime/classification/base.py

This PR contains four minor changes to `BaseClassifier`:
* bugfix in `_check_classifier_input`, this was using `shape` of `X` assumed `numpy` or `pandas` instead of the `metadata["n_instances"]` field. This yields wrong results for `pd-multiindex` and potentially other mtypes.
* bugfix in `score`, this did not conduct any input checks or conversions on `X`
* docstrings updated to reflect the correct assumptions on input types - after refactor, `BaseClassifier` can handle all `Panel` input
* moved repeated, identical boilerplate code from `predict`, `predict_proba`, `score` into a new method `_check_convert_X_for_predict` (feel free to revert this if you don't like @TonyBagnall)

[ENH] bugfix in BaseClassifier, updated base class docstrings

---

sktime/forecasting/base/_base.py

There was a small mistake in `predict_interval` and `predict_quantiles` which would lead to buggy behaviour if `fh` was already passed in `fit`.
The problem was using `fh` (passed in the function) instead of using `self.fh` which contains the `fh` if it was already passed in `fit`.
I admit that this convention seems very counterintuitive and exists more out of historical legacy.
For this to be more consistent, we should perhaps move to a syntax
`fh = self._check_fh(fh)` instead of `self._set_fh(fh)`
(and expect all developers ot know that the latter modifies `self.fh` which must be used instead of `fh` after that)
However, this is not done in this PR, the scope is only to fix the inconsistency in `predict_interval` and `predict_quantiles`.
FYI, @kejsitake, @SveaMeyer13, @mloning, …

[BUG] fix fh -> self.fh in `predict_interval` and `predict_quantiles`

---

sktime/base/_base.py
sktime/forecasting/compose/_pipeline.py
sktime/tests/_config.py
sktime/tests/test_all_estimators.py

This PR extends functionality of the `test_all_estimators` test suite, specifically the fixture generation preamble `pytest_generate_tests`, to use all test instances and not just the first one returned by `create_test_instance`.
This is going to be useful for pipelines where we can have different instance cases, and to achieve better case coverage in terms of class parameters. So far we were restricted to covering a single parameter case which is quite brittle.
In terms of implementation, the current call to `create_test_instance` is replaced by a call to `get_test_params` and instance creation based on all parameter sets, not just one.
One minor design question that I have is whether the function `_create_all_test_instances` shouldn't actually be a method of `BaseObject` instead of …

[ENH] Testing all test instances in testing framework

---

sktime/datatypes/_registry.py

This PR extends the current function `datatypes.mtype_to_scitype` to accept not only `str` but also `list` of `str` arguments.
If a `list` of `str` argument is passed, the old function is applied to all elements (by recursion).
The function also has an argument `return_unique` now - if `False` (default), the behaviour si as above; if `True`, the returned list is made unique.
Further minor change to the function are full input checks
Separated this out, but this is now used in #1790 and will be useful in the hierarchical forecasting upgrade, too.

[ENH] upgraded mtype_to_scitype to list-like args

---

.pre-commit-config.yaml
build_tools/check_install_from_test_pypi.sh
docs/symlink_examples.sh

- yml formatting to precommit-config
- add shellcheck to precommit
- update precommit
- run shellcheck on shell scripts
Just a pre-commit dependency:
* https://github.com/shellcheck-py/shellcheck-py
* https://github.com/koalaman/shellcheck (web version: https://github.com/koalaman/shellcheck)
* VS Code extension: https://github.com/vscode-shellcheck/vscode-shellcheck

[MNT] Add shellcheck to pre-commit

---

sktime/classification/base.py

This PR removes unnecessary duplicated input checks from `BaseClassifier.score`.
Since `score` calls `predict`, which directly does the same input checks again at the beginning, this is superfluous.
It also caused a downstream error with `ColumnEnsembleClassifier` which is not yet refactored to the new interface, hence inherits the "univariate" tag despite being multivariate. Since the original `ColumnEnsembleClassifier` overrides `fit`/`predict` but not `score`, this will cause an exception if multivariate data are being passed to `score`.
The `score` function is used in notebook 3, and causes the notebook to break, hence.
This downstream error is also fixed by the removal of the duplication.

[BUG] remove duplicated input checks from `BaseClassifier.score`

---

sktime/classification/base.py
sktime/datatypes/_check.py

The `"mtype"` return field of the optional metadata dict returned by `check_is_scitype` was incorrectly always returning the integer 0 instead of the inferred mtype, due to a type.
This has been fixed in this PR.
The bug masked another bug in the new classifier base class introduced by PR https://github.com/alan-turing-institute/sktime/pull/1594: the `predict` etc (non-state changing) methods were writing to `self`, via the boilerplate code that, for some reason, stored the `check_is_mtype` metadata to `self` in the input checks.
This has been changed to merely using it temporarily, which fixes the masked bug, too.

[BUG] fixed mtype return field in `check_is_scitype`

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py
extension_templates/transformer.py

This PR updates documentation in all extension templates regarding `get_test_params`, to clarify:
* imports can be used, and they should happen inside the method
* purpose of `get_test_params` function, and usage details

[DOC] updated `get_test_params` extension template docs regarding imports

---

sktime/datatypes/_check.py
sktime/datatypes/_convert.py
sktime/datatypes/_examples.py
sktime/datatypes/_hierarchical/__init__.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_hierarchical/_convert.py
sktime/datatypes/_hierarchical/_examples.py
sktime/datatypes/_hierarchical/_registry.py
sktime/datatypes/_registry.py

This PR adds a scitype `Hierarchical` with a single mtype, with 2 or more levels of hierarchy.
The representation is a `pandas.DataFrame` with 3 or more levels, out of which the lowest one must correspond to an `sktime` supported time index type.
The scitype can be used in input checks and conversions.

[ENH] experimental: hierarchical time series scitype

---

sktime/classification/base.py
sktime/classification/interval_based/_risf.py
sktime/classification/interval_based/_tsf.py
sktime/classification/interval_based/tests/test_risf.py
sktime/classification/interval_based/tests/test_tsf.py
sktime/regression/interval_based/_tsf.py
sktime/series_as_features/base/estimators/interval_based/_tsf.py

fixes #1068 and fixes #1609 
also fixes #1589 
this adds wrapper methods for fit, predict and predict proba with the pattern used in https://github.com/alan-turing-institute/sktime/pull/1761
the problem is these classifiers use multiple inheritance, from BaseClassifier and sklearn classifiers. If we do not override the methods fit and predict then they are inherited from sklearn rather than BaseClassifier. These wrapper methods are the simplest way around this problem. They redirect fit to BaseClassifier fit. See #1761 for a discussion of alternatives. 
Not this also effects the TSF based regressor. This has been adapted to work, but the solution is temporary since  the BaseRegressor class will soon be refactored.
Also based on https://github.com/alan-turing-institute/sktime/issues/1589, …

[ENH] TSC refactor:  TSF, RSF

---

sktime/forecasting/exp_smoothing.py

This PR adds parameters of `statsmodels.tsa.holtwinters` in `fit` as loopthrough to `sktime`'s `ExponentialSmoothing` interface.
So far, only the constructor parameters were accessible, not the parameters in `fit`.
Solves #1845.

[ENH] add missing `fit` parameters to `statsmodels` Holt-Winters exponential smoothing interface

---

docs/source/installation.rst

In Install required packages section:
Running `pip install numpy=1.19.3` gives this error:
(base) C:\Development\alan-turing-institute\sktime>pip install numpy=1.19.3
ERROR: Invalid requirement: 'numpy=1.19.3'
Hint: = is not a valid operator. Did you mean == ?
Hence `pip install numpy=1.19.3` should be `pip install numpy==1.19.3`.

Fix typo in Setting up a development environment section

---

extension_templates/forecasting.py
extension_templates/transformer.py

This PR contains various corrections and updates to extension templates.
Forecasting extension template:
* clarified that `fh` in private methods is always `ForecastingHorizon`
* incorrect docstring for `update`, was copy-pasted from `predict`
* replaced "core logic" with proper descriptions of where this is called from. @chrisholder will be happy about this.
* uniformization of content, various minor improvments to formulation
Transformer extension template:
* docstrings for `transform` and `inverse_transform` were mixed up
* clarified that `self` return is reference to `self`

[DOC] updates to forecaster and transformer extension template

---

sktime/transformations/series/detrend/_detrend.py

The recent refactor of the detrender (part of transformers refactor #1795) introduced a mixup of variables X, y, Z.
The main difficulty is realizing that `X` and `y` of the transformer must be passed to `y` resp `X` of the forecaster, since `X` (of the transformer) is the series being detrended.
This was correct before the renaming of arguments in series transformers that moved `Z` to `y` and `y` to `X`. In the renaming, `y` was not correctly renamed to `X` internally.
This PR fixes that mixup, and straightens out the internal logic, too.

[BUG] fixing mixup of internal variables in detrender

---

sktime/registry/__init__.py
sktime/registry/_scitype.py
sktime/registry/tests/test_lookup.py

This PR adds a single utility `scitype` which produces the unique scitype string in `BASE_CLASS_REGISTER` and `BASE_CLASS_SCITYPE_LIST`, given a class or object inheriting from `BaseObject`.
This is useful in refacturing occurrences of this query which have been dealt with manually, for instance when combining a lookup call `all_estimators` or `all_tags` starting at the class, or for a near-future refactoring of `_make_args`.
This PR also introduces a test which links `scitype` to its (quasi) inverse, an existing utility function called `_check_estimator_type`.

[ENH] estimator scitype utility

---

sktime/alignment/dtw_python.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_meta.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/_stack.py
sktime/transformations/series/func_transform.py
sktime/transformations/series/theta.py
sktime/utils/validation/series.py

Testing using scenarios https://github.com/alan-turing-institute/sktime/pull/1833 has uncovered a number of bugs that went undetected due to limited input case coverage prior. The smaller ones are fixed here.
This does *not* assume the scenario testing PR which is still a draft.
Bugs fixed:
* bug in `StackingForecaster`: passing `X` raised `NotImplementedError`, while instead the argument `X` should have been ignored. In fact, `X` could have been used in the forecaster, which is what happens now.
* bug in `StackingForecaster`, `X` was passed to the `fh` argument of `_predict_forecasters`; `fh` was using `self.fh` and not input to `_fit` and `_predict` (which comes from `self.fh`, but it should be passed/referenced)
* the pipelines inheriting from `_Pipeline` were using a test case …

[BUG] bugfixes for various bugs discovered in scenario testing

---

sktime/utils/_testing/deep_equals.py

This PR extends the `deep_equals` utility used in testing with an optional second return argument, an error message that states at which location precisely two potentially highly nested objects are not equal.
This is useful since printouts in tests may involve `repr`-s of nested estimators or nested dicts, lists, tuples, which are really hard to parse. Already two dicts with 6 elements, where elements may be in different display order, can easily cause headache in reading the diagnostic output from a test failure.
This PR tries to alleviate that tedious, repeated staring at printouts of dicts, arrays, data frames and whatnot.

[ENH] Extended deep_equals, with precise indication of why equality fails

---

sktime/datatypes/_series_as_panel/_convert.py
sktime/transformations/base.py

This PR collects bugfixes and changes to `BaseTransformer` arising from #1854.
Bugfixes:
* the output logic for `Panel` returns of `_transform` and `_inverse_transform` was incorrect. The line that was introduced to deal with multivariate outputs when `Series` are passed accidentally blocked all `Panel` returns. The check is now done only if the return is `Series`.
* when a `Series` is passed to `transform` and the internal `_transform` supports only `Panel`, and the internal mtype is `nested_univ`, the back-conversion function `Panel`->`Series` could not cope, since it was not compatible with the `nested_univ` mtype. An additional `convert_to` fixes this.
* checks and conversion for `convert_Panel_to_Series`, was incorrect for `np.ndarray` input (3D `Panel` -> 2D, `Series`)
* relaxed …

[BUG] transformer base class changes and bugfixes

---

sktime/dists_kernels/_base.py
sktime/dists_kernels/dtw.py
sktime/registry/_tags.py
sktime/tests/_config.py
sktime/tests/test_all_estimators.py

This PR contains the new `sktime` native, `numba` based distances wrapped as composable distance classes in `dists_kernels`.
There is one new class, `DtwDist`, which wraps the four dynamic time warping distances in `distances` as `BaseEstimator` compatible objects in `dists_kernels`.
This PR also contains some minor modifications to the panel distance base class, `BasePairwiseTransformerPanel`, and testing:
* now allows arbitrary internal mtypes, since the `sktime` native distances require 3D `numpy`, not `df-list` internal format
* for that, moved `_pairwise_panel_x_check` into the class to be in line with other base classes' input checking and coercion
* `fit` related tests were escaped since before work on `BaseObject`. This has been removed, and remedied by adding the …

[ENH] Composable distances interface prototype for numba distance module

---

sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/trend.py

Fixes #1835
Fixed incorrect tags for exogenous variable support
No
Correct support for tags for exogenous variables.
NA

Fix for forecasting tags

---

sktime/classification/distance_based/_time_series_neighbors.py
sktime/datasets/_data_io.py
sktime/distances/lower_bounding.py

Fixes #1713  
Fixes #578
Fixes #1057 
Simple fix to allow for correct parameter setting with GridCV. It removes a temporary measure to allow KNN to pass tests and fixes thanks to the new distance factory. Note we should do some work on making the valid parameters clearer for the different distance measures
Below code all works
knn = KNeighborsTimeSeriesClassifier(distance="dtw", n_neighbors=1, distance_params={
"window":0.5})
knn2 = KNeighborsTimeSeriesClassifier(distance="dtw", n_neighbors=1)
param_matrix = {"distance_params": [{"window": x/10.0} for x in range(0,10)]
}
grid = GridSearchCV(knn2, param_grid=param_matrix, cv=2, scoring="accuracy")
grid.fit(x_train, y_train)
print(pd.DataFrame(grid.cv_results_))
print(grid)
print(" params after CV = ",knn2.get_params())
knn4 = …

[BUG] Knn bugfix to allow GridsearchCV and usage with column ensemble.

---

sktime/tests/test_all_estimators.py

An attempt at diagnosing #1941.
This PR removes a single individual test from `test_all_estimators`: `test_multiprocessing_idempotent`.
See also #1952.
Apparently, this renders the remote tests working again. Suggest this PR as a temporary fix.

Temporary fix for CI/CD: removal of `test_multiprocessing_idempotent`

---

sktime/forecasting/naive.py

This PR adds more testing parameters to `NaiveForecaster`, which now should cover all significant parameter cases.
This follows a report of @aiwalter that `NaiveForecaster` does not work with the parameter setting `sp=2`, with a failure in `_reshape_last_window_for_sp`.

[ENH] more testing parameters for `NaiveForecaster`

---

sktime/datatypes/_check.py
sktime/forecasting/base/_base.py
sktime/forecasting/compose/_pipeline.py
sktime/transformations/base.py
sktime/transformations/series/summarize.py

This PR adds 0.10.0 deprecation warnings and removes deprecation subjects scheduled for removal in 0.10.0:
* `MeanTransformer`, deprecated since 0.8.0, is removed
* `check_is` is deprecated and scheduled for removal in 0.11.0
* `Z` arg of series transformers is deprecated and scheduled for removal in 0.11.0
* `return_pred_int` arg of `predict` and related functions is deprecated and scheduled for removal in 0.11.0

0.10.0 deprecations and removals

---

docs/source/api_reference/classification.rst
docs/source/examples/02_classification_univariate.ipynb
docs/source/examples/03_classification_multivariate.ipynb
docs/source/examples/mrseql.ipynb

I did not realise there was a duplicate notebook in docs. MrSEQL has been deprecated with cython, hopefully it will come back at a later date, but this notebook should go

[BUG] remove MrSEQL notebook in docs

---

extension_templates/clustering.py

Fix broken import. Module was rename from `base.py` to `_base.py`.

[BUG] fix import on clustering extension template

---

pyproject.toml

This PR introduces an upper bound `scipy<1.8.0` to keep our CI breaking due to #1994.
One that is resolved, the upper bound can be relaxed.

[MNT] hotfix: scipy upper bound from 1.8.0

---

sktime/datasets/_data_io.py
sktime/datasets/_single_problem_loaders.py
sktime/distances/_numba_utils.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/transformations/panel/catch22.py
sktime/transformations/panel/padder.py

This PR replaces all deprecated `numpy.str` and `numpy.float` with `python` native `str` an `float`, respectively - as the deprecation message recommends.
This should turn off the annoying deprecation messages.
FYI @TonyBagnall, @chrisholder, @MatthewMiddlehurst, since this was all coming from the classification module.
Also adds/changes some docstrings in `PaddingTransformer` to be linting compliant.

[ENH] replace deprecated `np.str` and `np.float`

---

.github/workflows/test.yml
.github/workflows/wheels.yml
Makefile
pyproject.toml
sktime/tests/test_all_estimators.py

Update: upgrading this from a draft.
This PR removes `pytest-xdist` from CI-CD and adds back `test_multiprocessing_idempotent`.
This is based on the observation/conclusion that `pytest-xdist` is causing multiple strange interactions which lead to crashes and erroring out of our CI-CD under hard to specify conditions.
Implements https://github.com/alan-turing-institute/sktime/issues/2012 (also see there for further details)
---
Draft, attempt at diagnosing #1941 - removing `pytest-xdist`.
Also adds back `test_multiprocessing_idempotent` to see what happens.

[MNT] Remove `pytest-xdist` from CI-CD, un-skip `test_multiprocessing_idempotent`

---

sktime/classification/dictionary_based/_tde.py
sktime/classification/interval_based/_drcif.py
sktime/classification/kernel_based/_arsenal.py
sktime/contrib/vector_classifiers/_rotation_forest.py

Reverts the revert alan-turing-institute/sktime#2029
which is the same as adding #2020 back into the repository.
Checking whether the tests pass, with `test_multiprocessing_idempotent` removed.
FYI @MatthewMiddlehurst, @TonyBagnall

[MNT] Revert "Revert "HC2 component bugfixes""

---

sktime/datatypes/_panel/_convert.py

This PR fixes a bug in the old function `from_nested_to_multi_index` that is wrapped by `convert`/`convert_to`.
The bug occurs if any of the series in the data frame have names.
In this case, the corresponding rows are empty, up to the entire resultant data frame becoming empty if all series had names.
The reason is a call to the `pd.DataFrame(series, columns=sth)` constructor, assuming that passing a `columns` argument always renames the columns. This assumption is false - if the argument `series` already has names, sub-setting is attempted, leading to an empty `pd.DataFrame` if a name is present, but the name is not identical with the name(s) in `sth`.

[BUG] fix conversion of nested to multiindex if series have names

---

sktime/datatypes/_table/_check.py
sktime/datatypes/_table/_convert.py
sktime/datatypes/_table/_examples.py
sktime/datatypes/_table/_registry.py

This PR introduces two new mtypes for the `Table` scitype:
* a `pandas.Series` based mtype, `pd_Series_Table`, which has less conditions on the type than for time series (e.g., no ordered indices needed). This is being used in various components of classifiers, where `y` is a `pandas.Series` but without ordered time index.
* `list_of_dict`, which is a `list` of `dict` with the condition that all entries are primitive (`str`, `int`, or `float`). This is currently returned by bag of words type transformers, see discussion in #2064. Introduction of this type would make those transformers interface compliant.
FYI @patrickzib, @MatthewMiddlehurst

[ENH] new table mtypes: `pd.Series` based, `list` of `dict` (as used in bag of words transformers)

---

sktime/datatypes/_panel/_check.py

Bug can be seen in this code, that will pass with first group but fail with second.
```
import pandas as pd
from sktime.datasets import load_airline
from sktime.datatypes import get_examples
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.datatypes._panel._check import check_pdmultiindex_panel
y_pd = get_examples(mtype="pd.DataFrame", as_scitype="Series")[0]
y_series = get_examples(mtype="pd.Series", as_scitype="Series")[0]
y_multi = get_examples(mtype="pd-multiindex", as_scitype="Panel")[0]
y_train, y_test = temporal_train_test_split(y)
mi = pd.MultiIndex.from_product([[0], y.index], names=["instances", "timepoints"])
y_group1 = pd.DataFrame(y.values, index=mi, columns=["y"])
mi = pd.MultiIndex.from_product([[1], y.index], …
```

[BUG] Fixed bug with check_pdmultiindex_panel

---

docs/source/developer_guide.rst

Fixes #2129 
Moved bracket line (22) to same line as previous line (21). Text now aligned and next bullet point item formatted correctly
No

Updated developer_guide.rst

---

sktime/utils/tests/test_plotting.py

This adds `xfail` escapes to the stochastically failing tests on windows CI/CD reported in #2066.
Once the root cause is identified and the bug fixed, these `xfail`s should be removed.

[ENH] add xfails in `test_plotting` until #2066 is resolved

---

sktime/utils/tests/test_plotting.py

`xfail` does not resolve the failures in `test_plotting` since the tests are still executed and error out, `pytest` does not catch this.
This PR hence replaces `xfail` by `skip`.
Temporary fix for #2066, follows #2144.

[MNT] add skips in `test_plotting` until #2066 is resolved

---

sktime/utils/tests/test_plotting.py

This PR hence replaces adds `skip` to all tests in `test_plotting` - the #2066 issue seems to stochastically affect all tests in the file.
Temporary fix for #2066, follows #2144 and #2146.

[MNT] add skips to entirety of `test_plotting` until #2066 is resolved

---

sktime/forecasting/base/_sktime.py

Hierarchical data cannot be usefully returned as an np.ndarray without index information, since we will then lose the mapping of rows to individual instances of thed data. It is preferential to return data from a prediction function that already contains the correct multiindex featuring instances and  timepoints.
We will at a later timepoint include modification to the reduce class that will return multiindex information from prediction, see this prototoype.
You can see a working example here:
https://github.com/alan-turing-institute/sktime/pull/2074
see above
No.
- [x ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).

[ENH] _predict_fixed_cutoff for Hierarchical Data 

---

sktime/forecasting/theta.py

Contrary to specification `ThetaForecaster.predict_quantiles` changed object attributes - namely, an attribute `sigma_` was created in `self`. This was probably accidental.
The tests did not pick this up, since much of the generic test suite was deactivated for the new probabilistic forecasting methods.
This is being changed in https://github.com/alan-turing-institute/sktime/pull/2100, which picked up the issue.

[BUG] fixed state change caused by `ThetaForecaster.predict_quantiles`

---

sktime/utils/_testing/deep_equals.py

This PR makes a minor change to improve the error reporting of `deep_equals`.
In case dictionary key sets are found discrepant, the error message is now more informative - instead of displaying the two key sets, it now displays the difference explicitly.

[ENH] improved `deep_equals` return message if `dict`s are discrepant

---

sktime/alignment/dtw_python.py
sktime/clustering/k_shapes.py
sktime/clustering/kernel_k_means.py
sktime/clustering/metrics/averaging/_averaging.py
sktime/forecasting/arima.py
sktime/forecasting/base/adapters/_tbats.py
sktime/forecasting/bats.py
sktime/forecasting/fbprophet.py
sktime/forecasting/hcrystalball.py
sktime/forecasting/tbats.py
sktime/transformations/panel/signature_based/_compute.py
sktime/transformations/panel/tsfresh.py
sktime/transformations/series/matrix_profile.py
sktime/utils/validation/_dependencies.py

This PR is an attempt to address the doc build fails that @aiwalter had reported, i.e., empty/missing pages for estimators with soft dependencies. This was also reported earlier as #2013.
The way this is done is via a minor change to `_check_soft_dependencies`, which gets an additional argument `severity` that controls whether a warning is raised, or an exception.
The extended utility is then used as follows:
* called on module import, but raises only a warning, so execution does not terminate
* called additionally on class construction, with an exception.
That way, users as well as the doc build process can import classes, read docstrings, and will get an error only when the class is constructed. The informative error message is still raised at the earliest possible point in time.
This …

[BUG] Addressing doc build issue due to failed soft dependency imports

---

docs/source/developer_guide/coding_standards.rst

This updates the docs on soft dependency handling with the workflow implied by the fix in https://github.com/alan-turing-institute/sktime/pull/2170.
The main change is explaining that the check needs to be in two places, at the top of the module (warning), and in the estimator init (error).
Other, minor changes:
* restructuring of the "soft dependency" section, hopefully better to follow now
* removal of duplicate "deprecation" section, newer version is on the "deprecation" page

[DOC] updated soft dependency docs with two tier check

---

sktime/transformations/series/summarize.py

Fixes the first part of #2143 : replacing float variable names by str in pandas.DataFrame passed.
I trace the warning and find out in summarize.py, quantiles are presented as "float" while other features are represented as "str", and that is the root of this warning. So I transform these float numbers to string.
No.
All unit tests in 'classification' directory have passed. And here is the output:
```
======================================== test session starts ========================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-1.0.0
rootdir: /root/sktime_dev/sktime, configfile: setup.cfg
plugins: cov-3.0.0, xdist-2.5.0, forked-1.4.0
collected 1 item …
```

[BUG] dealing with sklearn 1.2 deprecation warnings and solving the first part

---

.all-contributorsrc
sktime/forecasting/tests/test_sktime_forecasters.py
sktime/utils/_testing/hierarchical.py

Fixes #2192.
Renamed three occurrences of the typo `same_cuttoff` in `_make_hierachical`, and one in a docstring of `test_oh_setting`.
I could not find any other occurrences in the code base (`grep -rn '.' -e 'cuttoff'`).

[BUG] Same cutoff typo-fix

---

sktime/forecasting/compose/_reduce.py

This PR fixes the `ignores-exogeneous-X` for reducers which seems to have been set incorrectly - it should be `False` since the `X` argument is being used in a non-trivial way, internally.
See https://github.com/alan-turing-institute/sktime/discussions/2184
FYI @ngupta23.

[BUG] fixed ignores-exogeneous-X tag for forecasting reducers

---

sktime/utils/_testing/deep_equals.py
sktime/utils/_testing/tests/test_deep_equals.py

This PR adds unit tests for the `deep_equals` utility which were not present so far.
Includes #2555 (`ForecastingHorizon` compatibility).

[ENH] unit tests for `deep_equals` utility

---

sktime/forecasting/compose/_multiplexer.py
sktime/forecasting/model_selection/_tune.py

This PR speeds up the two slowest docstring examples by reducing the size of data sets in those examples:
`ForecastingGridSearchCV` and `MultiplexForecaster`. This saves ca 60-90sec in testing (according to CI/CD and local timings).

[MNT] Faster docstring examples - `ForecastingGridSearchCV`, `MultiplexForecaster`

---

docs/source/get_involved/mentoring.rst

This PR complements the migration of the the sktime mentoring form from @mloning's gmail account to the sktime account.
For this, the link in the docs needs to be updated with the linkt to the migrated form.

[DOC] migrating mentoring form to sktime google docs

---

sktime/utils/sklearn.py
sktime/utils/tests/test_sklearn_typing.py

This PR contains the following typing utilities related to sklearn:
* a function `is_sklearn_estimator` which returns True/False whether the argument is an `sklearn` estimator.
* a function `sklearn_scitype` which returns a string (`"classifier"`, `"regressor"` etc) denoting the scitype of the estimator.
* four shorthances `is_sklearn_classifier`, for `is_sklearn_estimator` logical-and `sklearn_scitype` equal to certain scitype.
This can be used in type checking, as `sklearn_scitype` is closer to the use of `type`, and avoids `sklearn` imports of mixin classes.
Note: the logic is intentionally different from `sklearn.base.is_classifier` etc, as that assumes certain attributes to be set. The functions above do *not* assume that the argument is an `sklearn` estimator, and they check …

[ENH] sklearn typing util

---

sktime/datatypes/_convert.py
sktime/datatypes/_examples.py
sktime/datatypes/_registry.py

This PR adds pointers to the scitype and mtype registers, which contain the list of valid scitype and mtype strings, to all docstrings in the `datatypes` module that have arguments which need to be valid scitype or mtype strings.
In addition, this PR makes the `scitype` argument of `get_examples` optional, inferring `scitype` from `mtype`.

[DOC] add scitype/mtype register pointers to docstrings in datatypes

---

docs/source/about/team.rst
sktime/classification/hybrid/_hivecote_v1.py

fixes https://github.com/alan-turing-institute/sktime/issues/2213 (hopefully) by expanding the docstring comments about the implementationin hive-cote v1.0

[DOC] improved docstrings for HIVE-COTE v1.0

---

docs/source/developer_guide/add_estimators.rst

This PR contains a typo fix and a minor clarification in the estimator implementation guide.
The clarification is improving clarity of the section on using the sktime test suite in a third party module.

[DOC] typo fix and minor clarification in estimator implementation guide

---

extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This PR adds two simplified extension templates for forecasters and transformers - these cover the minimal case for a functional forecaster and transformer, removing all optional features. This is meant to reduce cognitive load in the "most common case" for extenders.
Further changes in this PR:
* todos added for file docstring and copyright notice in the extension templates (main and simplified)
* todo for forecaster docstring is now numpydoc compliant
* formatting fixes

[DOC] simplified extension templates for transformers and forecasters

---

sktime/transformations/bootstrap/_mbb.py

This PR fixes an error message and docstrings in `STLBootstrapTransformer`.
@ltsaprounis, can you kindly check whether the error message regarding `sp` is correct now?

[BUG] fixing `STLBootstrapTransformer` error message and docstrings

---

sktime/datatypes/_panel/_check.py

This PR relaxes the `pd-multiindex` mtype to allow arbitrary instance indices.
`STLBootstrapTransformer` was (sensibly) returning non-integer instance indices, this relaxation of the mtype now makes that interface compliant.

[ENH] Relaxing `pd-multiindex` mtype to allow string instance index

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/adapters/_pmdarima.py

@ngupta, thank you for bringing this bug to our attention, this fixes https://github.com/alan-turing-institute/sktime/issues/2275.
There were three interacting bugs that are now fixed:
* `BaseForecaster`'s default conversion of `predict_interval` to `predict_quantiles` was mathematically incorrect. It should have said `coverage = abs(1 - 2 * a)` but it said sth completely different. Not sure how that happened.
* `BaseForecaster`'s default conversion of `predict_interval` to `predict_quantiles` could break on occasion when two (float/numerically) identical coverages were produced, due to non-unique indexing. This should be fixed now.
* `ARIMA.predict_interval` was passing `coverage` as `alpha`, where `alpha` in `ARIMA` is in fact `1-coverage`. This has been fixed.
So, all should now …

[BUG] fix conversion interval->quantiles in `BaseForecaster`, and fix `ARIMA.predict_interval`

---

extension_templates/forecasting_simple.py

The simple forecasting extension template was not numpydoc compliant, since it was accidentally using a section "hyper-parameters". This has been fixed, and is now in line with the full forecasting extension template

[DOC] numpydoc compliance fix of simple forecasting extension template

---

sktime/datatypes/_vectorize.py
sktime/datatypes/tests/test_vectorize.py
sktime/forecasting/base/tests/test_base.py

Fixes #2194 
After a lot of debugging in #2224, I found that the tests are failing for Windows because the series obtained when looping through `VetorizedDF` have frequency `None` in Windows and `"D"` for both Linux and Mac. The fix is to  add a new function that uses `pd.infer_freq` to update the frequency of each series in `VetorizedDF.__getitem__`.

Fix windows bug with index freq in VetorizedDF.__getitem__

---

pyproject.toml

This PR fixes two recent CI issues:
* `pyproject` license field flagged as erroneous, by replacing the license field by a table
* readthedocs CI failure in https://github.com/alan-turing-institute/sktime/issues/2297, by upper bounding `jinja2` with 3.0.3 in the docs dependency set

[BUG] fixing pyproject and jinja2 CI failures

---

sktime/forecasting/base/_base.py

This PR fixes a merge accident that made it onto main.
There were two Returns sections in `_predict_var`, which is now corrected.
Emergency merge due to the problem being on main already.

[BUG] fixes duplication of Returns section in `_predict_var` docstring

---

sktime/transformations/series/adapt.py

This PR adds a boolean parameter `fit_in_transform` to `TabularToSeriesAdaptor`.
This lets a user choose whether `fit` is mapped on `fit`, or whether it is executed in `transform`.
The default setting defaults to `False`, which is the current behaviour, ensuring downwards compatibility.
The reason for that is as follows:
* when used in forecasting or on a single series, the most common use is usually `fit_in_transform=False`.
* when used in TSC or TSR, on a panel, the most common (intended) use is usually `fit_in_transform=True`, since the test indices/instances are usually considered distinct from the training indices/instances. Otherwise, the automatic vectorization from the base class will consider train and test indices identical, and refuse to `transform` if number or set of indices …

[ENH] Tabular transformer adaptor "fit in transform" parameter

---

docs/source/changelog.rst

Unfortunately, there was a typo in the 0.11.0 release notes which leads to bad formatting in the highlights section.
This PR fixes that.

[DOC] fix 0.11.0 release note highlights formatting

---

pyproject.toml

should be able to pass as soon as `jinja2` got a new release
#2297 #2299

[MNT] Remove jinja2 version

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py
sktime/utils/validation/forecasting.py

This PR adds an additional assumption to `predict_interval` and `predict_quantiles`: that values in potential lists `alpha` and `coverage` should be unique.
Related to discussion in https://github.com/alan-turing-institute/sktime/pull/2320.
Reason for adding these assumptions is that not all implemented methods may work if non-unique values are passed, e.g., if indexing of columns happens.
A check for uniqueness has been added to the utility `check_alpha`; docstrings, comments, and error messages have been improved.

[ENH] require uniqueness from multiple alpha/coverage in interval/quantile forecasts

---

extension_templates/classification.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

Fixes a systematic typo: contsructor -> constructor, in extension templates.
(accidental leftover of #2343 so I assume approval extends)

[DOC] typo fix contsructor -> constructor in extension templates

---

.pre-commit-config.yaml

`code-quality` checks in CI are failing due to an incompatibility ot `click` with the newest `black` version.
This PR follows the fix suggested in
https://github.com/psf/black/issues/2964
to restore `code-quality` CI functionality temporarily, until the incompatibility is fixed.

[BUG] pinning click due to incompatibility with newest black

---

sktime/tests/test_all_estimators.py

This PR changes the `raise_exception` flag in test fixture generation to True, such that test generation errors are raised (and the test suite not run) if there is a fixture generation error in test collection.
This should take off testing compute load from tests where the collection already crashes, and produce informative errors and tracebacks in those cases.

[ENH] test generation error to raise and not return

---

sktime/forecasting/base/_base.py

Fixes https://github.com/alan-turing-institute/sktime/issues/2361:
If no `fh` was passed in `fit`, and `update` was called with the default `_update`, it would break as it tried to read `self.fh` which would raise an error. Instead, `self_fh` should be read, which does not raise an error.

[BUG] fix `_update` default for late `fh` pass case

---

sktime/forecasting/base/_fh.py

closes #2338 
Extract `ForecastingHorizon.to_relative` and `ForecastingHorizon.to_absolute` to `_to_relative` and `_to_absolute`, respectively, to allow caching without B019 error.
No

[ENH] Extract cached `ForecastingHorizon` methods to functions and avoid B019 error

---

docs/source/installation.rst

Removed pip install instructions for `pmdarima` and `tbats` as they are now included in conda install by default
Closes #2350 
This PR is related to [conda-forge/sktime-feedstock/33](https://github.com/conda-forge/sktime-feedstock/pull/33).
The [conda-forge PR](https://github.com/conda-forge/sktime-feedstock/pull/33) adds `tbats` as dependency to conda install and `pmdarima` was already part of conda install. So, the docs have been updated accordingly by removing the pip installation instructions for the two packages.
No

[DOC] Updated conda installation instructions

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This PR:
* addresses #1578, by adding a link to the "writing sktime compatible estimator" documentation page
* updates the testing requirements stated to a reference to `check_estimator`

[DOC] updated extension templates: link to docs and reference to `check_estimator`

---

.pre-commit-config.yaml

`code-quality` checks in CI are failing due to an incompatibility ot `click` with the newest `black` version.
This bumps `black` to 22.3.0 for both code and notebook checks.
It also removes the pin on `click`, in an attempt to fix #2354.
This PR follows the fix suggested in
https://github.com/psf/black/issues/2964

[BUG] fixing click/black incompatibility in CI

---

sktime/transformations/compose.py
sktime/transformations/tests/test_compose.py

`FeatureUnion` was returning incorrect column labels due to a bad `str.join` command. This is now fixed.
The tests did not catch this since the format was correct, but not the number of columns.
This has been corrected, and a test has been added to ensure that `FeatureUnion` produces the right column names.

[BUG] FeatureUnion output column names fixed

---

sktime/forecasting/base/_base.py
sktime/forecasting/ets.py

This PR simplifies the probabilistic prediction functionality in `AutoETS`.
Previously, `_predict_quantiles` was implemented, but `AutoETS` returns intervals. Hence `_predict_quantiles` was removed and replaced by a more direct interface through `_predict_interval`.
By discussion below, the interface was previously correct, most probably, so this is merely a simplification of the logic.

[ENH] `AutoETS` prediction intervals simplification

---

sktime/dists_kernels/_base.py

This PR upgrades `BasePairwiseTransformer` to use `datatypes` input conversions and checks.
For this, it uses the `Table` mtype to refactor the logic to parallel almost exactly that of `BasePairwiseTransformerPanel`.
Consequently, there is no longer a dependency on custom input checks or the legacy `check_series` utility.

[ENH] upgrade `BasePairwiseTransformer` to use `datatypes` input conversions and checks

---

sktime/forecasting/naive.py

This small PR adds two things to `NaiveVariance`:
* a `verbose` arg which is by default `False`, suppressing the many warnings that are raised on toy data
* an explanation in the docstring which methods are added and how the wrapped estimator relates to the composite

[ENH] `NaiveVariance`: verbose arg and extended docstring

---

sktime/datatypes/_utilities.py

This PR fixes an unreported bug with `get_time_index`, as it would not work with most mtypes that it had claimed for in the docstring.
This should be fixed now.
I have not added tests, but that should be done soon.
Originally, in #2375, but factored it out due to the complexity of the issue with fixing the nested conversions.
FYI @danbartl

[BUG] fixed `get_time_index` for most mtypes

---

sktime/base/_meta.py
sktime/transformations/compose.py

This PR extends `_HeterogeneousMetaEstimator` estimator to optionally allow mixed tuple/estimator lists.
Detail changes:
* `_check_estimators` gets a new `allow_mix` argument, whether lists of mixed estimator/tuple type should be allowed. Default is now `True`.
* `get_estimator_sth` functions are refactored and extended to yield the correct result even in the mixed case
* `_is_name_and_trafo` utility is generalized to `_is_name_and_est` and moved to the `_HeterogeneousMetaEstimator`
As a result, concatenating two pipelines which different internal type (one tuple, one only estimator) should not cause problems anymore.
Since this relaxes input assumptions while retaining output guarantees for previously admissible inputs, this is fully downwards compatible and does not require deprecation.

[ENH] extend `_HeterogeneousMetaEstimator` estimator to allow mixed tuple/estimator list

---

sktime/forecasting/model_selection/tests/test_split.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/utils/tests/test_check_estimator.py

This PR adds tests to test that tests conducted by the `check_estimator` utlity are passing, on three example estimators that are known to pass all tests in the full test suite.
This ensures that future tests catch unintentional side effects to changes in the test module that cause a `check_estimator` test to fail, such as the problem addressed recently in https://github.com/alan-turing-institute/sktime/pull/2405
Also turns some instances of `pytest.skip` inside tests into `return None`, as that currently breaks `check_estimator`. An issue to replace this workaroudn has been opened here: https://github.com/alan-turing-institute/sktime/issues/2419

[ENH] tests for `check_estimator` tests passing

---

sktime/forecasting/arima.py
sktime/forecasting/base/adapters/_pmdarima.py

The "missing value" tag was incorrectly set in `ARIMA` and `AutoARIMA`, as reporte by @ngupta23 in https://github.com/alan-turing-institute/sktime/issues/2204
This has been confirmed and is now fixed.
Note to reviewers: I'm not setting the tag in the adapter class but in the concrete classes, to have the more conservative choice for any potential future model we interface from `pmdarima` by default.

[BUG] Sets "can handle missing value" tag in ARIMA and AutoARIMA

---

sktime/performance_metrics/forecasting/probabilistic/_classes.py
sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py

This PR:
* fixes a bug in probabilistic metrics, `score_average` was not written to `self`, and not passed to super
* adds a proper "return" field to the docstrings

[BUG] fixed `score_average` parameter of proba metrics, docstrings

---

sktime/alignment/dtw_python.py
sktime/registry/_lookup.py
sktime/utils/validation/_dependencies.py

issue #2386: 
registry.all_estimators shows deprecation warnings from module level in cases where estimators have been moved. These should by default not be raised, only a direct import of the deprecated location should raise these.
sktime/registry/_lookup.py
ignores warnings in all_estimators() by filtering out UserWarning matching regex ".*has been moved to.*"
no
issue #2385:
Every time one imports the dtw-python module, even when attempting to do so silently and with warning suppressed, the following is printed...
The print issue is here in dtw: https://github.com/DynamicTimeWarping/dtw-python/blob/master/dtw/__init__.py
sktime/utils/validation/_dependencies.py
_check_soft_dependencies imports with overwritten sys.stdout (setup text trap, imports, then restores) …

[ENH] suppressing deprecation messages in `all_estimators` estimator retrieval, address `dtw` import message

---

sktime/forecasting/compose/_pipeline.py
sktime/transformations/series/detrend/_detrend.py

In a case where `TransformedTargetForecaster` inverses were called, and more than one quantile was queried, the probabilistic predict methods would break.
The reason was that the `inverse_transform` of the transformers would be applied to a multivariate data frame (the output of the proba predict methods).
A workaround was using the `ColumnTransformer`, but that was not obvious to a user.
This has now been fixed by implementing column vectorization.
Going forward, we should consider implementing column vectorization out of the box, like we did with row instances.

[BUG] `TransformedTargetForecaster` inverses were not working for univariate transformers and more than one quantile

---

sktime/forecasting/compose/_pipeline.py

This PR fixes the fitting logic for postprocessing in `TransformedTargetForecaster`.
This is a functional bug since there was no exception raised, but the behaviour was incorrect.
The postprocessing transformers should be chain-fitted starting with the `X` passed in `fit`, not with the output of the pre-processing chain - this is because in `predict`, the pre-processing chain is inverted before it reaches the post-processing.

[BUG] fixed fitting logic for postprocessing in `TransformedTargetForecaster`

---

sktime/transformations/hierarchical/aggregate.py

The `Aggregator` incorrectly assumed that all levels of the hierarchy were named.
This made it near impossible to use it in certain relevant pipelines.
This PR introduces a workaround which names the levels at the start and reverts to the original names at the end.
It should eventually be replaced by sth less hacky, but will have to do for pydata...

[BUG] temp workaround for unnamed levels in hierarchical X passed to aggregator

---

sktime/forecasting/compose/_pipeline.py
sktime/transformations/compose.py

This fixes a semi-bug in the dunders for forecasting pipelines.
Since forecasting pipelines were both forecasters and transformers, the transformer chain logic would take precedence as parsing of the expressions was currently coded, resulting in a transformer and not a forecaster when chaining transformers and a forecaster. Strictly speaking that was not wrong, since forecasting pipelines can be used as transformers.
This PR changes precedence so that the forecaster type takes precedence over the transformer type, ensuring that multiplying transformers with forecaster results in forecasters.

[BUG] forecasting pipeline dunder fix

---

sktime/forecasting/compose/_column_ensemble.py

Fixes #2435, applying the bugfix described therein.

[BUG] fix erroneous direct passthrough in `ColumnEnsembleForecaster`

---

sktime/forecasting/compose/_reduce.py

Takes self._y instead of y_pred

[BUG] Incorrect indices returned by make_reduction on hierarchical data fixed

---

.coveragerc
.github/workflows/test.yml
.github/workflows/wheels.yml
.gitignore
Makefile
sktime/utils/_testing/panel.py

* addresses the deprecation of Codecov Bash Uploader: https://docs.codecov.com/docs/about-the-codecov-bash-uploader#deprecation-notice-and-schedule
* fixes the partial misconfiguration of codecov uploader https://github.com/alan-turing-institute/sktime/runs/5817665318?check_suite_focus=true#step:9:37
* fixes covergepy warnings: https://github.com/alan-turing-institute/sktime/runs/5807142605?check_suite_focus=true#step:7:12
* `make test` by default doesn't measure coverage but allows it via PYTESTOPTIONS variable
* uses `pytest -n auto`, which seems to work reliably. GHA MacOS runners have 3 core CPUs available, so that should speed up these builds
Check if code coverage got uploaded as it should. See if there are unwanted differences in the build or tests in general.

[ENH] upgrade codecov uploader and cleanup coverage reporting

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py

This PR carries out a small refactor on `_predict_moving_cutoff`:
* removal of code blocks conditional on `return_pred_int=True`, these were never reached
* changing `_update_predict_single` call to `update_predict_single`, this was a bug, since this causes the cutoff to not be updated in `_update_predict`

[ENH] refactor `_predict_moving_cutoff` and bugfix, outer `update_predict_single` should be called

---

sktime/transformations/series/boxcox.py

This PR fixes https://github.com/alan-turing-institute/sktime/issues/1994, what I think is the last issue that prevents sktime from being compatible with `scipy` 1.8.0.
The fix is to remove the otherwise unused `alpha` arg from `_boxcox`, which allows to remove the `_boxcox_conf_interval dependency` entirely

[BUG] remove `alpha` arg from `_boxcox`, remove private method dependencies, ensure scipy 1.8.0 compatibility

---

extension_templates/transformer_simple.py
sktime/transformations/series/adapt.py
sktime/transformations/tests/test_base.py

This PR changes what I think are all remaining references to the deprecated tag `fit-in-transform` to the tag that replaces it, `fit_is_empty`.

[ENH] changed references to `fit-in-transform` to `fit_is_empty`

---

sktime/forecasting/compose/_reduce.py

The `_DirRecReducer` did not comply with the generic forecaster interface, where exogeneous `X` should not raise an error (in the worst case it should be ignored). The reducer did raise an error.
This PR does not add use of exogeneous `X`, it simply makes the reducer interface compliant, by ignoring `X` instead of raising an error.
Surfaced via widening tests here: https://github.com/alan-turing-institute/sktime/pull/2462

[ENH] remove error message on exogeneous X from DirRec reducer

---

sktime/forecasting/fbprophet.py

This PR tries to speed up Facebook `Prophet` tests.
Changes in the test settings:
* reduced number of "uncertainty samples" from 1000 to 10

[ENH] speed up Facebook Prophet tests

---

sktime/classification/compose/_column_ensemble.py

This PR fixes two bugs in ColumnEnsembleClassifier` related to this report https://github.com/alan-turing-institute/sktime/issues/2312:
* tags were incorrectly set - `ColumnEnsembleClassifier` always thought it could not handle unequal length data, even if components supported that. This is now correctly inferred from the internal tags.
* the internal mtype was set to `numpy3D` which could handle only equal length data by definition of this data type. This was changed to the `pandas.DataFrame` based data types.

[BUG] fixed `ColumnEnsembleClassifier` handling of unequal lenght data

---

examples/loading_data.ipynb
sktime/datatypes/_panel/_convert.py

This PR does some minor cleaning in the `_panel._convert` module which had much copy-pasted legacy code:
* removal of commented out code
* removal of heavy input checks (this should be done by the `check` functions if needed)
* added module docstring
It also removes redundant and outdated parts in the `loading_data` tutorial, which was importing a lot of now private functionality of the `datatypes` module. This is replaced by references to the datatypes tutorial which explains the multiple data formats.

[ENH] cleaning up `_panel._convert` module

---

sktime/forecasting/compose/tests/test_multiplex.py

As mentioned in #2514 wrote some tests to see if `MultiplexForecaster` performs as expected.  
Essentially - run `ForecastingGridSearchCV`  on `MultiplexForecaster` and verify that the best forecaster from the grid search is also the one we select if we simply evaluated all the forecasters separately. 
*Note - I use a very small data set and only compare have 2 forecasters in `MultiplexForecaster`.  I did this to not make the test too slow - but it is not the most thorough test.  Hopefully it would still help catch some obvious issues.*
No
Any other obvious tests that should be added? Should we add more forecasters?  Does this test make sense to you? 
@aiwalter I went ahead and added you as an author to this file.  I figured since you had a hand in co-creating `MultiplexForecaster` in the …

[ENH] Added tests for MultiplexForecaster

---

sktime/classification/distance_based/_proximity_forest.py

This PR changes test parameters of `ProximityForest` and `ProximityTree` to faster settings (reduced recursion depth), for lower runtime.
It leaves the special "unit test" parameters unchanged.

[ENH] Proximity forest faster test param settings

---

.github/workflows/test.yml
.github/workflows/wheels.yml
build_tools/azure/build_wheels.sh
pyproject.toml

This PR adds a dependency on `pytest-timeout` in the `dev` dependency set, and a timeout-fail of 5min on all individual tests.
This will address tests hanging for 6 hours such as in https://github.com/alan-turing-institute/sktime/issues/2448 (they will fail earlier, at the 5min bound)

[MNT] added pytest timeout of 5 minutes

---

examples/AA_datatypes_and_datasets.ipynb

This PR updates the datatypes notebook with two recent additions to the time series container interfaces:
* relaxation of `pd-multiindex` mtype to allow arbitrary row index names
* addition of hierarchical mtype `pd_multiindex_hier`

[DOC] updated datatypes notebook

---

sktime/regression/base.py
sktime/utils/_testing/scenarios_classification.py

This PR adds a scenario, `ClassifierFitPredictUnequalLength`, where the `X` used in `fit` and `predict` has unequal length, for testing of classifiers and regressors.
This scenario is used by the test suite whenever the classifier/regressor claims to be capable of handling unequal length series via the `capability:unequal_length` tag.
Introducing this scenario should prevent issues such as
https://github.com/alan-turing-institute/sktime/pull/2513
from happening again (in cases where the tags are correctly set).

[ENH] unequal length classifier scenario

---

sktime/registry/_lookup.py
sktime/utils/estimators/_base.py
sktime/utils/estimators/tests/test_base.py

This PR makes the following changes to `_MockEstimatorMixin`:
* changes the name of the log attribute from `_log` to `__log`. That way, the attribute becomes hidden and cannot be affected directly.
* write logic is slightly changed, with `log` getting a setter that appends to the log (instead of overwritin it); `__init__` is removed entirely, first access creates the list and not the `__init__`.
Reason to make these changes:
* `__init__` clashes with linear inheritance structure of `sktime` estimators, in particular the pattern of passing args to `super` (which it blocks)
* clashes with `BaseObject` extension here: https://github.com/alan-turing-institute/sktime/pull/2531
Also adds the `utils` module to the ignore-list of the `all_estimators` retrieval utility, since (a) the test …

[ENH] Logger update - `__init__` removal, private `log` attribute

---

.github/workflows/test.yml
.github/workflows/wheels.yml
build_tools/azure/build_wheels.sh

This raises the per-test time limit in `pytest-timout` from 5min to 10min.
Reason: some tests, depending on time of day and total number of CI jobs run, may exceed 5min.

[ENH] raise `pytest-timeout` time limit to 10min

---

sktime/forecasting/theta.py

This PR fixes #2524.
The bug is explained by `_predict_quantiles` calling `super.predict` and not `super._predict` - the latter always returns a `pd.Series` as expected, while the former is polymorphic and breaks the function in case something else is returned (e.g., when `y` is a data frame).

[BUG] fix `ThetaForecaster.predict_quantiles` breaking on `pd.DataFrame` input

---

sktime/forecasting/base/_base.py

The default `_predict_var` implementation had an unreported bug where it compared column names in the multivariate case.
This is now fixed.

BUG] bugfix for default `_predict_var` implementation

---

sktime/utils/estimators/__init__.py
sktime/utils/estimators/_base.py
sktime/utils/estimators/_forecasters.py
sktime/utils/estimators/tests/test_forecasters.py
sktime/utils/tests/test_check_estimator.py

This PR introduces a `MockForecaster` without logging, for testing the test utilities.
It also cleans up the `MockUnivariateForecaster`, including a name change to `MockUnivariateForecasterLogger`, to distinguish mocks that log and mocks that do not log.
`MockUnivariateForecaster` methods are also cleaned up, it had some unnecessary and duplicative assignments.
Finally, the PR makes the following changes to speed up tests:
* replace `NaiveForecaster` in testing of `check_estimator` with `MockForecaster`, this reduces the `check_estimator` run from 2-5min to 20sec.
The PR relies on:
* https://github.com/alan-turing-institute/sktime/pull/2538 , a bug which the testing of `MockForecaster` uncovered.
FYI @ltsaprounis

[ENH] MockForecaster without logging, MockUnivariateForecaster clean-up

---

sktime/dists_kernels/_base.py
sktime/dists_kernels/compose_from_align.py
sktime/dists_kernels/compose_tab_to_panel.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/tests/_config.py
sktime/tests/test_all_estimators.py
sktime/transformations/series/clasp.py

`transform`, `predict` should not change state - these tests were turned off in the test refactor since some estimators were non-compliant.
This PR turns those tests on again, and excepts non-compliant estimators until fixed.
Fixes or escapes the following estimators that are failing the test:
* escapes the row transformers, these will be deprecated, see #2370
* escapes the column transformer, this has a bug and also still needs to be refactored, see #2537
* removes the `self.X_equals_X2` write in `transform` of pairwise transformers entirely, replaces instances of use with a local `deep_equals` check. Internal docstrings are updated accordinly. Not a public attribute, so no deprecation necessary. FYI @chrisholder.
* removes the `self.scoring_metric_call` and `self.knn_mask` writes in …

[ENH] turn on tests for no state change in `transform`, `predict`

---

.github/workflows/test.yml

Attempts a fix for #2552 suggested by @ciaran-g, changing the conda mirror for `scipy` (to anaconda)

[BUG] switch scipy mirror to anaconda on windows to resolve `gfortran` `FileNotFoundError` in all CI/CD

---

.all-contributorsrc
sktime/transformations/panel/rocket/_minirocket.py
sktime/transformations/panel/rocket/_minirocket_multivariate.py

Correctly resetting estimators in https://github.com/alan-turing-institute/sktime/pull/2562 unmasked a hidden bug with `MiniRocketMultivariate`, which was overwriting its `random_state` variable in `__init__`. This has been fixed.

[BUG] fix random state overwrite in MiniRocketMultivariate

---

sktime/transformations/series/summarize.py
sktime/transformations/series/tests/test_window_summarizer.py

Fixes #2504 
Removed any dependency on level names. Only requires the agreed convention for `pd-multiindex` and `hierarchical` that the time dimension is the last level.
Validate the quality of the hierarchical case unit tests

[BUG] Fixes the index name dependencies in WindowSummarizer

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py
sktime/registry/_scitype.py
sktime/utils/_testing/estimator_checks.py
sktime/utils/_testing/scenarios_getter.py

This PR fixes three interacting bugs, causing #2455:
* an error in the `scitype` utility where None would be returned instead of a list of scitype in a case where the passed estimator was type polymorphic (had multiple scitypes). This is fixed.
* an error in the forecasting pipelines constructor check that would consider another forecasting pipeline as type-less and hence raise an error, because forecasting pipelines were expected to be constructed with transformers or forecasters. This is fixed by changing the default behaviour of `scitype` to what was assumed (just one type is returned).
* Since the `scitype` would come back empty for the `TransformedTargetForecaster`, no scenarios would be found in testing, because retrieval was based on the `scitype` utility. Now, with the change, …

[BUG] Fix type checking error due to pipeline type polymorphism when constructing nested pipelines 

---

sktime/transformations/series/difference.py
sktime/transformations/series/tests/test_differencer.py

From a pair programming session with @lbventur (at the community meetup).
This PR solves #2478, it upgrades `Differencer` with NA handling parameter `na_handling`, which allows, besides the two current behaviours, a third behaviour `fill_zero` that fills zero.
This parameter replaces the boolean `drop_na` parameter, and adds deprecation with replacement at 0.13.0, and move to a `fill_zero` default.
Why is the `fill_zero` parameter a better default? It results in a "same index" and "no NA" condition at the end, which is the most compatible out of the alternatives when used in a pipeline. See also discussion (and user frustration) here: https://github.com/alan-turing-institute/sktime/issues/2452 and here: https://github.com/alan-turing-institute/sktime/issues/2451

[ENH] Differencer NA handling - "fill zero" parameter

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py

Post https://github.com/alan-turing-institute/sktime/pull/2466, there were dead args and functions, i.e., not called resp used by anything anymore. Both occurrences are in private locations, so can be removed without any adverse effect.
* `return_pred_int` args in `_predict_moving_cutoff` - would raise a `NotImplementedError`, which is moved upwards into the `_BaseWindowForecaster`
* `_format_moving_cutoff_prediction` in `_sktime.py` is an older version of the one in the base module, and not called anywhere.

[ENH] removing dead args and functions post `_predict_moving_cutoff` refactor

---

sktime/forecasting/base/_base.py
sktime/forecasting/online_learning/tests/test_online_learning.py

This PR fixes #2556, the `update_predict` state handling bug, by replacing the `detached_cutoff` by a call of `deepcopy` and working with the deep copy.
This is a temporary fix which ensures correctness - long-term we should probably deprecate the `update_predict` behaviour that resets the `cutoff`.
One secondary problem was that some tests for the online forecaster were *assuming* the behaviour that was problematic in #2556, i.e,. that the inner state *does* get updated by `update_predict`.
This was accounted for by adding a `reset_forecaster` argument to `update_predict`, which can be used to switch between the two behaviours currently assumed in the code base, of `update_predict`.
Docstrings have also been added to clarify what `update_predict` actually does.

[BUG] fix for `update_predict` state handling bug, replace detached cutoff by deepcopy

---

.github/workflows/test.yml
.github/workflows/wheels.yml

PR attempting to address #2584.
Removes the extra install of `scipy` and `matplotlib`, so it is directly installed as dependency of `sktime`.
That was probably causing the issue, as it installed a second time.

[MNT] CI/CD failure diagnostics: remove extra scipy/matplotlib install

---

sktime/tests/test_all_estimators.py

The `check_estimator` utility can test estimator instances, which is useful to test specific hyper-parameter settings.
Unfortunately, this had side effects on the passed estimator - which was used in testing throughout - and would break if the estimator was already fitted.
This PR fixes that issue by passing a clone and not the reference to the testing framework, in `run_tests`.

[ENH] fix side effects in `check_estimator` utility

---

sktime/base/_base.py

Simple PR which adds a `return self` to `BaseObject` reset.
Prior to this, `reset` was returning `None`, which was an oversight.

[ENH] `BaseObject.reset` to return `self`

---

sktime/base/_base.py

This PR fixes a minor typo in a tag deprecation message.

[BUG] typo fix in tag deprecation message

---

pyproject.toml

This PR bounds `sklearn` to <1.1.0 as a temporary fix for #2631.

[MNT] bound sklearn to <1.1.0 as a temporary fix for #2631

---

sktime/forecasting/fbprophet.py

Resolves: https://github.com/alan-turing-institute/sktime/issues/2626
To restate what is mentioned in the issue, the interval_width parameter of Prophet is not used and is later overwritten, and is not mentioned in the docstring. The initialization logic can be replaced by the default value if needed. So interval_width is removed as an __init__ argument and deleted where self.interval_width = interval_width.

[ENH] Removed interval_width parameter of Prophet

---

sktime/alignment/dtw_python.py
sktime/utils/validation/_dependencies.py

This PR solves https://github.com/alan-turing-institute/sktime/issues/1906 by adding an option to specify a package name different from an import name directly in `_check_soft_dependencies`.
This is then used to address the issue with the `dtw-python` import (whose import name is `dtw`, but package name is `dtw-python`).
This PR also adds:
* a missing soft dependency check in the same module
* input checks to `_check_soft_dependencies`
* the option to pass a class or string to pass information on the object, class, or module requiring the import to the error message generation logic

[ENH] allow different import and package names in soft dependency check

---

sktime/datatypes/_series/_convert.py

Internal conversions could lead to unexpected results and breakage in a rare case where internal methods or pipeline components produced non-conformant `pd.Series`, i.e., `pandas.Series` with a name (as opposed to no name).
In that case, `convert_to` would produce an empty `pandas.DataFrame`, in line with actual (but highly unintuitive behaviour) of the `pandas` native constructor converter `pd.DataFrame(my_series, columns="col_name")`, which also produces an empty `pandas.DataFrame` if `my_series` is a `pandas.Series` with a name that is not `"col_name"`.
This PR is a bugfix for such cases, by catching this edge case properly. From now on, even if `pd.Series` with a name are provided, the column name is correctly assigned, and the content of the data frame is correctly retained.
Should …

[BUG] fix `pd.Series` to `pd.DataFrame` mtype conversion in case series has a name

---

sktime/forecasting/structural.py

The `ignores-exogeneous-X` tag was set incorrectly for `UnobservedComponents`.
As can be seen in the methods, `X`, is used non-trivially, so the tag should be `False`.

[BUG] `ignores-exogeneous-X` tag correction for `UnobservedComponents`

---

sktime/distances/_numba_utils.py
sktime/distances/tests/test_numba_distances.py

This PR fixes a bug where the distance factory was incorrectly handling a 1d array being passed.

[BUG] fixed bug with distance factory 1d arrays

---

sktime/_contrib/datasets/_single_problem_loaders.py
sktime/datasets/_single_problem_loaders.py

Replace deprecated argument `squeeze` with the method `.squeeze("columns")` in `pd.read_csv`. This argument is deprecated since version `1.4.0` of `pandas` (see https://pandas.pydata.org/docs/whatsnew/v1.4.0.html and https://github.com/pandas-dev/pandas/pull/43427).

[ENH] Replace deprecated argument `squeeze` with the method `.squeeze("columns")` in `pd.read_csv`

---

sktime/utils/estimators/_base.py
sktime/utils/estimators/tests/test_base.py

fixes #2685 
This deals with the problem of not being able to pass the relevant arguments in the __init__ of the returned mock estimator class (described in #2685) by allowing the user to pass a dictionary that contains the kwargs of the input estimator class.

[ENH] make_mock_estimator passing constructor args for the mocked class

---

sktime/forecasting/conformal.py

This PR adds a prediction interval wrapper that adds simple empirical and conformal forecast intervals based on Stankeviciute et al, 2021. Also includes more naive empirical/frequentist strategies.
The estimator implements the algorithm as a wrapper which can add the intervals to any forecaster, not just the special case presented there for RNN.

[ENH] empirical and conformal probabilistic forecast intervals (Stankeviciute et al, 2021)

---

sktime/forecasting/base/adapters/_pmdarima.py

This fixes an unreported bug where `ARIMA` and, more generally, `pmdarima` adapted estimators would break if `X` contained strictly more indices than `y`. The fix is simply subsetting `X` to the indinces of `y` before carrying out existing logic.

[BUG] fixing pmdarima interface index handling if `X` index set is strictly larger than `y` index set

---

extension_templates/transformer_simple.py

Removed redundant `todo: rename to capability:missing_values` from `tags` in the `transformer_simple` extension template.  
https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/transformer_simple.py#:~:text=%23%20todo%3A%20rename%20to%20capability%3Amissing_valueslink 
It seems to be a `todo` for package maintainers, not a `todo` for Estimator implementors.

[MNT] Removed redundant `todo` from `transformer_simple` extension template

---

.all-contributorsrc

I just checked the contributors list and noticed I have probably earnt some new badges 😄 
* `bug` - plenty of [bug reports!](https://github.com/alan-turing-institute/sktime/issues?q=is%3Aissue+is%3Aopen+%5BBUG%5D+author%3Afkiraly)
* `maintenance` - I've been sorting out [various maintenance issues](https://github.com/alan-turing-institute/sktime/pulls?q=is%3Apr+%5BMNT%5D+author%3Afkiraly+is%3Aclosed)
* `video` - pydata Berlin 2022

[DOC] updating allcontributors contribution key of fkiraly

---

sktime/forecasting/base/_base.py

The docstrings for `update_predict_single` and `update_predict` were not properly reflecting the actual output of those methods.
This was updated to ensure the docstrings corresponds to what is actually returned.

[ENH] Update predict docstrings corrected

---

docs/source/api_reference/utils.rst

Fixes https://github.com/alan-turing-institute/sktime/issues/2528 by updating the utils API ref, removing listing of legacy functions in favour of current functionality.

[DOC] updated utility API docs

---

sktime/forecasting/compose/_stack.py

Fixes #2665 according to suggestions of @indinewton.
Also makes the following to `StackingForecaster`:
* changes the test parameter settings such that one of the forecasters actually uses `X`. This should enable the test suite to catch bugs like #2665.
* sets the capability tags correctly, dependent on the components. For the `"X-y-must-have-same-index"` tag, this should catch incompatible `X` indices at runtime and raise the standard error message.

[BUG] fixing `StackingForecaster` for exogeneous data

---

.all-contributorsrc

I've looked at my own contrib badges in #2682 in the wake of GSoC mentoring start, so I also noticed that the other GSoC mentors and core devs have not been particularly stringent in updating their own badges.
I made guesses based on my knowledge of your contributions here, @aiwalter, @danbartl, @GuzalBulatova, @lmmentel, @Lovkush-A, @ltsaprounis, please check.

[DOC] core dev & gsoc mentor contributions badges

---

pyproject.toml

Resolves https://github.com/alan-turing-institute/sktime/issues/2748 by upper bounding the `holidays` indirect soft dependency to 0.13.

[MNT] upper bound `holidays` to 0.13 in soft dependencies

---

sktime/datatypes/_check.py
sktime/datatypes/_table/_check.py
sktime/datatypes/_table/_examples.py
sktime/transformations/compose.py
sktime/transformations/series/summarize.py
sktime/transformations/series/tests/test_summarize.py
sktime/transformations/tests/test_all_transformers.py
sktime/transformations/tests/test_compose.py
sktime/utils/multiindex.py

This PR adds tests for series-to-primitives output in `test_fit_transform_output`, and ensures the `SummaryTransformer` is compliant with that output.
This fixes #2717.
Further changes:
* functionality of flattening hierarchical column indices, which is now used in two estimators, is moved to the `sktime.utils` module. This hence affects `FeatureUnion` through refactoring of the common functionality.
* the type check for `Table` is modified to return a `n_instances` (number of rows/instances) metadata field, for all `Table` mtypes. This is used in the return type check, e.g., to check that `SummaryTransformer.fit_transform` returns the correct number of rows for multivariate input.

[ENH] SummaryTransformer multivariate output fix and tests for series-to-primitives transform output

---

sktime/forecasting/ets.py

Part of a fix for #2733, for `AutoETS`.

[BUG] fixing constructor non-compliance with sklearn: `AutoETS`

---

sktime/annotation/adapters/_pyod.py
sktime/tests/_config.py

Carries out refactor described in issue https://github.com/alan-turing-institute/sktime/issues/1678 for `PyODAnnotator`.
Pre-PR state blocks the pydata 2022 tutorial due to making `check_estimator` dependent on `pyod`, so needs to be done asap.
Slightly confused, I thought you did that, @NoaBenAmi? Why was https://github.com/alan-turing-institute/sktime/pull/2352 closed and not merged?

[ENH] `get_test_params` refactor for `PyODAnnotator`

---

sktime/tests/test_all_estimators.py
sktime/utils/estimator_checks.py
sktime/utils/tests/test_check_estimator.py

This PR adds arguments to `check_estimator` and the underlying `run_tests` utility that allows to exclude tests and fixture/test combinations by name.
In-principle, this would already be possible by passing a positive list and removing the tests to exclude, but currently there is no easy way to get the positive list. Hence, the argument is an easier (non-redundant) way to do this.

[ENH] option to exclude tests/fixtures in `check_estimator`

---

sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/fbprophet.py

Fixes #2564, i.e., ensures that `Prophet` works with integer index input.
This is done by translating integer indices to "days since Jan 1, 2000", internally, when fitting, and converting back to integer indices, after predicting.

[ENH] add int handling to prophet

---

.github/workflows/test.yml

Accidentally, the new `nosoftdeps` worfklow was overwriting code coverage from the full tests.
This PR removes that accidental overwrite.

[MNT] remove accidental codecov overwrite from nosoftdeps

---

.gitignore
CODEOWNERS
docs/source/api_reference/transformations.rst
sktime/transformations/multiplexer.py
sktime/transformations/tests/test_multiplexer.py

Restored #2738 to allow fixing remaining CI/CD failure.
The failure is fixed by aligning both sides of the comparison in the test `test_multiplex_transformer_in_grid`, by using a transformer without fit that is element-wise (`ExponentTransformer`). Previously, the sides would not necessarily agree, since in one side fit/transform is done on the entire batch, in the other sequentially/stream-wise.

[ENH] Add MultiplexTransformer - reverted & restored to fix remaining CI/CD issue

---

sktime/transformations/tests/test_all_transformers.py

This removes the skip of tests for hierarchical input to transformations in `test_fit_transform_output`.
This should ensure that hierarchical input/output formats are also tested for transformers.

[ENH] testing hierarchical input to transformers

---

pyproject.toml

Reverts alan-turing-institute/sktime#2749, to check whether facebook prophet have resolved their problem https://github.com/alan-turing-institute/sktime/issues/2748 with `holidays`, pre-0.12.0 release. Fixes #2748.
If it passes, we can merge to undo the upper bound temporary workaround.

[MNT] experimental removal of upper bound `holidays` to 0.13 in soft dependencies

---

extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This adds a list of reserved variables to the instructions in the extension templates, to avoid accidental write to reserved variables by implementers of estimators.
FYI @miraep8 (#2738 was an example of this accident)

[DOC] reserved variables listed in extension templates

---

Makefile
sktime/tests/test_all_estimators.py
sktime/utils/validation/_dependencies.py

This PR ensures that `check_estimator` can always run without soft dependencies, and adds a test for it.
It addresses a recent issue fixed by https://github.com/alan-turing-institute/sktime/pull/2755 where `check_estimator` could only be run with one specific soft dependency installed, and the problem that `check_estimator` runs for probabilistic forecasters only when `tensorflow-probability` is installed (for `predict_proba`).
This PR adds:
* a test for checking that `check_estimators` runs if no soft dependencies are installed, to the "no soft dependencies" CI checks.
* a `"none"` severity level for the dependency checker functions, which results in a return of True/False based on whether packages are installed or not
* a conditional escape from testing `predict_proba` in forecasters if …

[MNT] `check_estimators` to run without soft dependencies

---

docs/source/api_reference/forecasting.rst

This cleans up the forecasting API reference and adds some missing forecasters.

[DOC] cleaning up forecasting API reference

---

docs/source/changelog.rst

By accident, @TonyBagnall did not make it on the overall contributor list of 0.12.0.
The release is already on its way, but we should add him in.
The reason for the accident is the bug https://github.com/alan-turing-institute/sktime/issues/2796 in the release script, and that @TonyBagnall did not have a PR merged that was opened between 0.11.4 and 0.12.0.
(this shows that the bug also affects the list of contributors, not just the PR which I added manually in this case)
@TonyBagnall is individually credited next to his merged PR, as well as in the first line of the "highlights", so I hope there is not too much harm done.

[DOC] add missing TonyBagnall to contributors of 0.12.0 in changelog

---

docs/source/api_reference/transformations.rst

This PR cleans up the transformer API reference:
* a lot of transformers were simply missing. Included a number of transformers contributed by non-core-devs, and hierarchical transformers (aggregation, reconciliation). They were added.
* the high-level taxonomy of transformers was re-ordered, e.g., to be clear about what the return is (primitives, series, panel, etc). This is explained in a table at the start.
* new mid-level taxonomy of transformers. Parts correspond to the TSC estimator taxonomy, parts based on methodological details.
Further, it seems that the transformers have been placed in the `series` and `panel` folders more or less at random, historically. The taxonomy does not reflect well the folder structure, so we may like to move around things in the folders at some point in …

[DOC] cleaning up transformer API reference

---

sktime/transformations/base.py
sktime/transformations/compose.py
sktime/transformations/tests/test_multiplexer.py

Related to design discussion on transformer dunder methods in #2459.  Also related to #2670 #2738
The `|` dunder is implemented the same way it is for `MultiplexForecaster` (ie makes use of `dunder_concat`). There are also tests for this that pass locally.

[ENH] Adding | dunder for MultiplexTransformer

---

sktime/transformations/base.py

Thie fixes the following unreported bug related to https://github.com/alan-turing-institute/sktime/issues/2841 and https://github.com/alan-turing-institute/sktime/issues/2711:
when a transformer entered vectorization mode and `y` was passed (and also vectorized), then the transformer would pass the vectorized `X` to the inner methods where a vectorized `y` should have passed, i.e., passing `X` as `X` (correctly), and `y` as `X` as well (incorrectly). This has been fixed.
(was difficult to spot since the condition is a rare combination of (a) a transformer uses `y` at all, and (b) vectorization happens)
Relation to the bugs:
* after the type inference bug in #2841 is fixed, the test example posted by me breaks due to this unreported bug
* in #2711, it seem like `X` in the forecaster is not …

[BUG] Vectorization in transformers overwrote y with X

---

sktime/transformations/series/lag.py

For strange reasons, `Lag` errors out if the integers in an integer lag specification are `numpy` integers, as opposed to python native integers.
This is relevant when attempting to pass integers from a `ForecastingHorizon` to `Lag`, which is the natural thing to do in reduction.
The fix is added to `Lag`, which now also can deal with `numpy` integers.

[ENG] fix `Lag` for numpy int

---

docs/source/api_reference/transformations.rst
sktime/transformations/series/subset.py
sktime/transformations/series/tests/test_subset.py

This PR contains two transformers for subsetting/slicing:
* `IndexSubset`, which subsets a time series `X` to indices of `y`
* `ColumnSelect`, which subsets a multivariate time series `X` to a pre-specified set of column names or integer indices of columns
Tests specific to the transformers are included.

[ENH] subsetting transforms

---

sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_utils.py

The `get_window` utility was broken when `window_length` was `None`, it would return the object `obj` unchanged.
This has now been fixed.
In addition, the `lag` default has been set to zero, which is interpreted as a zero integer or `timedelta`, depending on `obj`.
Test cases for `None` input behaviour have been added.

[ENH] fix `get_window` utility when `window_length` was `None`

---

sktime/transformations/base.py

Fixes #2841.
The output type checks in transformers could run into problems in the specific case where the inner `_transform` produced a `pd.DataFrame` that was compliant both with a `Panel` and a `Table` specification.
In cases where this happened, the transformer would error out.
This is easily fixed, since we *know*  when to expect a `Panel` or a `Table`, based on the output scitype. The bug has been fixed by using that tag to restrict the expected outputs, which prevents multiple type identifications.

[BUG] transformers: output type check fix for ambiguous return types

---

sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_utils.py
sktime/forecasting/base/tests/test_base.py

This PR:
* makes `get_cutoff` compatible with all time series input formats by putting a conversion step at the start of the function.
* fixes #2872, by extending `get_cutoff` so it can deal with `VectorizedDF`, and adds tests to check correct behaviour.
Other changes:
* updated docstrings, and corrected docstrings for functions in the module
* add `reverse_order` arg to `get_cutoff` to obtain the *first* time stamp instead of the *last* time stamp
* add `check_input` arg (default False) for input checks in `get_cutoff`, and optional input checks

[ENH] make `get_cutoff` compatible with all time series formats, fix bug for VectorizedDF input

---

sktime/base/_base.py
sktime/tests/test_all_estimators.py

This PR modifies `set_params` to also execute a full `reset`, which calls any `__init__` code such as dynamic tag setting.
Also adds parameter inspection related class methods to `BaseObject`:
* `get_param_names` - retrieves list of parameter names
* `get_param_defaults` - retrieves name/default dict of parameter defaults
Why `set_params` should execute a `reset`: @aiwalter pointed me to this specification document in `sklearn` which makes a key interface assumption explicit, namely that the result of `set_params` must be the same as `__init__(**self.get_params())`.
Since `sktime` may have some `__init__` content besides `self` writes (in deviation from `sklearn` due to varia discussed in #2573), we can ensure consistency here by calling `reset` from `set_params`.
This relates to …

[ENH] `set_params` to call `reset`, to comply with `sklearn` parameter interface assumptions

---

sktime/forecasting/base/_base.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/transformations/compose.py

This PR loosens checks related to index equality related tags:
* if a forecaster has `"X-y-must-have-same-index"` and `"ignores-exogeneous-X"` tag both set to True, this will no longer result in an exception if `X` is passed and is not index compliant with `y`. Why: if `X` is ignored, then `X.index` should also not matter for anything, including checks.
* In transformer and forecaster pipelines, the `"X-y-must-have-same-index"` tag is no longer copied from forecaster or conjunction-inferred from transformers. This was logically incorrect, as there are transformers that can add or remove indices. There have been actual instances of unexpected behaviour around this in pipelines. Example 1: `Aggregator` which adds indices https://github.com/alan-turing-institute/sktime/issues/2711; example …

[BUG] loosen index check related tags and fix incorrect pipeline tag inference

---

sktime/classification/all/__init__.py
sktime/forecasting/all/__init__.py
sktime/transformations/all/__init__.py

This PR upgrades the `all` modules to automatic retrieval and export of all estimators of a certain type, and adds an `all` module for `transformations`.
Intended use is via `from modulename.all import *` which then loads all estimators and relevant objects (like `ForecastingHorizon` for forecasters) in memory.
The `all` modules have fallen very much out of date, current `main` state is perhaps around 0.7.X or 0.8.X. Part of the reason is that the extension guidelines did not list "add your estimator to the export list in the `all` module.
This PR also removes the need for doing that, as retrieval is automatic, via the `all_estimators` utility.

[ENH] upgrade the "all" modules to automatic retrieval

---

pyproject.toml

closes #2898 
Remove `cmdstanpy` from `all_extras` since it is installed as a direct dependency of `prophet`.
No

[MNT] Remove `cmdstanpy` from `all_extras`

---

sktime/datatypes/_vectorize.py

`VectorizedDF` had a few lines of hack to ensure compliance with a legacy convention on `multiindex-df`, namely the naming of the row index levels.
This convention is no longer part of the data type speification, and also not enforced elsewhere, so the lines can be removed.

[ENH] remove old `multiindex-df` index convention hack from `VectorizedDF`

---

sktime/registry/_lookup.py

The registry lookup utility file was missing an `__author__` variable, this has been added based on commit history.
FYI @mloning, @KatieBuc, @miraep8, @xloem.

[ENH] `all_estimators` authors variable

---

sktime/datatypes/_vectorize.py
sktime/datatypes/tests/test_vectorize.py
sktime/forecasting/base/_base.py
sktime/transformations/base.py

This PR adds functionality in `VectorizedDF` to vectorize across columns/variables.
* adds an `iterate_cols` arg to the `VectorizedDF` constructor which enables vectorization across columns.
* changes `get_iter_indices` to produce row/column indices for subsetting
* relaxes requirements on scitypes so that `iterate_as` and `is_scitype` can be equal, i.e., when iteration/vectorization is only over columns and not of rows
* tests are kept for regression testing, only negative tests are relaxed where previously `iterate_as=is_scitype` was tested to raise an error
* tests are extended to also test column vectorization
* since the interface of `get_iter_indices` changed to return cols/rows, counter-adaptation in the `BaseForecaster` and `BaseTransformer` were necessary. In the future, this …

[ENH] `VectorizedDF` to support vectorization across columns/variables

---

sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_utils.py

The utility function was incorrect for `get_time_index` for 1D and 2D numpy formats, where the 0-th index is time. This has been fixed.
Also adds functionality for `VectorizedDF` (by looking for the `X` attribute)

[BUG] fixing `get_time_index` for 1D and 2D numpy formats

---

sktime/datatypes/_utilities.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_sktime.py
sktime/forecasting/base/tests/test_base.py
sktime/forecasting/base/tests/test_fh.py
sktime/forecasting/compose/_reduce.py
sktime/utils/datetime.py

This PR is an attemted partial fix to the `freq` issue, by ensuring the private `_cutoff` attribute of forecasters is always a `pandas.Index` that carries `freq` (when `freq` is present or inferrable).
Relies on PR https://github.com/alan-turing-institute/sktime/pull/2908 which ensures that `get_cutoff` extracts and preserves `freq`.
The public `cutoff` is unchanged, a `pandas` compatible index element rather than an index, which means that no deprecation is necessary.

[ENH] turn private cutoff of forecasters into an index that carries `freq`

---

extension_templates/forecasting.py
extension_templates/forecasting_simple.py

This PR adds the reserved attribute `_is_vectorized` to the exclusion list of the forecaster extension templates.

[DOC] add `_is_vectorized` to forecaster extension template exclusion list

---

sktime/transformations/series/subset.py

This is a minor syntactic sugar update to `ColumnSubset` that allow to pass `pandas` scalars as `columns`, which would not be coercable to `pd.Index`. In that case, the arg is interpreted as one-element list before coercing to `pd.Index`.

[ENH] extend `ColumnSubset` to work for scalar `columns` parameter

---

pyproject.toml

Enable using numpy 1.22. This is the change suggested in #2978

[MNT] Update numpy to <=1.22

---

setup.cfg

This PR sets the number of `pytest-xdist` workers to `auto`, which will use max.
This is 3 on mac, and 2 on the other OS
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
so this should cut down time on mac to 2/3.
Related PR: #2890.

[MNT] set number of `pytest-xdist` workers to auto

---

sktime/transformations/panel/segment.py
sktime/transformations/panel/tests/test_segment.py

Fixes #2968 by ensuring that no duplicate columns get added to output of `IntervalSegmenter` and descendants.

[BUG] ensure `IntervalSegmenter` unique column output

---

sktime/datatypes/_vectorize.py
sktime/transformations/base.py
sktime/transformations/panel/segment.py
sktime/transformations/panel/tests/test_sliding_window_segmenter_transformer.py
sktime/transformations/tests/test_base.py

This PR deals with an edge case where a transformer is vectorized that transforms a univariate series or panel into a multivariate series or panel.
In such a case, automated vectorization would typically produce non-unique columns.
This PR modifies the `VectorizedDF.reconstruct` function to create a flattened multiindex that makes the columns unique, by introducing a level for the variable name, in such a case.
Example where non-unique variable names are produced currently after transform:
```python
from sktime.transformations.series.theta import ThetaLinesTransformer
X = pd.DataFrame({"a": [1, 2], "b": [3, 4], "c": [5, 6]})
t = ThetaLinesTransformer()
t.fit_transform(X)
```
This PR also contains:
* tests that check that unique columns are produced in the above case, and in a similar …

[ENH] transformer vectorization: ensure unique column names if unvectorized output is multivariate

---

sktime/transformations/bootstrap/_mbb.py

This fixes an unreported bug with the boostrap transformers `MovingBlockBootstrapTransformer` and `STLBootstrapTransformer` that return a `pd.DataFrame` with `NaN` in the column label.
The column names are now replaced with the names of the input data frame (or data frame coercion).

[BUG] fix NaN columns in bootstrap transformers

---

sktime/classification/feature_based/_fresh_prince.py
sktime/classification/feature_based/_tsfresh_classifier.py

python dependency tags were missing in `tsfresh` dependent estimators `FreshPRINCE` and `TSFreshClassifier`, these have been added.

[ENH] missing `tsfresh` depependency tags

---

sktime/datatypes/_panel/_convert.py
sktime/transformations/panel/truncation.py

Fixes #2998:
* ensures that `pd-multiindex` index is preserved in transformers and forecasters when converted to and back from a different internal panel type. This was an issue not specific to `TruncationTransformer`.
* `TruncationTransformer` `transform` output now has same columns as input. This was an issue specific to `TruncationTransformer`

[BUG] preserve `pd-multiindex` index names, and ensure `TruncationTransformer.transform` output now has same columns as input

---

sktime/dists_kernels/compose_from_align.py
sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/_stack.py
sktime/tests/_config.py
sktime/tests/test_all_estimators.py
sktime/tests/test_softdeps.py
sktime/utils/validation/_dependencies.py

This PR changes the `pytest` test generator in `TestAllEstimators` and similar classes to collect only tests involving estimators that are compatible with the current developer environment (python version and dependencies).
This should improve developer experience and get us a good way along the way towards a state where the full test suite on core estimators can be run without the `all_extras` packages installed locally, or running tests based on a custom dependency set.
Some notes:
* this change is imo low risk, since the estimators broken by a change are typically estimators whose soft dependencies are installed by a developer; and the full suite with all soft dependencies will always be run on the remote CI.
* this PR does not get us fully to the point where the entire test suite runs …

[ENH] run test suite only for estimators with dependencies present in python environment

---

.github/workflows/test.yml
.github/workflows/wheels.yml
Makefile
setup.cfg

This PR removes use of `pyargs` from `pytest`.
According to @tarpas, --pyargs are no longer needed since we no longer have cython, and --pyargs stand in the way of the `testmon` approach to #2890

[MNT] removal of pytest pyargs in CI/CD

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/stream/__init__.py
sktime/forecasting/stream/_update.py

This PR adds two wrappesr that control frequency of updates in stream forecasting:
* `DontUpdate`, wraps a forecaster and turns off update. I.e., the internal model is not updated, irrespective of whether `update_params=True` or not, in `update`. This is the "variant of model X without update".
* `UpdateEvery`, wraps a forecaster and carries out a "true update" only every time after `update_interval` time difference has elapsed, similar to `UpdateRefitsEvery`
This PR also fixes an bugs with `UpdateRefitsEvery`:
the "last refit timestamp" was not updated, so `UpdateRefitsEvery` would refit only once after it has been fitted.

[ENH] regular update for stream forecasting, and "no update" wrappers

---

sktime/tests/_config.py
sktime/transformations/panel/compose.py

Related to estimator test parameter refactoring in #1678.
Refactoring applied to ColumnTransformer by creating get_test_params method as explained in issue https://github.com/alan-turing-institute/sktime/issues/1678 and removed params from tests/_config.py.
No.

[ENH] refactored test params for ColumnTransformer

---

sktime/transformations/panel/summarize/_extract.py

`RandomIntervelFeatureExtractor` had the same sporadic column non-uniquness as `IntervalSegmenter`, see here: https://github.com/alan-turing-institute/sktime/pull/2970
This PR makes the columns unique

[BUG] fixes `RandomIntervalFeatureExtractor` to have unique column names

---

.gitignore

when one runs `make test` it produces a directory `testdir/`. this should be ignored by git.

add testdir to .gitignore

---

sktime/benchmarking/tests/test_evaluator.py

This adds a test xfail of the known sporadic test failure reported as  bug #2368.
The cause of the bug is not known, and the skip is added to avoid sporadic test crashes unrelated to the addition.

[MNT] xfail known sporadic test failure #2368

---

sktime/forecasting/model_selection/_split.py

This PR addresses imminent removal/change in `sklearn` `_pprint` and the private import in `sktime` `BaseSplitter`, and partially addresses #3037.
`BaseSplitter` inherits from `BaseObject` which has its own `__repr__` (from `sklearn` `BaseEstimator`), and is `BaseEstimator` compatible already, therefore the complete removal of the custom `__repr__` should address this instance of `_pprint` import.

[MNT] remove custom `__repr__` from `BaseSplitter`

---

sktime/transformations/series/difference.py
sktime/transformations/series/tests/test_differencer.py

This fixes `Differencer`'s inverse transform not having access to the `freq` attribute, following deprecations of `freq` in various places in `pandas`. Relies on the recent upgrade of `freq` handling in `ForecastingHorizon` to future `pandas` compatibility with @khrapovs.
Fixes #2806 (and, by extension, #2879).
Contains a compressed version of the code in #2806, as test.

[BUG] fix for `Differencer.inverse_transform` not having access to data index `freq`

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/early_classification.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This PR updates extension templates to the decision in https://github.com/alan-turing-institute/sktime/issues/2573.
That is, `__init__` can now contain additional logic of parameter checking kind, or tag setting, but it must be after the call to `super.__init__`.

[ENH] parameter checking and move of `super.__init__` in extension templates

---

sktime/datasets/_data_io.py
sktime/datatypes/_panel/_check.py

#3029, but without the checks. Only has the changes that guarantee unique instance index. Fixes #1290.

[ENH] ensure data loaders produce unique instance index

---

sktime/benchmarking/data.py
sktime/datasets/_data_io.py
sktime/datatypes/_panel/_check.py
sktime/series_as_features/model_selection/_split.py
sktime/transformations/panel/compose.py

This fixes a recurring issue with duplicated indices from the time series classification datasets. This has been repeatedly breaking things downstream and made refactors difficult. Fixes #1290, fixes #2331 for the instance index, addresses the example in #1893 fixes the problem that prevents #2379 to be refactored.
Initial bug report about duplicate indices: https://github.com/alan-turing-institute/sktime/issues/1290
Nature of the fix:
* adds a check for `nested_univ` mtype that prohibits duplicate instance index
* makes changes in the `datasets` module that ensures unique index for loaded time series classification datasets, via `reset_index(drop=True)`
* fixes an instance of duplicate indices in the benchmarking module
* ensures that any `nested_univ` returns of the old …

[ENH] add check for `nested_univ` duplicate index and ensure unique instance index in `sktime` datasets

---

.all-contributorsrc
sktime/datatypes/_utilities.py

Fixes #3069
Removes redundant computations in L299 of [`sktime.datatypes._utilities.py`](https://github.com/alan-turing-institute/sktime/blob/5767dbaac759ed6ac43a8977f4c46beb93d0f18c/sktime/datatypes/_utilities.py#L299) 
No
N/A
Maybe there exists a more efficient solution?

[BUG] Remove redundant computations in sktime.datatypes._utilities.get_cutoff

---

sktime/classification/base.py
sktime/classification/tests/test_base.py

This PR makes the following additions to the classifier base class:
* a default for `_predict` if `_predict_proba` is implemented: predicting the most probable class (distribution mode). This allows the implementer to pick one of `_predict` and `_predict_proba` to implement, the other one is filled in. Currently, `_predict` must be implemented even if `_predict_proba` is available.
* a `fit_predict` to obtain a full set of predictions on a training set, in-sample or out-of-sample. A `cv` argument controls whether in-sample or out-of-sample. If `cv=None`, equivalent to `fit(X, y).predict(X)`. If `cv` is provided, cross-validated predictions for the entirety of `X` are produced according to an sklearn splitter.
* `fit_predict_proba`, same as `fit_predict` but for probabilistic predictions. …

[ENH] classifier `fit_predict` methods and default `_predict`

---

sktime/tests/_config.py
sktime/transformations/series/detrend/_deseasonalize.py

Two transformers in the `_deseasonalize` have not been refactored to the modern transformer interface (`_fit`, `_transform`, removal of mixins).
This has been done in this PR for:
* `ConditionalDeseasonalizer`
* `STLTransformer`
This should address the failures in the new soft dependency tests https://github.com/alan-turing-institute/sktime/pull/3039

[ENH] Refactor transformers in `_deseasonalize` module

---

sktime/tests/test_softdeps.py

This PR extends the `test-nosoftdep` CI element with additional tests:
* test that test parameters returned by `get_test_params` do not require soft dependencies.
* test that estimators without soft dependencies (according to tag) can be fitted without a `ModuleNotFoundError`. Currently, the `test-nosoftdep` CI only tests that estimators construct, which may be too weak, since soft dependencies may show up only in `fit`.

[ENH] test estimator `fit` without soft dependencies

---

sktime/forecasting/naive.py

This allows `sp=None` in the `NaiveForecaster`, as an alias to `sp=1`.
This makes it consistent with `ExponentialSmoothing`, `TBATS`, and `BoxCoxTransformer`.

[ENH] allow `sp=None` in the `NaiveForecaster`

---

sktime/classification/compose/_pipeline.py

This PR removes unused methods from `ClassifierPipeline`, which probably got there as part of a copy-paste accident from `_HeterogeneousMetaEstimator`.

[ENH] remove unused methods from `ClassifierPipeline`

---

sktime/classification/compose/__init__.py
sktime/classification/compose/_ensemble.py

A number of popular (and not so popular) time series classifiers in `sktime` use a weighted ensemble strategy for ensembling a selected set of other classifiers.
Despite this being a repeated pattern, there does not seem to be a compositor in `sktime` that would allow users to build similar ensembles - restricting users to those hand-picked sets of base classifiers and "special ensembles", rather than being given the tools to build their own ensembles.
Instead of building more and more of those special ensemble classifiers a la HIVE-COTE with repetitive, copy-pasted boilerplate, I think we should just give users a compositor to build these ensembles.
So here it is, voila!
(finally there is an "actual" ensemble compositor in the `classification` `_ensemble` module)

[ENH] weighted ensemble compositor for classifiers to allow users to build their own HIVE-COTE like ensembles

---

sktime/benchmarking/tasks.py

This PR addresses imminent removal/change in `sklearn` `_pprint` and the private import in `sktime` `BaseTask`, and partially addresses #3037.
`BaseObject` has its own `__repr__` and could be used here, but `BaseTask` did not inherit from `BaseObject`.
To address the change in `__repr__`, `BaseTask` was changed to inherit from `BaseObject`, with some compatibility changes towards the `sklearn` interface. The complete removal of the custom `__repr__` in favour of `BaseObject.__repr__` should address this instance of `_pprint` import.

[MNT] remove custom `__repr__` from `BaseTask`, inherit from `BaseObject`

---

docs/source/developer_guide/coding_standards.rst
docs/source/developer_guide/continuous_integration.rst

This PR updates and clarifies the documentation on coding standards and how to set up local linting, including a new section on vs code.
Moves the section on "setting up pre-commit" to the "coding standards" section, and leaves a reference in place.

[DOC] code quality docs expanded with instructions for local code quality checking set-up

---

sktime/forecasting/model_selection/_tune.py

Fixes #3051, also see #3046.
Adds an `update_behaviour` parameter to grid tuners which allows the user to select which of tuning parameters and inner parameters are updated in `update` of the grid search wrapper. Also:
* cleans up docstrings which were missing parameters
* adds the new parameter to the tests

[ENH] flexible `update` behaviour of forecasting tuners

---

CODEOWNERS
pyproject.toml

#2677 
removed leftover `hcrystalball `stuff

[MNT] Removed hcrystalball from all_extras

---

.github/workflows/test.yml
.github/workflows/wheels.yml

Bumping the CI host/runner for macos from 10.15 to 11 since github is going to deprecate macos-10.15 soon. 
see: https://github.com/actions/virtual-environments/issues/5583
ongoing migration work might be related to some issues with macos referenced in #3103

[MNT] Bump macos github actions host to macos-11

---

sktime/classification/base.py
sktime/classification/compose/_pipeline.py

This fixes some unreported bugs with `BaseClassifier` default methods and `SklearnClassifierPipeline` for `predict_proba`.
* `BaseClassifier._predict_proba` worked only for certain mtypes, since `n_instances` was obtained as `len(X)` which is correct only for some mtypes. This has been replaced by `len(y)` which is always the same as `n_instances`.
* `SklearnClassifierPipeline._predict_proba` would break if the `sklearn` classifier interfaced had no `predict_proba`. This was fixed by defaulting to the `BaseClassifier._predict_proba`.
* `SklearnClassifierPipeline` had the `capability:multivariate` tag set exactly the wrong way, a `not` was missing. This did not cause a breakage but a lot of incorrect warnings.

[BUG] fixes to `BaseClassifier._predict_proba` default and `SklearnClassifierPipeline` in case `predict_proba` is not implemented

---

sktime/forecasting/arima.py
sktime/forecasting/base/adapters/_pmdarima.py

Implements #3064.
One difference, in the adapter which also adapts `ARIMA`, the `_update` just calls `pmdarima` `update`.
This is overridden in `AutoARIMA`, which has the `update_pdq` option.

[ENH] AutoARIMA update options

---

sktime/forecasting/base/_base.py
sktime/forecasting/tests/test_all_forecasters.py

This fixes a bug reported by @lbventura in https://github.com/alan-turing-institute/sktime/pull/3105: the default implementation of `_predict_quantiles`, when `_predict_interval` is implemented, would return quantiles only for the first variable - which is fine in univariate forecasting, but produces too few columns in multivariate forecasting.
This has now been fixed, the correct columns are now returned in both cases, under the condition that `_predict_quantiles` is implemented but `_predict_interval` is not.
Odd that this was not tested so far, I still need to investigate why.
To the bets of my knowledge, we should be testing the proba predict methods with multivariate scenarios?

[BUG] fix forecaster default `predict_quantiles` for multivariate data

---

sktime/base/_base.py
sktime/base/tests/test_base.py

This partially addresses #971 by providing a default `get_fitted_params` interface, in `BaseEstimator`.
Behaviour of `get_fitted_params` is as follows:
* returns a `dict` with `str` keys, obtained from private `_get_fitted_params` and nested component `get_fitted_params`
* component `get_fitted_params` are indexed by `[componentname]__[paramname]`, in analogy to `get_params`
* raises a `NotFittedError` when called before estimator is fitted.
Default behaviour is also implemented:
* `_get_fitted_params` retrievese all attributes ending in `_`, and presents them with keys where the ending `_` is removed
* the default is compatible with the nesting interface
A test is added to check the expected behaviour.

[ENH] default implementation for `get_fitted_params` and nested fitted params interface

---

sktime/tests/_config.py

Excludes the failing `RandomShapeletTransform` from tests until we know what is going on.
See #3138 for the failure.

[MNT] temporarily exclude `RandomShapeletTransform` from tests

---

sktime/classification/feature_based/_random_interval_classifier.py
sktime/classification/hybrid/_hivecote_v1.py
sktime/classification/hybrid/_hivecote_v2.py
sktime/classification/interval_based/_rise.py
sktime/tests/_config.py

Update: this seems to be a reliable fix in the sense of on/off condition.
Preparing to merge as a temporary measure.
---
This is a diagnostic PR to investigate https://github.com/alan-turing-institute/sktime/issues/3103
Purpose: see whether there is a list of specific estimators trigger the failure.
Will remove specific estimators from tests, until there is no longer a failure.
First batch removed:
* `HIVECOTEV1`
* `HIVECOTEV2`
* `RandomIntervalSpectralEnsemble`
* `RandomInvervals`
* `RandomIntervalSegmenter`
* `RandomIntervalFeatureExtractor`
* `RandomIntervalClassifier`
Second batch removed:
* `MiniRocket`
* `MatrixProfileTransformer`

[MNT] temporary fix for Mac CI failures: skip recurringly failing estimators

---

.all-contributorsrc
sktime/datasets/_data_io.py

As per #2697, reduced some boilerplate code in the loader functions
- In the `_data_io.py` file,  Private functions `_load_provided_dataset()` and `_load_dataset()` were refactored in a manner that `_load_dataset()` takes care extraction of data and then calls the former to load the provided data.
- Only use `load_from_tsfile()` as the sole entrypoint. Initially, both `load_from_tsfile()` and `load_from_tsfile_to_dataframe()` were used in private functions mentioned above which is un-necessary since the former calls later anyways. This also gives more control over how data is to be returned.
- Owing to above changes, three default parameters were introduced in both functions combined. Namely, `return_type=None` in `load_dataset()` and `local_module`, `local_dirname` in …

[ENH] Refactor dataset loader

---

sktime/forecasting/model_selection/_split.py

This PR fixes the non-conformance with `sklearn` specs in the `ExpandingWindowSplitter` constructor reported in #3119.
The problem is that `ExpandingWindowSplitter` calls its parent constructor, of `BaseWindowSplitter`, with certain parameter names switched. This has the effect of overwriting `self.initial_window` with a value that is in general not equal to that passed to the constructor, which breaks the `sklearn` constructor interface expectation.
The solution is as follows:
* `BaseWindowSplitter` internally now accesses a property `self._initial_window` wherever it previously accessed `self.initial_window`
* that property reads from `self.initial_window` if exists, otherwise returne `None`
* `ExpandingWindowSplitter` overrides the property, and does not overwrite `self.inital_window`, …

[BUG] `ExpandingWindowSplitter` constructor `sklearn` conformace fix

---

sktime/forecasting/model_selection/_split.py
sktime/forecasting/tests/_config.py
sktime/utils/validation/forecasting.py

Closes #3082 
Allow lists to be `cutoff` argument in `sktime.forecasting.model_selection._split.CutoffSplitter`.
No

[ENH] Allow lists to be `cutoff` argument in `CutoffSplitter`

---

build_tools/changelog.py

[MNT] Restrict changelog generator to changes to main branch

---

sktime/regression/_delegate.py
sktime/regression/base.py
sktime/regression/compose/__init__.py
sktime/regression/compose/_pipeline.py
sktime/regression/kernel_based/__init__.py
sktime/regression/kernel_based/_rocket_regressor.py
sktime/transformations/base.py
sktime/transformations/compose.py

This PR reprises the old PR https://github.com/alan-turing-institute/sktime/pull/767 and attempts to solve it with abstract composition functionality instead of a rocket specific refactor.
This PR introduces compositors for regressors similar to those of classifiers:
* two regressor pipelines, an sktime one and an sklearn one, with dunders
* a delegator for regressors
With the above, the intended translation of classifier to regressor in #767 is as simple as taking the rocket classifier, and changing every string "classifier" in the code to "regressor".
There is a lot of copy-paste, so a common parent such as in #767 could be attempted based on this.

[ENH] Rocket regressor and regressor pipelines, regressor delegators

---

sktime/transformations/base.py
sktime/transformations/series/adapt.py
sktime/transformations/series/func_transform.py

This PR makes a number of improvements around `FunctionTransformer` and `TabularToSeriesAdaptor`, resulting in increased scope of the case where `fit` is being skipped ("stateless" in `sklearn` terminology):
* `FunctionTransformer` has checks from `fit` moved into `transform`, in order to ensure an empty `fit` and allow vectorization with different number of instances in `fit` and `transform` for panel data
* `TabularToSeriesAdaptor` now checks if the `transformer` passed has `sklearn` tags, and if `stateless`, skips `fit` and sets the tag accordingly
* makes `TabularToSeriesAdaptor` more robust to `transform` returns that are not 2D `np.ndarray` by coercion

[ENH] increase stateless scope of `FunctionTransformer` and `TabularToSeriesAdaptor`

---

sktime/tests/_config.py

One specific test for `VARMAX` on windows terminates with an exception:
https://github.com/alan-turing-institute/sktime/issues/3176
Since this happens frequently, removing the test until we understand what is going on.

[MNT] skip known failure case for `VARMAX`

---

sktime/classification/interval_based/_drcif.py
sktime/classification/kernel_based/_arsenal.py
sktime/classification/sklearn/_rotation_forest.py

Reverts alan-turing-institute/sktime#3094
Problem with #3094 is possibly infinite loop if data passed has only one class.
See discussion in https://github.com/alan-turing-institute/sktime/pull/3110 which tries to address secondary bugs caused by #3094.

Revert "[BUG] Fix HIVE-COTE2 sporadic test failure"

---

sktime/classification/base.py
sktime/classification/early_classification/base.py
sktime/classification/interval_based/_drcif.py
sktime/classification/kernel_based/_arsenal.py
sktime/classification/sklearn/_rotation_forest.py
sktime/classification/tests/test_all_classifiers.py
sktime/classification/tests/test_base.py
sktime/regression/base.py

Handles "single class seen in `fit`" scenario that can lead to infinite loops according to unreported bug discussed in PR #3110.
Alternative solution which simply returns "that class" predicted every time, instead of erroring out. Includes tests.

[ENH] classifier single class handling

---

sktime/alignment/dtw_python.py
sktime/transformations/series/kalman_filter.py
sktime/utils/validation/_dependencies.py

The argument `object` of `_check_soft_dependencies` was shadowing the builtin `object`, which is error-prone.
Replaced the argument with `obj`.
No deprecation needed, since this is a private utility.

[BUG] address shadowing of `object` in `_check_soft_dependencies`

---

docs/source/api_reference/transformations.rst
sktime/classification/compose/_pipeline.py
sktime/transformations/panel/shapelet_transform.py
sktime/utils/_testing/scenarios_transformers.py

This refactors the `ShapeletTransform` from the `_contrib` module  and moves it to the `transformations` module.
This allows users to build shapelet transform pipelines and composite estimators (e.g., like shapelet classifers).
Also:
* adds shapelet transformers (incl others) to API reference
* fixes/enhances the classifier pipelines by passing `y` to the transformers.

[ENH] refactor/move simple `ShapeletTransform` from `_contrib` to `transformations` module

---

sktime/classification/sklearn/_continuous_interval_tree.py
sktime/classification/sklearn/_rotation_forest.py

This allows single class in training set in the sklearn classifiers `RotationForest` and `ContinuousIntervalTree`.
Fixes #3202.

[BUG] allowing single class case in sklearn classifiers (trees/forests)

---

sktime/registry/_lookup.py

Addresses #3166.
The use of `pkgutils.walk_package` in `all_estimators` could lead to circular imports if a sub-module also used `all_estimators` to load exports (e.g., the `all` modules).
In theory, this should be prevented by putting these sub-modules on the exclusion list, but is not, because `pkgutils.walk_package` imports all sub-modules, and `all_estimators` not preventing the import of modules on the exclusion list.
The issue is addressed by:
* replacing `walk_package` by a custom utility `_walk`, based on `pgkutil.iter_modules` that does not import sub-modules on the exclusion list
* putting the `all` sub-modules, which use `all_estimators`, on the exclusion list in `all_estimators`

[BUG] prevent circular imports in `all_estimators`

---

.all-contributorsrc
sktime/forecasting/compose/_ensemble.py
sktime/forecasting/compose/tests/test_autoensemble.py

Fixes #3199
Fix the error described in #3199 that occurred in `AutoEnsembleForecaster` when `method="inverse-variance"` was used. This was caused by passing `X` instead of `X_test` to the internal forecasters when making predictions in `fit` method. This has been fixed. In addition, tests for the `AutoEnsembleForecaster` have been added.
No
No

 [BUG] Fix `AutoEnsembleForecaster` inverse variance bug

---

sktime/classification/dictionary_based/tests/test_tde.py
sktime/classification/interval_based/tests/test_drcif.py
sktime/classification/shapelet_based/tests/test_stc.py

This PR removes a stochastic failure from `main` coming from checks in tests of contracted classifiers, see #3206.
#3206 should be used for finding a better resolution of the failure, this PR simply removes the problem from `main`.

[BUG] skip check for no. estimators in contracted classifiers

---

sktime/forecasting/base/_fh.py

Improves the error message of `ForecastingHorizon` when constructor is receiving incompatible input.
Related to https://github.com/alan-turing-institute/sktime/issues/3235 which would produce a confusing message (input is numpy array but 3D and float).

[ENH] better `ForecastingHorizon` construction error message

---

sktime/utils/estimators/_base.py

Added the `functools.wrap` decorator in `make_mock_estimator` to make sure that things like `help(mock_estimator.fit)` return the docstring of the mocked estimator and not something meaningless.

functools-wrapper-in-make_mock_estimator

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/_functions.py
sktime/performance_metrics/tests/test_metrics_classes.py
sktime/utils/estimator_checks.py

Fixes #3221.
There were two problems with the dynamic metric after refactoring:
* `lower_is_better` tag was only set if false
* `func` attribute was not properly written or invoked
Further bugs in the metrics base classes were discovered in the process of fixing:
* the `BaseForecastingMetric` did not call `super.__init__` in its `__init__`, breaking dynamic tag functionality
* the `BaseForecastingMetric` would overwrite `self.name` even if it was set by a child class already, leading to potential `sklearn` incompatibility (parameter get/set)
The bug was also not caught since the dynamic metric started with an underscore, so was not collected in tests.
This has been remedied by adding to tests:
* a version of the example in #3221
* the custom metric from #3221 as test parameters for the …

[BUG] fixing bugs in metrics base classes and custom performance metric

---

sktime/datatypes/_panel/_convert.py

Removes stray args in `from_multi_index_to_3d_numpy` that remained after earlier removal of index name args, in a piece of code not covered by tests (apparently), but covered by new tests here: https://github.com/alan-turing-institute/sktime/issues/3169

[BUG] fix stray args in one `from_multi_index_to_3d_numpy` call

---

sktime/datatypes/_convert.py
sktime/datatypes/_table/_check.py
sktime/tests/test_all_estimators.py
sktime/utils/_testing/_conditional_fixtures.py
sktime/utils/_testing/scenarios.py

This fixes recurring instances of the issue identified by @achieveordie, where instead of a condition
`np.all([sth for sth in sthelse])`
a condition
`np.all(sth for sth in sthelse)`
would be carried out. The latter is more often true, and the condition was used in checks, making the checks weaker (and erroneous) in consequence, letting wrong input pass instead of catching it.
This was also not caught in tests, as it would require to pass very specific failure cases (lists with first element complying, but not all elements complying).
This PR fixes all occurrences of the bug that a code base search for `np.all(isinstance` found.
An exhaustive search for `np.all(` did not find more of this (list comprehension with forgotten brackets).

& achieveordie [BUG] fix recurring instances of forgotten list comprehension brackets inside `np.all`

---

sktime/forecasting/compose/_reduce.py

`DirectReductionForecaster` is meant to allow for exogenous variables. However, because it inherits from `BaseForecaster` the default tag for exogenous variables was: ` "ignores-exogeneous-X": True`. This meant that any instance of `DirectReductionForecaster` was ignoring any exogenous variables passed to it during training and prediction. This PR fixes the tag so that `DirectReductionForecaster` uses `X`.

[BUG] Fix tag in DirectReductionForecaster

---

sktime/transformations/series/lag.py
sktime/transformations/series/tests/test_featureizer.py
sktime/transformations/series/tests/test_lag.py

Problem:
`Lag` outputs column names prefixed with "lag_x__" when using multiple lags. If a single lag is specified then the output column name is the same as the original column name (if the input is a `pd.DataFrame` rather than a `pd.Series`) without "lag_x__" prefixed to the original column name. It would be desirable for the output column names to be consistent, irrespective if a single lag or multiple lags is specified.
Fix implemented:
`Lag` now outputs the same column name irrespective of whether a single lag or multiple lags is specified.

[ENH] in `Lag`, make column naming consistent between single-lag and multi-lag case

---

sktime/base/_base.py

This PR robustifies `BaseObject.set_tags` against forgotten `__init__`, e.g., if a child object forgets to `super.__init__` (or intentionally does not call `super.__init__`).
Without this, an unexpected exception can occur if a developer implements a class that inherits from `BaseObject`, does not directly or indirectly call `BaseObject.__init__` before calling `set_tags`. Likely failure mode is a sub-base-class, as has previously happened in https://github.com/alan-turing-institute/sktime/pull/3225

[ENH] robustify `BaseObject.set_tags` against forgotten `__init__`

---

sktime/forecasting/base/_base.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py

This PR adds a shorthand `**` dunder to apply transformers to exogeneous data in forecasters.
Under the hood, a `ForecastingPipeline` is constructed.
This complements the existing dunders `*`, `+`, and `[ ]`, allowing quick construction of the most common linear forecasting pipelines.
In addition, this PR:
* adds dedicated tests for the forecasting pipeline dunders
* removes `pmdarima` dependency from a number of pipeline tests by replacing `ARIMA` with `SARIMAX` (from core dependency `statsmodels`)
* fixes some docstring typos

[ENH] `**` dunder for applying transformers to exogeneous data in forecasters

---

sktime/datatypes/_panel/_convert.py

This PR extends the converter `nested_univ` to `pd-multiindex` to allow it to deal with non-nested columns.
See discussion in https://github.com/alan-turing-institute/sktime/issues/3169
Bit clunky (double loop), but I currently have no better idea, and there is no compute overhead if all the columns are nested.

[ENH] treat non nested cols in conversion `nested_univ` to `pd-multiindex`

---

sktime/forecasting/base/_base.py

This PR sets the default for the forecaster tag `ignores-exogeneous-X` to `False`.
This is the safer default, or otherwise exogeneous `X` will be inored under the default setting, and this might be accidental and unexpected for an implementer.
See bug here:
https://github.com/alan-turing-institute/sktime/pull/3257

[ENH] set default `ignores-exogeneous-X` to `False`

---

pyproject.toml

Temporary maintenance fix for https://github.com/alan-turing-institute/sktime/issues/3300, until bugs are resolved.

[BUG] bound `pmdarima < 2.0.0`

---

sktime/param_est/compose.py

This fixes the concatenation dunder `*` for the `ParamFitterPipeline`, when concatenated with another transformer.
Also fixes some docstring issues due to copy-paste from classifier pipeline.

[BUG] fixed concat dunder for `ParamFitterPipeline`

---

sktime/dists_kernels/__init__.py

maintenance PR that fixes a recent merge accident that deleted `DtwDist` export in the `dists_kernels` module.
Will emergency merge once tests pass, as this got accidentally removed by my confusion over multiple merges in the `dists_kernels` module.

[BUG] fix merge accident that deleted `DtwDist` export

---

sktime/transformations/compose.py
sktime/transformations/series/compose.py

This PR deprecates `transformations.series.compose` in favour of `transformations.compose`, with estimators to be moved in 0.15.0.
The `compose` module in `transformations.panel` will be deprecated separately:
* row transformers here: https://github.com/alan-turing-institute/sktime/pull/2370
* `ColumnTransformer` should be merged with `ColumnwiseTransformer`
* `ColumnConcatenator` should move to a "multivariate" module or similar.
The estimators still remain in the deprecated module, to make refactor in separate PR easier.

[ENH] deprecate `transformations.series.compose` in favour of `transformations.compose`

---

sktime/transformations/base.py
sktime/transformations/tests/test_compose.py

This PR adds a shortcut for wrapping in `OptionalPassthrough` via the `__neg__` dunder of transformers.
This seems very natural, since "negation" is intuitively very close to "not having the transformer", which is added as a parameter configurable condition via the composition.
Inversion (e.g., switching `transform` and `inverse_transform`) is more natural in the `__invert__` dunder, which would have been the other, "obvious" option.
Also adds a test for ensuring the dunder works as intended.

[ENH] `OptionalPassthrough` wrapping via `neg` dunder

---

sktime/datasets/_data_io.py

Fixes the following issue when reading a tsfile written with `write_ndarray_to_tsfile`
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_1092/2889448795.py in <module>
----> 1 df = load_from_tsfile_to_dataframe("./amex_train_1.ts/AMEX-Data/AMEX-Data.ts", replace_missing_vals_with='NaN', return_separate_X_and_y=False)
/tmp/ipykernel_1092/3989994789.py in load_from_tsfile_to_dataframe(full_file_path_and_name, return_separate_X_and_y, replace_missing_vals_with)
159                         print(has_data_tag)
160                         raise IOError(
--> 161                             "a full set of metadata has not been provided "
162                             "before …
```

[BUG] Fix `write_ndarray_to_tsfile` for `classLabel = False`

---

sktime/transformations/series/detrend/_deseasonalize.py
sktime/transformations/series/detrend/tests/test_deseasonalise.py

Fixes https://github.com/alan-turing-institute/sktime/issues/3267
There seem to be no tests for transformer `update`, so we should not merge this unless we have a test.
Will work on that in a separate PR.
Adds the failure case from #3267 as a test.

[BUG] fix `Deseasonalizer._update`

---

docs/source/get_involved/governance.rst

This PR expands on a discussion I recently had with @miraep8, where it was suggested that we should perhaps treat `sktime` more as a library of algorithms (like `openml` or `huggingface`) than an expert curated selection like `sklearn`.
Related recent discussions are those about which algorithms we should include (or not).
A salomonic solution, suggested by @miraep8, would be to simply include everything that meets the standards of having a basic scientific reference, i.e., all algorithms that have a minimal description of basic scientific quality.
I would actually be in favour of this idea.
I have made a proposed change to the governance document.
Relates to the changes in https://github.com/alan-turing-institute/sktime/pull/3154 that clarify the role of algorithm maintainer and …

[GOV] `sktime` as a "library", not a "curated selection"

---

sktime/forecasting/base/adapters/_statsmodels.py
sktime/forecasting/tests/test_structural.py
sktime/utils/_testing/forecasting.py

This adds a test to ensure that forecasters do not add a `name` attribute to `pd.Series`.
This prevents edge cases in conversion to `pd.DataFrame` where the `name` becomes a column name, and can lead to inconsistency between train series column name and test series column name.
It also fixes an issue with the `statsmodels` adapter which could create a `predicted_mean` name on resulting series.

[BUG] ensure that forecasters do not add `pd.Series.name` attribute

---

sktime/utils/_testing/scenarios_forecasting.py

This changes one of the univariate `pd.Series` `y` fixtures in the scenarios for forecasters to have a `name` attribute.
Relies on https://github.com/alan-turing-institute/sktime/pull/3290. Combined with that, this change additionally tests that the `name` is preserved and is handled without exceptions.

[ENH] test `pd.Series` with name attribute in forecasters

---

sktime/datatypes/_vectorize.py

Vectorization could break for short time series with a `freq` index attribute, since `pandas.infer_freq`, called from within `_enforce_infer_freq` in the vectorization modeule breaks on time series of length 1 or 2.
Example: https://github.com/alan-turing-institute/sktime/pull/3270
Completely unintuitive imo (it could just infer `None` or not break), but that is what happens.
Also FYI @ltsaprounis.

[ENH] fix `_enforce_infer_freq` private utility for short time series

---

sktime/classification/compose/_ensemble.py
sktime/classification/interval_based/_tsf.py
sktime/forecasting/model_selection/_split.py
sktime/networks/cnn.py
sktime/regression/interval_based/_tsf.py
sktime/tests/test_all_estimators.py
sktime/transformations/panel/compose.py

This adds checks and user friendly messages in the test suite, to ensure that all objects and estimators call their respective parent constructor in `__init__`.
Also adds missing `__init__` calls (to `super`'s `__init__`) in the following classes:
* `ComposableTimeSeriesForest`
* `ColumnTransformer`
* `BaseSplitter`
* `CNNNetwork`
* `TimeSeriesForestClassifier` and `TimeSeriesForestRegressor`
(all discovered by the new test 😄 )

[ENH] test `super.__init__` call in objects and estimators

---

sktime/forecasting/ets.py

Removes unnecessary warning from ETS estimator
Bug #3311 
This removes a warning about multiplicative components when self.additive_only == True 
No
Open to any feedback, this is my first open source PR
I also added a space in the warning string so it will be formatted slightly better when printed. I will add myself to the list of contributors and add unit tests if necessary.

[BUG] removes superfluous `UserWarning` in `AutoETS.fit` if `auto=True` and `additive_only=True` #3311

---

sktime/forecasting/base/_base.py

This fixes an unreported bug where call to default `_update` would empty the converter store, due to a call to `self.fit`.
This has unintended side effects such as returning wrong column names when the mtype passed is not the internal mtype supported.

[BUG] fix bug where default forecaster `_update` empties converter store

---

sktime/forecasting/base/_base.py
sktime/forecasting/compose/_column_ensemble.py

Fixes `ColumnEnsembleForecaster` for hierarchical input - bug undetected so far due to problems with hierarchical testing, and found by https://github.com/alan-turing-institute/sktime/pull/3321
Relies on https://github.com/alan-turing-institute/sktime/pull/3325 which fixes an unreported bug that would create identically named columns in the test cases.

[BUG] fix `ColumnEnsembleForecaster` for hierarchical input

---

sktime/forecasting/compose/_reduce.py

This PR removes hierarchical datatypes from recursive reduction forecasters as a temporary measure to address #3316.
Until #3316 is addressed at the root, this will allow the recursive forecasters to be applied to hierarchical data without raising an exception - what happens is simply naive vectorization, i.e., one model is fitted per unit/instance.

[ENH] remove hierarchical datatypes from recursive reduction forecasters

---

sktime/datatypes/_panel/_convert.py

Building a nested column with all instances at once trough pd.DataFrame instead of interating over every instance improves performance by factor 3.
I was doing some inference on a big dataset 500k observations using a numpy array. The inference on big datasets is very slow. In this case one of the issues is that the numpy array was converted to a nested dataframe with `from_3d_numpy_to_nested`. And the function is very slow for bigger Dataframe sizes.
Have a look at this example:
No
The changes are rather small. You can test how the performance improves for bigger Dataframes, see my example provided above.

 [ENH] Optimize `from_3d_numpy_to_nested` converter function

---

extension_templates/classification.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
sktime/forecasting/base/_base.py

This updates the extension templates:
* tags are explained in the forecaster template (for review, is this good for other templates?). Towards https://github.com/alan-turing-institute/sktime/issues/3280
* paragraph on soft dependencies is added to all (non-simple, non-experimental) templates, replacing https://github.com/alan-turing-institute/sktime/pull/1900

[DOC] updated extension templates - tags explained, soft dependencies

---

docs/source/api_reference.rst
docs/source/api_reference/dists_kernels.rst

This PR adds an API reference for `dists_kernels` module to the docs.

[DOC] API reference for `dists_kernels` module

---

sktime/networks/mlp.py

Fixes a bug that was introduced to main in https://github.com/alan-turing-institute/sktime/pull/3232.
The tests passed before merge, but the branch was not up to date, missing some newer tests.
@AurumnPegasus, please make sure your branch is up to date with the latest release, for any future PR.

[BUG] fixes missing `super.__init__` call in `MLPNetwork`

---

pyproject.toml
sktime/datatypes/_series/_check.py
sktime/datatypes/_series/_convert.py
sktime/datatypes/_series/_examples.py
sktime/datatypes/_series/_registry.py
sktime/utils/_testing/deep_equals.py

[ENH] support for `xarray` `DataArray` & mtypes

---

sktime/classification/deep_learning/cnn.py

This skips the `CNNClassifier` doctest in order to isolate the `tensorflow` soft dependency.
Test coverage is not reduced, sinfe `fit` is tested in `TestAllClassifiers` already.

[MNT] skip `CNNClassifier` doctest

---

sktime/tests/_config.py
sktime/transformations/base.py
sktime/transformations/panel/dictionary_based/_paa.py
sktime/transformations/panel/dictionary_based/_sax.py
sktime/transformations/panel/dictionary_based/_sfa.py
sktime/transformations/panel/signature_based/_augmentations.py

Refactors the inheritance of three transformers still inheriting from `_PanelToPanelTransformer`: the transformers `PAA`, `SAX`, `SFA`:
* replaces `_PanelToPanelTransformer` parent by `BaseTransformer`
* sets tags appropriately, instead
* moves `transform` content into `_transform`
A silent/private attribute `_output_convert` has been introduced to `BaseTransformer` that skips the output conversion.
This is currently needed to keep legacy behaviour of the above transformers, as they produce non-compliant output.
This is a temporary measure, and can be replaced by an public interface point, or an additional mtype.
Minor fixes:
* `_CumulativeSum` did not call `BaseTransformer.__init__`

[ENH] refactor inheritance of `PAA`, `SAX`, `SFA`

---

sktime/transformations/compose.py

fixes incorrect warning condition in `InvertTransform`, which was flipped (superfluous `not`)

[BUG] fixes incorrect warning condition in `InvertTransform`

---

sktime/forecasting/compose/_reduce.py

This introduces a parameter `pooling` to `DirectReductionForecaster`, which can be set to `"global"` for global pooling, `"local"` for per-instance pooling, and `"panel"` for panel-wise pooling. Pooling refers to the `X` and `y` passed to the supervised sklearn regressors, which could be constructed from single instances, or the entire panel/hierarchy, in case there are more than one instances.
Giving the user a choice is the way to go here imo, as all settings can make sense.
The logic of `DirectReductionForecaster` also had to be extended to also accommodate for potential multi-indexed `pandas.DataFrame` appearing in the `fit`/`predict` parts. Unfortunately this is a bit fiddly, since it seems `pandas` interfaces are quite discrepant between the 1-level case and the 2- and multi-level …

[ENH] global/local setting for `DirectReductionForecaster`

---

sktime/transformations/series/lag.py

This PR adds a parameter `keep_column_names` (default=`False`) to the `Lag` transformer, which enables `Lag` to return the same column names in `transform` as in the input. This is for avoiding to produce column names `lag_x__varname1`, `lag_x__varname2`, etc, if only one lag `x` is input.
The default is `False` and not `True` according to the reasoning in the recent https://github.com/alan-turing-institute/sktime/pull/3261 which made the defaults consistent.
The use case for not having too long variable names is in cases where we lag twice, or the lagging happens internally in another estimator, such as the reduction prototypes: https://github.com/alan-turing-institute/sktime/pull/3333
FYI, what do you think, @KishManani?

[ENH] option to keep column names in `Lag`

---

sktime/datatypes/_series_as_panel/_convert.py

This PR makes minor improvements to the between-scitype converter module:
* simplifies `convert_to_scitype` logic by direct call to `scitype`, instead of daisy chain of mtype related functions
* fixes omissions in exports and docstrings

[ENH] simplify `convert_to_scitype` logic, fix export and docstring omissions in scitype converter module

---

sktime/datatypes/_check.py

This PR makes the utility `scitype` (infer scitype) more efficient by avoiding calls to `check_is_scitype` with the `return_metadata=True` flag.
The internal logic is changed to call `check_is_scitype` with the `return_metadata=False` flag, which avoids the more expensive metadata related calculations (e.g., in a `nested_univ` frame, check all indices of all series for equal length, etc).

[ENH] avoid metadata computation in `scitype` utility

---

sktime/transformations/panel/compose_distance.py

This adds a `DistanceFeatures` transformer that uses a pairwise distance/kernel to create an ordinary transformer.
In `transform`, it outputs the distance matrix to the series seen in `fit`, which always has the same number of columns, and can be used as features in a pipeline, e.g., classifier pipeline.

[ENH] distance features transformer

---

sktime/transformations/series/clear_sky.py

This PR skips the `ClearSky` doctest to avoid `load_solar` crashing upon intermittent connection to the data repository.
The problem has already been addressed by using the `backoff` library in `load_solar` itself and testing, and test coverage is not reduced as `ClearSky` is still subject to the full transformer test suite, and `load_solar` is tested separately.

[ENH] skip `ClearSky` doctest to avoid `load_solar` crash

---

sktime/datatypes/_utilities.py
sktime/registry/_tags.py
sktime/transformations/base.py
sktime/transformations/compose.py
sktime/transformations/series/adapt.py
sktime/transformations/series/impute.py
sktime/transformations/series/lag.py
sktime/transformations/series/subset.py
sktime/transformations/series/summarize.py
sktime/transformations/tests/test_all_transformers.py

Variant of https://github.com/alan-turing-institute/sktime/pull/3306 which introduces a `remember_data` tag. Data is only remembered and stored to `self._X` if the `remember_data` tag is set.
This PR adds a data memory to transformers, similar to forecasters.
If enabled by the tag, all data seen are stored in an attribute `self._X`, as a reference if possible (due to coercions, storing a reference may not be possible).
This allows to refactor some transformers which already to that internally, and remove a layer of boilerplate:
* `Imputer`
* `Lag`
* `IndexSubset`
* `PandasTransformAdaptor`
* `WindowSummarizer`
The tag is set to `False` by default, and to `True` only in estimators that currently use `self._X` already (the refactored transformers listed in #3306).
Because `self._X` may now …

[ENH] `BaseTransformer` data memory - enabled by tag

---

sktime/forecasting/arima.py
sktime/param_est/seasonality.py

This PR has some additions to make `sp` handling consistent in case no `sp` is present:
* `AutoARIMA` now also accepts `sp=None`, interpreting this as `sp=1`
* the two seasonality estimators in `param_est` will produce `sp_=1` and `sp_significant_ = []` if no seasonality is significant, instead of both being `None`. This ensures type consistency (`int` and `list`).

[ENH] consistent `sp` handling in parameter estimators and `AutoARIMA`

---

sktime/annotation/tests/test_all_annotators.py

Temporarily addresses sporadic failure on `main`
https://github.com/alan-turing-institute/sktime/issues/3394
by skipping the affected test.

[ENH] skip sporadic failure in testing `HMM`

---

sktime/annotation/hmm.py
sktime/annotation/tests/test_all_annotators.py

Thank you to @fkiraly for bringing this error to my attention in #3394 
I believe the issues was arising from potential randomness in the generation of fake data for the testing of output types for the estimator.  Depending on the data set that was generated, I believe the probability of seeing that data was accidentally running into a -Inf.  This is behavior I should fix in a more elegant manner (ie by detecting that we are approaching a -Inf and either recalibrating or using a modulo solution), but for now I believe I have fixed the error by changing two things:
- Increasing the sd of the emission functions for my test parameters.  This should make a range of values far more likely than what we saw before, helping the tests to avoid the region where it encountered errors
- changing the …

[ENH] Fix for hmm sporadic test failure

---

docs/source/about/team.rst

Update core dev list according to [governance ](https://www.sktime.org/en/stable/get_involved/governance.html#end-of-tenure)
> Core developers that have not contributed to the project in the past one-year-period will automatically become inactive and give up their rights and responsibilities. 
Thanks for all contributions made by you :) You can come back and become active again at any point in time.
fyi: @SveaMeyer13 , @jasonlines @james-large @abostrom

[GOV] Update core dev list

---

sktime/forecasting/model_selection/_split.py

This PR corrects and clarifies some docstrings of `BaseSplitter` methods.
`split_series` was incorrect in that it did not state that all time series containers incl `Panel` and `Hierarchical` were supported.

[ENH] correcting and clarifying `BaseSplitter` docstrings

---

README.md

Fixes expired link to Slack under the "Where to ask questions" section of the README.
Related to #3014

[DOC] Expired slack link under "Where to ask questions"

---

docs/source/developer_guide/dependencies.rst

@fkiraly had some useful suggestions for how to fully isolate new soft dependencies.  In particular there were a few comments about how to skip (or selectively skip) tests for estimators with a new soft dependency.  Just copying those over to the developer docs.

[DOC] Instructions for how to skip tests for new soft dependencies.

---

sktime/classification/deep_learning/mlp.py

This isolates the soft dependency in the `MLPClassifier` doctest by skipping it.
Coverage is not reduced as fitting is already tested by the test suite.

[ENH] isolate soft dependency in `MLPClassifier` doctest

---

sktime/classification/feature_based/_catch22_classifier.py
sktime/transformations/series/exponent.py
sktime/transformations/tests/test_all_transformers.py
sktime/utils/estimators/_forecasters.py

Towards #3429. This adds a second parameter set for all estimators checked via `check_estimator` in the `no-softdeps` CI element.
This is generally useful, and also allows https://github.com/alan-turing-institute/sktime/pull/2862 to pass that CI element.
... and we already discovered a bug, which I suppose proves that #3429 is generally a good idea.
The bug is `ExponentTransformer.inverse_transform` breaking if `power` is close to zero. This is now dealt with by a skip and a warning.

[ENH] second param sets for selected estimators

---

extension_templates/forecasting.py
sktime/forecasting/base/_base.py
sktime/forecasting/compose/_reduce.py
sktime/forecasting/ets.py

This PR introduces missing data input checks to forecasters and fixes #3402.
Changes:
* `_check_X_y` in forecasters now raises an informative exception if input contains missing data and the forecaster does not support it
* the forecaster extension template is updated accordingly
* reducers are updated so missing value handling tags mirror the wrapped sklearn estimator's tag
* switched the tag to `True` in some estimators causing issues: `AutoETS`

[ENH] missing data input check in forecasters

---

sktime/transformations/panel/tests/test_interpolate.py

This updates `test_interpolate` to be `pandas 1.5.0` compatible.
Apparently, it is no longer possible to assign `pd.Series` to fields of `pandas.DataFrame` via `iloc` or `at`.
Assignment via `iloc` breaks, and `at` now seems to result in `numpy` rather than `pd.Series`. Bug or not, this is fixed by accessing `values` directly.

[MNT] update `test_interpolate` to be `pandas 1.5.0` compatible

---

sktime/datatypes/_panel/_check.py

One of the previous `sktime` versions extended the `nested_univ` mtype to allow for scalar valued columns.
The check for that worked fine, but the metadata extraction would break if such a column was present.
This was not directly or indirectly tested as the example fixtures did not cover this case.
With the data loaders being tested, the case is covered and uncovers the bug.
This PR ensures that the `nested_univ` metadata inference does not break in the case where scalar columns are present.

[BUG] ensure `nested_univ` metadata inference passes for scalar columns present

---

sktime/transformations/series/lag.py

Attempted fix for failure in https://github.com/alan-turing-institute/sktime/pull/3450 after update to pandas 1.5.0.
This ensures that `Lag` uses `infer_freq` if no `freq` passed or specified.

[ENH] pandas 1.5.0 compatibility fix: use `infer_freq` in `Lag` if no `freq` passed or specified

---

sktime/datatypes/_check.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/transformations/base.py

This PR changes `check_is_scitype`'s second return to a `dict`, so the error message is indexed by the corresponding mtype.
The old return was not very useful, as it was not possible to easily or clearly match the message with its mtype.
Includes:
* deprecation mechanism to change the return type
* improved input check feedback for transformers
* cleanup of formatting and grammar in some check error messages

[ENH] `check_is_scitype` error message return changed to `dict`

---

sktime/forecasting/ardl.py
sktime/forecasting/base/adapters/_statsmodels.py
sktime/forecasting/dynamic_factor.py
sktime/forecasting/ets.py
sktime/forecasting/exp_smoothing.py
sktime/forecasting/sarimax.py
sktime/forecasting/structural.py
sktime/forecasting/tests/test_ardl.py
sktime/forecasting/tests/test_sarimax.py
sktime/forecasting/tests/test_structural.py
sktime/forecasting/tests/test_var.py
sktime/forecasting/tests/test_varmax.py
sktime/forecasting/tests/test_vecm.py
sktime/forecasting/trend.py
sktime/forecasting/var.py
sktime/forecasting/varmax.py
sktime/forecasting/vecm.py
sktime/param_est/seasonality.py
sktime/transformations/bootstrap/_mbb.py
sktime/transformations/series/acf.py
sktime/transformations/series/clear_sky.py
sktime/transformations/series/detrend/_deseasonalize.py
sktime/transformations/series/detrend/tests/test_deseasonalise.py
sktime/utils/seasonality.py

This PR isolates `statsmodels` imports in estimators in the `fit` methods of said estimators.
It also adds the `statsmodels` package as a python dependency tag to the `_StatsModelsAdapter`.
This is beneficial because:
* it prevents imports of new `statsmodels` submodules like `ARDL` when not needed, thus making `sktime` compatible with older versions of `statsmodels`
* it reduces the number of `statsmodels` imports at typical use, making the import & interface behaviour of `sktime` cleaner
* it makes handling of `statsmodels` more consistent with other estimator interface dependencies
* it prepares a potential move of `statsmodels` to a soft dependency (although due to afew non-estimator dependencies this seems unlikely in the near future)

ENH] isolate `statsmodels` imports

---

docs/source/developer_guide/deprecation.rst

This adds clarifications and a worked example to the deprecation policy.
The policy itself does not change, only clarifying details are added.

[DOC] clarifications on deprecation notes

---

sktime/base/__init__.py
sktime/base/_base.py
sktime/base/_serialize.py
sktime/tests/test_all_estimators.py

This adds a prototype design for serializing and deserializing estimators.
This follows the current (Aug 19) draft STEP 27 https://github.com/sktime/enhancement-proposals/pull/27.
This is done via `save` and two `load` methods which can be overridden by class, and a generic `load` (class agnostic), in the `BaseObject` module.
Also changes the pickle/unpickle test to a generic serialize/deserialize test which allows custom, class specific implementations of serialize and deserialize.
FYI @AurumnPegasus - design alternative to https://github.com/alan-turing-institute/sktime/pull/3128 which avoids the workflow where we have to construct an object first when we load.

[ENH] design for generic save/load aka serialization/deserialization of estimators

---

sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/tests/test_column_ensemble.py

Fixes #3502, `ColumnEnsembleForecaster` failed for str indices.
This was a little involved, as it seems that string indices were not properly parsed at all.
Also adds a test based on @canbooo's example
Also extends `ColumnEnsembleForecaster` so that multiple columns can be passed, in which case a forecaster is applied as multivariate.

& canbooo [BUG] fix `ColumnEnsembleForecaster` for str index; extend `ColumnEnsembleForecaster` to allow application of multivariate forecasters

---

sktime/clustering/k_means.py
sktime/clustering/metrics/averaging/_averaging.py

Updated kmeans to handle average params when using derivative.
Not all average params were able to be properly passed to kmeans when using DBA. This pr fixes it. In particular the fix is for ddtw and wddtw distances as preprocessing of the time series is done inside the clusterer and therefore doesn't need to be redone each iteration in the DBA function.

[BUG] Pass all average params to kmeans

---

sktime/classification/deep_learning/tapnet.py

@TonyBagnall Here's the PR that we talked about. Let's work on it together.
Fixes #3525
Add a class method `get_test_params()` similar to other estimators that is to be used by runners during tests. 
No.
We want to reduce total time taken for tests to run on `TapNetClassifier` and `TapNetRegressor`.

[BUG] Add `get_test_params()` to TapNet Estimators

---

sktime/forecasting/naive.py
sktime/forecasting/tests/test_naive.py

Fixes #3469 
The current `_predict_var` implementation for `NaiveForecaster` does not deal with "mean" strategies with `sp > 1` or `window_length != None`. Moreover, the "drift" strategy does not account for the fact that the "starting" point for the line is set to `y[-window_length]` if `window_length` is not null.
This PR fixes both issues by computing residuals for rolling means (seasonal and non-seasonal) and setting the starting point of the drift line to `-(window_length or len(y))`
No.
- Logic for computing residuals for rolling means and rolling seasonal means
- Prior art (R fable): https://github.com/sktime/sktime/issues/3469#issuecomment-1256862149
Please note the debate on computing residuals across rolling windows vs computing residuals against a single y hat array (#3469).

[BUG] Fix residuals formula in NaiveForecaster predict_var for non-null window_length

---

sktime/datatypes/_convert_utils/__init__.py
sktime/datatypes/_convert_utils/_convert.py
sktime/datatypes/_panel/_convert.py
sktime/datatypes/_series/_convert.py
sktime/datatypes/_table/_convert.py

This PR refactors mtype conversion extension utils into one location.
Three almost identical instances of `_concat` and two of `_extend_conversions` ( in `_convert` modules of `_series`, `_panel`, and `_table`) are moved into the new module `datatypes._convert_utils` and replaced by imports.
One instance of `_extend_conversions` without function wrapping in `_series._convert` is also replaced by use of `_extend_conversions`.
This should make future addition of mtypes, e.g., dask support, or further xarray support, easier.
FYI @benHeid, @topher-lo

[ENH] refactor mtype conversion extension utils into one location

---

sktime/classification/deep_learning/tapnet.py
sktime/regression/deep_learning/tapnet.py

Fixes #3525
- Add `get_test_params()` for `TapNetRegressor` and `TapNetClassifier` with two parameter set.
- Remove the redundant `is_fitted` variable from TapNet estimators.
- Correct minor typos.
No
@TonyBagnall LMK if we should make any more changes here.

[BUG] fast test parameters for `TapNet` estimators and docstring/interface cleanup

---

sktime/transformations/hierarchical/aggregate.py

Replaces inplace sort by non-inplace sort in `Reconciler` to avoid any inplace related issues (e.g., side effects)

[ENH] replace inplace sort by non-inplace sort in `Reconciler`

---

sktime/regression/deep_learning/cnn.py

Fixes #3538
- Add the following parameters into constructor:
- `optimizer`
- `activation`
- `use_bias`
No.
@AurumnPegasus do let me know if you see more changes that we can add in this PR.

[ENH] Add more relevant parameters to `CNNRegressor` for user flexibility

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py

closes #3547 
@ngupta23 please have a look
I removed the tag inheritance bcz if the forecaster cant handle missing values, it will raise an exception then anyways but it will work if an `Imputer` was used in the pipe.

[BUG] Fix pipeline tag for NaN values

---

sktime/tests/_config.py
sktime/transformations/panel/shapelet_transform.py

…avoid empty shapelet lists for edge case
fixes #3138 
#3138 describes an edge case bug where RandomShapeletTransform returns an empty list of shapelets. This happens when the max number of shapelets
>self = RandomShapeletTransform(batch_size=20, max_shapelets=5, n_shapelet_samples=50)
is set to be less than the number of classes.
>y          = array([4, 3, 6, 8, 1, 2, 9, 7, 0, 5])
these makes the transform set
max_shapelets_per_class = 0.5
this PR simply floors the max_shapelets_per_class to be 1, ensuring that at least one shapelet per class is returned. 
no
I guess the alternative would be to throw an exception or actually return max_shapelets so that some classes have no shapelets. I think this is more sensible and robust solution.

[BUG] RandomShapeletTransform: floor the maximum number of shapelets to be the number of classes

---

sktime/utils/estimator_checks.py
sktime/utils/tests/test_check_estimator.py

Fixes #3565, i.e.,. `check_estimator` exclude arguments would not work for non-base scitype specific tests
This was due to the exclude arguments not being passed on properly to `run_tests`.
The existing test did not cover this failure because it looked at base scitype tests only. It has been modified to also include some non-base scitype tests.

[BUG] fix `check_estimator` exclude arguments not working for non-base scitype tests

---

sktime/forecasting/model_evaluation/_functions.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py

Carries out item from https://github.com/sktime/sktime/issues/2243.
Extends `evaluate` to accept hierarchical `X` and `y`.
By extension, should enable `GridSearchCV` to handle hierarchical data and resolve bug https://github.com/sktime/sktime/issues/3464.
Less hacky version of https://github.com/sktime/sktime/pull/3509 which uses the centralized checker functions and hierarchical functionality of splitters instead of custom duplicates.
FYI @aiwalter, @danbartl, @ngupta23

[ENH] extend `evaluate` to hierarchical and panel data

---

docs/source/get_involved/governance.rst

This PR adds some minor clarifications to the governance document, without changing any of the rules.
The nature of most changes is removing vagueness or reference ambiguity in the governance rules.
These changes are from https://github.com/sktime/sktime/pull/1237, without the changes proposed in that PR.

[DOC] minor clarifications of governance

---

sktime/base/_meta.py

This PR removes `ABCMeta` inheritance from `_HeterogeneousMetaEstimator` which fails currently due to `flake8` `B024`, i.e., abstract base class without abstract decorators.
In fact, `_HeterogeneousMetaEstimator` is a mixin and not an abstract base class, so this is indeed a style/pattern failure which was not picked up earlier (possibly since `flake8` was not enabled back then).

[MNT] Remove `ABCMeta` inheritance from `_HeterogeneousMetaEstimator`

---

sktime/transformations/panel/tests/test_Truncate.py
sktime/transformations/panel/truncation.py

Tests the failure case in https://github.com/sktime/sktime/issues/2998, where `TruncationTransformer` could destroy column and index names.
Also makes the `TruncationTransformer` safer by preserving index explicitly.

[ENH] test that `TruncationTransformer` preserves index and column names in `pd-multiindex`

---

docs/source/get_involved/code_of_conduct.rst

This fixes outdated points of contact in the code of conduct, and updates documentation to agree with its current composition.
Updates to composition:
* @mloning resigned when he left CC (2021)
* @TonyBagnall resigned when he left CC https://github.com/sktime/sktime/pull/2794 (June 2022)
* @martinagvilas resigned via communication to CC
This leaves me as its sole member, so to ensure a proper process the interim document points to the numfocus process.
We also have had a repeated action in CC to ask for CoCC members, but this did not result in expressions of interest so far.

[DOC] fixes outdated points of contact in code of conduct

---

.github/ISSUE_TEMPLATE/config.yml
docs/source/get_involved/code_of_conduct.rst

Fixes #3592 and some remaining references to specific members of the committee.

[DOC] fixes incorrect coc issue reporting link in issue tracker and remaining references in coc

---

pyproject.toml

This PR loosens the upper version bound for `scipy` to `<2.0.0`, thus removing any restriction on `1.X.X` versions.
We had the MINOR bound introduced after repeated breakage, this was mostly on `sktime` side using private methods (which was a mistake). Afaik we are no longer doing that, and `scipy` is very good at deprecation, so I think we can safely move the bound up to the MAJOR cycle.
Fixes #3586.

[MNT] loosen `scipy` bound to <2.0.0

---

sktime/classification/sklearn/_continuous_interval_tree.py
sktime/utils/numba/stats.py

Fixes #3582
#3582 identified a bug that occurs with DrCIF classifier when n_jobs > 1 and the dataset is large. This originated in the numbaversion of the median function in utils/numba/stats.py. The problem is that when the data is beyond some size threshold, Parallel uses mmap to write the data to local storage to avoid unnecessary data cloning. When this happens, a bug occurs in the interaction between numba and np.median caused by write permissions. See 
https://github.com/numba/numba/issues/3070
The np.median implementation in Numba doesn't support read-only arrays, and once the mmap condition in Parallel is triggered, the cached arrays are all read-only (and need to be to avoid thread interference). This triggers the error seen in #3582. It was not detected in testing since it only …

[BUG] Numba/np.median interaction raises error for large data sets run with n_jobs>1 issue #3582

---

sktime/utils/estimators/tests/__init__.py
sktime/utils/numba/general.py
sktime/utils/numba/tests/__init__.py
sktime/utils/numba/tests/test_general.py

Fixes #2397 
#2397 identified that STC could fail when passed float32 data instead of float64. On investigation, it turns out that the actual problem was with the call to np.zeros in the numba method z_normalise_series. Numba does some strange type checking, and it does not like the return signature of np.zeros when called with float32. We could fix this by setting the dtype for np.zeros, but this would not work with int32 or int64. 
So the simplest solution is to replace the function with this
```
@njit(fastmath=True, cache=True)
def z_normalise_series(X):
"""Numba z-normalisation function for a single time series."""
std = np.std(X)
if std > 0:
X_n = (X - np.mean(X)) / std
else:
X_n = X - np.mean(X)
return X_n
```
adapting the original code in #2397 
```
def debug_numba_stc_2397(type): …
```

[BUG] bug in the interaction between Numba and np.zeros identified in #2397

---

sktime/tests/_config.py

This PR emergency-removes tapnet based estimators from tests to avoid failures unrelated to PR from CI.
See https://github.com/sktime/sktime/issues/3525 for the bug.

[MNT] temporarily remove stochastically failing tapnet from tests

---

sktime/datasets/_single_problem_loaders.py
sktime/transformations/series/clear_sky.py
sktime/transformations/series/tests/test_clear_sky.py

Missing values which should be retained as missing in the transformed domain were being overwritten to zero.
* Simple fix to only set transformed values to zero when they are below the clear sky power threshold **and** if the original value is not null

[BUG] `ClearSky` fix missing value problem after transform

---

sktime/utils/_testing/scenarios.py
sktime/utils/_testing/scenarios_classification.py
sktime/utils/_testing/scenarios_clustering.py
sktime/utils/_testing/scenarios_forecasting.py
sktime/utils/_testing/scenarios_transformers.py

This PR handles the edge case of `get_args` in scenarios, where the requested key does not exist in the scenario.
In that case, `get_args` returns an empty parameter set.
Also resolves some copy-paste by `super` calls.

[ENH] `get_args` default handling for keys not present

---

sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/tests/test_column_ensemble.py

This PR adds support for `numpy` based integer types in `ColumnEnsembleForecaster`, previously this would have broken.
Also changes one of the current tests to cover this case.

[ENH] `numpy` integer support for `ColumnEnsembleForecaster`

---

extension_templates/classification.py
extension_templates/clustering.py
extension_templates/early_classification.py
extension_templates/forecasting.py
extension_templates/transformer.py
sktime/base/_base.py
sktime/classification/_delegate.py
sktime/forecasting/base/_delegate.py
sktime/regression/_delegate.py
sktime/transformations/_delegate.py

This PR updates the extension templates to be in line with the extender contract for `get_fitted_params` introduced a while ago.
Users should implement `_get_fitted_params`, similar to the template pattern used in the extension contracts for `fit`, `predict`, etc.
Also updates the docstrings of present `_get_fitted_params` methods to be clearer about the return.

[DOC] update extension templates and docstrings for `_get_fitted_params`

---

.all-contributorsrc
sktime/forecasting/base/adapters/_statsmodels.py

Fixes [1788](https://github.com/sktime/sktime/issues/1788)
When `update_params=False`, calling `update` with any `_StatsModelsAdapter` model does not work as expected. This PR changes behavior only when `update_params=False` and `self.is_composite=False`, and now uses the `statsmodels` `append` functionality to add new observed data without refitting the model.
No
The following outstanding questions
1. For now if the user doesn't pass data with the correct index to `update()`, they will get the error message from `statsmodels` that `ValueError: Given endog does not have an index that extends the index of the model.` I could add functionality to check if the updated data intersects with the original data and only take the new subset, but could use advice on which data types we would need …

[BUG] Fixes 1788 - Add statsmodels append() to _update() in _StatsModelsAdapter

---

sktime/base/_base.py

The default `get_fitted_params` would break if unfittable components were present, i.e., `BaseObject` children that were not `BaseEstimator` children due to a query to the `_is_fitted` attribute that only `BaseEstimator` children have.
This has been fixed.
Fixes various issues in https://github.com/sktime/sktime/pull/3590 which occur for calling `get_fitted_params` on composites with unfittable components.

[BUG] fix `get_fitted_params` default for unfittable components

---

sktime/classification/interval_based/_tsf.py
sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/model_selection/_tune.py
sktime/series_as_features/base/estimators/_ensemble.py
sktime/series_as_features/base/estimators/interval_based/_tsf.py
sktime/transformations/compose.py

This fixes `get_fitted_params` for estimators that were non-conformant to the interface specification or where the standard call would break, highlighted by new tests in https://github.com/sktime/sktime/pull/3590
* `pmdarima` based estimators returned dict with non-str keys, this was fixed
* time series forests broke due to call to attribute in `sklearn` that was not used, this was fixed by overriding with a custom `_get_fitted_params`
* `Id` broke since it was accidentally inheriting from the delegator, not from the `BaseTransformer`
* `FitInTransform` did not raise `NotFittedError`, was broken in vectorization/broadcasting case
* grid searches did not raise exception with expected error message, was broken in vectorization/broadcasting case

[BUG] fix `get_fitted_params` for non-conformant estimators

---

sktime/forecasting/compose/__init__.py
sktime/forecasting/compose/_grouped.py

This PR adds a wrapper-compositor that allows to specify by which level to fit forecasters: global, panel (per-panel), or local (per-instance).
This uses the same logic as in the reducer prototype.
Potential use case is controlling the level on which grid search is being conducted, in case the forecaster in the grid search is already looping over hierarchy levels.

[ENG] forecast-by-level wrapper

---

docs/source/get_involved/code_of_conduct.rst

Reverts sktime/sktime#3095
Reverting due to merging without approval and pending change requests. Merging this PR was a violation of our governance rules outlined in https://www.sktime.org/en/stable/get_involved/governance.html#decision-making

Revert "[GOV] proposed code of conduct update - mature sktime structure and decision making on resources"

---

sktime/param_est/fixed.py

This PR introduces a parameter fitter `FixedParams`, which simply sets fitted parameters to certain fixed values.
This can be used as a dummy/mock, or as a pipeline element, e.g., to set parameters to certain values, or in model selection as the "fixed" option.
It is also useful in isolating `statsmodels` (as a pseudo-mock), since currently all non-composite parameter estimators depend on `statsmodels`.

[ENH] fixed parameter setter estimator

---

sktime/utils/_testing/scenarios_forecasting.py

Changes one of the forecaster scenarios to include a string `pd.DataFrame` column name.
Somewhat surprisingly, none of the test cases covered string column names, all were integers.
Also see https://github.com/sktime/sktime/issues/3502, a very straightforward failure for string columns.
The new test should pick up #3502 before it is fixed.

[ENH] add forecaster test case with string columns

---

sktime/datatypes/_utilities.py

Fixes `get_cutoff` for `numpy` formats.
Was apparently not tested.
Todo: tests.

[BUG] fix `get_cutoff` for numpy format

---

sktime/tests/test_all_estimators.py

This PR improves the estimator tests as follows:
* improves docstrings of some base class tests to explain what they test and why they are important
* adds additional asserts to test expected `clone` output

[ENH] improve base class test docstrings and clone test

---

sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_series/_check.py

This PR fixes erroneous asserts in input checkers for some `pandas` based types.
The result is that no informative error message would be returned (none instead of one), "informative" is not picked up by tests (and perhaps not testable)

[BUG] fix erroneous asserts in input checkers

---

.all-contributorsrc
sktime/forecasting/model_selection/_split.py
sktime/forecasting/model_selection/tests/test_split.py
sktime/utils/validation/__init__.py

Fixes #2678 - second attempt after PR 3685 got messy.
`ExpandingWindowSplitter` now has consistent behavior when `start_with_window=False` or `initial_window=0`. In the case of the former, a warning is raised that `start_with_window` will be depreciated in version 0.15.0.
Also includes a test case for when `initial_window=0` with `ExpandingWindowSplitter`. 
Unlike the last PR, the scope does not affect behavior of `SlidingWindowSplitter`. 
I imported `warn` but no real deps.

[ENH] ExpandingWindowSplittter fix for initial_window=0 and depreciating "start_with_window" 

---

docs/source/get_involved/governance.rst

This PR is a proposal following my action to clarify certain points in the governance document. 
As it was discussed in the Oct 25 CC meeting, the original #3154 was contentious in its changes to the algo maintainer role, this should be the part that was **contentious** to @aiwalter. The other part is in #3675. Relevant action here: https://github.com/sktime/community-org/issues/40
Changes are clarifications to the role of an algorithm maintainer:
* the responsibility they have with respect to classes/estimators is clarified
* it is clarified that the responsibility and ownership is to/of python classes, not abstract concepts
* in particular, algorithm maintainers have no rights/responsibilities regarding other instances of the same abstract concept
* algorithm maintainers are better …

[GOV] clarifications on algorithm maintainers

---

sktime/transformations/panel/tests/test_tsfresh.py
sktime/transformations/panel/tsfresh.py

Attempt to fix #3526
- Fixes parameter passing logic of `TSFreshFeatureExtractor` (previously, as mentioned in #3526, the user-specified feature set was overriden by the `default_fc_parameters` argument)
- Improved docstring
- Added test cases (also for user-selected features via `kind_to_fc_parameters`)
No

[ENH]  `TSFreshFeatureExtractor` cleanup, tests, and docstring

---

docs/source/get_involved/governance.rst

Reverts sktime/sktime#3684
Sorry, did not see this - it was merged within a very short time of the PR being opened.
I disagree with the change.
I agree that governance documents need to be approved, so I agree with removing the lazy consensus condition.
However, I do not agree removing the requirement for a STEP, which means the change must be made public.
Here's the change I would want:
* there must be at least one presentation of proposed GOV changes in teh CC meeting before they can be merged
* it requires approval by at least one CC member (if gov doc) or CoC committee member (if CoC doc)

Revert "[GOV] Lazy consensus on GOV PRs"

---

sktime/classification/feature_based/_tsfresh_classifier.py
sktime/classification/interval_based/_drcif.py
sktime/classification/sklearn/_continuous_interval_tree.py
sktime/classification/sklearn/_rotation_forest.py
sktime/classification/sklearn/tests/test_all_classifiers.py
sktime/classification/sklearn/tests/test_continuous_interval_tree.py
sktime/tests/_config.py
sktime/transformations/panel/dictionary_based/_sfa_fast.py
sktime/transformations/panel/rocket/tests/test_MiniRocket.py
sktime/transformations/panel/rocket/tests/test_MiniRocketMultivariate.py
sktime/transformations/panel/rocket/tests/test_MultiRocket.py
sktime/transformations/panel/rocket/tests/test_MultiRocketMultivariate.py
sktime/transformations/panel/rocket/tests/test_Rocket.py

Fixes some small classification bugs and typos.
- `TSFreshClassifier` returns the majority class if all attributes are removed in feature selection
- `ContinuousIntervalTree` allow NaNs in its input (includes test for NaN input)
- `RotationForest` replaces PCA NaNs with 0s
- Fixes #3694 by setting a random state for ROCKET tests

[BUG] Small classification bugfixes

---

sktime/transformations/panel/tsfresh.py

Adds a `tsfresh` reference in `TSFreshFeatureExtractor` missing in the docstring description.
The reference was there in the "references" section, but not clear in the description section.

[DOC] `tsfresh` reference in `TSFreshFeatureExtractor` docstring

---

docs/source/developer_guide/release.rst
pyproject.toml
setup.py

This PR attempts to address the failed pypi upload for v0.14.0, fixes https://github.com/sktime/sktime/issues/3715.
My suspicion is that there is an interaction between `setup.py` and `pyproject.toml` in the email address fields.
* this PR removes personal email addresses from `pyproject.toml`
* in `setup.py`, replaces names of one author with "project developers", and emails with a hardcoded string `"info@sktime.org"`
Also adds instructions to the release process docs how to re-release in a case where the wheel upload fails.

[MNT] addressing failed v0.14.0 pypi upload

---

sktime/forecasting/base/_base.py

This updates the warning raised by the default `BaseForecaster._update` to point to the `forecasting.stream` module, to point out to users the possibility to update less often or turn off refitting at `update` call (which is available but extrinsic as wrapper).

[ENH] forecast default update warning to point to stream forecasting wrappers

---

docs/source/api_reference/classification.rst

Reverts sktime/sktime#3735.
Agreed with the addition of missing classifiers.
Disagree with the change in sequence and overall sequence, this makes more obscure classifiers more prominent.
First listed should be more well-known classifiers or those that people would like to find, and/or sensible baselines.
Re categories, the first ones should be
* composition
* dummy
* feature-based
* distance-based
Inside categories, common classifiers or generalizations of well-known classifiers from sklearn should be first.
* in distance-based, should be KNN
* in interval-based, it should be the forests
Early classification and tabular classification should be separate rubrics.

Revert "[DOC] Add missing estimators to classification API page"

---

CODEOWNERS

Removes owners of classification sub-packages and replaces them with owners for individual files. This impacts @TonyBagnall and @patrickzib, let me know if you are fine with these changes or if you want any other changes to ownership.
Adds myself as owner to `sktime/transformations/panel/random_intervals.py`, `sktime/transformations/panel/supervised_intervals.py`, `sktime/classification/sklearn/_continuous_interval_tree.py`, `sktime/classification/sklearn/_rotation_forest.py`.
Moved the owners of `sktime/transformations/panel/shapelets.py` to the correct file (`shapelets.py` does not exist).

[MNT] update CODEOWNERS

---

sktime/classification/compose/_ensemble.py
sktime/classification/compose/tests/test_ensemble.py

minimally reconfigures the test for ComposableTimeSeriesForestClassifier to speed them up. 
The testing contains this line
@pytest.mark.xfail(reason="SeriesToPrimitivesTransformer will be deprecated, see 2179")
not sure if this has been resolved. There is no code owner for ComposableTimeSeriesForestClassifier and I do not want to change the algorithm at all, so I am leaving this as is.

[ENH] slightly speed up the tests for ComposableTimeSeriesForestClassifier 

---

sktime/classification/dictionary_based/_tde.py

Rather than throwing an error when the minimum window length is too small, this PR changes `TemporalDictionaryEnsemble` to warn the user and lower the minimum window length instead.

[ENH] Warning rather than error for TDE small series

---

sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/tests/test_column_ensemble.py

Fixes https://github.com/sktime/sktime/issues/3764, with the fix proposed by @rikstarmans (with a minimal change)
Includes the failure case in #3764 as a test.

& RikStarmans [BUG] fix `ColumnEnsembleForecaster` for hierarchical `X`

---

sktime/transformations/base.py

This PR improves the error message if the transform output check fails, by pointing to the estimator type and printing the output.

[ENH] better error message on transform output check fail

---

sktime/transformations/panel/supervised_intervals.py

Fixes a bug with `SupervisedIntervals` `fit_transform` where the output was not converted (it was missing the boilerplate from `transform`).
Adds the option for the user to select the `joblib` background, with the default preference set to "threads".
Also includes some interval variable renames and small docstring additions.

[BUG] SupervisedIntervals bugfixes and clean up

---

sktime/classification/shapelet_based/_stc.py

Adds to the `ShapeletTransformClassifier` docstring and fixes some quirks with the auto-generated API webpage for the estimator.

[DOC] Improve ShapeletTransformClassifier docstring

---

docs/source/api_reference/classification.rst

Restored reverted #3735 by @MatthewMiddlehurst since I have a change request.
My change request:
Agreed with the addition of missing classifiers.
Disagree with the change in section sequence and overall sequence, this makes more obscure classifiers more prominent.
First listed should be more well-known classifiers or those that people would like to find, generalizations of common tabular classifiers, and/or sensible baselines.
Re categories, the first ones should be
* composition
* dummy
* feature-based
* distance-based
Inside categories, common classifiers or generalizations of well-known classifiers from sklearn should be first.
* in distance-based, should be KNN
* in interval-based, it should be the forests
Early classification and tabular classification should be separate rubrics.

by matthewmiddlehurst [DOC] Add missing estimators to classification API page

---

sktime/forecasting/compose/tests/test_reduce_global.py

See the bug report for the reasoning: https://github.com/sktime/sktime/issues/3601#issuecomment-1307787414 .
There is not a bug in the implementation, but it actually makes sense to check for this fact.

[ENH] Add test for global forecasting

---

sktime/forecasting/compose/_pipeline.py

This PR decouples the forecasting pipeline module `forecasting.compose._pipeline` from the `registry` module, fixing some of the import coupling and `numba` related issues in https://github.com/sktime/sktime/issues/3660.
With this, only test modules, the `all` modules and utils should import from the `registry`, and no estimators.

[BUG] decouple forecasting pipeline module from registry

---

sktime/classification/tests/test_base.py

This PR temporarily skips the new failure `test_deep_estimator_full[keras-adamax]`, possibly coming from an update in the dependencies.
See here for the failure: https://github.com/sktime/sktime/issues/3816

[MNT] temporary skip of new failure `test_deep_estimator_full[keras-adamax]`

---

sktime/tests/_config.py

Tests are failing for strange reasons, see for example
https://github.com/sktime/sktime/actions/runs/3492869189/jobs/5847895424
I cannot reproduce locally. TapNet was excluded but recently put back in. This PR is just to test to see if it is the root of the problem

[BUG] exclude TapNet from tests

---

sktime/base/_meta.py
sktime/classification/_delegate.py
sktime/classification/compose/_column_ensemble.py
sktime/classification/compose/_ensemble.py
sktime/classification/compose/_pipeline.py
sktime/dists_kernels/algebra.py
sktime/dists_kernels/compose.py
sktime/forecasting/base/_delegate.py
sktime/forecasting/base/_meta.py
sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/_grouped.py
sktime/forecasting/compose/_multiplexer.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/stream/_update.py
sktime/param_est/compose.py
sktime/regression/_delegate.py
sktime/regression/compose/_pipeline.py
sktime/transformations/_delegate.py
sktime/transformations/compose.py

This PR adds a default `get_params`/`set_params` for the `_HeterogenousMetaEstimator` with varying part based on a private attribute, which can replace many of the copy/pasted `get_params`/`set_params` for concrete heterogeneous estimators.
This replaces abstract methods of the same name that raise an error if called.
For this to work as a replacement of copy-pasted methods in descendants, two changes are made:
* `_HeterogenousMetaEstimator` no longer inherits from `BaseEstimator`, so is turned back into a mixin from a base class
* descendants now must inherit from `_HeterogenousMetaEstimator` *before* a base class
A full refactor is carried out to replace duplicated `get_params`/`set_params` with the default from `_HeterogenousMetaEstimator`.
No deprecation is necessary since the class …

[ENH] default `get_params`/`set_params` for `_HeterogenousMetaEstimator` & [BUG] fix infinite loop in `get_params` for `FeatureUnion`, with hoesler

---

sktime/forecasting/base/_base.py
sktime/forecasting/compose/tests/test_pipeline.py
sktime/transformations/base.py

This PR adds a square brackets / `__getitem__` dunder for forecasting.
This mirrors the same dunder for transformers:
* first bracket element subsets the exogeneous input data
* second bracket element subsets the forecast
See docstring of the new dunder.
The choice for subsetting the exogeneous and not endogeneous input data is due to that being a more frequent use case (I think).
Tests are also added for the new dunder.
Other minor content:
* docstring fix for the transformer square bracket dunder

[ENH] getitem / square brackets dunder for forecasting

---

sktime/transformations/series/scaledlogit.py

The `ScaledLogitTransformer` docstring was missing defaults. Added here.

[ENH] add defaults in `ScaledLogitTransformer` docstring

---

sktime/transformations/base.py
sktime/transformations/tests/test_base.py
sktime/transformations/tests/test_compose.py

Transformers with `Primitives` output would return unexpected indices in case of vectorization: this would always reset to a `RangeIndex`, but the expectation is that the hierarchy/instance index is preserved, if there is at least one hierarchy level.
Fixed the bug and added a test.
Other changes:
* replaced the "abuse" of `Series` converter in the same location with the `Table` converter (this was introduced after the original code was written, and is the correct type check).
* the test `test_sklearn_after_primitives` needed to be slightly relaxed, as the above changes lead to indices with same elements but different type in `Table` typed returns, i.e., `Int64Index` being preserved from the instance index level, instead of being reset to `RangeIndex`. This happens in the panel data …

[ENH] fix return index for transformers' `Primitives` output in row vectorization case

---

sktime/classification/dummy/_dummy.py

In `DummyClassifier`, the `capability:multivariate` tag was incorrectly set to `False`.
This has been changed to `True`.
Reason: `DummyClassifier` ignores `X` (besides its length), so it is unimportant whether it was multivariate or not.

[BUG] in `DummyClassifier`, fix incorrectly set `capability:multivariate` tag

---

sktime/transformations/series/date.py
sktime/transformations/series/tests/test_date.py

This PR adds `is_weekend` as an option to the `manual_selection` argument in the `DateTimeFeatures` transformer. I have also added more examples to the docstring.
Example usage:
```Python
import pandas as pd
from sktime.transformations.series.date import DateTimeFeatures
df = pd.DataFrame(
data={"y": [1, 1, 1, 1, 1, 1, 1]},
index=pd.date_range(start="2000-01-01", freq="D", periods=7),
)
result = DateTimeFeatures(manual_selection=["is_weekend"]).fit_transform(df)
```
The changes made to `_RAW_DUMMIES` on line 32. I'm forced to create a child/parent relationship so I made the child `day` and parent `week`. I'm unsure whether this could have unintended consequences. None were picked up in testing.
The setting of the `fourier` column in the `DUMMIES` dataframe on line 324. I am unsure whether …

[ENH] Add `is_weekend` option to `DateTimeFeatures` trafo

---

docs/source/developer_guide/dependencies.rst

Fixes #3421 
* Modified introductory sentence with simple enumeration of types;
* Merge the three *note* blocks into one that uses a list for explaining the types;
* less redundant phrasing

[DOC] fixed rendering in dependencies doc

---

sktime/transformations/series/clear_sky.py
sktime/transformations/series/tests/test_clear_sky.py

No open issue
Added some bug fixes which were highlighted by @robertmcleod2 - cheers!
The bugs were
* The `ClearSky` transformer relies on the datetime index to get the time of day. I thought the `enforce_index_type` tag would deal with removing range indexes, but it doesn't at the moment. Added a check for this
* The frequency of the data should be set and there was no check for this. I added one along with a function to infer it if possible. 
* The frequency should be within a range to be suitable for the transformer, so added a check for this as well.
Added tests for these bugs as well. 
No

[BUG] `ClearSky` doesn't raise error for range indexes and when `X` has no set frequency

---

docs/source/get_involved/governance.rst

#3865 
Remove ability of CC to overrule decisions made by core devs.

[GOV] Remove ability of CC to overrule core dev decisions

---

docs/source/get_started.rst

Hi devs, 
thanks for this library!
I was trying to use the example in the **Time Series Clustering** paragraph of the [Getting Started page](https://www.sktime.org/en/stable/get_started.html), but `plot_cluster_algorithm` was not in `sktime.clustering.evaluation._plot_clustering` but in `sktime.clustering.utils.plotting._plot_partitions`.
Therefore, this PR changes this line.
I hope this might be useful for others too.
Changing the import of `plot_cluster_algorithm` from `sktime.clustering.evaluation._plot_clustering` to `sktime.clustering.utils.plotting._plot_partitions`.

[DOC] changing import path for `plot_cluster_algorithm`

---

sktime/transformations/series/detrend/_detrend.py
sktime/transformations/series/detrend/tests/test_detrend.py

This PR adds a `model` argument to `Detrender`, similar to `Deseasonalizer`, which gives the option to divide by the trend component rather than subtract. 
Example usage:
```python
from sktime.datasets import load_airline
from sktime.transformations.series.detrend import Detrender
detrender = Detrender(forecaster, model="multiplicative")
y_transformed = detrender.fit_transform(y)
```
If the extracted trend has a zero value at any point, it would result in an `np.inf` value when we divide by the trend. What should the expected behaviour be in this case? Throw an error or return an output with an infinite value?

[ENH] Add multiplicative option to `Detrender`

---

sktime/classification/distance_based/_time_series_neighbors.py
sktime/classification/distance_based/tests/test_time_series_neighbors.py
sktime/regression/distance_based/_time_series_neighbors.py
sktime/regression/distance_based/tests/__init__.py
sktime/regression/distance_based/tests/test_time_series_neighbors.py

This PR fixes a bug that prevented KNN estimators' `kneighbors` methods to work with all mtypes.
This fixes #3798 for `KNeighborsTimeSeriesClassifier`, and an unreported analogue bug for `KNeighborsTimeSeriesRegressor`
The reason was missing check/conversion boilerplate that was present in `predict` and similar methods, the fix was simply adding that.
This PR also adds tests for the `kneighbors` method.

[BUG] fixes KNN estimators' `kneighbors` methods to work with all mtypes

---

sktime/classification/distance_based/_time_series_neighbors.py
sktime/regression/distance_based/_time_series_neighbors.py

This PR fixes a compatibility issue with `sklearn 1.2` and removes the private import `_check_weights` from `KNeighborsTimeSeriesClassifier` and `KNeighborsTimeSeriesRegressor`.
This can be done without deprecation or change in functionality, because `_check_weights` was just an erroneous leftover from an earlier version that used inheritance and not composition.
Right now, the `sklearn` classifier is wrapped as a component, so `_check_weights` (or its 1.2 equivalent) is called again inside the component - therefore, naive removal simply removes an unnecessary duplication.

[ENH] `sklearn 1.2.0` compatibility - remove private `_check_weights` import in `KNeighborsTimeSeriesClassifier` and -`Regressor`

---

sktime/series_as_features/base/estimators/interval_based/_tsf.py

In `sklearn 1.2.0`, the `base_estimator` parameter of `BaseForest` changed to `estimator`, but remained the first arg.
This ensures compatibility of  `sktime` interface points across versions, by
* removing the keyword from an instance of `BaseForest` init call for the `base_estimator` / `estimator` parameter
* dispatching on `sklearn` version when the attribute is being accessed

[MNT] `sklearn 1.2.0` compatibility - cover `BaseForest` parameter change

---

sktime/transformations/panel/channel_selection.py

`ElbowClassSum` and `ElbowClassPairwise` call `sklearn`'s `NearestCentroid` with an invalid shrinkage parameter `shrink_threshold=0`.
This parameter has always been invalid, but is only being checked for validity since `1.2.0`.
To be faithful to the current implementation, I suggest to set it to a small value - an alternative option would be to expose it as a parameter in the constructor, and set it to a small default.
I'm not sure whether `shrink_threshold=None` corresponds to zero mathematically.
@haskarb, what do you think?

[BUG] `sklearn 1.2.0` compatibility - fix invalid elbow variable selection shrinkage parameter passed to `sklearn` `NearestCentroid`

---

sktime/benchmarking/strategies.py

The benchmarking module was still calling the private method `sklearn.base._pprint` which has moved in `1.2.0`.
This is solved by replacing `_pprint` which a `repr` call, which may make things a bit less pretty but still leaves them functional (and compatible across `sktime` versions)

[BUG] `sklearn 1.2.0` compatibility - decouple `sklearn.base._pprint`

---

examples/rocket.ipynb
sktime/classification/dictionary_based/_muse.py
sktime/classification/dictionary_based/_weasel.py

This PR removes superfluous `normalize=False` args from `RidgeClassifierCV`.
The arg has been deprecated in `sklearn 1.2.0`, but was default `normalize=False` prior.
Simply removing the arg makes the occurrences compatible with `sklearn 1.2.0`.
Further, this PR removes use of the `normalize` argument from one of the secondary notebooks.

[MNT] `sklearn 1.2.0` compatibility - remove `normalize=False` args from `RidgeClassifierCV`

---

sktime/classification/compose/_ensemble.py
sktime/series_as_features/base/estimators/_ensemble.py
sktime/series_as_features/base/estimators/tests/test_feature_importances_.py

`ComposableTimeSeriesForest`, inheriting from `sklearn` `BaseForest`, was accessing the `estimator_` attribute which seems to have been made protected in `sklearn` 1.2.0.
The `sktime` attribute now has been changed to have another name.
Mid-term, this should be changed to composition, not inheritance.
Further, this skips the two tests for the private `sklearn` interface points (feature importances) failing in https://github.com/sktime/sktime/issues/3930.
The tests do not fail in `sklearn<1.2.0` with this PR but start failing on `sklearn 1.2.0`.
But, since the public interface contracts are tested and remain valid, seems fine enough for now.

[MNT] `sklearn 1.2.0` compatibility - `ComposableTimeSeriesForest` reserved attribute fix

---

pyproject.toml

Fixes https://github.com/sktime/sktime/issues/3895 where users are reporting failure to install `sktime[all_extras]` due to `pycatch22`.
This is a potential solution that removes `pycatch22` from the set of soft dependencies.
The dependent estimators can still be found in search via `all_estimators`, and users can install `pycatch22` manually, which should be an improvement above the `all_extras` dependencies set not installing at all for our users.

[MNT] remove `pycatch22` as a soft dependency

---

sktime/utils/plotting.py

packages must be str or a tuple of str. So, removing additional parenthesis.

[BUG] fix soft dependency check in `plotting.plot_correlations`

---

sktime/utils/plotting.py

Add an option to `plot_series()` to allow the user to pass a list of colors. I added a small util function to check that the length is correct, and use `from matplotlib.colors import is_color_like` to check that they are all valid colors. If either condition is not met, then it emits a warning and defaults back to the current behavior, which is using `sns.color_palette("colorblind", n_colors=n_series)`.

[ENH] Add `colors` argument to `plot_series`

---

pyproject.toml
sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/_functions.py
sktime/performance_metrics/forecasting/tests/__init__.py
sktime/performance_metrics/forecasting/tests/test_metrics.py

Fixes #3907 
* moves upper bound for `numpy` to `1.25` (`1.24` is out)
* fixes some compatibility issues due to some high precision numbers in doctests (by @fkiraly)

& fkiraly [MNT] bump numpy version bound to <1.25 and fix compatibility issues #3907

---

sktime/forecasting/compose/_multiplexer.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_multiplex.py
sktime/forecasting/compose/tests/test_pipeline.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py
sktime/forecasting/model_selection/_split.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/model_selection/tests/test_split.py
sktime/transformations/compose.py
sktime/transformations/series/tests/test_differencer.py
sktime/transformations/tests/test_multiplexer.py

It would appear the deprecation of `start_with_window` in `ExpandingWindowSplitter` according to https://github.com/sktime/sktime/issues/2678 was carried out incompletely - simply carrying out the deprecation action results in error, due to the parameter still being there in super calls and base constructor.
This PR introduces a quick fix which translates the parameter in `ExpandingWindowSplitter`, to the desired deprecation end state, but without full removal of the parameter in the base interface.
The original deprecation in #2678 still needs to be carried out fully.

[BUG] fix `start_with_window` deprecation in `ExpandingWindowSplitter`

---

sktime/forecasting/compose/_ensemble.py

Fixes #3961.
The bug occurred whenever `EnsembleForecaster` would receive a panel or hierarchical exogeneous data set.
`EnsembleForecaster` should, however, never vectorize/broadcast, and this clash of parameters should never happen.
But, it did happen because the `X_inner_mtype` was incorrectly set, which erroneously triggered vectorization/broadcasting any time an `X` that is panel or hierarchical is passed.
This PR fixes that problem by setting the `X_inner_mtype` tag.
Also corrects the docstrings.

[BUG] fix `EnsembleForecaster` erroneous broadcasting and attribute clash

---

sktime/tests/_config.py

This PR skips the known sporadic `ResNetClassifier` failures, see https://github.com/sktime/sktime/issues/3954
Since the failure seemingly appears in any test, we skip the entire estimator.

[MNT] skip sporadic `ResNetClassifier` failures

---

.github/workflows/test.yml
Makefile
docs/source/api_reference/utils.rst
pyproject.toml
sktime/utils/tests/test_mlflow_sktime_model_export.py

This PR makes two changes:
1. cleans up the dependency set from https://github.com/sktime/sktime/pull/3912 - `mlflow` and AWS dependencies are moved to a separate dependency set `mlflow`.
The CI for `mlflow` is also separated and isolated from the remaining tests, ensuring that the remaining tests, or a user who wants `all_extras` do not need to install a large python env or packages they do not want (e.g., AWS specific ones).
2. removes duplicate API reference from `utils`

[MNT] isolate `mlflow` and AWS dependency set

---

sktime/forecasting/compose/_pipeline.py

This adds functional `get_fitted_params` to forecasting pipelines and addresses the last open point in https://github.com/sktime/sktime/issues/1497
This is done by adding a `_components` function, which in turn is called from the default `get_fitted_params`, instead of overriding `_get_fitted_params` or `get_fitted_params`.

[ENH] forecasting pipeline `get_fitted_params`

---

sktime/base/_base.py
sktime/base/tests/test_base.py

This adds an equality dunder to `BaseObject` descendants.
Two `BaseObject` descendants are considered equal if they define the same estimator blueprint, i.e., nested `get_params` result in value-identical dictionaries (with nested call to `__eq__` should those dictionaries contain `BaseObject` descendants).
Includes a test for expected properties of the dunder.
This is prompted by issues of equality testing in tests such as in the failure relevant for https://github.com/sktime/sktime/pull/3857, where equality currently means object identity rather than parameter identity.
FYI @RNKuhns, this could/should be an `skbase` feature, so would appreciate opinion on whether it interacts with any of the other tests or properties.

[ENH] equality dunder for `BaseObject` to compare blueprint

---

sktime/base/_meta.py
sktime/classification/compose/_pipeline.py
sktime/classification/dummy/_dummy.py
sktime/regression/compose/_pipeline.py
sktime/utils/_testing/deep_equals.py

`set_params` bug in `ClassifierPipeline` and `RegressorPipeline` was broken, it would not correctly update parameters.
The failure to detect this is an instance of the known problem https://github.com/sktime/sktime/issues/3429
The bug has been fixed, and is now covered by appropriate tests (addition of a second parameter set).
The fix is as follow:
* the issue was in `set_params` which accidentally had one too many layer of nesting in the param dict indexing, e.g., `classifier__` etc. This would materialize only for doubly nested estimators.
* this was fixed, with a concomitant extension of the dict subset utility in the `_HetereogenousMetaEstimator`.
Depends on https://github.com/sktime/sktime/pull/3858 as the `DummyClassifier` is used as one of two param sets.

[BUG] fix unreported `set_params` bug in `ClassifierPipeline` and `RegressorPipeline`

---

docs/source/api_reference/transformations.rst
sktime/transformations/panel/reduce.py
sktime/transformations/panel/tests/test_timebinner.py

Implements `TimeBinner` transformer as requested in #242 
Adds the option to specify custom intervals which to use for aggregating time series/panel data. In that sense, it generalizes `Tabularizer`
No

[ENH] `TimeBinner` transformation for temporal bin aggregation

---

sktime/transformations/panel/rocket/_minirocket.py
sktime/transformations/panel/rocket/_minirocket_multivariate.py
sktime/transformations/panel/rocket/_minirocket_multivariate_variable.py
sktime/transformations/panel/rocket/_multirocket.py
sktime/transformations/panel/rocket/_multirocket_multivariate.py
sktime/transformations/panel/rocket/_rocket.py

This PR 
1) reduces the number of kernels in the examples to speed up testing and
2) standardises the format and expands descriptions of the docstrings 
this is an interim measure, there is duplication of code here, see https://github.com/sktime/sktime/pull/3786, its not fixing this, its a minor tidy up

[DOC] Tidy Rocket docstrings

---

.github/workflows/test.yml
pyproject.toml

This PR addresses comments in https://github.com/sktime/sktime/pull/3951 and https://github.com/sktime/sktime/pull/3975 related to handling of mlflow test dependencies.
I think we have heard some valid arguments:
* no user of `sktime` should be forced to install AWS dependencies, as there are other major cloud providers like MS and Google (with which `mlflow` is also compatible). That means the plain, `dev` (power user) and `all_extras` dependency sets
* putting the AWS dependencies used in the tests in the `mlflow` dep set is misleading, as a user could think this is for `mlflow` compatibility - point made by @ltsaprounis.
* we should isolate the `mlflow` AWS deps in the tests as they cause a large python environment and are not used anywhere else in the test suite, leaving them in can …

[MNT] separate dependency set for AWS based `mlflow` tests

---

.all-contributorsrc
CODEOWNERS
docs/source/api_reference/regression.rst
sktime/regression/dummy/__init__.py
sktime/regression/dummy/_dummy.py
sktime/regression/dummy/tests/__init__.py
sktime/regression/dummy/tests/test_dummy.py

Fixes #3899.
Adds a DummyRegressor that wraps over a sklearn DummyRegressor and inherits from BaseRegressor.
No.

[ENH] `DummyRegressor` for time series regression

---

sktime/forecasting/base/adapters/_statsforecast.py

When I use the StatsForecastAutoARIMA algorithm to forecast the past, the forecast is always returned from the start time of the training, even though fh specifies to start at a moment in the middle of the training time range.
I think the reason is that the index used is incorrect, the fh passed in is not used correctly, and the past results of the prediction are always returned from the start time of the training. We should use from_cutoff to true. I did this and the final result was as I expected.

[BUG] Fix `StatsForecastAutoARIMA_.predict` incorrect in-sample start index

---

sktime/utils/validation/_dependencies.py

This PR adds functionality to `_check_soft_dependencies` to parse and check PEP 440 package version specifier strings.
This is useful in a case where certain estimators require specific versions of dependencies, but this is not a requirement of the `sktime` framework itself.
An example where this could be useful is the case of version increments of `sktime` dependencies which do not break the framework but break individual estimators. The problems in those estimators would then be isolated to the estimators and do not prevent `sktime` version compatibility, i.e., of the framework code. Issues with individual estimators can then be resolved in a staggered way, not blocking framework releases for people who do not want to use that specific estimator (which is not an uncommon case as …

[ENH] Update `_check_soft_dependencies` to allow PEP 440 specifier strings for version bounds

---

sktime/dists_kernels/compose_tab_to_panel.py

This PR generalizes `AggrDist` and `FlatDist` to allow for arbitrary callables of suitable signature as distances/kernels inside.
This allows easy definition of common time series distances such as mean Gaussian kernel, mean pairwise Euclidean distance, or index flattened Euclidean distance.
This also adds:
* a test parameter case, using an `sklearn` kernel
* examples in the docstring to construct the distance/kernel either using an `sktime` distance or an `sklearn` kernel

[ENH] generalize `AggrDist` and `FlatDist` to allow arbitrary callables, including `sklearn` kernel functions

---

sktime/dists_kernels/compose_tab_to_panel.py

This fixes erroneous tag logic in `AggrDist` and `FlatDist`:
* the `"capability:unequal_length"` tag of `FlatDist` should be `False`, as the compositor flattens the time series to a 2D `numpy` array (with equal length rows). For `AggrDist`, it is correctly set as `True`, as the aggregated distance does not assume equal length.
* the `"capability:missing_values"` of both `AggrDist` and `FlatDist` should be set to the same as the wrapped tabular pairwise transformer.

[BUG] fix tag logic in `AggrDist` and `FlatDist`

---

sktime/transformations/series/detrend/_detrend.py

This PR improves the `Detrender` docstring after changes in https://github.com/sktime/sktime/pull/3931.
The changes ensure that the different part of the docstring make clear reference to the multiplicative detrending.
FYI @KishManani, small improvements. Thanks for your contribution!

[DOC] improve `Detrender` docstring

---

docs/source/api_reference.rst
docs/source/api_reference/classification.rst
docs/source/api_reference/transformations.rst

adds some missing entries in API reference:
* kernel SVC classifier
* `WeightedEnsembleClassifier` classifier
* link to deployment topical reference
* `TimeSince` transformer

[DOC] add some missing entries in API reference

---

sktime/dists_kernels/_base.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/utils/_testing/scenarios_transformers_pairwise.py

This PR adds a `transform_diag` method to pairwise transformers which allows to obtain the diagonal of a distance or kernel matrix, plus a generic test for the method in the estimator checks.
This parallels the `diag` interface point in kernels of `sklearn`, in `sklearn.gaussian_process.kernels`.
Currently this has only a default implementation, but we could extend this later to make room for a two-layer architecture if needed.

[ENH] `transform_diag` method for pairwise transformers, for computing diagonal of distance/kernel matrix

---

pyproject.toml
sktime/dists_kernels/_base.py
sktime/dists_kernels/dist_to_kern.py
sktime/dists_kernels/tests/test_all_dist_kernels.py
sktime/utils/plotting.py

This PR introduces two wrappers, `DistFromKernel` and `KernelFromDist`, which converts distances to kernels, resp kernels to distances.
Kernel to distances is via the common RKHS distance definition; distance to kernel is via a pseudo-inverse to the former, possibly using a transformer for the diagonal values.
Relies on PR https://github.com/sktime/sktime/pull/3957 for the diagonal transform method.

[ENH] wrapper to convert kernels to distances and distances to kernels

---

sktime/base/_meta.py
sktime/dists_kernels/_base.py
sktime/dists_kernels/algebra.py
sktime/dists_kernels/tests/test_dist_kernels_dunders.py

This PR adds dunders for time series distances and kernels (descendants of `BasePairwiseTransformerPanel`), behaving as per likely user expectation, description as below.
It also adds tests for the different combinations of dunders and estimators.
* `d = dist1 * dist2` satisfies `d(X1, X2) == dist1(X1, X2) * dist2(X1, X2)`, for all pairwise transformers `dist1`, `dist2`, equality for all elements of the resulting matrix
* `d = dist1 + dist2` gives `d(X1, X2) == dist1(X1, X2) + dist2(X1, X2)`, for all pairwise transformers `dist1`, `dist2`
* for a pairwise distance `dist` and an int or float `const`, `d = dist * const` or `d = const * dist` gives `d(X1, X2) == dist(X1, X2) * const`
* for a pairwise distance `dist` and an int or float `const`, `d = dist + const` or `d = const + dist` gives …

[ENH] dunders for time series distances and kernels

---

sktime/datatypes/_vectorize.py
sktime/forecasting/compose/_bagging.py

This PR fixes an unreported bug (discovered by #3969) with `BaggingForecaster` which would drop its column names if `pd.DataFrame` were passed.
The reason was that the internal type was set as `pd.Series`, but it always returned a `pd.DataFrame` (and with inconsistent column name, always the integer zero).
The back-conversion of `BaseForecaster` would get confused and not retrieve the input column names as it would with a returned `pd.Series`.

[BUG] fix dropped column index in `BaggingForecaster`

---

sktime/series_as_features/base/estimators/_ensemble.py
sktime/transformations/panel/channel_selection.py
sktime/transformations/panel/compose.py
sktime/transformations/panel/dictionary_based/_sfa_fast.py
sktime/transformations/panel/interpolate.py
sktime/transformations/series/augmenter.py
sktime/transformations/series/boxcox.py
sktime/transformations/series/clear_sky.py
sktime/transformations/series/dobin.py
sktime/transformations/series/tests/test_boxcox.py
sktime/transformations/series/tests/test_sklearn_adaptor.py

For reference: I did vote this down on 8th of December.
And you confirmed that my vote is unaffected:

Revert "[ENH] isolating `scipy` imports, part 1"

---

sktime/transformations/series/tests/test_time_since.py
sktime/transformations/series/time_since.py

This PR:
1.  allows the `TimeSince` transformer to operate directly on the time index of multi-index dataframes. This should give a performance boost when working with panel and hierarchical data.
2. simplifies the logic in `transform` and removes an unnecessary resampling of the dataframe when the index is of type `DateTimeIndex`. 
3. removes unnecessary copying of `X` unless `keep_original_columns=True`, in which case a copy of `X` is made so that we can return the original columns.
The use of `get_period_alias` to make it easier to convert from a datetime index to a period index.

[ENH] Enable `TimeSince` trafo to transform multiindex dataframes directly

---

sktime/transformations/series/time_since.py

There is a check that the type of the time index and the `start` argument are consistent. The check was still being done on `X.index` which is fine for series data, but not for panel or hierarchical data. The check has been changed to the `time_index` variable.

[BUG] Fix `TimeSince` check of inconsistency between `time_index` and `start`

---

sktime/transformations/series/time_since.py

Inspired by how @ltsaprounis calculated the integer time difference when using a `PeriodIndex` in the `FourierFeatures` transformer, I've switched to using this alternative method which is *much* faster. I measured a factor of ~100 speed up in `_transform`.
An example to measure the difference:
```Python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.transformations.series.time_since import TimeSince
df =_make_hierarchical(hierarchy_levels=(10000,), min_timepoints=200, max_timepoints=200)
trafo = TimeSince(freq="D")
trafo._fit(df)
trafo._transform(df)
```
This PR will have conflicting changes with https://github.com/sktime/sktime/pull/4015. Once https://github.com/sktime/sktime/pull/4015 has merged I will resolve the conflicts in this PR. 
Code quality. I'm …

[ENH] Make `TimeSince` trafo faster by changing period diff calculation

---

sktime/datatypes/_series/_check.py

This PR fixes #3990; related PR: #3827. FYI @KishManani, @danbartl.
Combining information from @danbartl and @KishManani, I understood where the issue must have been coming from - from a line of `np.diff` on the checked index, in `_index_equally_spaced`, but only in the case of `pd.PeriodIndex` (the latter condition I only understood from @KishManani's analysis).
I have used this insight to replace the time and memory consuming check by a much quicker one, exploiting mathematical assumptions on the `pd.PeriodIndex` (unique and sorted index).
While this PR seems to address the issue, some open questions remain:
* do we want to test this fix, or in general, checks being fast and not memory intensive? If yes, how? Runtimes can vary even on VM.
* is @danbartl's fix in …

[ENH] speed up mtype check for `pandas` based mtypes with `pd.PeriodIndex`

---

sktime/clustering/base.py

Fixes https://github.com/sktime/sktime/issues/3984 by using `len(preds)` and not `len(X)` as a proxy for number of instances.
A test covering this by integration is the classifier pipeline in https://github.com/sktime/sktime/pull/3967

[BUG] fix default `BaseClusterer._predict_proba` for all mtypes

---

docs/source/api_reference/utils.rst
sktime/pipeline/__init__.py
sktime/pipeline/_sklearn_to_sktime.py

This PR adds an generic adapter `sklearn_to_sktime` that exposes any `sklearn` estimator as an `sktime` pipeline (with one non-trivial element).
It also adds the `pipeline` module to the `sktime` API reference.

[ENH] sklearn to sktime pipeline adapter, API ref for `pipeline` module

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py

Fixes https://github.com/sktime/sktime/issues/3986 and includes consistency tests.
The reason for the bug is that columns may end up permuted, and the wrapped forecaster may or may not be able to cope with that. The fix is ensuring that the `X` in predict always has columns in the same order as in `fit`.
Probably, we should ensure that all estimators can deal with permuted columns by coercing in the base class, but that's a separate topic.

[BUG] fix `ForecastX` predictions

---

sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/fbprophet.py
sktime/forecasting/tests/test_prophet.py

This PR adds functionality to the `Prophet` interface to also allow `pd.PeriodIndex`. Fixes https://github.com/sktime/sktime/issues/2475 and also fixes https://github.com/sktime/sktime/issues/3537.
Also tests:
* testing `Prophet` functionality for `RangeIndex` and `PeriodIndex` in exogeneous and endogeneous data
* testing failure case in https://github.com/sktime/sktime/issues/3537

[ENH] extend `Prophet` to allow `pd.PeriodIndex`; [BUG] fix `Prophet` not working with non-integer forecast horizon

---

docs/source/api_reference/classification.rst
docs/source/api_reference/clustering.rst
docs/source/api_reference/dists_kernels.rst
docs/source/api_reference/forecasting.rst
docs/source/api_reference/regression.rst
docs/source/api_reference/transformations.rst

This adds a reference to `all_estimators` on all pages for estimators.
Taken partially from https://github.com/sktime/sktime/pull/3852 (which added this for some estimator types).

&matthewmiddlehurst [DOC] `all_estimators` reference on all estimator pages

---

sktime/tests/_config.py

Skips two recent test failures on `main` until diagnosed and fixed.
Failures are described in https://github.com/sktime/sktime/issues/4033

[MNT] skip #4033 related failures until fixed

---

.all-contributorsrc
docs/source/conf.py
docs/source/installation.rst

Fixes #3994.
This PR adds a warning for macOS users using ARM macs of the issues that they may encounter when installing ``all_extras``, related to some dependencies not compatible with that kind of setup.
This contribution does not add any new dependency.
Check if the warning is enough, or it would be appropriate to add a link to a separate new article in the documentation explaining in more detail the issue, listing the dependencies that cause the error, in case the user wants to install all the other dependencies in ``all_extras`` that do not generate any errors.

[DOC][BUG] Add warning regarding issues with macOS ARM

---

sktime/tests/_config.py

This skips all tests for `LSTMFCNClassifier` due to unfixed sporadic failures on `main`, see this issue: https://github.com/sktime/sktime/issues/4033
After fixing, we should add the tests back.
Also removes an orphaned comment related to this old issue which has been superseded in the exclusion list: https://github.com/sktime/sktime/issues/1627

[MNT] skip `LSTMFCNClassifier` tests due to unfixed failure on `main`

---

sktime/clustering/dbscan.py

This PR adds DBSCAN clustering for time series, combining `sklearn` `DBSCAN` with the `sktime` pairwise distances.
The clusterer should work for unequal length series, if a distance is used that is capable of unequal length time series.
Related to (but not strictly based on) the incomplete PR #780 adding DBSCAN, by @josuedavalos, which @TonyBagnall closed a while ago, hence I am also crediting @josuedavalos for this.

& josuedavalos [ENH] DBSCAN clustering for time series

---

sktime/forecasting/compose/_reduce.py
sktime/forecasting/compose/tests/test_reduce.py
sktime/utils/sklearn.py

This PR extends the utility `sklearn_scitype` to infer the scitype correctly from `Pipeline`-s and grid/random searches, and by extension also the `is_sklearn_[scitype]` functions.
Also changes a test for `make_reduction` raising an error on a pipeline to a test that it is correctly inferred.
Related to this discussion: https://github.com/sktime/sktime/discussions/3841

[ENH] extend `sklearn_scitype` to infer the scitype correctly from composites

---

sktime/utils/plotting.py

Fixes #3944
This implementation updates `plotting.py` under `utils` directory. The function `plot_series` is updated and now the user can enter the **plot title** for the figure. 
- The function `plot_series` now has one more parameter: `suptitle` (default value is `None`) to which user can give the title of the plot or figure.
No.
:white_large_square: I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
:white_check_mark: I've added unit tests and made sure they pass locally.
:white_check_mark: The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

[ENH] Implementing plot title for `plot_series`

---

pyproject.toml

The combined lower bounds of current core dependencies imply `scipy>=1.2.0` (from `pandas 1.1.0`).
This PR makes that lower bound explicit and consistent with other version specifications in the core dependency set.

[MNT] explicit lower version bound on `scipy`

---

sktime/tests/test_all_estimators.py

This PR improves error messages in the `test_estimator_tags` interface contract test, adding the source class and specific reasons for failures.

[ENH] Improve error messages in `test_estimator_tags` test

---

sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_panel/_examples.py

Roll out of  https://github.com/sktime/sktime/pull/3935 to hierarchical checks.
Also unified the approach here, since in my view checks should use the same functions (essentially panel and hierarchical are just variations of each other)

[ENH] Speed up hierarchical checks and unify with panel approach

---

docs/source/get_involved/code_of_conduct.rst

Changes of substance compared to the original PR #3095:
* upon suggestion of @GuzalBulatova (below), clarified the scope of applicability, including a clarification that the general terms of license by which the software is distributed are unaffected. The scope is clarified to apply, primarily, to elected members of the community in their elected roles (while excluding loopholes like saying "I did this in my other role, actually").
* upon suggestion of @GuzalBulatova (slack), changed expectations on creating opportunities. In the new version, leaders are expected to create fair opportunities (without restriction), and members of the community are strongly encouraged (not expected ) to create fair opportunities as have been created for them.
* upon request of @aiwalter (slack), removed …

[GOV] proposed code of conduct update - mature sktime structure and decision making on resources

---

sktime/forecasting/trend.py

This fixes an unreported but with `PolynomialTrendForecaster` detected through the new parameter set in https://github.com/sktime/sktime/pull/4043.
If `regressor` was passed, the `_fit` method would mutate it, by fitting an identity-equal instance inside an `sklearn` pipeline.
This is fixed by adding a `clone` around `regressor`.

[BUG] fix mutation of `regressor` in `PolynomialTrendForecaster._fit`

---

sktime/transformations/series/detrend/_detrend.py
sktime/transformations/series/detrend/tests/test_detrend.py

This PR improves the `Detrender`:
* it fixes https://github.com/sktime/sktime/issues/4051 and also simplifies the logic in the `Detrender`. As the `BaseForecasting` interface supports loop over hierarchy instances and variables natively, all the case distinctions internally can go, and with it goes the incorrect multivariate implementation.
* adds support for detrending with hierarchical forecasters
* adds support for detrending with forecasters that require `fh` in `fit` already (this was not possible previously)
As a consequence, the test `test_polynomial_detrending` had to be updated since the internal mtype of the `Detrender` changed, from `pd.Series` based to `pd.DataFrame` based (requiring a minor change in how objects are being compared).

[ENH][BUG] clean up `Detrender` and implement correct multivariate behaviour

---

sktime/forecasting/trend.py

This fixes an unreported but with `TrendForecaster` detected through the new parameter set in https://github.com/sktime/sktime/pull/4043.
If `regressor` is not boolean coercible (e.g., for `sklearn` `RandomForestRegressor`), the `_fit` method breaks at the line
```python
self.regressor_ = self.regressor or LinearRegression(fit_intercept=True)
```
This is fixed by replacing that line by an if/else that does not require said coercion.

[BUG] fix `TrendForecaster` if `regressor` is not boolean coercible

---

sktime/utils/validation/_dependencies.py

This fixes an unreported bug in `_check_soft_dependencies` for PEP 440 specifiers - if no class or class name was passed, the function would break as it was referencing the variable `class_name`.
This error has been detected through testing in `skbase` and is covered there (until we refactor).

[MNT] fix `_check_soft_dependencies` breaking for PEP 440 specifiers without class reference

---

sktime/forecasting/compose/tests/test_reduce_global.py
sktime/transformations/series/date.py
sktime/transformations/series/tests/test_date.py
sktime/utils/validation/_dependencies.py

This PR contains downwards compatibility fixes for the minimal version dependency set currently supported by `sktime`.
Because CI was not testing for minimal version dependencies, there have been punctual divergences in compatibility with the minimal dependency set. This PR aims to fix this.
PR https://github.com/sktime/sktime/pull/4016 introduces a CI element to test on the minimal dependency set, against which the fixes in this PR are developed.
Fixes:
* old `sklearn` versions require an experimental enablement flag for use of `HistGradientBoostingRegressor`. The fix is to include that flag conditional on `sklearn` version.
* the `DateTimeFeatures` transformer depends on `pandas` `DatetimeProperties` which is only available in its current form since `pandas 1.2.0`. The fix is to include …

[MNT] downwards compatibility fixes for minimal dependency set

---

docs/source/developer_guide/add_estimators.rst
examples/01b_forecasting_proba.ipynb
sktime/performance_metrics/tests/test_metrics_classes.py
sktime/tests/test_all_estimators.py
sktime/utils/estimator_checks.py
sktime/utils/tests/test_check_estimator.py

This PR changes the `return_exceptions` argument in some testing utilities to `raise_exceptions`, with deprecation (for 0.17.0).
Affected functions are `check_estimator`, and `QuickTester.run_tests`.
The reason for the change is that an argument `raise_exceptions` is much clearer to the user in semantics and function than `return_exceptions`. Since, in common user perception, `raise_exceptions` is "what happens" in comparison to a baseline case of it not happening.
It also becomes consistent with arguments in the testing module, e.g., conditional fixture generation functionality such as `create_conditional_fixtures_and_names` where the argument is already called `raise_exceptions`.
Also changes any internal references to the argument to the post-deprecation state.

[ENH] in `check_estimator` and `run_tests` replace `return_exceptions` arg  with `raise_exceptions`, with deprecation

---

sktime/forecasting/model_selection/_split.py

This PR addresses the deprecation message received from `pandas` for one instance of `pd.Series` constructor with `dtype` not explicitly set.
The fix is setting the `dtype` explicitly, which resolves the deprecation message in case the resulting series is empty.

[MNT] address `pd.Series` constructor `dtype` deprecation

---

sktime/forecasting/trend.py

Addresses a `pandas` deprecation warning from `TrendForecaster`.
Warning addressed is the following one:
```
FutureWarning: The behavior of .astype from datetime64[ns] to int32 is
deprecated. In a future version, this astype will return exactly the specified dtype
instead of int64, and will raise if that conversion overflows.
```

[MNT] address `pandas` `astype` deprecation in `TrendForecaster`

---

sktime/classification/deep_learning/base.py
sktime/classification/deep_learning/cnn.py
sktime/classification/deep_learning/fcn.py
sktime/classification/deep_learning/lstmfcn.py
sktime/classification/deep_learning/mlp.py
sktime/classification/deep_learning/tapnet.py
sktime/networks/tapnet.py
sktime/regression/deep_learning/cnn.py
sktime/regression/deep_learning/tapnet.py
sktime/tests/test_all_estimators.py

Fixes #4067
No
We need to discuss if there is another way that is superior to the current solution.

[BUG] Constructor of any DL estimator to pass non-default values to underlying `Network` object

---

.all-contributorsrc
sktime/classification/dictionary_based/_boss.py
sktime/classification/dictionary_based/tests/test_boss.py

This will fix #4090 which prevent predicted classes list from being populated correctly
When calling `np.zeros`, change `string` datatype to `object` so that np.zeros will not truncate the string to only the first character.
I've also tested this locally using provided example in the issues as well as running `check_estimator(IndividualBOSS)`. All tests PASSED!
No

[BUG] Fix BOSS based classifiers truncating class names to single character length

---

sktime/classification/dictionary_based/_boss.py
sktime/classification/dictionary_based/tests/test_boss.py

Improve testing parameter for `BOSSEnsemble` and `IndividualBOSS`, towards #4096 
- Reduce repetitive tests and group them together using `@pytest.mark.parametrize`
- Improve robustness by adding checks for `str` on top of `numpy.str_` for BOSS based classifier
No

[ENH] Reduce repetitive code in test_boss.py and add check for string datatype in _boss.py

---

sktime/forecasting/model_selection/_split.py

This PR addresses the `FutureWarning` deprecation message received from `pandas` for one instance of `pd.Series` constructor with `dtype` not explicitly set.
The fix is setting the `dtype` explicitly, which resolves the deprecation message in case the resulting series is empty.
Same as the fix in #4031, but for another splitter - I unfortunately did not spot the second instance here.

[MNT] address `pd.Series` constructor `dtype` deprecation / `FutureWarning` - part 2

---

examples/01_forecasting.ipynb

Fixes https://github.com/sktime/sktime/issues/4118, hopefully, by removing the quotes from the ToC line

[DOC] fixes table of contents in `01_forecasting.ipynb` tutorial

---

sktime/base/_meta.py
sktime/classification/compose/_column_ensemble.py
sktime/classification/compose/_ensemble.py
sktime/dists_kernels/algebra.py
sktime/forecasting/base/_meta.py
sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/_multiplexer.py
sktime/forecasting/compose/_pipeline.py
sktime/transformations/compose.py

This PR adds full functionality for `get_fitted_params` of pipelines (incl forecasting pipelines) and other heterogenous meta-estimators. Fixes https://github.com/sktime/sktime/issues/1468
`get_fitted_params` would already work previously, but not crawl the estimators in the "fitted steps" for fitted parameters.
This is now added, by adding a `_steps_fitted_attr` to configure in the `_HeterogenousMetaEstimator`, which is then used to retrieve the fitted parameters. In effect, this PR adds more keys and values that are retrieved to the return of `get_fitted_params`, from crawling the fitted steps.
Further updates the `_HeterogenousMetaEstimator` with a relaxed interface assumption: the `_steps_attr` now only needs to be an iterable of tuples of which the 0-th element is the name, 1-st …

[ENH] `get_fitted_params` for pipelines and other heterogenous meta-estimators

---

sktime/forecasting/arima.py

Second test parameter set for `ARIMA`, towards #3429.
Split off from https://github.com/sktime/sktime/pull/2862 where it must have ended up accidentally.

[ENH] second set of test parameters for `ARIMA`

---

sktime/forecasting/base/_delegate.py
sktime/forecasting/model_selection/_tune.py
sktime/forecasting/model_selection/tests/test_tune.py

Due to a faulty override, key fitted parameters of the forecaster tuners (children of `BaseGridSearch`, e.g., `ForecastingGridSearchCV`) such as `"best_forecaster"` would not be returned as key/value pairs of `get_fitted_params` returns.
Only fitted parameters of the best forecaster, but not metadata about the grid search fit would be returned.
This has been fixed by simply adding a getter call for the default fitted parameters of the grid search fit in the private `_get_fitted_params` of the grid search base class `BaseGridSearch`.
Related discussion: https://github.com/sktime/sktime/discussions/4101

[BUG] fix `get_fitted_params` for forecaster tuners, missing `best_forecaster` etc

---

sktime/forecasting/base/_base.py
sktime/transformations/base.py

This PR fixes an unreported bug that was noticed here: https://github.com/sktime/sktime/discussions/4101#discussioncomment-4679066
The bug causes only the diagonal combinations of rows/columns to be present as string keyable values in the fitted params dict in case of vectorized forecasters and transformers.
What should be present is the cartesian product, not the diagonal. This is solved by correctly using `product` instead of `zip` that was used accidentally.
Also fixes an issue (not necessarily bug) with the convention of constructing the strings - they should now always be a string that evaluates to a correct data frame `loc` access command, which previously was not the case for `str` keys (as that would eat away the quotes in `str` coercion).

[BUG] fix `get_fitted_params` in case of vectoriztion for forecasters, transformers

---

sktime/transformations/compose.py
sktime/transformations/tests/test_optionalpassthrough.py

Fixes https://github.com/sktime/sktime/issues/4114.
The bug occurs when the `OptionalPassthrough` is applied in a case that requires broadcasting. Through interaction with the `_DelegatedTransformer`, this can lead to wrong conversions.
The fix is delegating all conversions to the wrapped transformer (by removing the override of the `X_inner_mtype` tag and letting all mtypes through).
Adds two tests for the failure case in #4114 (column broadcast) and the parallel failure case for rows.

[BUG] Fix `OptionalPassthrough` `X_inner_mtype` tag

---

sktime/forecasting/tests/test_trend.py
sktime/forecasting/trend.py

Fixes https://github.com/sktime/sktime/issues/4131 and a parallel issue for `TrendForecaster` which is the cause of #3230 (also fixes #3230).
Erroneous coercion caused huge arrays to be allocated when the input data had a `DatetimeIndex`.
Also, previously, any time stamp based fits and coefficients were related to a reset index (naive replacement with `RangeIndex`) rather than the time stamp.
This has been changed to periods since start of 1970 (with correct time stamp conversion). I've now added a clarifying docstring on what the coefficients mean, and changed it consistently to periods since start of 1970.
Since this was subject to a bug previously (and, likely, confusion), we don't need deprecation for this change.
Contains new and updated tests:
* …

[BUG] fix erroneous `int` coercion of `TrendForecaster` and `PolynomialTrendForecaster` on `DatetimeIndex`

---

.github/workflows/test.yml
.pre-commit-config.yaml

Temporary workaround for #4162 to allow other development and release.
Removes the `isort` pre-commit step to which the problem can be isolated.

[MNT] emergency fix for precommit CI failure - remove `isort`

---

sktime/datatypes/_vectorize.py
sktime/datatypes/tests/test_vectorize.py
sktime/forecasting/base/_base.py
sktime/transformations/base.py

This PR moves functionality for broadcast/vectorized application of estimator methods to `VectorizedDF`, to a new method called `vectorize_est`. It also serves to explore refactor end states.
Reasons to move broadcast/vectorized application to `VectorizedDF`:
* duplication between transformers and forecasters which have very similar logic implemented
* current state can be seen as a violation of the law of Demeter; target state improves cohesion, reduces coupling between base classes and `VectorizedDF`
* localized logic in `VectorizedDF` seems to be a more natural starting point for adding `dask` and scaling/distributed features, see https://github.com/sktime/sktime/issues/4013
Also contains a direct unit test for `vectorize_est`.
Note that the new method `vectorize_est` is also …

[ENH] refactor - localize broadcasting in `VectorizedDF`

---

sktime/forecasting/compose/_hierarchy_ensemble.py

An unisolated instance of `statsmodels` accidentally made it onto `main` after making `statsmodels` a softdep: in the `HierarchyEnsembleForecaster` docstring.
This is now remedied by replacing a `statsmodels` dependent estimator with an `sktime` native one.
Also fixes some formatting issues in the docstring example.

[MNT] isolate `statsmodels` in `HierarchyEnsembleForecaster` docstring

---

.all-contributorsrc
.pre-commit-config.yaml

I updated the sort version in pre-commit to stop pre-commit checks from failing.
Closes #4162

[MNT] Bump isort to 5.12.0 in pre-commit config

---

sktime/transformations/series/fourier.py
sktime/transformations/series/tests/test_fourier.py

See discussion here: https://github.com/sktime/sktime/pull/3996#issuecomment-1364733772
This PR makes the following changes:
1. Adds a `keep_original_columns` option and sets the default to `True` with a deprecation warning that in the future this should be set to `False`. This will make it easier to use `FourierFeatures` in the context of a pipeline (or FeatureUnion) where we do not wish to passthrough the other columns of `X`. 
2. Adds tests and modifies the existing tests now that the class can take a `keep_original_columns` as an argument. 
3. Removes the use of deep copies of `X` to make this more memory efficient. 
- Are there any concerns about removing the deep copies of `X` here? @ltsaprounis - would be great to hear your thoughts!
For additional context around the impact of …

[ENH] Add `keep_original_columns` option to `FourierFeatures` trafo

---

sktime/distances/_distance.py
sktime/dists_kernels/dtw.py

This improves the docstring of `dtw_distance` with mathematical detail, and adds related information to `DtwDist`.
Based on @matthewmiddlehurst's PR https://github.com/sktime/sktime/pull/3852, with following changes:
* clarifies assumptions, e.g., equal length, only Euclidean distance
* links to more general time warping distance in `sktime`
* mathematic formalism is clarified and corrected in some places
* valuative formulations, e.g., "most researched" or "most common", are removed

& matthewmiddlehurst [DOC] improved docstring for `dtw_distance`

---

sktime/forecasting/tests/test_all_forecasters.py

Adds a test, `test_predict_series_name_preserved`, to the forecasting test suite, to test that the `name` attribute of `pd.Series` is preserved in `fit`/`predict`.
A test for detecting the general issue at the root of https://github.com/sktime/sktime/issues/4144, which currently was not covered by the forecasting test suite, as the scenarios containing `pd.Series` with non-None `name` attribute did not interact with the tests in which the time index and name were checked for consistency via `_assert_correct_pred_time_index`.
If this works, this should surface a number of cases with the problem, among them `NaiveForecaster` (where this surfaced through manual testing in the context of https://github.com/sktime/sktime/pull/4150 failures)

[ENH] test that forecasters preserve `name` attr of `pd.Series`

---

sktime/datasets/tests/test_data_io.py

This fixes a race condition in tests, if run in parallel. The "./Temp" dir might get deleted while another test is relying on its presence. This fix replaces the explicit creation of a temp dir with a fixture, unique to each test execution.

[BUG] fix race condition in `tsfile` tests

---

sktime/param_est/seasonality.py

Fixes https://github.com/sktime/sktime/issues/4169, by correcting the `range` expression, and clarifying the docstring.

[BUG] fix `nlag` logic in `SeasonalityACF` and `SeasonalityACFqstat`

---

sktime/forecasting/model_selection/_tune.py
sktime/utils/validation/forecasting.py

This improves the `scoring` argument for forecasting tuners and fixes the incorrect docstring.
Fixes https://github.com/sktime/sktime/issues/4149
Context: the docstring of forecasting tuners claims that `scoring` should be a function, but current checker methods only allow `BaseMetric` descendants through. This is at least a wrong docstring, but I think both classes and functions (like in sklearn) should be allowed.
Improvements:
* the `scoring` arguments of `BaseGridSearch` and descendants are changed so that *both* functions and `BaseMetric` desendant classes are allowed.
* this is achieved by a change in `check_scoring`, which coerces functions to scorer classes, and now raises an informative error message.
Fixes:
* the `scoring` docstrings of the tuners (grid and random search) were …

[ENH] improved/fixed `scoring` argument for forecasting tuners

---

sktime/forecasting/ets.py
sktime/forecasting/structural.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/tests/_config.py

Fixes https://github.com/sktime/sktime/issues/4173, the index generation in `AutoETS` and `UnobservedComponents` was wrong.
Also extends the `test_predict_interval` to test integer based indices (the default `_make_series` output starts at 3, not 0).
This covers the fix - it has also highlighed the same buggy behaviour in `SquaringResiduals` which seems to have a different cause.
As this is a different bug, it has been added to the bug tracker here https://github.com/sktime/sktime/issues/4181, and is excepted from tests temporarily.

[BUG] `AutoETS`, `UnobservedComponents`: fix `predict_interval` for integer based index not starting at zero

---

sktime/datatypes/_vectorize.py
sktime/forecasting/base/_base.py
sktime/transformations/base.py

This PR primarily improves instance iteration performance in `VectorizedDF`, by replacing pandas loc-iteration with groupby. It also fixes a memory leak I observed when `_get_X_at_index` is called multiple times, by returning a copy of a slice (I still don't fully understand the root cause, but this solved it).

[ENH] Improve vectorization performance

---

.all-contributorsrc
sktime/datatypes/_panel/_check.py
sktime/datatypes/_series/_check.py
sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_panel_converters.py

Overlaps with https://github.com/sktime/sktime/issues/3827, https://github.com/sktime/sktime/pull/3991
This PR improves the performance of `check_pdmultiindex_panel`.
It was developed in parallel to the work of @danbartl, so some improvements might be outdated or just implemented differently. I would be grateful, if he could support here.

[ENH] Improve panel mtype check performance

---

sktime/forecasting/tests/test_all_forecasters.py

The tests `test_predict_time_index` and `test_predict_residuals` were duplicative - a lot of `fit` calls for the same data.
Merging the tests reduces the runtime by a factor of 2 (of the runtime arising from said tests).

[ENH] faster test for forecasters' `predict_residuals`

---

sktime/tests/_config.py

This PR prevents discovery of abstract `TimeSeriesLloyds` by interface contract tests (which fail since the class is abstract), which surfaces in clean package crawls, see, e.g., https://github.com/sktime/sktime/pull/4208

[BUG] prevent discovery of abstract `TimeSeriesLloyds` by contract tests

---

sktime/regression/compose/_ensemble.py
sktime/series_as_features/base/estimators/_ensemble.py
sktime/utils/_testing/estimator_checks.py

Partially fixes https://github.com/sktime/sktime/issues/4220 for `ComposableTimeSeriesRegressor`. This is done by:
* doing the same as in the existing `ComposableTimeSeriesClassifier`, introducing a dummy abstract method that satisfies the abstract parent class
* renaming the reserved `estimator_` attribute (by the `sklearn` parent class) to `_estimator`
* fix parameters inconsistent with underlying `sklearn` decision tree/forest

[BUG] fix broken `ComposableTimeSeriesRegressor`

---

sktime/forecasting/compose/_reduce.py
sktime/forecasting/model_selection/_split.py

Fixes #4158.
The solution is via indentation, in which case the symbol table is rendered as a code block incl newlines.

[DOC] improved reducer docstring formatting

---

sktime/datatypes/_vectorize.py

This improves the docstringd for `VectorizedDF.items` and `.__iter__`, see discussion in https://github.com/sktime/sktime/pull/4195
FYI @hoesler, comments and suggestions are appreciated.

[DOC] improve docstring for `VectorizedDF.items` and `.__iter__`

---

sktime/base/_meta.py
sktime/forecasting/compose/_column_ensemble.py

This PR factors out column ensemble functionality from `_ColumnEnsembleForecaster` to a new mixin, `_ColumnEnsemble`, in the `base` module.
This prepares a refactor of the `ColumnTransformer` which will depend on `_ColumnEnsemble`, also see https://github.com/sktime/sktime/issues/2537

[ENH] factor out column ensemble functionality from `_ColumnEnsembleForecaster` to new base mixin

---

extension_templates/transformer.py
extension_templates/transformer_simple.py
sktime/forecasting/model_evaluation/_functions.py

This updates transformer extension template docstrings with references to the `Hierarchical` data types.
Also correct a typo in one of the URLs.

[DOC] update transformer extension template docstrings, reference to `Hierarchical`

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/dummy.py

This adds a forecaster, `ForecastKnownValues`, that produces forecasts from a set of known or prescribed values passed to it in construction.
use cases include:
* as a dummy or naive forecaster with a known baseline expectation
* as a forecaster with (non-naive) expert forecasts, "known" values as per expert
* as a counterfactual in benchmarking experiments, "what if we knew the truth"
* to pass forecast data values in a composite used for postprocessing,
e.g., in combination with `ReconcilerForecaster` for an isolated reconciliation step, as discussed in https://github.com/sktime/sktime/issues/4239
FYI @ajdin2022

[ENH] Forecaster that forecasts prescribed known or expert forecast values

---

sktime/param_est/stationarity.py
sktime/param_est/tests/test_seasonality.py
sktime/param_est/tests/test_stationarity.py
sktime/transformations/series/adapt.py

This PR adds two parameter estimators for stationarity - ADF (Augmented Dickey-Fuller) and KPSS (Kwiatkowski-Phillips-Schmidt-Shin) tests, directly interfacing `statsmodels.tsa.stattools`.
Besides exposing them in the unified `sktime` interface, a fitted parameter `stationary` is added which tells the user whether the test considers the time series stationary.
This can be used, for instance, for conditional differencing in a pipeline where the boolean can be forwarded to an `OptionalPassthrough`.
This PR also contains some docstring fixes discovered elsewhere, in the context of this piece of work.
FYI @ngupta23, you might find this useful. I'll add a pipeline example to the docstring once all PR it would be conditional on are merged.
It would be apprecated if reviewers could check the …

[ENH] parameter estimators for stationarity - ADF and KPSS

---

sktime/transformations/panel/compose.py

References PR #4262
This PR adds an updated docstring that provides an example for how to use it, as well as a slightly more detailed explanation about its use case.
No
Making sure the new example is adequate to provide context about how to use the tool
Being that this is just an update to a DOC string, there is no need to add a unit test
I think more of these PR's should be created because it often difficult to see where to import different tools from.  It was too difficult to figure out how to use such a simple piece of the program.
- [ X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [X ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, …

[DOC] Update Docstring for ColumnConcatenator

---

sktime/datatypes/_panel/_convert.py
sktime/transformations/panel/channel_selection.py

`pandas.DataFrame.iteritems` has been deprecated in favour of ``pandas.DataFrame.items`, this PR replaces all occurrences.

[MNT] address deprecation of `pandas.DataFrame.iteritems`

---

docs/source/api_reference.rst
docs/source/api_reference/param_est.rst

This PR adds the API reference page for the parameter estimator module, which contains, e.g., seasonality estimators and auto-seasonality plugin forecasters.

[DOC] API reference for parameter estimator module

---

sktime/datatypes/_panel/_convert.py

This PR fixes level name handling in conversions between `nested_univ`/`pd-multiindex`. When converting from `nested_univ` to `pd-multiindex` and back, the level names would unexpectedly change.
This bug is the cause of the remaining failure in
https://github.com/sktime/sktime/pull/4267

[BUG] fix level name handling in conversions `nested_univ`/`pd-multiindex`

---

.all-contributorsrc
sktime/distances/_ddtw.py

#4182 
Fixed B016 Cannot raise a literal. Did you intend to return it or raise an Exception?
No
No
No

[ENH] Fix B016 Cannot raise a literal error in `Distances` module

---

sktime/datatypes/_vectorize.py
sktime/performance_metrics/forecasting/_classes.py

Followup to #4195
This PR implements `BaseForecastingErrorMetric._evaluate_vectorized` using `VectorizedDF.vectorize_est`.
Further, by removing with it the last reference to `VectorizedDF.__getitem__`, it deprecates this method. Random access is not needed, and developers should use `__iter__` for iteration instead (implemented in #4195).
Also, unused method `get_iloc_indexer` is marked as deprecated for the same reason.

[ENH] Improve vectorized metric calculation and deprecate VectorizedDF.__getitem__ and VectorizedDF.get_iloc_indexer

---

sktime/datatypes/_utilities.py
sktime/datatypes/_vectorize.py
sktime/transformations/panel/segment.py
sktime/transformations/panel/summarize/_extract.py

This refactors three segmentation transformers, `RandomIntervalSegmenter`, `SlidingWindowSegmenter` and `IntervalSegmenter` to the `pandas` native mtype, `pd-multiindex`, from the deprecated mtype `nested_univ` which had nested pandas objects.
As a consequence, this also fixes https://github.com/sktime/sktime/issues/4266 for which the use of the nested data type seems to have been the cause.
This seems to cause a substantial improvement in runtime too (ca 25% reduction in the example in #4266), we may like to benchmark.
Relies on bugfix https://github.com/sktime/sktime/pull/4270 for an unreported bug was discovered through this.

[ENH] refactoring segmentation transformers to use `pandas` native data types

---

extension_templates/annotation.py
extension_templates/classification.py
extension_templates/clustering.py
extension_templates/dist_kern_panel.py
extension_templates/dist_kern_tab.py
extension_templates/early_classification.py
extension_templates/forecasting.py
extension_templates/forecasting_simple.py
extension_templates/transformer.py
extension_templates/transformer_simple.py

This PR makes the same small change to all extension templates, clarifying the cases where `get_test_params` should be implemented - contribution to `sktime` *and* for use with `check_estimator`. The latter has been incorrectly omitted from the extension templates.

[DOC] clarified requirement for `get_test_params` in extension templates

---

sktime/classification/compose/_ensemble.py

This fixes an unreported bug where `WeightedEnsembleClassifier._predict_proba` would not work with `pandas` multiindex based mtypes. This is due to an array initialization that assumes `X.shape[0]` as axis 0 length for an array (number instances), which is not correct for the multiindex based mtype.

[BUG] fix `WeightedEnsembleClassifier._predict_proba` to work with `pandas` based mtypes

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/probabilistic/_classes.py
sktime/registry/_tags.py
sktime/tests/test_all_estimators.py

This PR introduces:
* an interface test for the `get_test_params` method of `BaseObject` descendants. It tests whether the return has the expected type.
* introduces the concept of "reserved parameters", i.e., constructor parameters that are not object parameters but type modifying and therefore cannot be tested in the same way as ordinary parameters. Examples are the existing `multioutput` and `multilevel` parameters, which change the logical type of the metric. This is implemented as a tag `reserved_params`.
* adds the `reserved_params` tag in the base metric classes

[ENH] test for `get_test_params`, and reserved parameters

---

sktime/base/_base.py
sktime/networks/lstmfcn_layers.py
sktime/registry/_lookup.py

#4182 
- Fix B028 No explicit stacklevel keyword argument found
No
No
No

[MNT] Fixes linting issues in `base`, `networks`, `registry` modules

---

sktime/transformations/tests/test_pipeline.py

This removes one test for output values in `test_FeatureUnion_pipeline`, as this is sporadically no longer satisfied.
This is due to the refactor https://github.com/sktime/sktime/pull/4267 changing how random seeds map onto estimator states, and the test in question only testing validity of the pipeline.

[ENH] remove test for output values in `test_FeatureUnion_pipeline`

---

sktime/forecasting/model_evaluation/_functions.py

Fixes https://github.com/sktime/sktime/issues/4292
@marrov, thanks, I think you've correctly identified the source location of the bug!
I'm not quite clear why we are dealing with a `DataFrame` that has repeated index (zero??), but I've fixed it now by chaging the chained double access to single `loc` access with two indices, and ensuring the multiple indexp roblem does not occur.
Perhaps @topher-lo has a piece of wisdom to offer what eactly was happening there with the index...

&marrov [BUG] fix `Settingwithcopywarning` when using custom error metric in `evaluate`

---

sktime/performance_metrics/forecasting/_classes.py

This PR cleans up some internal interfaces of `BaseForecastingErrorMetric`, by putting output format conversion and coercion concerns into a single blocks before return, in the methods `evaluate` and `_evaluate_vectorized`.

[ENH] `BaseForecastingErrorMetric` internal interface cleanup

---

docs/source/about/team.rst

This PR updates the "roles" page on the documentation with the status quo.
The following individuals are joining the community council: @jonathanbechtel, @kirilral, @marrov, @RNKuhns,
subject to planned widening of governance to include users and the community of early career contributors in formal decision making (see https://github.com/sktime/community-org/issues/46)

[DOC] Update of roles - community council

---

sktime/utils/_testing/hierarchical.py
sktime/utils/datetime.py
sktime/utils/tests/__init__.py
sktime/utils/tests/test_utils_time_series.py
sktime/utils/validation/_dependencies.py
sktime/utils/validation/tests/__init__.py
sktime/utils/validation/tests/test_check_window_length.py

#4182
- isort auto-fixes
- Ignore flake8 issue (B023 Function definition does not bind loop variable)
- Fix pydocstyle issues (D100, D103, D104)
- Fix flake8 issues (B028)
No
- isort auto-fixes
- flake8 issue (B023 Function definition does not bind loop variable)
- pydocstyle issues (D100, D103, D104)
- flake8 issues (B028)
No
No

[MNT] Fix linting issues in `utils` module

---

pyproject.toml

Attempted/diagnostic fix to #4349 - attempt is downgrading packages to last known working versions: `dash` to 2.8.1, from 2.9.0

[MNT] addressing `pytest` failure - downgrade `dash` to <2.9.0

---

sktime/clustering/k_means.py

The documentation says that TimeSeriesKMeans defaults to `forgy`. However, in the actual code, it defaults to `random`.
Here is the incorrect line: https://github.com/sktime/sktime/blob/main/sktime/clustering/k_means.py#L23

[DOC] `TimeSeriesKMeans` - correct `init_algorithm` default in docstring 

---

docs/source/about/team.rst

This PR:
* adds Sagar Mishra (@achieveordie) to the transition council
* clarifies the status of the committee, i.e., in delegation and subject to transition in #46

[DOC] roles - add Sagar Mishra to TCC, clarify status of TCC

---

sktime/param_est/seasonality.py

This fixes an unreported bug when `candidate_sp` in two seasonality estimators would be `int`. According to the docstring, this should be treated as a one-element iterable, but instead led to error.
This is fixed by coercing to one-element iterable, and covered by an additional test case.
The estimators concerned are `SeasonalityACF` and `SeasonalityACFqstat`.

[BUG] fix seasonality estimators for `candidate_sp` being `int`

---

conftest.py
sktime/forecasting/base/__init__.py
sktime/forecasting/base/_base.py

PR https://github.com/sktime/sktime/pull/4319 has highlighted a potential issue with a circular import in `forecasting.base`.
`forecasting.base` was importing `BaseForecaster` from `forecasting.base._base`, which was importing `ForecastingHorizon` from `forecasting.base`, resulting in a circular import. Fixed by importing `ForecastingHorizon` from its direct location.

[MNT] resolve circular imports in `forecasting.base`

---

sktime/classification/dictionary_based/_cboss.py

This PR carries out a forgotten depreation (scheduled for 0.15.0), of the `typed_dict` parameter in `ContractableBOSS`.
Fixes #4313

[MNT] carry out forgotten deprecation for `ContractableBOSS` `typed_dict` parameter

---

sktime/transformations/series/bkfilter.py

Following discussion in https://github.com/sktime/sktime/pull/4342, I noticed that the `BKFilter` did not interface, but in fact copy the code from `statmodels`.
This was an oversight in review, apologies. The code should interface (not copy) the statsmodels function, to avoid duplication and forking.
The fix should not change any functionality.
Also adds a second set of test parameters.

[ENH] turn `BKFilter` into a direct interface

---

sktime/forecasting/compose/_pipeline.py

This adds informative error messages and warnings to cover cases in https://github.com/sktime/sktime/issues/4370.
Fixes #4370 by adding informative user feedback.

[ENH] informative error messages for forecasting pipeline constructors, for `steps` arg

---

pyproject.toml

Loosens bound to allow `pandas` 2 versions as dependencies - let's see what breaks...

[MNT] `pandas` 2!

---

sktime/tests/_config.py

This PR excepts the forecasters with failures in the probabilistic prediction tests that were masked due to bugs in said tests https://github.com/sktime/sktime/pull/4361.
This is a temporary measure until fixes for the forecasters are found, to allow fixing of the test.
The failures of the forecasters are tracked here:
* `BaggingForecaster` https://github.com/sktime/sktime/issues/4363
* `DynamicFactor` https://github.com/sktime/sktime/issues/4362

[MNT] except forecasters failing proba prediction tests (previously masked by buggy tests)

---

sktime/forecasting/tests/test_all_forecasters.py
sktime/tests/_config.py
sktime/utils/_testing/forecasting.py

This PR fixes unreported bugs in the contract testing framework for forecasters:
* an ancient part of legacy code, `_assert_correct_pred_time_index` was supposed to check whether the time index of forecasts is correct. Instead of checking, the code did nothing, as it was missing an `assert`. Fixed.
* `test_update_predict_single` was using the wrong expected time index for the check (which was not detected because the check was broken), also fixed
This is expected to surface bugs, such as in `DynamicFactor`, see
https://github.com/sktime/sktime/actions/runs/4457787440/jobs/7829202210
Relies on https://github.com/sktime/sktime/pull/4364 which excepts the failing tests after they have been turned into bug reports.

[BUG] in forecasting test framework, fix ineffective assertion for correct time index check

---

sktime/forecasting/compose/_pipeline.py

This PR fixes a number of unreported probabilistic prediction bugs detected through https://github.com/sktime/sktime/pull/4393:
* `TransformedTargetForecaster` would return colums of a prediction interval forecast in unexpected order. This is fixed by reordering.

[BUG] fix unreported probabilistic prediction bugs detected through #4393

---

sktime/forecasting/vecm.py

See also #4394 (relevant comment: https://github.com/sktime/sktime/pull/4394#issuecomment-1489052793).
The previous implementation of `VECM` caused `ValueError` when `coverage` was passed as a list of float to `predict_interval`. This was caused because lower/upper bounds determined for different coverages were not stored, and it was trying to match the last iteration with all columns generated independently. This PR addresses that by combining the results from all the different coverage values, and then creating the final results.
No.
No.

[BUG] Support multiple coverage values for VECM

---

sktime/datatypes/_adapter/dask_to_pd.py
sktime/datatypes/_alignment/_check.py
sktime/datatypes/_check.py
sktime/datatypes/_common.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_proba/_check.py
sktime/datatypes/_series/_check.py
sktime/datatypes/_table/_check.py
sktime/datatypes/tests/test_check.py

This PR:
* adds granular control of metadata computation requests for all mtypes. This is controlled by allowing `return_metadata` to not just be boolean, but str or list of str. If the latter, controls exactly the fields of metadata that are requested. If empty list, no metadata are computed - but the error messages are still returned.
* As a consequence, we can implement the idea in @hoesler's https://github.com/sktime/sktime/pull/4191 without losing the informative error messages, which should also speed up thet input checks.
* refactors some common functions into a new `datatypes._common` module. Deals with the proliferation of `ret`/`_ret` functions all over the place.
Crediting @hoesler for this due to the idea in #4191 for speed-up (second bullet point).

& hoesler [ENH] granular control of mtype metadata computation, avoid computation when not needed

---

sktime/classification/base.py
sktime/classification/early_classification/base.py
sktime/clustering/base.py
sktime/datatypes/_adapter/dask_to_pd.py
sktime/datatypes/_alignment/_check.py
sktime/datatypes/_check.py
sktime/datatypes/_common.py
sktime/datatypes/_hierarchical/_check.py
sktime/datatypes/_panel/_check.py
sktime/datatypes/_proba/_check.py
sktime/datatypes/_series/_check.py
sktime/datatypes/_table/_check.py
sktime/datatypes/tests/test_check.py
sktime/dists_kernels/_base.py
sktime/forecasting/base/_base.py
sktime/param_est/base.py
sktime/regression/base.py
sktime/transformations/base.py

This PR aims to turn off all unnecessary input checks in base class boilerplate.
Relies on https://github.com/sktime/sktime/pull/4389 for granular control on metadata computation.
The blanket strategy is controlling the input checks at the level of the interface between base classes and `check_is_scitype` or `check_is_mtype`. An argument `return_metadata=True` is replaced by `return_metadata=` the list of metadata fields that is subsequently actually used in the current code.
This typically avoids the most expensive metadata calculations such as index checks, and should therefore speed up computation time substantially for cases where that turns out to be the bottleneck.

[ENH] turn off all unnecessary input checks in current base class boilerplate

---

pyproject.toml

Fixes https://github.com/sktime/sktime/issues/4354.
CI runs, which means we can revert the temporary emergency measure in https://github.com/sktime/sktime/pull/4353.

[MNT] replace emergency `dash` bound by exclusion of failing version 2.9.0

---

docs/source/developer_guide/add_estimators.rst

This adds a small paragraph to the estimator contribution guide to cover cython based estimators.
Based on the example https://github.com/sktime/sktime/pull/4337, and a guide-like summary of the discussion in https://github.com/sktime/sktime/issues/4296.
FYI @heerme, @lnthach.

[DOC] guide for adding cython based estimators

---

sktime/forecasting/compose/_pipeline.py

This PR adds an example in the docstring of `ForecastX` that shows how to use it to forecast only some columns.
Related to https://github.com/sktime/sktime/issues/4386, as this is @yarnabrina's use case.

[DOC] add example for `ForecastX` forecasting only some exogeneous variables

---

sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_utils.py

Fixes https://github.com/sktime/sktime/issues/4405, by adding logic to `get_cutoff` that infers the `freq` attribute if it is inferrable, per `pd.infer_freq`.
Also adds a test, using the failure case in #4405.
Open question, is this really a bug that needs fixed? Or, should the user be asked to set the `freq` attribute to indicate the period we are dealing with?

[BUG] ensure forecaster `cutoff` has `freq` inferred if inferable, for single series

---

README.md
docs/source/api_reference/classification.rst
docs/source/api_reference/clustering.rst
docs/source/api_reference/dists_kernels.rst
docs/source/api_reference/forecasting.rst
docs/source/api_reference/param_est.rst
docs/source/api_reference/regression.rst
docs/source/api_reference/transformations.rst

This PR makes various improvements to the README and adjacent docs.
* in the "tasks" table in the README, adds parameter estimatino as maturing and distributions/simulations as experimental
* in the "tasks" table in the README, changes partially valid API reference links to valid direct links into the respective subsections
* in the "overview" table, changes the time for the community meetup from 4pm UTC to 3pm UTC (daylight saving time change)
* fixes a systematic typo in API references where a space was missing
* adds the lookup paragraph present in other API reference sub-pages on the parameter estimator API reference page

[DOC] README and docs update - tasks table, typos, lookup

---

pyproject.toml

Reintroduces the `pandas` 2 bound given compatibility issues, see https://github.com/sktime/sktime/issues/4426
Will relax again if issues can be resolved quickly for 0.17.0

[MNT] reintroduce `pandas<2.0.0` bound

---

sktime/performance_metrics/forecasting/_classes.py
sktime/utils/datetime.py

This PR addresses som deprecation warnings from dependencies:
* use of the `warn` arg in `pandas.infer_freq` is removed
* comparison of `numpy` iterables and strings in metrics code

[ENH] address deprecation warnings from dependencies

---

sktime/datatypes/_utilities.py
sktime/datatypes/tests/test_utils.py
sktime/forecasting/conformal.py
sktime/param_est/plugin.py

This PR enables `PluginParamsForecaster` to accept any fittable estimator as `estimator`.
This enables use of exogeneous data when said parameter estimator is a forecaster.
What this also enables is combining conformal interval estimators and tuners according to the comment https://github.com/sktime/sktime/issues/4218#issuecomment-1488122851, this partially covers #4218 when nesting can be avoided by sequencing.
An example for the `ConformalIntervals` wrapper is added, how to use the `PluginParamsForecaster` to enable conformal intervals together with tuning, without incurring the high computational cost from nesting.
FYI @bethrice44, @adoherty21.
Accidentally contains https://github.com/sktime/sktime/pull/4406 due to wrong branching - but that should not be an issue since we'll merge …

[ENH] `PluginParamsForecaster` to accept any estimator, conformal tuned fast example

---

sktime/tests/_config.py

Excepts `Prophet` from `test_predict_quantiles` due to sporadic failures of the current test (quantile prediction monotonocity), see https://github.com/sktime/sktime/issues/4431

[MNT] except `Prophet` from `test_predict_quantiles` due to sporadic failures

---

sktime/tests/_config.py

Excepts `VECM` from `test_predict_quantiles` due to sporadic failures of the current test (quantile prediction monotonocity), see https://github.com/sktime/sktime/issues/4431

[MNT] except `VECM` from `test_predict_quantiles` due to sporadic failures

---

pyproject.toml
sktime/annotation/ggs.py
sktime/annotation/igts.py
sktime/annotation/tests/test_ggs.py
sktime/annotation/tests/test_igts.py

This PR isolates `attrs` imports and also fixes https://github.com/sktime/sktime/issues/4449, as "fix 1" proposed there.
This turns `attrs` from an implied (non-explict) soft dependency into an explicit soft dependency.
As the "de-facto" state of `attrs` as a soft dependency does not change, this does not require deprecation (instead, if removes the failure condition in #4449 from the status quo).

[MNT] isolating `attrs` imports

---

sktime/forecasting/ardl.py
sktime/forecasting/base/tests/test_base.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/model_selection/tests/test_tune.py
sktime/forecasting/tests/test_ardl.py
sktime/transformations/hierarchical/tests/test_reconcile.py

This fixes and sharpens a number of soft dependency isolations.
* supersedes some incorrect soft isolation statements with the below. E.g., the run condition for some tests involving `ARIMA` was `statsmodels` present, while `ARIMA` requires `pmdarima`. This may not have been spotted since `pmdarima` requires `statsmodels`, and users of `statsmodels` might often have `pmdarima` installed.
* replaces all `pmdarima` isolation statements with `_check_estimator_deps` statements, which is clearer to read as it relates directly to the estimator.
* same for all statements affecting `ARDL`
* sharpens the dependency tag of `ARDL` from `statsmodels` to `statmodels>=0.13.0`

[MNT] fix and sharpen soft dependency isolation logic for `statsmodels` and `pmdarima`

---

sktime/transformations/series/summarize.py

The `"mad"` option in the `pandas` `agg` methods has been deprecated and removed from `pandas` 2.
This is a problem as it is available in `SummaryTransformer`.
This PR replaces the deprecated functionality with a manual replicate as recommended in the deprecation message from `pandas`, allowing to keep the option in `SummaryTransformer`.
Test cases to cover the special logic are added.

[ENH] address deprecation of `"mad"` option on `DataFrame.agg` and `Series.agg`

---

sktime/benchmarking/evaluation.py

Prior to `pandas 2`, `DataFrame.agg` would automatically drop non-numeric columns for numeric aggregations.
That is no longer the case from `pandas 2` and causes exceptions.
This PR addresses the deprecation by manually dropping respective columns.

[MNT] address deprecation of automatic drop on `DataFrame.agg` on non-numeric columns

---

sktime/forecasting/base/_fh.py
sktime/forecasting/compose/_reduce.py

Fixes https://github.com/sktime/sktime/issues/4422, addresses the `freq` warnings by moving from `Timestamp` based arithmetic to `Index` based arithmetic, using the forecasters' `Index` valued cutoff and passing it through all methods.

[ENH] resolve `freq` related deprecations and `pandas 2` failures in reducers

---

README.md
docs/source/changelog.rst
pyproject.toml
sktime/__init__.py

Release PR for 0.17.1
* changelog
* instructions for `pandas 2` upgrade (if desired) and `pandas 1` continuity
NOTE: this is a patch focused on `pandas 2` compatibility and upgrade.

Release 0.17.1

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/_fh.py

In 0.16.0, the `BaseForecaster.cutoff` has changed from being an index element to `pandas.Index`, the `pandas.Index` version was available only as the private element `_cutoff` previously.
The `ForecastingHorizon` object's interface to `BaseForecaster` was still pointing to the private element, but can now be pointed to the public interface point which is `pandas.Index` since 0.16.0, see https://github.com/sktime/sktime/pull/3678.
Further, the `BaseForecaster.cutoff` getter has been made safer, i.e., it can also be called on non-fitted forecasters now (and will return `None`).

[ENH] shift `ForecastingHorizon`-`BaseForecaster` `cutoff` interface to rely on public point

---

sktime/forecasting/base/_base.py

In the existing implementation of `_predict_interval` in `BaseForecaster`, first it checks whether any of `_predict_interval`, `_predict_quantiles` or `_predict_proba` is overridden or not. But the check on `_predict_interval` would never evaluate to `True` when called from an inherited forecaster, as if it is indeed overridden, that overridden method would have been called, and not that of the `BaseForecaster`.
(Edit: stroked out no-more-affected areas by PR, because of update as suggested below)
~~On the other hand, even if `_predict_proba` is implemented, as of current implementation it is not used to generate prediction interval in case `_predict_interval` is not implemented. Plus presence of this check can possibly lead to `NameError` from `return pred_int` line, in case …

[ENH] remove superfluous implementation checks in `_predict_interval` and `_predict_quantiles` of `BaseForecaster`

---

sktime/forecasting/compose/_bagging.py
sktime/tests/_config.py

Fixes #4363, probabilistic forecasts of `BaggingForecaster`.
The probabilistic methods of `BaggingForecaster` would break, the reason being an unsafe dataframe column write.
Plausible reason may be a break through a `pandas` update which was not detected due to lacking test coverage before the proba prediction tests were updated.
The unsafe write has been replaced with a column write that does actually work under current `pandas 1` version.

[BUG] fix `pandas` write error in probabilistic forecasts of `BaggingForecaster`

---

sktime/forecasting/base/tests/test_base.py

This fixes an index input error in the test for nullable input compatibility, `test_nullable_dtypes`
The problem was masked by the `_PmdArimaAdapter` which would accept `X` of expected length no matter the index.

[BUG] fix index error in nullable input test

---

sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/base/adapters/_statsforecast.py
sktime/forecasting/tests/test_pmdarima.py

Fixes https://github.com/sktime/sktime/issues/4468.
An accident in the `pandas 2` upgrade in 0.17.1 broke the `predict_quantiles` method of the `_PmdArimaAdapter` and the `_StatsForecastAdapter`.
That this went undetected is due to quantile predictions not being tested in-sample, we need to add tests for that.

[BUG] fix `predict_quantiles` in `_PmdArimaAdapter` and `_StatsForecastAdapter` post 0.17.1

---

sktime/forecasting/tests/test_all_forecasters.py
sktime/tests/_config.py

This PR removes the monotonicity requirement from the quantile and interval prediction contract, and from the test `test_predict_quantiles`.
Related issue: https://github.com/sktime/sktime/issues/4431
Also removes the test skips from estimators sporadically failing monotonicity.

[ENH] remove monotonicity requirement from quantile prediction contract

---

.github/workflows/test.yml

This PR modifies the CI test matrix to ensure that all elements run, by using the `fail-fast` element, inspired by this discussion with @yarnabrina: https://github.com/sktime/sktime/discussions/4453#discussioncomment-5571043
As I see it:
* this is no major drawback, as in teh current test schema, all matrix elements start simultaneously and have similar duration. Failing the first usually shuts down runs that were almost finished.
* as we distribute estimators across matrix elements, a single failure may mask other estimator failures, if `fail-fast` is on.

[MNT] ensure all elements in test matrix complete runs

---

docs/source/api_reference/transformations.rst
sktime/transformations/compose/__init__.py
sktime/transformations/compose/_grouped.py

This PR adds a `TransformByLevel` transformer, which applies a transformer by panel or instance.
This allows to add to any transformer that does not have granular control on whether to apply it by level or not the option to apply it by panel or instance.

[ENH] transformer compositor to apply by panel or instance

---

sktime/datatypes/_utilities.py

This PR adds two arguments to `get_slice` to allow exclusive/inclusive bounding at either and of the slice.
The default of the two new arguments leads to current behaviour, so no deprecation is necessary.
This will be useful as a utility, and also for fixing https://github.com/sktime/sktime/pull/3667

[ENH] allow inclusive/exclusive bounds in `get_slice`

---

sktime/forecasting/base/adapters/_tbats.py
sktime/forecasting/tests/test_tbats.py
sktime/forecasting/tests/test_theta.py

Fixes https://github.com/sktime/sktime/issues/4491
The `_predict_interval` interface in `_TbatsAdapter` was a bit of a mess.
There was also really strange code that triggered specifically whenever the `fh` was longer than the training data, I was unable to understand why that condition should be the same as "contains in-sample prediction intervals".
This is the code:
```python
if len(pred_int) > len(self._y):
len_out = len(pred_int) - len(self._y)
pred_int["idx"] = [x for x in range(-len(self._y), len_out)]
```
It explains @ngupta23's issues in #4491, but I don't get why this was there in the first place.
Either way, I just completely rewrote the interface to prediction intervals from scratch.
The logic was simple, it is producing `nan` for insample predictions.
Contains the failure case …

[BUG] fix `BATS` and `TBATS` `_predict_interval` interface

---

docs/source/api_reference/classification.rst
sktime/classification/deep_learning/__init__.py

This PR adds the `InceptionTimeClassifier` and `LSTMFCNClassifier` to API docs. It also ensures all DL classifiers are consistently direct exports in the `deep_learning` module.

[MNT] add `InceptionTimeClassifier` and `LSTMFCNClassifier` to API docs and as direct export

---

sktime/utils/_testing/series.py

This cleans up the `_make_series` utility in preparation for moving it to the simulator interface:
* adds docstring
* adds `return_mtype` argument, similar to `_make_panel`
* silent deprecates `return_numpy` argument.
This is a private utility, so needs no deprecation.

[ENH] improved `_make_series` utility and docstring

---

sktime/registry/_tags.py

FIxes a merge accident in the `_tags` registry that made it to `main`.

[BUG] fixes merge accident in `_tags`

---

sktime/dists_kernels/dist_to_kern.py
sktime/forecasting/squaring_residuals.py
sktime/transformations/series/kinematic.py
sktime/transformations/series/subset.py

This PR addresses some warnings deprecation messages from dependencies:
* default `dtype` set explicitly in `pandas` constructors to `float64`
* adding `np.abs` to prevent negative values in square roots

[MNT] address some warnings and deprecation messages from dependencies

---

sktime/forecasting/vecm.py

Extended test coverage on `predict_interval` from https://github.com/sktime/sktime/pull/4470 revealed that `VECM._predict_interval` did not work with date-like indices.
This is now fixed.

[BUG] fix `VECM._predict_interval` interface for date-like indices

---

docs/source/index.rst

(coauthored with @fkiraly, based on an original PR by @howdy07)
improvements to description of sktime on the readthedocs landing page:
* shortened summary of features
* removed duplications

[DOC] improvements to description of `sktime` on the readthedocs landing page

---

sktime/registry/tests/test_lookup.py

This adds a test for the tag filter parameter of `all_estimators`, i.e., that only the filtered estimators are returned, and the filtered estimators are returned.

[ENH] add test for `all_estimators` tag filter

---

examples/mlflow.ipynb
sktime/utils/mlflow_sktime.py
sktime/utils/tests/test_mlflow_sktime_model_export.py

This makes the `mlflow` forecasting interface safe from the default interface changes to the `predict_proba` in 0.18.0, by ensuring that `predict_proba` calls in `mlflow` forecasting interface explicitly call `legacy_interface`.
This is fine for now, as the `mlflow` interface explicitly says that it does not support `predict_proba` (it just returns quantiles obtained from the distribution object).
We will need to change these calls to use the new interface, but that will be a separate issue.
Towards the 0.18.0 release action of deprecating the legacy interface.

[ENH] ensure `predict_proba` calls in `mlflow` forecasting interface explicitly call `legacy_interface`

---

sktime/forecasting/base/_base.py
sktime/proba/base.py
sktime/proba/tests/test_all_distrs.py

This PR introduces a `quantile` method to all `sktime` distributions.
This complements `ppf` (which also returns quantiles) in that it returns quantiles in the same format as forecasters' `predict_quantiles`, and broadcasts quantile points in the same way as in forecasters.
This PR also adds a default implementation of `predict_quantiles` if `predict_proba` is present, through calling `quantiles` of the `predict_proba` return.
This also enables the common usage pattern beyond 0.18.0, where `quantile` is called on the `predict_proba` return, similar to the `tensorflow` method, but in an `sktime` compatible mtype.

[ENH] `quantile` method for distributions, default implementation of forecaster `predict_quantiles` if `predict_proba` is present

---

docs/source/changelog.rst

This PR fixes a typo in the 0.17.2 changelog, the highlights tutorial link

[DOC] fix changelog typo - 0.17.2 highlights tutorial link

---

docs/source/api_reference/dists_kernels.rst
sktime/dists_kernels/indep.py

This PR adds a wrapper which can turn any univariate distance or kernel into a multivariate one by virtue of applying an aggregation function over variables.
If the aggregation function is the sum, sometimes this is called "independent distance" in literature.

[ENH] independent distance and multivariate aggregated kernel wrapper

---

sktime/dists_kernels/_base.py
sktime/dists_kernels/tests/test_dist_kernels_dunders.py
sktime/transformations/base.py

This adds variable subsetting functionality to the `__getitem__` dunder of distances and kernels, i.e., to `BasePairwiseTransformerPanel`.
This is in analogy to the same dunder of ordinary transformers.
Also includes a test.

[ENH] variable subsetting dunder `[...]` for distances and kernels

---

sktime/dists_kernels/_base.py

This PR fixes an unreported bug where the informative error message from a failed input check in `BasePairwiseTransformerPanel` would not be displaye, instead a cryptic exception about `NoneType` would be raised.
The failure is due to a return of `check_is_mtype` being `None` in the case where the check fails, but being treated as a `dict` erroneously (which it is in the success case). This was fixed.

[BUG] fix input check error message in `BasePairwiseTransformerPanel`

---

sktime/classification/deep_learning/rnn.py
sktime/regression/deep_learning/rnn.py
sktime/tests/_config.py

Due to a merge accident, a failure related to RNN made it to main.
This fixes fixture construction bugs and removes the estimators from testing temporarily.
The full fix will be developed in https://github.com/sktime/sktime/pull/4527, which is dependent on this PR (and removes the test skips).

[MNT] remove RNN related failure from main

---

sktime/classification/deep_learning/rnn.py
sktime/networks/rnn.py
sktime/regression/deep_learning/rnn.py
sktime/tests/_config.py

By accident, we merged https://github.com/sktime/sktime/pull/4185 without re-running the tests - this masked a bug. Which is not too grave as it is post-release, and the release CI has all passed.
Details: on the new `main`, the merge caused a clash with the `ABC` inheritance in `BaseRegressor` as one of the methods was not overridden. Also, `fit` should be `_fit`, which is also fixed.

&achieveordie [BUG] fix bug from clash between `ABC` inheritance and RNN `fit` override

---

sktime/forecasting/base/_base.py

As @yarnabrina pointed out in #4528, `predict_interval` would break in the case where neither `_predict_interval` nor `_predict_quantiles` are implemented but `_predict_proba` is.
In this case, `_predict_interval` would run into an exception, since no dispatch would be taking place.
This PR fixes this so that `_predict_interval` dispatches to `_predict_quantiles`, which in turn will dispatch to `_predict_proba`.

[ENH] corrected default logic for `_predict_interval` in case `_predict_quantiles` is not implemented but `_predict_proba` is

---

sktime/tests/test_all_estimators.py

This PR replaces replace `joblib.hash` with `deep_equals` in `test_fit_does_not_overwrite_hyper_params` for comparing `pandas` objects.
This is since `joblib.hash` seems to have issues with `pandas` objects, see #4534 or https://stackoverflow.com/questions/71312750/joblib-memory-and-pandas-dataframe-inputs
Version of https://github.com/sktime/sktime/pull/4537 where the replacement happens only for `pandas` objects.

[ENH] replace `joblib.hash` with `deep_equals` in `test_fit_does_not_overwrite_hyper_params` for `pandas` based parameters

---

.github/workflows/test.yml
pyproject.toml
sktime/_nopytest_tests.py

Resolves https://github.com/sktime/sktime/issues/4544, i.e., testing that `pytest` is isolated in a plain `sktime` install (which does not have `pytest` as a declared core dependency).
The approach is as follows:
* addition of a new GHA job
* only `sktime` plain is installed, no `dev` dependencies
* a test file `_nopytest_tests` is added, which can contain `pytest`-free checks
* currently, `all_estimators` plain is executed. As this crawls all modules (except tests and a few others), it will spot unisolated `pytest` imports, or imports of other packages.
* further checks can be added later
Depends on https://github.com/sktime/sktime/pull/4551

[MNT] test for isolation of `pytest`

---

sktime/transformations/base.py

This PR fixes an unreported bug where the `y` input type check in `BaseTransformer` would not return additional information on failure reasons for the check. The failure reasons were accidentally not appended to the failure string.

[BUG] fix informative error message on `y` input type check in `BaseTransformer`

---

docs/source/api_reference/classification.rst
sktime/classification/compose/__init__.py
sktime/classification/ensemble/__init__.py
sktime/classification/ensemble/_ctsf.py
sktime/classification/ensemble/_weighted.py
sktime/series_as_features/base/estimators/tests/test_feature_importances_.py

This PR moves the (proper) classification ensembles from `compose` to `classification.ensembles`, with a deprecation horizon of 0.20.0.
This makes it more similar to `sklearn`, and leaves only pipeline composition patterns in `compose`.

[ENH] move classification ensembles to `classification.ensembles`

---

pyproject.toml

Fixes https://github.com/sktime/sktime/issues/4566 temporarily by bounding `tensorflow-probability` to `<0.20.0`.

[MNT] bound `tensorflow-probability` to `<0.20.0`

---

sktime/transformations/series/date.py
sktime/transformations/series/tests/test_date.py

Fixes #4541. As the issue states, the formula with the modulos was broken, this is fixed now.
Also adds the example case as a test.

[BUG] fix incorrect values returned by `DateTimeFeatures` `'month_of_quarter'` feature

---

sktime/forecasting/model_evaluation/_functions.py

This PR improves the error message raised in `evaluate` when fitting fails for a forecaster.
Raised by sevs on discord.

[ENH] Clearer error message on fitting fail of `evaluate`

---

sktime/forecasting/compose/_pipeline.py

This PR removes the warning at construction of length 1 forecasting pipelines.
While helpful to the user if they explicitly construct the pipeline via the constructor, it is also raised when constructing pipelines via the dunder, or the `make_pipeline` utility, in which case it confuses the user.
As there is no way currently to evoke different behaviour in these two cases, we should remove it instead.
Side consideration: I have thought whether the config system and https://github.com/sktime/sktime/pull/4536 could be used for this - but for this, the config would have to be set before construction, which is currently not possible, not even with #4536.

[ENH] remove warning for length 1 forecasting pipelines

---

sktime/transformations/series/outlier_detection.py

Not found any
Consists on two fixes:
1. SlidingWindowSplitter split assumes a default forecasting horizon of 1 which leaves one datapoint out for test.  
- Impact: all the datapoints checked for outlier in the last window have miscalculated stats since the window is shifted by 1 position, leaving the last datapoint out.
- Solution: changed SlidingWindowSplitter forecasting horizon to 0, this creates an additional window including the missing datapoint, thus ensuring the calculations for the last window are accurate.
2. Current way of finding the start and end where the window is incomplete is not accurate for odd-sized windows
- Impact: for an odd-sized window, the datapoint n - floor(half_window_length) - 2 is not being considered as an outlier.
- Solution: changed the logic to identify …

[BUG] Fixes incorrect window indexing in `HampelFilter`

---

sktime/distances/_lower_bounding_numba.py
sktime/forecasting/model_selection/_split.py
sktime/transformations/series/fourier.py
sktime/transformations/series/hidalgo.py
sktime/transformations/series/impute.py

Fixes #4379 
in type annotations, replaces all instances of `Union[int | float]` (either way round) with `float`
This is my first contribution.
replacing Union[int | float] to just float

[ENH] changing Union[int | float] to float as per issue #4379

---

sktime/performance_metrics/forecasting/_classes.py

Fixes #4457. See also #4303 
1. Added adjusted vs symmetric clarifications for sMAPE.
2. Improved docstring documentation to include a mathematical summary of the metric and additional parameters that the metric class currently supports.
No
This isn't directly related to the PR, but I ran the documentation build locally to confirm that the changes were displayed correctly. During the process, I noticed that it took a while to build the HTML docs. It would be great if this process could be sped up a bit. Maybe consider `sphinx-autobuild` extension to automatically detect changes in docs with live-reload in the browser during local development.

[DOC] Improve Docstring for MAPE Metrics

---

sktime/proba/base.py
sktime/registry/_tags.py

This PR moves the approximation sample sizes in distributions to config - as originally planned when the base class was written but the config system (from `skbase`) was not available yet.

[ENH] move probability distribution statistic approximation sample sizes to config interface

---

sktime/classification/deep_learning/rnn.py
sktime/networks/inceptiontime.py
sktime/registry/_lookup.py
sktime/regression/deep_learning/cnn.py
sktime/regression/deep_learning/rnn.py

This removes a number of remaining import warnings from module imports, these are raised for example when running `all_estimators`.
Completes the work and dependency handling requirements from https://github.com/sktime/sktime/pull/4398 - most of the remaining warnings are from PR which were still in progress when #4398 was merged.

[ENH] remove remaining soft dependency related module import warnings

---

sktime/forecasting/compose/_reduce.py

This fixes compatibility issues of the experimental (unreleased) `RecursiveReductionForecaster` with pandas 2.

[ENH] `RecursiveReductionForecaster` pandas 2 fix

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/compose/__init__.py
sktime/forecasting/compose/_reduce.py

This adds a simple tabular prediction reduction forecaster to the reducers module.
The new `YfromX` forecaster uses tabular regression to forecast `y` from temporally concurrent `X` - it does not lag `y` and just uses `X` at the same time.
This is perhaps the simplest reduction strategy to supervised tabular regression, and so far it has not been easily obtainable afaik.

[ENH] simple tabular prediction reduction for forecasting

---

sktime/benchmarking/forecasting.py
sktime/benchmarking/tests/test_forecasting.py

I recently looked through the changes made to the benchmarking module in sktime because I'm interested in extending sktime benchmarking with `kotsu`.  As I went through the codebase, I noticed a comment below in the code 
> TODO re-write evaluate to allow multiple scorers, to avoid recomputation
that there was a need to rewrite `evaluate` to handle multiple metrics but `evaluate` indeed already supports this. we just need to give the scoring argument as a list of `BaseMetric` and it will compute multiple metrics without having to refit a model n number of times for n metrics.
I've also added an extra test coverage to ensure this works properly. 
@alex-hh @DBCerigo @TNTran92 @fkiraly 
Please confirm that this changes tackle the `todo` comment

[ENH] Extend forecasting benchmarking framework to multiple metrics, add test coverage

---

pyproject.toml

This fixes a new CI problem which seems to come from `holidays`, see https://github.com/sktime/sktime/pull/4589#issuecomment-1549991608

[MNT] bound `holidays` to avoid error in `Prophet`

---

docs/source/api_reference/dists_kernels.rst
docs/source/conf.py

changed  `language = None` to `language = "en"`  along with fixing import errors in confy.py

[ENH] fix warnings in make sphinx - language (`conf.py`) and `dists_kernels.rst` wrong imports

---

sktime/datatypes/_panel/_convert.py
sktime/transformations/panel/tsfresh.py

This PR:
* removes an unneccesary conversion in `TSFreshFeatureExtractor`, it would convert first to `nested_univ` then to `pd-long`. This is unnecessary, it should convert directly to `pd-long`.
* adds a direct converter from `pd-multiindex` to `pd-long`, removing the need to rely on the dodgy `nested_univ` data format.
Depends on https://github.com/sktime/sktime/pull/4573

[ENH] remove unneccesary conversion in `TSFreshFeatureExtractor`

---

sktime/forecasting/ets.py

This adds a second test parameter set to `AutoETS`.
Towards https://github.com/sktime/sktime/issues/3429
Related: https://github.com/sktime/sktime/issues/4587, as the second set has `auto=True`

[ENH] add more test parameter sets to `AutoETS`

---

sktime/tests/_config.py

Temporary measure to address sporadic memouts caused by `FCNClassifier`.
See https://github.com/sktime/sktime/issues/4610

[MNT] excepting `FCNClassifier` from CI to prevent memouts until bugfix

---

sktime/classification/deep_learning/rnn.py
sktime/regression/deep_learning/rnn.py

Towards #4558
Added DocStrings for the `[SimpleRNNClassifier]`(https://github.com/sktime/sktime/blob/main/sktime/classification/deep_learning/rnn.py#L20)

[DOC] docstring for `SimpleRNNClassifier`

---

sktime/forecasting/base/adapters/__init__.py
sktime/forecasting/base/adapters/_generalised_statsforecast.py
sktime/forecasting/base/adapters/_statsforecast.py
sktime/forecasting/statsforecast.py

See #4447 for discussions.
The existing `_StatsForecastAdapter` was too specific for `AutoARIMA`, and it was not possible to use same base adapter class for other estimators, e.g. `AutoTheta`. This PR attempts to rewrite in a general way to avoid this problem.
No.
* `copyright` part - not sure what to use
* `__author__` part - replaced `FedericoGarza` as I rewrote entirely, but since it's Nixtla's implementation, not sure if that's okay
* specification of tags `X-y-must-have-same-index` and `enforce_index_type` - not sure what is appropritae, skipped to use default
* introduced `fh_type`, which should only be either `in-sample` or `out-of-sample` - should this be an Enum, or normal check is fine?
* modified import for `StatsForecastAutoARIMA`, as `statsforecast.models` is publicly …

[ENH] rewrite of `_StatsForecastAdapter` in a generic way to support other models than `AutoARIMA`

---

sktime/classification/kernel_based/_svc.py

This adds a default kernel to `TimeSeriesSVC`, the `kernel` argument, which previously had no default.
The new default is the mean Euclidean kernel, same as ``AggrDist(RBF())``, where ``AggrDist`` is from ``sktime`` and ``RBF`` from ``sklearn``.
This is in analogy to the same default in `sklearn`'s `SVC` (with the mean added).
This PR also makes minor improvements to the docstring of `TimeSeriesSVC`.
As adding a default that did not previously exist does not break any existing dependent code, no deprecation is needed.

[ENH] add default kernel to `TimeSeriesSVC` - mean RBF kernel

---

sktime/proba/base.py

This PR fixes an unreported bug where the `alpha` returned in the columns of the return of `BaseDistribution.quantiles` were not sorted in the same order as `alpha` of `quantiles`, in the rare case where the input `alpha` were not already ascendingly sorted.
This violates the assumption on the `predict_quantiles` interface per the default using `predict_proba` - however, as that default was never used, it did not show up as a test failure.
This is fixed, and is tested as part of `skpro` PR https://github.com/sktime/skpro/pull/18 (although `sktime` does not depend on it yet)

[BUG] fix wrong `alpha` sorting in `BaseDistribution` `quantile` return

---

sktime/dists_kernels/scipy_dist.py
sktime/dists_kernels/tests/test_scipy_dist.py

This PR addresses the `kulsinski` deprecation in `scipy` by ensuring the tests use the distance of the right name, depending on `scipy` version.

[MNH] address `kulsinski` deprecation in `scipy`

---

sktime/proba/base.py
sktime/proba/normal.py

Fixes error messages in `BaseDistribution` if default methods are not implemented - this was calling a function that did not exist.
Also removes the redundant `sample` in `Normal` with defaulting to the parent class.

[BUG] fix error messages in `BaseDistribution` if default methods are not implemented

---

docs/source/developer_guide/coding_standards.rst

Fixes minor issues in coding standards guide:
* typos
* reference to glossary in a confusing location removed

[DOC] fix minor issues in coding standards guide

---

sktime/datatypes/_check.py

This PR removes a `legacy_interface` reference from `check_is_scitype` docstring that should have been removed in carrying out a deprecation action but was forgotten.

[DOC] remove forgotten `legacy_interface` reference from `check_is_scitype` docstring

---

sktime/base/_meta.py
sktime/forecasting/base/tests/test_base_bugs.py

This fixes a bug in `get_fitted_params` of `_HeterogenousMetaEstimator`, which is at the root of https://github.com/sktime/sktime/issues/4574. Also fixes #4574.
`get_fitted_params` of `_HeterogenousMetaEstimator` was accidentally calling the private interface point of components rather than the public interface point that it should have.
For reviewers: the first call should be to `_get_fitted_params` of the base class, which is correct. Subsequent calls to components should be to the public interface, `get_fitted_params`.
Contains a regression test for #4574.

[BUG] fix for `get_fitted_params` in `_HeterogenousMetaEstimator`

---

.github/workflows/test.yml
pyproject.toml

PR for planned release action to release `pandas 2` bound in 0.19.0.
This relaxes the `pandas 2` bound for the package (main dependency sets), and:
* leaves the `pandas<2` bound in the `binder` dependency set which is used for `binder`, notebook tests, and required for some dependencies, e.g., `statsforecast`
* adds a `pandas1` dependency set which restricts `pandas<2`, and a full set of tests on ubuntu with `pandas1`
See https://github.com/sktime/sktime/issues/4441 for a discussion of the release strategy.

[MNT] 0.19.0 release action - `pandas 2` bound

---

docs/source/changelog.rst

In the changelog, marks 0.19.0 as skipped - this should cause less confusion to users.

[DOC] skip 0.19.0 in changelog

---

docs/source/api_reference/regression.rst
sktime/regression/deep_learning/resnet.py
sktime/tests/_config.py

Part of #3351
Add `ResNetRegressor`
None …

[ENH] migrate `ResNetRegressor` from `sktime-dl`

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/ets.py
sktime/forecasting/statsforecast.py

Part of #4643.
This PR adds an interface to the `AutoETS` model provided in `statsforecast`. It's exposed to users as `StatsForecastAutoETS`, which inherits from `_GeneralisedStatsForecastAdapter` added in #4629.

[ENH] statsforecast AutoETS direct interface estimator

---

.github/workflows/test.yml
Makefile
sktime/tests/_config.py

Update: removes some recent esetimators from the tests.
Reference to the memory issue is added to the comments in the config files, so we can get back to this, e.g., when we change the testing framework.
---
Suspecting `MACNNClassifier` to be beind the memory related crashes on windows, python 3.9 (https://github.com/sktime/sktime/issues/4610), seeing what happens if we except it from the tests.
Suspicion is due to it being a recent addition. FYI @achieveordie.

[MNT] except some DL and `numba` based estimators from tests to prevent memory overload

---

sktime/forecasting/model_evaluation/_functions.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py

Fixes: #4685
fixing `no-update_params`  strategy in `evaluate` to ensure that the forecaster is fitting the first cv window but not the rest of the cv windows and saving the fitted model state. Also, included the `no-update_params` argument to pytests.

[BUG] - bugfix for `no-update_params` strategy in evaluate

---

sktime/base/_base.py
sktime/classification/early_classification/_probability_threshold.py
sktime/classification/early_classification/_teaser.py
sktime/classification/kernel_based/_arsenal.py
sktime/forecasting/compose/_bagging.py
sktime/series_as_features/base/estimators/_ensemble.py
sktime/tests/test_all_estimators.py
sktime/utils/random_state.py

Towards https://github.com/sktime/sktime/issues/4670
Eliminates private imports from `sklearn`:
* `set_random_state` and `_set_random_states` imports replaced by an `sktime` local `set_random_state` (consensus replacement)
* fixes an unreported bug where internal random state seeds could under some conditions exceed the max permissible in `numpy`, of `2**32 -1`
Todo:
* `_partition_estimators` imports
* `from sklearn.ensemble._forest import`-s

[MNT] remove private imports from `sklearn`

---

docs/source/developer_guide/testing_framework.rst

This doc adds a section to the developer guide on the `sktime` testing framework that describes the remote setup of the test suite, including the subsampling.
It is a bit compact, so a case could be made to extend it into its own section that also explains the GHA setup (not sure if that's duplicative).
FYI @yarnabrina who requested/suggested this - review appreciated.

[DOC] developer guide on remote setup of test suite

---

sktime/datasets/tsc_dataset_names.py

The `IOError` dataset from the TSC data registry no longer seems to exist - this PR simply removes it from the string registry.

[BUG] remove `IOError` dataset from TSC data registry

---

sktime/utils/_maint/_show_versions.py

This PR adds `skbase` to the default package version display of `show_versions` - it's a core dependency so should be there.

[ENH] add `skbase` to default package version display of `show_versions`

---

sktime/datatypes/_panel/_convert.py
sktime/datatypes/tests/test_convert_bugfixes.py

Fixes https://github.com/sktime/sktime/issues/4668.
See there for a bug description - the fix replaces the level values by the set of unique indices in the first (index 0) `MultiIndex` level, to avoid indexing at a non-existing index level value.

[BUG] fix conversion from `pd-multiindex` to `df-list` if not all index levels are present

---

.github/workflows/test.yml
Makefile

This PR makes small changes to the CI to reduce verbosity of test logs.
Recently increased to diagnose issue https://github.com/sktime/sktime/issues/4610, but we probably should revert the setting before the 0.19.2 release.

[MNT] reduce CI test log verbosity

---

docs/source/index.rst

This PR replaces, in the sktime docs landing page call-to-action box, the internship application (now closed) with a link to encourage user registration and participation in tech roadmap and governance. As per action in last weeks' council meetings.

[DOC] User registration link on documentation landing page

---

sktime/forecasting/base/_base.py

This PR improves some exception messageas in `BaseForecaster`, to point to the class name that raised the error - this is useful in diagnosing errors raised by composites such as in #4698.

[ENH] improved `BaseForecaster` exception messages, with reference to `self` class name

---

sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_pipeline.py

For multivariate `y`, the compositor `ForecastX` would always broadcast over variables of `y`, even if wrapped forecasters were multivariate.
However, `ForecastX` itself should never broadcast over `y`, that should be left to component forecasters.
Fixed here, this also fixes #4718
Includes a slightly extended test case from the bug report #4718 by @yarnabrina

&yarnabrina [BUG] correct `ForecastX` behaviour in case of multivariate `y`

---

sktime/base/tests/test_base_sktime.py

This adds a test case for the failure of `set_params` with nested `sklearn` objects, see https://github.com/sktime/sktime/issues/4704
The fix is in `skbase` and is also tested there: https://github.com/sktime/skbase/pull/195
This PR adds a test in `sktime` with the `sktime` objects for which the failure was reported in #4704.

[BUG] add test case for failure of `set_params` with nested `sklearn` object

---

.all-contributorsrc
sktime/forecasting/base/_fh.py
sktime/forecasting/base/tests/test_base.py
sktime/forecasting/base/tests/test_fh.py

Related #4698.
Before this PR, `ForecastingHorizon` did not support passing `range` objects. Since asking for all horizons till a specific one is quite common, one had to do `ForecastingHorizon(values=list(range(12)))` to get next `12` predictions, or use `numpy.arange`.
This PR adds support for `range` (and tests for the same), so that one can do `ForecastingHorizon(values=range(12))` to do the above. This also updates the documentations slightly to explicitly note that list/array passed to create horizon must be of integers.
(note: also added few contribution types to my name as part of this PR. can be removed by reverting commit https://github.com/sktime/sktime/pull/4716/commits/f8d9429c2ff3b32b3a176b7b124c788efaf871af if inappropriate.)

[ENH] support passing horizons as `range` object in `ForecastingHorizon` and in `fit` and `predict` methods

---

.github/workflows/test.yml
.github/workflows/wheels.yml

Removes testing on python 3.7 on CI.
Part of https://github.com/sktime/sktime/pull/4717, but in case 3.7 tests start failing due to dependencies.

[MNT] remove python 3.7 tests from CI

---

.github/workflows/wheels.yml

To strengthen our security posture, we've enabled 2FA on the pypi account.
It appears that this implies that uploads are only possible with API tokens, so we need to replace the login/password secret with an API token secret.
This PR points the release workflow to the API token secret, and we need to enter the secret via the GitHub settings.

[MNT] use `pypi` API token for release

---

.github/workflows/test.yml
.github/workflows/wheels.yml
README.md
build_tools/check_install_from_test_pypi.sh
docs/source/get_started.rst
docs/source/installation.rst
pyproject.toml
sktime/forecasting/base/adapters/_generalised_statsforecast.py
sktime/forecasting/compose/tests/test_ensemble.py

Scheduled release action for 0.20.0 - removing python 3.7 due to end of life. See https://github.com/sktime/sktime/issues/4569
Removed from:
* package metadata, support
* estimator metadata
* CI and tests
* documentation

[MNT] 0.20.0 release action - remove python 3.7 support

---

sktime/benchmarking/tests/test_TSCStrategy.py
sktime/benchmarking/tests/test_orchestration.py
sktime/classification/compose/__init__.py
sktime/classification/ensemble/_ctsf.py
sktime/classification/ensemble/_weighted.py
sktime/classification/ensemble/tests/__init__.py
sktime/classification/ensemble/tests/test_ensemble.py
sktime/forecasting/base/_fh.py

Deprecation actions for the 0.20.0 release:
* remove deprecation period imports and warnings after moving `ComposableTimeSeriesClassifier` and `WeightedEnsembleClassifier` to `classification.ensemble`
* bump next checkpoint for `pandas` `freq` related compatibility fix for 0.21.0

[MNT] 0.20.0 deprecation actions

---

pyproject.toml

For 0.20.0 release: increase `scikit-base` bound to `<0.6.0`.
The 0.5.X releases of `scikit-base` will also drop python 3.7 support.

[MNT] 0.20.0 release action - increase `scikit-base` bound to `<0.6.0`

---

sktime/tests/_config.py

In reference to #4610, skipping all DL estimators that are causing several CI runs to crash till we find a root cause and hence a solution to this.

[MNT] Temporarily skip all DL Estimators

---

.all-contributorsrc
sktime/clustering/k_means.py
sktime/clustering/k_medoids.py

Adds to #4264. 
Added usage examples to `k_means` and `k_medoids`.
No.
No. …

[DOC ] Added examples to docstrings for K-Means and K-Medoids

---

.github/workflows/test.yml

This removes a forgotten "verbose" flag from the windows CI that was added for diagnostic of the sporadic failures.

[MNT] remove verbose flag on windows CI

---

pyproject.toml

This bounds `scipy` away from the new release, given `BracketError` failures #4769, which may or may not be due to a bug in `scipy` - in any case they seem unclear and hard to fix.
We may also want to consider making the defensive bounds in `scipy` more granular in the future.

[MNT] bound `scipy<1.11.0` after bracket failures

---

sktime/forecasting/base/_base.py
sktime/forecasting/base/tests/test_base_bugs.py

Fixes https://github.com/sktime/sktime/issues/4766
The `predict_residuals` internal calculation of residuals could break due to different data types for the observed and the predicted, as in some cases the observed would be obtained from `self._y` which can be data type coerced.
The "optimal" solution would be to not do any coercion or conversion, but for now this should be fixed by converting to the predicted which has the data type consistent with the `fit` input.

[BUG] Fix `predict_residuals` internal data type conversion

---

docs/source/conf.py
pyproject.toml

Closes #4677 
Adds a new dependency `sphinx-version-warning` as part of `docs` optional dependency. The changes in this PR follows `elyra` example almost unchanged, though `ray`, `marshmallow`, etc. also seem to have same format.

[DOC] adds a banner for non-latest branches in read-the-docs

---

pyproject.toml
sktime/transformations/series/boxcox.py

Fixes https://github.com/sktime/sktime/issues/4769 by using `scipy`'s on-board box-cox-fitter for methods `"mle"` and `"pearsonr"` and enforcing positive values.
The reason for the failure was use of negative values in some interface test cases, which previously would produce garbage results but `scipy` would not complain. As of 1.11.0, it complains (albeit with a confusing error message that makes it hard to track down that it is in fact from negative values in some test cases). See further discussion here: https://github.com/scipy/scipy/issues/18761
This is now solved by introducing an `enforce_positive` argument to `BoxCoxTransformer`, which ensures positive values before fitting. This can be turned off to obtain the previous behaviour, but for positive values it will be the same …

[BUG] fix `BoxCoxTransformer` failure after `scipy` 1.11.0

---

sktime/transformations/compose/_column.py

`sklearn`'s `if_delegate_has_method` is deprecated and will be removed in 1.3.
This PR removes one instance of the method being imported - it is not relevant for the transformer contract, therefore it can be safely removed.
Also see https://github.com/sktime/sktime/issues/4585#issuecomment-1604960337 for this being reported by @celestinoxp.

[MNT] address deprecation of `sklearn` `if_delegate_has_method` in 1.3

---

docs/source/api_reference/performance_metrics.rst
sktime/performance_metrics/forecasting/probabilistic/__init__.py
sktime/performance_metrics/forecasting/probabilistic/_classes.py

This PR adds some missing metrics to the API reference:
* quantile prediction metrics
* distribution forecast metrics
* time series segmentation metrics

[DOC] add missing metrics to API reference

---

.all-contributorsrc
sktime/forecasting/base/_sktime.py
sktime/forecasting/tests/test_window_forecasters.py

Added temporary fix to _BaseWindowForecaster to handle simultaneous in and out-of-sample forecasts (see #4773). Also added a test to check if NaiveForecaster and BaseWindowForecaster work as expected.
Fixes #4773
Added an if clause to [_BaseWindowForecaster _predict method](https://github.com/sktime/sktime/blob/32493231800d94f8a5b6df6d1bc42ae0fb398c69/sktime/forecasting/base/_sktime.py#L44) to correctly concatenate the outputs of in and out of sample forecasts.
No
Added `test_insample_and_outofsample_forecasting` to `sktime/forecasting/tests/test_window_forecasters.py`
As this is my first contribution to this package, I'm not sure if I'm skipping some name or other convention. Please feel free to highlight if something should be altered in this PR.

[BUG] Add temporary fix to _BaseWindowForecaster to handle simultaneous in and out-of-sample forecasts

---

pyproject.toml

`tslearn` has released 0.6.0, which now imports `geomstats`, which imports `pytorch`.
The dependency tree is vastly increasing, and `tslearn` does not seem to isolate their (soft?) dependencies properly, as the backend seems to be required by the code but is not actually installed (resulting in failing import exceptions).
This is now causing CI failures in the soft dependency set on `main`, and will likely cause failures to users who install it (or `tslearn`). Therefore we need to restrict the `tslearn` version.

[MNT] bound `tslearn<0.6.0` due to bad dependency handling and massive imports

---

.github/workflows/test.yml
.github/workflows/wheels.yml
pyproject.toml

Fixes https://github.com/sktime/sktime/issues/4794
This is done by removal of packages conflicting with `pandas 2` from the dependency set that is tested.
The `all_extras` set does not change, instead a smaller `all_extras_pandas2` is tested.

[MNT] ensure CI for python 3.8-3.10 runs on `pandas 2`

---

pyproject.toml

Ensures that the addition in https://github.com/sktime/sktime/pull/4795 also has the bound from https://github.com/sktime/sktime/pull/4819

[MNT] also restrict `tslearn` on the `pandas 2` testing dependency set

---

CODEOWNERS

This cleans up the `CODEOWNERS` file as follows:
* orders `CODEOWNERS` by alphabet
* sets the general owners to the currently four core developers with daily/weekly contribution frequency - @achieveordie, @benHeid , @fkiraly, @yarnabrina - this does not have a formal meaning of ownership, it only means we receive review requests
* removes codeowners of base and some general framework building modules - these are "commonly owned" and not an individual's
* rectifies ownership where it was missing or incorrect
* adds missing `DateTimeTransformer` (@danbartl, @KishManani)
* adds missing `ClearSkyTransformer` (@ciaran-g)
* adds missing `HierarchyEnsembleForecaster` (@VyomkeshVyas)
* added missing owners in the annotation module - @miraep8, @katiebuc
There are probably others, I wonder whether …

[MNT] clean-up of `CODEOWNERS`

---

sktime/classification/ensemble/_bagging.py

This ensures that `BaggingClassifier` can be used as univariate-to-multivariate compositor, by turning off the input check that would incorrectly prevent multivariate data from being passed in the case `n_features=1`, and the internal estimator being univariate.
This important special case is also stressed in the docstring.

[ENH] ensure `BaggingClassifier` can be used as univariate-to-multivariate compositor

---

sktime/transformations/series/tests/test_kalman_filter.py

Temporary fix for https://github.com/sktime/sktime/issues/4835, skips test with an `xfail`

[MNT] skip failing `test_transform_and_smooth_fp` on `main`

---

pyproject.toml

This PR replaces all the pins from `sphinx` and plugins with defensive upper bounds - next MAJOR release if the package is post-0, next MINOR release if the package is on zero-point.
---
original post: Diagnostic PR to see what happens if we remove all the pins from sphinx and plugins.

[MNT] unpin `sphinx` and plugins, with defensive upper bounds

---

docs/source/developer_guide/dependencies.rst

From a few discussions I had, it turns out that the guide on soft dependencies is slightly confusing, as it has content about handling existing soft dependencies and adding one, but both in a section called "adding a soft dependency".
To resolve the confusion, I've split the existing section in two:
* a section about handling soft dependencies
* a section about adding soft dependencies
I've also updated the documentation with how pandas 1 and pandas 2 conditional testing of soft dependencies is currently handled in `pyproject.toml`

[DOC] improved guide for soft dependencies

---

docs/source/api_reference/forecasting.rst

The estimators in the forecasting API reference were slightly disordered, some estimators were sorted in the wrong category.
The mismatches were mostly `statsforecast` based estimators which were mistakenly added below the first such model - in the ARIMA category, even though they didn't belong there.
I made the following changes:
* sorted the `statsforecast` models in the right categories, Auto-Theta, Auto-ETS and -CES need to go in the exponential smoothing category
* split the AR/MA category into plain (V)AR(I)MAX and Auto-ARIMA models
* added an intermittent time series category

[DOC] sort slightly disordered forecasting API reference

---

docs/source/changelog.rst
sktime/dists_kernels/_base.py
sktime/forecasting/base/_base.py
sktime/transformations/base.py

In various places in the documentation, `ColumnSelect` is referred to as `ColumnSubset`, erroneously. This is fixed in all instances.

[DOC] fix `ColumnSelect` typos in documentation

---

sktime/tests/test_softdeps.py

In response to #4820 and maintainance in #4860,
The current test_softdepds does not account for package versions and aliases. It only checks if dependencies can be imported using the package name via `import_modules` that only captures cases like "pmdarima" but not "pmdarmia<1.3". This resulted in failures if the **python_dependencies** tag had a package version bound or a different import name. This PR leverages `_check_soft_dependencies` to account for the drawbacks.

& fkiraly [MNT] Extend softdep error message tests support for packages with version speciefier and alias

---

docs/source/developer_guide/dependencies.rst
sktime/alignment/dtw_python.py
sktime/base/_base.py
sktime/classification/distance_based/_elastic_ensemble.py
sktime/classification/feature_based/_matrix_profile_classifier.py

There are some remaining compatibility issues from the `sklearn 1.3.0` release which the pre-release testing did not catch. See https://github.com/sktime/sktime/pull/4778. This PR fixes those.
* `ElasticEnsemble` instantiated `sklearn` `RandomizedSearchCV` with `float` `n_iter`, which sets off the parameter validation since 1.3.0. Fixed by coercing to `int` (rounding down)
* `MatrixProfileClassifier` fails due to `sklearn` bug https://github.com/scikit-learn/scikit-learn/issues/26768. This is 1.3.0 specific and appears fixed for (not yet released) 1.3.1, so added an `sklearn!=1.3.0` version requirement for `MatrixProfileClassifier`
Depends on the bugfix https://github.com/sktime/sktime/pull/4867 to ensure the specifier `sklearn!=1.3.0` is handled correctly.

&hazrulakmal [MNT] fix remaining `sklearn 1.3.0` compatibility issues

---

sktime/base/_meta.py

This improves the `_HeterogenousMetaEstimator` by widening its functionality.
`_HeterogenousMetaEstimator` now allows tuples of any length in the `_steps_attr`, as long as the zeroth elements are str names, and the first elements are estimators
The change to `_HeterogenousMetaEstimator` is indirectly tested in https://github.com/sktime/sktime/pull/4789 (which depends on this) and will be tested in `scikit-base`.

[ENH] `_HeterogenousMetaEstimator` to accept list of tuples of any length

---

sktime/classification/early_classification/_probability_threshold.py

This removes a forgotten, old import of `deprecated` dating back to 0.13.0.
There was a deprecation action attached which never got carried out, we should revisit this later (so I added a todo with the next MINOR release instead)

[MNT] remove forgotten `deprecated` import from 0.13.0

---

extension_templates/forecasting_supersimple.py
extension_templates/transformer_simple.py
extension_templates/transformer_supersimple.py

Makes minor improvements to the forecasting and transformer extension templates:
* adds reference to the "simple" extension template in the preamble
* updates the files to comply with the new (post-3.7) linting conventions

[DOC] minor improvements to forecasting and transformer extension templates

---

docs/source/api_reference/forecasting.rst
sktime/forecasting/compose/__init__.py
sktime/forecasting/compose/_fhplex.py

Fixes https://github.com/sktime/sktime/issues/3018
Implements a forecaster `FhPlexForecaster` that allows to specify different parameters per forecasting horizon.
To specify different forecasters, combine with `MultiplexForecaster` or `MultiplexTransformer`.
Potentially useful in https://github.com/sktime/sktime/issues/4776#issuecomment-1616804513.
FYI @davidgilbertson, would appreciate feedback.
Currently does not have as features (but should have?)
* multiple `fh` indices per forecaster
* inheritance from `_HeterogenousMetaEstimator` - I already prepared the `_forecasters` attr for that but didn't yet test it with inheritance. Hopefully works out of the box.

[ENH] by-horizon forecaster, for different estimator/parameter per horizon

---

sktime/base/_base.py
sktime/tests/_config.py

@yarnabrina and @fkiraly  caught a possible memory leak in the saving method of our base object. I'm adding a context manager to explicitly close files that may or may not be closed by the garbage collector.
@fkiraly also suspects that this could be the culprit behind the memouts that DL estimators were suffering from. To test this, I'm temporarily skipping all excepted DL estimators.

&yarnabrina [ENH] Add an explicit context manager during estimator dump

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/tests/test_metrics.py

Fixes https://github.com/sktime/sktime/issues/4827 by ignoring parameters that are not present in the default params of a metric.

[BUG] allow unused parameters in metric when using `make_forecasting_scorer`

---

sktime/forecasting/compose/_pipeline.py

This PR sets the `ForecastX` missing data handling tag to `True` to properly cope with future unknown variables.
An edge case - or, arguably, a general case if none of the future variables are known - is showcased in this issue discussion:
https://github.com/sktime/sktime/issues/4848
More precisely, `ForecastX` should always allow for `nans` in future `X`, as these may be in places where there is genuinely no knowledge about the future. Alternatively, dummy values have to be provided which sounds odd.
FYI @davidgilbertson

[ENH] set `ForecastX` missing data handling tag to `True` to properly cope with future unknown variables

---

sktime/forecasting/model_selection/__init__.py
sktime/forecasting/model_selection/_split.py

This PR adds a composite splitter which takes any splitter and changes its test splits to be the union of respective test plus train split.
Related issues and PR:
https://github.com/sktime/sktime/issues/4842
https://github.com/sktime/sktime/pull/4851
https://github.com/sktime/sktime/pull/4861

[ENH] test-plus-train splitter compositor

---

sktime/datatypes/_proba/_convert.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_delegate.py
sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/base/adapters/_generalised_statsforecast.py
sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/base/adapters/_statsforecast.py
sktime/forecasting/base/adapters/_statsmodels.py
sktime/forecasting/base/adapters/_tbats.py
sktime/forecasting/compose/_bagging.py
sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_bagging.py
sktime/forecasting/conformal.py
sktime/forecasting/dynamic_factor.py
sktime/forecasting/naive.py
sktime/forecasting/squaring_residuals.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/forecasting/theta.py
sktime/forecasting/var.py
sktime/forecasting/vecm.py
sktime/utils/estimators/_forecasters.py
sktime/utils/estimators/tests/test_forecasters.py

Reverts sktime/sktime#4780 as it needs to go into 0.21.0, not 0.20.1

Revert "[ENH] replace `"Coverage"` and `"Quantiles"` default variable name in univariate case with variable name"

---

sktime/forecasting/model_selection/__init__.py
sktime/forecasting/model_selection/_split.py
sktime/forecasting/model_selection/tests/test_split.py
sktime/registry/_tags.py

This adds a splitter that takes a splitter and some data, and always replicates the same `loc` references for splits of another splitter.
Related issue and discussion: https://github.com/sktime/sktime/issues/4842
More general form of `temporal_train_test_split`, particularly useful for the case where we want to split `X` and `y`, and primarily `y`, and `X` can have different indices from `y`.
This ability partially addresses #4842, FYI @felipeangelimvieira

[ENH] splitter that replicates `loc` of another splitter

---

docs/source/api_reference/utils.rst

This PR adds the blueprint serialization utilities in `registry`(`craft`, `deps`, `imports`) to the API reference.

[DOC] add blueprint serialization utilities to API reference

---

.gitignore
sktime/forecasting/tests/test_ets.py
sktime/utils/tests/test_mlflow_sktime_model_export.py

Small maintenance actions:
* `xfail`-s the `mlflow` failure in #4904 until debugged
* add `py-spy` outputs to `.gitignore`, see #4900

[MNT] xfail `mlflow` failure #4904 until debugged, gitignore for `py-spy`

---

sktime/performance_metrics/forecasting/_classes.py

This fixes an interaction of new input checking logic in `sklearn 1.3.0` with dynamic forecasting error metics based on `partial` that was uncovered `test_make_scorer`, regression test for #4827.

[BUG] 0.21.0 release bugfix - fix interaction of `sklearn 1.3.0` with dynamic error metic based on `partial` in `test_make_scorer`

---

sktime/datatypes/_proba/_convert.py
sktime/forecasting/base/_base.py
sktime/forecasting/base/_delegate.py
sktime/forecasting/base/adapters/_fbprophet.py
sktime/forecasting/base/adapters/_generalised_statsforecast.py
sktime/forecasting/base/adapters/_pmdarima.py
sktime/forecasting/base/adapters/_statsforecast.py
sktime/forecasting/base/adapters/_statsmodels.py
sktime/forecasting/base/adapters/_tbats.py
sktime/forecasting/compose/_bagging.py
sktime/forecasting/compose/_column_ensemble.py
sktime/forecasting/compose/_fhplex.py
sktime/forecasting/compose/_pipeline.py
sktime/forecasting/compose/tests/test_bagging.py
sktime/forecasting/conformal.py
sktime/forecasting/dynamic_factor.py
sktime/forecasting/naive.py
sktime/forecasting/squaring_residuals.py
sktime/forecasting/tests/test_all_forecasters.py
sktime/forecasting/theta.py
sktime/forecasting/var.py
sktime/forecasting/vecm.py
sktime/utils/estimators/_forecasters.py
sktime/utils/estimators/tests/test_forecasters.py

Copy of https://github.com/sktime/sktime/pull/4780 which was reverted to ensure it ships with 0.21.0, not 0.20.1.
Fixes #4709 - in `predict_interval` and `predict_quantiles` return, replaces `"Coverage"` and `"Quantiles"` default variable name in the univariate case with the variable name, to make this consistent with the multivariate case. If no variable name is available, the variable name used is the integer 0.
This is done with a deprecation horizon or two MINOR cyles, by introducing a `legacy_interface` argument to public and private `predict_interval`, `predict_quantiles`. A value `True` (default) gives current behaviour, `False` gives future behaviour. In 0.22.0, we switch the default to `False`, and remove the argument in 0.23.0.
This includes tests for `legacy_interface` both …

[ENH] replace `"Coverage"` and `"Quantiles"` default variable name in univariate case with variable name

---

docs/source/developer_guide/deprecation.rst

In preparation of deprecation of `deprecated` as a dependency and for use in the deprecation process scheduled for 0.22.0 https://github.com/sktime/sktime/pull/4822, the deprecation guide is updated to reflect the post-deprecation state.

[DOC] 0.21.0 release action - update deprecation guide to reflect deprecation of use of `deprecated`

---

docs/source/api_reference/transformations.rst

The row transformers (compositors that add broadcasting that is now standard for all transformers) have been removed a while ago from `sktime` - this PR removes the dead references to them from the transformers API.

[DOC] remove outdated references from transformers API

---

pyproject.toml

According to @yarnabrina, `statsforecast` is now compatible with `pandas 2`, so should be added to the respective dependency set in `pyproject.toml`.

[MNT] add `statsforecast` to the `pandas2` compatible dependency set

---

sktime/transformations/series/feature_selection.py

Fixes https://github.com/sktime/sktime/issues/4881
The reason was that internally, the `y` passed to the `sklearn` estimator was 2D (a `pd.DataFrame`), not 1D as expected by `sklearn`.
This is fixed by changing the internal `y`-type coercion to `pd.Series` (which is 1D and `sklearn` compatible)

[BUG] fix `DataConversionWarning` in `FeatureSelection`

---

docs/source/installation.rst

Fixes #4934 . See also #4933 
This PR provides more clarity and consistency to the installation documentaton. https://www.sktime.net/en/stable/installation.html
In the steps describing the installation process for development setup using conda the pip install statement was changed. The attribute "all_extras" is deleted - not proposing the installation of the soft dependencies.

Installation documentation: Pip install without soft dependencies for conda environments

---

.all-contributorsrc
CONTRIBUTORS.md
sktime/forecasting/base/_base.py

Fixes #4947
The default value of the mean_absolute_percentage_error function changed to the non-symmetric MAPE. This has been made explicit, and the doc-string is adjusted.
none 
Was the change from symmetric  - MAPE to non-symmetric MAPE intended for the score function of the BaseForecaster? 
How are down-stream tasks affected in either way?
Functionality was not changed.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test …

[DOC] correct docstring of `BaseForecaster.score`, reference to use of non-symmetric MAPE

---

sktime/datasets/tests/test_single_problem_loaders.py

The UEA benchmark data repository has grown increasingly unreliable, see https://github.com/sktime/sktime/issues/4754 - there is also a current failure on `main`.
This PR `xfail`-s the loader tests until this is fixed by a buffer or mirror, see #4754.

[MNT] xfail UEA data loaders until fixed by mirroring/buffering

---

sktime/clustering/base.py
sktime/forecasting/base/_base.py
sktime/registry/_tags.py

Fixes #4898
As discovered by @benHeid, the error messages were quite unhelpful in the case there was a mismatch between the supported and provided type. I've updated the code to be a slightly more generalized validation function and more information is provided in case of an error.
I also found a very minor bug in forecasting's validation function and took the liberty to correct it.
Finally, `clusterer` was not added by the original authors into the registry so I added that as well.
None
There are a bunch of `TODOs in `BaseForecaster`, we might want to take care of that in the upcoming PRs.
No test is required for this change.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the …

[BUG] Add Informative Error messages for incompatible `scitype` in `BaseClusterer`

---

sktime/forecasting/conformal.py
sktime/param_est/plugin.py
sktime/param_est/tests/test_plugin.py

Fixes https://github.com/sktime/sktime/issues/4921
The internal logic for parsing the `dict` for plugin specification was jumbled - the subsetting would subset the opposite way round, compared to the plugin direction.
This has now been fixed by changing the plugin direction, making it also consistent with user expectation in the `dict` case.
The failure case from https://github.com/sktime/sktime/discussions/4884#discussioncomment-6506787 has been added as a test.
Deprecation is not needed imo, as this replaces a bug failure with actual behaviour, even if it changes the specification claimed by the docstring.

[BUG] fix `PluginParamsForecaster` in `params: dict` case

---

sktime/forecasting/compose/_fhplex.py

Fixes #4918, by adding parameter for "option 3", as discussed here: https://github.com/sktime/sktime/issues/4918#issuecomment-1645205543

[ENH] contiguous `fh` option for `FhPlexForecaster`

---

sktime/forecasting/model_selection/tests/test_tune.py

This PR speeds up the `test_gscv_proba` test by cutting down on the data size and therefore the number of folds in the tuning.
Each run of the test takes ca 1min, at a total of 18 fixture combinations.

[MNT] speed up `test_gscv_proba` test

---

sktime/forecasting/model_selection/_tune.py

This PR fixes https://github.com/sktime/sktime/issues/4929
As discussed there, the `refit=False` parameter was incorrectly described in docstrings, and error messages that were raised were not informative.
This PR updates the docstring with a clear description of how `refit=False` is intended to be used, and adds an informative error message.

[BUG] clarify tuning estimators' docstrings and error messages in case of `refit=False`

---

.all-contributorsrc
sktime/transformations/series/impute.py

Fixes #4997
Passes the missing ForecastingHorizon to the fit method
Adds a test to check with a forecaster requiring fh in fit and not only in predict.
No
Yes
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.h …

[BUG] Fix forecaster based imputation strategy `Imputer` if forecaster requires `fh` in `fit`

---

sktime/performance_metrics/forecasting/_classes.py
sktime/performance_metrics/forecasting/_functions.py
sktime/performance_metrics/tests/test_metrics_classes.py

Fixes https://github.com/sktime/sktime/issues/4952 as follows:
It turns out that "pooled" application of a metric, i.e., ignoring index and passing the panel data as single 2D array was alreay possile, using `multilevel="uniform_average_time"`.
This is perhaps a bit of a misnomer, either way the docstrings did not inform the user of the option.
This has now been rectified:
* docstrings of (point forecast) metrics now all explain the multilevel argument and its possible values
* a test has been added to ensure that the parameter indeed corresponds to "ignoring level index"
* removes "hidden" input checks in some of the metric functions - these are covered by the base class, and inconsistently present in the functions. As they prevent the `"univorm_average_time"` logic in the four metrics …

[ENH] applying forecasting metrics disregarding index - docstrings and tests

---

sktime/performance_metrics/forecasting/_functions.py
sktime/performance_metrics/forecasting/tests/test_metrics.py

[BUG] use correct arguments in `geometric_mean_absolute_error`

---

sktime/benchmarking/tests/test_orchestration.py

This speeds up the `test_stat` benchmarking test from 60s to in the order of seconds, by using a smaller dataset.
Related to: https://github.com/sktime/sktime/issues/2890

[MNT] speed up `test_stat` benchmarking test

---

sktime/forecasting/compose/tests/test_reduce_global.py
sktime/forecasting/model_evaluation/tests/test_evaluate.py
sktime/forecasting/tests/test_interval_wrappers.py

This speeds up various tests by reducing the number of data points or folds:
* `test_reduce_global`
* `test_evaluate_hierarchical`
* `test_evaluate_with_window_splitters`
Related to: https://github.com/sktime/sktime/issues/2890

[MNT] speed up various tests in the forecasting module
