sktime/forecasting/reconcile.py, sktime/utils/_testing/hierarchical.py
This PR:
* adds a length option to `_bottom_hier_datagen` hierarchical data generator, allowing to generate much smaller data sets
* speeds up the `ReconcilerForecaster` doctest by using this option, to generate a much smaller data set in the doctest
Due to the test speed-up, related to https://github.com/sktime/sktime/issues/2890
=> [ENH] add length option to `_bottom_hier_datagen` hierarchical data generator, speed up `ReconcilerForecaster` doctest

sktime/utils/tests/test_check_estimator.py
This speeds up the `check_estimator` tests by replacing the computationally expensive `MockForecaster` (probably due to printing and logging?) with the very quick `ForecastKnownValues` dummy, the oracle forecaster.
Related to: https://github.com/sktime/sktime/issues/2890
This should not change test coverage, as it is `check_estimator` which is tested, so any forecaster with maximal capabilities (such as `ForecastKnownValues`) should be fine.
=> [MNT] speed up basic `check_estimator` tests

sktime/classification/distance_based/_elastic_ensemble.py
This PR speeds up tests by skipping the costly, redundant `ElasticEnsemble` classifier doctest.
The doctest is redundant with the basic fit/predict interface contract test in `TestAllClassifiers`, but costs 10-20s of test time.
=> [MNT] speed up costly redundant `ElasticEnsemble` classifier doctest

sktime/transformations/series/adapt.py
This PR extends `TabularToSeriesAdaptor` so it is compatible with feature selectors such as `SelectKBest` or `VarianceThreshold`, and allows passing of `y`.
Addresses feature request in https://github.com/sktime/sktime/discussions/4967.
* the default behaviour for an inner estimator that requiesa `y` in `fit` (i.e., having a defaultless named argument `y`) is to pass on any `y` seen in `fit`, and only pass `X` otherwise (i.e., if the inner estimator does not have an arg `y`, or one with a default); and, never passing `y` to `transform`.
* the behaviour can be modified by the new `pass_y` argument to pass never, always (including to `transform`), or to `fit` (covering the case where `y` can be passed but is not a named argument)
No deprecation is needed as far as I see, because the …
=> [ENH] enable use of `TabularToSeriesAdaptor` with feature selectors, and passing of `y`

sktime/transformations/series/difference.py, sktime/transformations/series/tests/test_differencer.py
This fixes an unreported bug in `Differencer._inverse_transform` for integer index.
In `_inverse_transform`, `Differencer` would call the `shift` method of the index which is not defined for integer based index - this should have used the internal `_shift` method.
The tests did not catch this as all tests were datetime-index based.
This has now been rectified.
=> [ENH] fix `Differencer` for integer index

sktime/transformations/series/difference.py, sktime/transformations/series/tests/test_differencer.py
Set first lag values to nan if it has the same index as the train time series. This should fix the strange results in inverse_transform of the Differencer if fill_zero is set.
Fixes #4993 and fixes #4965.
Regarding both issues, I am not sure if there are additional problems... 
The fix sets the first lag values of the input time series to nan if the index aligns with the index of the train time series. Thus, the  combine_first operation will set it to the values of the original time series and cumsum reproduces the original time series.
No
* Is the solution understandable and maintainable or looks it like black magic.
* Regarding both linked issues, are they solved with this single bugfix or are additional problems there.. Currently, I am not sure about it. 
I added a test for reproducing …
=> &MCRE-BE [BUG] Fix `Differencer.inverse_transform` on train data if `na_handling=fill_zero`

sktime/forecasting/model_selection/_tune.py
This PR fixes #5020 by improving the description of the `scoring` parameter in the tuning forecasters in `forecasting.model_selection._tune`.
=> [DOC] improve description of `scoring` in docstrings of tuning forecasters such as `ForecastingGridSearchCV`

sktime/forecasting/base/adapters/_generalised_statsforecast.py
This PR changes the `StatsForecastBackAdapter` to ensure it is not affected by the change of `predict_interval` return format.
This is done by simply dropping the first column index level, which should therefore avoid any impact of the default change.
Note to @yarnabrina, @luca-miniati - it sems the adapter assumes a univariate forecaster. Is this intentional, and is this sufficient?
=> [ENH] ensure robustness of `StatsForecastBackAdapter` w.r.t. change of `predict_interval` return format

sktime/utils/_testing/tests/test_testscenarios.py
This PR reames one of the test class mocks, `TestedMockClass`, to `MockTestedClass`.
The reason is that `pytest` test collection tries to collect all classes whose names commence with `Test`, expecting to find tests there. But `TestedMockClass` is not a test, so it should be renamed.
=> [MNT] rename `TestedMockClass` to `MockTestedClass`

sktime/tests/test_all_estimators.py
Mirror of `skbase` https://github.com/sktime/skbase/pull/212
This PR removes the `sklearn` dependency in `get_test_params`, by replacing `_check_get_params_invariance` with an `skbase`-native implementation.
The call to `clone` is replaced with the object's one `clone`method.
Related: https://github.com/sktime/sktime/pull/2903 which needs a custom `clone` to function (due to a serialized estimator being a parameter).
=> [ENH] remove `sklearn` dependency in `test_get_params`

sktime/utils/_testing/deep_equals.py
This PR speeds `deep_equals` by string-coercion of pandas objects unless necessary using the idea of lazy evaluation. This is an alternative to #5028.
=> [MNT] Speed-up `deep_equals` - lazy evaluation of costly error message string coercions

sktime/base/adapters/__init__.py, sktime/base/adapters/_tslearn.py, sktime/clustering/base.py, sktime/clustering/kernel_k_means.py
This PR adds a generalized adapter for `tslearn` classifiers, clusterers, and regressors.
As a proof-of-concept and refactor test, the estimator with `tslearn` depndency is refactored to use the adapter.
On short-term, if this works as intended, this should allow to interface all of `tslearn` easily.
=> [ENH] generalized `tslearn` adapter and clusterer refactor

sktime/forecasting/model_selection/_split.py, sktime/registry/_tags.py
This PR introduces, for splitters (`BaseSplitter` descendants):
* an optional private `_split_loc` to implement, which can differ from the default of looking up `loc` from `iloc` indices
* a tag `split_series_uses`, which determines whether `split_series` dispatches to `split_loc` or `split` (iloc). This may be later extended to have splitters where only `split_series` exists, e.g., which are not just determined by rows
This PR also changes implementation of two splitters which in sum make the forecasting benchmark `evaluate` more performant:
* for the `SameLocSplitter`, `split_series` should dispatch to `split_loc` for performance gain.
* the `TestPlusTrainSplitter` should dispatch to the same as the wrapped, for performance gain.
An alternative approach to …
=> [ENH] private `split_loc` and tag to control dispatch of `split_series` to `split` vs `split_loc`

Makefile, setup.cfg
Fixes the duplication of the `pytest` `durations` parameter where `setup.cfg` would override the `durations` passed later on.
=> [MNT] fix duplication of `pytest` `durations` parameter in CI

sktime/forecasting/compose/_reduce.py
Fixes #5061 
Changes tag on YfromX to allow missing data in X
=> [ENH] allow `YfromX` to take missing data

.github/workflows/test.yml, conftest.py, setup.cfg, sktime/forecasting/statsforecast.py, sktime/tests/test_all_estimators.py, sktime/utils/git_diff.py
Experimental PR that ensures only estimators are tested that have changed compared to `main`.
The design relies on a new utility that checks changes to `main` using `subprocess` calling `git`.
How we know it works:
* The CI in this PR runs none of the suite tests for any of the estimators in `sktime`, since this PR does not change any of the relevant files.
* whereas, in this PR https://github.com/sktime/sktime/pull/5023 where two estimator modules have changed, it runs exactly the suite tests for the two estimators.
Also, this most likely gets us a good way towards https://github.com/sktime/sktime/issues/2890, at least when it comes to tests arising from the `TestAll` portion of the test framework.
=> &yarnabrina [MNT] testing only estimators from modules that have changed compared to `main`

docs/source/api_reference.rst, docs/source/api_reference/alignment.rst
Adds API reference for the time series alignment module.
Looks like this was missing (even though linked from README).
Towards https://github.com/sktime/sktime/issues/1634
=> [DOC] API reference for time series aligners

sktime/datatypes/_convert.py, sktime/datatypes/_series_as_panel/_convert.py, sktime/transformations/base.py
This PR speeds up `BaseTransformer` checks and conversion boilerplate:
* replacing some `convert_to` calls by more specific `convert` calls that ensure we do not repeat mtype checks
* specifying explicitly the needed metadata in an instance where all metadata was returned, to avoid costly metadata queries that are discarded
* refactoring `convert` and `convert_to`, moving logic that determines the target mtype into a separate function, and allowing `convert` to have `list` as `to_type`
* adding an option to `convert_to_scitype` to return the mtype of the converted-to output. This is passed as an input to `convert` in the `BaseTransformer` boilerplate to avoid checks to obtain this information.
=> [ENH] speed up `BaseTransformer` checks and conversion boilerplate

sktime/datasets/_data_io.py
This PR reworks the somewhat messy data loader module, and adds an ability to specify download mirrors for remote datasets.
This is towards https://github.com/sktime/sktime/issues/4754 but does create a framework for arbitrary data loader mirrors - I focused mainly on enabling the mirroring/fallback feature for existing loaders, rather than a framework level refactor.
A refactor would also include the forecasting data loader and factor out more of the repetitive code in functions.
FYI @achieveordie, @hazrulakmal, as you have both recently worked on this module.
In terms of addressing #4754, it should now be easy to add an arbitrary number of mirrors to prevent a blowout failure to users if the UEA data repository decides to abruptly change folder structure again without deprecation or …
=> [ENH] rework data loader module, ability to specify download mirrors

sktime/transformations/series/lag.py, sktime/transformations/series/tests/test_lag.py
Fixes an unreported bug: due to a confusion between strings `"shift"` and `"shifted"`, the `Lag` transformer would run incorrect logic for `index_out="shift"`.
This has been rectified, and the test has been sharpened to check for this.
=> [BUG] fix wrong logic for `index_out="shift"` in `Lag` transformer

.all-contributorsrc, docs/source/api_reference/transformations.rst, sktime/transformations/series/dropna.py, sktime/transformations/series/tests/test_dropna.py
Fixes #4977.
Implements a `DropNA` transformer that saves the dropped index/column names from `fit`.
No.
Any feedback is appreciated. This is mostly a thin wrapper around `pd.DataFrame.dropna`, accepting the arguments `axis`, `how`, and `thresh`, defaulting to `axis=0` and `how=any`. With univariate series, only `axis=0` will work. 
I am validating the inputs to some degree and I've extended the `thresh` argument to also accept a fraction of non-NA values (pandas only accepts counts). I've always found the pandas default of specifying the threshold in terms of non-NA values strange (as opposed to specifying NA values) , but I've left it as is to be consistent. Thoughts on this?
I've added a couple of tests for the functionality and to make sure the parameter validation works. I haven't …
=> [ENH] Add DropNA transformer

sktime/clustering/dbscan.py, sktime/dists_kernels/__init__.py, sktime/dists_kernels/algebra.py, sktime/dists_kernels/base/__init__.py, sktime/dists_kernels/base/_base.py, sktime/dists_kernels/compose.py, sktime/dists_kernels/compose_from_align.py, sktime/dists_kernels/compose_tab_to_panel.py, sktime/dists_kernels/dist_to_kern.py, sktime/dists_kernels/dtw.py, sktime/dists_kernels/dummy.py, sktime/dists_kernels/edit_dist.py, sktime/dists_kernels/indep.py, sktime/dists_kernels/scipy_dist.py, sktime/dists_kernels/signature_kernel.py, sktime/registry/_base_classes.py, sktime/registry/_tags.py, sktime/tests/test_all_estimators.py
This PR makes improvements to the distances/kernels module:
* addition of a tag `"pwtrafo_type"` to distances/kernels, which tells the user whether it is (mathematically) a distance or a kernel, in the ML sense
* moves the `_base` module into a `base` folder and updates references, to bring the module in line with all others
=> [ENH] distance/kernel tag, uniformize base module

sktime/base/_serialize.py, sktime/classification/compose/_pipeline.py, sktime/clustering/compose/_pipeline.py, sktime/dists_kernels/algebra.py, sktime/dists_kernels/compose_tab_to_panel.py, sktime/dists_kernels/dtw.py, sktime/dists_kernels/edit_dist.py, sktime/forecasting/auto_reg.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_column_ensemble.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/conformal.py, sktime/forecasting/dummy.py, sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_selection/_split.py, sktime/forecasting/model_selection/_tune.py, sktime/param_est/compose.py, sktime/param_est/plugin.py, sktime/param_est/seasonality.py, sktime/pipeline/_make_pipeline.py, sktime/regression/compose/_pipeline.py, sktime/transformations/compose/_pipeline.py, sktime/transformations/panel/channel_selection.py, sktime/transformations/series/date.py, sktime/transformations/series/holiday/_holidayfeats.py, sktime/transformations/series/kalman_filter.py, sktime/transformations/series/lag.py, sktime/transformations/series/summarize.py, sktime/transformations/series/time_since.py, sktime/utils/estimator_checks.py
Fixes #5013.
Adds empty lines to docstrings examples missing new lines before or after comments in examples sections.
=> [DOC] improves formatting of docstring examples

sktime/datatypes/_convert.py, sktime/datatypes/_series_as_panel/_convert.py, sktime/param_est/base.py, sktime/transformations/base.py
This PR speeds up the parameter fitter base class boilerplate by avoiding to carry out mtype checks twice.
This is achieved by replacing one instance of `convert_to` (which checks the mtype, redundant to `check_is_mtype`), by an equivalent instance of `convert`, using the mtype output of `check_is_mtype`.
Related:
https://github.com/sktime/sktime/discussions/5056
https://github.com/sktime/sktime/pull/5036
Depends on https://github.com/sktime/sktime/pull/5036 due to the changes to `convert` being common to both speed-ups.
=> [ENH] speed up parameter fitter base class boilerplate

sktime/performance_metrics/forecasting/_classes.py, sktime/performance_metrics/forecasting/probabilistic/_classes.py
This PR adds a second set of test parameters to those metrics classes that did not have these, but had non-reserved parameters that could be set to at least two values.
=> [ENH] metrics classes - add testing parameters

sktime/benchmarking/benchmarks.py, sktime/benchmarking/tests/test_forecasting.py
See #4873 
The current ForecastingBenchmark interface requires manually looping over multiple estimators to benchmark multiple models, as the add_estimator interface only accepts one estimator per call. This PR provides an option for users to add multiple models with a single add_estimator call while maintaining the existing interface. The interface for multiple models looks as follows:
```python
from sktime.benchmarking.forecasting import ForecastingBenchmark
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.arima import AutoARIMA
benchmark = ForecastingBenchmark()
models = [NaiveForecaster(), AutoARIMA()]
benchmark.add_estimator(models)
models ={"Arima-v1":AutoARIMA(),
"Naive-v1":NaiveForecaster()}
benchmark.add_estimator(models) …
```
=> [ENH] input checks for `BaseBenchmark`, allow `add_estimator` to accept multiple estimators

sktime/registry/_craft.py
This PR fixes an unreported bug in the `craft` utility, which incorrectly identified reserved expressions `True`, `False`, as class names as they were `UpperCamelCase`.
The fix simply hard codes an exclusion of reserved expressions `True`, `False`.
Afaik there are also no further reserved expressions which look like class names.
Tested indirectly in https://github.com/sktime/sktime/pull/5058 which initially failed due to an example that included `True`.
=> [BUG] in `craft`, fix false positive detection of `True`, `False` as class names

sktime/transformations/series/summarize.py
This PR adds an option to remember data in `SplitterSummarizer`.
This copies some logic from the similar functionality for the `Lag` transformer on which I was working, see PR https://github.com/sktime/sktime/pull/5035
FYI @BensHamza
=> [ENH] option to remember data in `SplitterSummarizer`

sktime/datatypes/_alignment/_registry.py, sktime/datatypes/_hierarchical/_registry.py, sktime/datatypes/_panel/_registry.py, sktime/datatypes/_proba/_registry.py, sktime/datatypes/_series/_registry.py, sktime/datatypes/_table/_registry.py, sktime/forecasting/conformal.py, sktime/forecasting/tests/test_conformal.py
This PR fixes #5092, i.e., the `ConformalIntervals` failure where the wrapped estimator supports hierarchical or panel mtypes.
As discussed in the issue, the failure condition was if the wrapped estimator supported a hierarchical mtype. As the tags were cloned and `ConformalIntervals` did not support hierarchical or panel mtypes, this led to failure.
This is fixed by no longer cloning the mtype tags, but letting all mtypes through.
This PR also cleans up the mtype lists exported from the `registry`, which - despite the name, weren't lists but `numpy.ndarray`-s. This would also cause problems if they were directly used in tags. This has been rectified, the objects are now lists (as the name claims and as the user would expect).
=> [BUG] fix `ConformalIntervals` failure if wrapped estimator supports hierarchical mtypes - restriction to Series

sktime/datatypes/_alignment/_registry.py, sktime/datatypes/_hierarchical/_registry.py, sktime/datatypes/_panel/_registry.py, sktime/datatypes/_proba/_registry.py, sktime/datatypes/_series/_registry.py, sktime/datatypes/_table/_registry.py, sktime/forecasting/conformal.py, sktime/forecasting/tests/test_conformal.py
This PR fixes #5092, i.e., the `ConformalIntervals` failure where the wrapped estimator supports hierarchical or panel mtypes.
As discussed in the issue, the failure condition was if the wrapped estimator supported a hierarchical mtype. As the tags were cloned and `ConformalIntervals` did not support hierarchical or panel mtypes, this led to failure.
This is fixed by adding vectorization functionality for panel and hierarchical scitypes.
This lets genuinely hierarchical predictions through, but does the conformal interval computation per individual instance.
Depends on https://github.com/sktime/sktime/pull/5091, which contains the test for #5092, and a clean-up of the `datatypes` registry.
=> [BUG] fix `ConformalIntervals` failure if wrapped estimator supports hierarchical mtypes - genuinely hierarchical

sktime/datatypes/_vectorize.py, sktime/forecasting/base/tests/test_base.py
Fixes #5108.
Similar to the fix in #4684, although `pandas` needs to be prevented from sorting columns in two places:
* in the `groupby` call in `items`
* in/after the `pivot` call in `vectorize_est`, same problem as #4684.
Adds a compact version of the failure case reported in https://github.com/sktime/sktime/issues/5108 as a test.
Further, removed the `statsmodels` dependency in the related column test by replacing a `statsmodels` dataset with an equivalent, randomly generated one (also with string, non-ordered columns).
=> [BUG] Fix `vectorize_est` returning jumbled rows for row vectorization, `pd.DataFrame` return, if row names were not lexicographically ordered

sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/naive.py, sktime/forecasting/vecm.py, sktime/transformations/series/date.py
This PR adds test parameters to some estimators, specifically to those in files touched by the 0.22.0 deprecation action, in order to make the incremental tests happy.
=> [ENH] add more test parameters to some estimators

docs/source/changelog.rst, sktime/tests/test_all_estimators.py
As the release workflow runs all tests, it fails with the estimators that do not have `get_test_params` returning 2 or more estimator sets.
To enable the 0.21.1 and 0.22.0 releases, we temporarily revert the addition to the `get_test_params` to test for 2 or more estimator sets.
=> [MNT] temporary skip `get_test_params` number check for 0.21.1 and 0.22.0 release

sktime/alignment/base.py, sktime/alignment/dtw_numba.py, sktime/alignment/edit_numba.py
This PR fixes a bug in the `numba` based aligners which were detected by the release action.
The bug was unreported, and causes `transform` to break at call, due to the `X_inner_mtype` tag and the handling of `X` in `transform` being inconsistent. This has now been rectified, assuming `numpy3D` in both tag and `_transform` logic.
Odd that we did not catch this earlier.
FYI @yarnabrina, any idea why the differential testing did not catch this?
=> [BUG] fix `numba` based aligners

.all-contributorsrc, sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py
#2890
Explicit prediction generation rather than via the NaiveForecaster/NaiveVariance to speed up testing
No
=> [MNT] speed up `test_probabilistic_metrics` by explicit fixture generation instead of using forecaster fit/predict

sktime/forecasting/model_selection/tests/test_tune.py, sktime/forecasting/tests/test_interval_wrappers.py, sktime/forecasting/tests/test_reconcile.py, sktime/transformations/tests/test_optionalpassthrough.py
This PR speeds up the non-suite test CI elements by making more costly tests conditional on change of the tested estimator:
* tests for forecaster tuning estimators
* probabilistic forecast interval wrappers
* `OptionalPassthrough`
* `ReconcilerForecaster`
=> [ENH] widen scope of change-conditional test execution

sktime/forecasting/base/tests/test_fh.py
This PR speeds up tests in `test_fh` by:
* making tests relying on costly estimators conditional on `run_test_for_class`
* adding copies of the same tests using `NaiveForecaster` to ensure coverage in unconditional runs
=> [ENH] speed up tests in `test_fh`

sktime/proba/t.py
Related to #4518
Add t-distribution to the `proba` subpackage.
No
Not yet.
=> [ENH] Student's t-distribution

sktime/forecasting/conformal.py
This fixes a potential exception caused by late passing of `fh` in `ConformalIntervals` in `predict`.
=> [BUG] fix check causing exception in `ConformalIntervals` in `_predict`

sktime/forecasting/base/_delegate.py
This PR fixes minor typos in docstrings in the `_DelegatedForecaster` module.
=> [DOC] minor docstring typo fixes in `_DelegatedForecaster` module

extension_templates/forecasting.py
This updates forecasting extension template on `predict_proba` - the body was still making reference to `tensorflow_probability`.
Also, details were added on the `index` and `columns` of the return.
=> [DOC] update forecasting extension template on `predict_proba`

sktime/datasets/tests/test_single_problem_loaders.py
This PR speeds up testing the forecastingdata downloads by checking availability only on a small random subset of datasets (size 5).
As the individual downloads cost 1-2 seconds, and there are dozens, this results in a speedup of 30-60sec per CI element without reducing coverage substantially.
=> [MNT] test forecastingdata downloads only on a small random subset

sktime/benchmarking/evaluation.py
This PR patches a call to `binomtest`, which is `binom_test`  on lower `scipy` versions, to ensure compatibility in a wide version range.
=> [MNT] lower dep bound compatibility patch - `binom_test`

sktime/transformations/series/tests/test_date.py
This PR fixes faulty dependency isolation of `DateTimeFeatures` tests, and adds a change-conditional run condition.
The soft dependency isolation was incomplete, as variables generated only if the soft dependency were present were used in unisolated parts, in the `pytest` decorator, which would make the test fail if dependencies are not satisfied.
Further, I think the entire ad-hoc fixture generation should move into `pytest` tests, but it is quite messy, as it seems to be inside a single, massive `pytest` decorator.
FYI @KishManani, do you see a quick way to change this?
=> [MNT] fix dependency isolation of `DateTimeFeatures` tests

sktime/forecasting/compose/tests/test_reduce_global.py
This PR moves the fixtures in `test_reduce_global` to `pytest` fixtures.
This minimizes test collection time and ensures that failures in the fixture generation code remain isolated.
=> [MNT] move fixtures in `test_reduce_global` to `pytest` fixtures

sktime/distances/tests/test_distance_correctness.py, sktime/distances/tests/test_numba_distance_parameters.py
This PR refactors some of the `numba` based distance tests to use `pytest` parametrization, and ensures that they are only executed conditional on change of the logic.
Also corrects the condition where this had previously been done, as the test distances are split across functions and classes.
To ensure the refactored tests run, see PR https://github.com/sktime/sktime/pull/5142 which removes the conditional execution, and executes always for this diagnostic purpose.
=> [ENH] refactor and add conditional execution to `numba` based distance tests

extension_templates/transformer.py, sktime/registry/_tags.py, sktime/transformations/base.py, sktime/transformations/tests/test_all_transformers.py
This PR adds a tag for inexact `inverse_transform`-s, i.e., transformers where `inverse_transform` is not assumed to be an exact inverse to `transform`.
This tag is then used to turn off the test for exact inversion, conditional on the tag being `False`.
An example of an inexact inverse would be recomposition in VMD (e.g., https://github.com/sktime/sktime/pull/5129), or more generally recomposition after decomposition that removes an error term.
=> [ENH] add tag for inexact `inverse_transform`-s

sktime/forecasting/model_selection/_tune.py, sktime/forecasting/model_selection/tests/test_tune.py
This PR introduces parameters to forecasting tuners such as `ForecastingGridSearchCV` to control whether parameters are tuned overall, or for instances or variables.
The current behaviour is retained for the default, which is tuning per variable and for all instances.
As this is somewhat inconsistent, this PR also starts a deprecation period with an end state where the default is a single parameter tuned for all instances and variables.
Fixes #5143, see there for a discussion why this is a (logic) bug - the solution is now to move to the most intuitive setting as a default, but leave the option to tune by instance or variable to an user, and expose this cleaerly in the docstrings.
Also extends the tests as follows:
* adds test cases where the multivariate case is tested
* adds checks for …
=> &SmirnGregHM [BUG] ensure forecasting tuners do not vectorize over columns (variables)

sktime/proba/tests/test_all_distrs.py
Minor improvement for the probability distribution suite tests - changes fixture names of method tests to include method name. Als see https://github.com/sktime/skpro/pull/24
=> [ENH] fixture names in probability distribution tests

sktime/utils/tests/test_datetime.py
`test_set_freq_hier` fails since `pandas 2.1.0` as the condition for the test - a `freq` is set to `none` - is not anymore established. This is due to a change in `pandas` that preserves this attribute more widely.
To ensure equivalent test coverage, the fix is to set the `freq` to `none` manually in the relevant case.
=> [ENH] fix `test_set_freq_hier` for `pandas 2.1.0`

sktime/proba/base.py, sktime/proba/normal.py, sktime/proba/t.py, sktime/proba/tests/test_base_default_methods.py, sktime/proba/tfp.py
Related issue [https://github.com/sktime/skpro/issues/21](https://github.com/sktime/skpro/issues/21)
Moves the `_get_bc_params` method from child distributions to the parent distribtion class, `BaseDistribution`.
No
This implementation is quite simple and doesn't use `_tags` and still means the child distributions have to call the `_get_bc_params` method.
Would you prefer the child distributions to not have to call the `_get_bc_params` method. This will mean putting the parameter names that need to broadcasted in `_tags` dictionary then writing the broadcasted parameters from `BaseDistribution`. Personally I think this is slightly over complicated although this approach follows the DRY principles more closely. I am open to intput here and happy to implement whatever is preferred.
Altered …
=> [ENH] Refactor of `BaseDistribution` and descendants - generalised distribution param broadcasting in base class

sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_selection/_tune.py
See #4652, #4281, and #5175
Using keywords instead of positional arguments when the grid search is calling fit, predict, ... to enable the grid search with the graphical pipeline.
No …
=> [ENH] Robustifying `ForecastingGridSearchCV` towards free kwarg methods in estimators, e.g., graphical pipeline

README.md, docs/source/installation.rst
This PR adds documentation in the two main installation instructions of the granular soft dependency sets introduced with
https://github.com/sktime/sktime/pull/5136
=> [DOC] installation instruction docs for learning task specific dependency sets

docs/source/api_reference/forecasting.rst
Fixes a minor typo in the forecaster API reference.
=> [DOC] fix typo in forecaster API reference

docs/source/conf.py
This PR adds an autoupdate for copyright range in `sphinx` docs, so it contains as latest always the current year rather than the word "current".
=> [MNT] autoupdate for copyright range in `sphinx` docs

sktime/pipeline/__init__.py, sktime/pipeline/pipeline.py
Fixes #5229.
`Pipeline` is now exported by `sktime.pipeline`.
FYI @benHeid - I would agree with the implicit issue that @ujohn33 has, `pipeline.pipeline.Pipeline` is unintuitive as a location...
=> [BUG] fix missing `Pipeline` export in `sktime.pipeline`

sktime/tests/_config.py, sktime/tests/test_all_estimators.py
This moves the `Pipeline` exception from `test_all_estimators` to test `_config`.
Aware that some lines are being tested until the exception, although to me that rather indicates that we may perhaps like to rewrite the test instead of excepting in the middle of it.
FYI @benHeid
=> [MNT] move `Pipeline` exception from `test_all_estimators` to test `_config`

.all-contributorsrc, sktime/forecasting/arch.py, sktime/forecasting/base/adapters/_generalised_statsforecast.py, sktime/forecasting/statsforecast.py
Fixes #5024 and #5207:
* Versions previous to v1.5.0 of `statsforecast` do not have the `level`
argument in the `predict` or `predict_in_sample` methods of the
forecasters.
* `statsforecast` removed the `parallel` argument in some estimator since v1.6.0
Details:
Now before calling `predict` or `predict_in_sample`  we make sure the methods contain the `level` argument otherwise we do not pass it.
To handle the `level` argument we will set tags dynamically at instantiation time to see if they are there in the methods `predict_in_sample` and `predict`. 
Also newer versions of `statsforecast` removed parameters that were available in previous versions. We will take care of it by throwing a warning if the user passes a keyword argument that is not supported by the current version of …
=> [ENH] make `statsforecast` adapter compatible with optional `predict` `level` arguments, and different init param sets

sktime/forecasting/trend.py
Fixes #4148
As per what the title says.
=> [DOC] Simple edits to make `STLForecaster` docstring render proprely

sktime/forecasting/compose/tests/test_reduce_global.py
Fixes missing `y_train` key in `y_dict` in tests for composite forecasters.
Related: https://github.com/sktime/sktime/pull/5253
=> [BUG] Fix missing `y_train` key in `y_dict` in tests for composite forecasters

conftest.py
This PR fixes the `conftest.py` docstrings which were missing two of the three `pytest` flags.
=> [DOC] fixing `conftest.py` docstrings

.github/workflows/test.yml
This reverts PR #5241 and addresses https://github.com/sktime/sktime/issues/5257
Strange that the PR CI passed originally, but now it fails everywhere.
=> [MNT] Revert " [Dependabot](deps): Bump codecov/codecov-action from 3 to 4

sktime/datasets/_data_io.py, sktime/datasets/tests/test_single_problem_loaders.py
This sets the mirrors for time series classification data loaders:
1. to the new URL of the UEA repository (the one that is constantly changing)
2. to the mirror URL on the sktime GitHub, as a backup
Testing of the download utility is re-enabled.
Related: #4754, https://github.com/sktime/sktime/pull/4749
=> [ENH] set mirrors for time series classification data loaders

docs/source/api_reference/classification.rst, pyproject.toml, sktime/classification/shapelet_based/__init__.py, sktime/classification/shapelet_based/_mrseql.py
Fixes #4296, adds back `MrSEQL` to `sktime`.
See discussion there regarding temporary removal and complications in soft dependency isolation which now should all be resolved.
=> [ENH] adding back `MrSEQL` to `sktime`

sktime/transformations/panel/tests/test_shapelet_transform.py
This adds an `xfail` to except sporadic failures in the `RandomShapeletTransform` exact output test.
=> [MNT] `xfail` sporadic failure in `RandomShapeletTransform` exact output test

sktime/transformations/series/vmd/_vmd.py, sktime/transformations/series/vmd/test_vmd.py
This adds @davelyttinen's original example in https://github.com/sktime/sktime/issues/5128 on using the `VmdTransformer` for decomposition, forecast, then recomposition as a docstring example in the transformer, and a test case in a new `vmd` specific test module.
We should have added this with the `VmdTransformer`, not sure why we didn't - but now that we're showing the example at pycon Prague it should be continuously tested.
=> [ENH] `VmdTransformer` add decompose-forecast-recompose as a docstring example and test

pyproject.toml
Adds a bound `numba<0.58` - currently `numba 0.58` causes failures.
=> [MNT] bound `numba<0.58`

sktime/forecasting/model_evaluation/_functions.py
This PR improves, in `model_evaluation.evaluate`, the error message when the fit fails on a fold, by adding a reference to the fold index and the cutoff.
=> [ENH] improve `evaluate` failure error message

sktime/utils/__init__.py
This PR adds exports of common utilities in `utils` module.
The selection aims at those that users or developers would frequently import.
=> [ENH] add exports of common utilities in `utils` module

sktime/transformations/series/impute.py, sktime/transformations/series/tests/test_imputer.py
This fixes #5284.
The reason that `y` was not passed is the `y_inner_mtype` tag which always said that internally `y` is not needed (or passed). However, `method="forecaster"` may require it as example #5284 shows, and this is a bug. The fix is setting the tag correctly, in this case.
Adds the failure case from #5284 as a test.
=> [BUG] in `Imputer`, fix `y` not being passed in `method="forecaster"`

sktime/transformations/series/detrend/_deseasonalize.py
This PR fixes https://github.com/sktime/sktime/issues/5247 by implementing a proper `inverse_transform` for `STLTransformer`. This is simply "sum up the components again", and makes it possible to use it in `TransformedTargetForecaster`, i.e., a signal decomposition forecaster with different forecaster per component.
Some minor changes to the transformer:
* `X_inner_mtype` is changed to `pd.DataFrame` for more consistent handling of one or multiple components
* `y_inner_mtype` is changed to `"None"` as `y` is not used internally
=> [ENH] add proper `inverse_transform` to `STLTransformer`

pyproject.toml, sktime/annotation/ggs.py, sktime/annotation/igts.py, sktime/annotation/tests/test_ggs.py, sktime/annotation/tests/test_igts.py
Closes #5290.
* Replaces `attrs` with `dataclasses` in the `igts` and `ggs` modules of the `annotation` module.
No, but it removes `attrs` as a dependency for the `annotation` module.
I would like feedback on the `get_params` methods for the `InformationGainSegmentation` and `GreedyGaussianSegmentation` classes. Using `attrs`, one can easily filter attributes where `init` is `False`. That is not so easy with `dataclasses` so I filtered the unwanted attributes manually. We could have tags in the `GSS` and `IGTS` classes called something like `__attributes_to_ignore__` which would be a list of attributes to ignore in the `get_params` methods. But, since the pattern used for `GGS` and `IGTS` is likely going to change soon, I didn't think it necessary to use the tags approach.
No, but I …
=> [ENH] Remove attrs dependency

sktime/split/tests/test_temporaltraintest.py
This PR adds tests for `temporal_train_test_split` expected outputs.
Curiously, it does not seem the function was previously covered by tests in the case `fh=None`.
=> [ENH] add tests for `temporal_train_test_split`

sktime/forecasting/tests/test_interval_wrappers.py
This PR manually links one test in `test_interval_wrappers` reliant on `evaluate` to changes in `evaluate`, i.e., that the respective test is run when code in `evaluate` changes.
This is to prevent a future occurrence of https://github.com/sktime/sktime/issues/5336, i.e., improvements to `evaluate`.
Optimally, the tests in `test_evaluate` would cover the case here, ut that does ot seem e the status quo.
=> [ENH] Link `test_interval_wrappers.py` to changes in `evaluate` for conditional testing

sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/tests/test_interval_wrappers.py
This PR ensures pre-existing syntax to pass `alpha` and `coverage` via metrics to `evaluate` works again, fixing https://github.com/sktime/sktime/issues/5336.
Not commenting here on whether the status quo is a good idea or not (I think it was cleaner to remove it, or is, in the long run), but such a change should not happen without deprecation.
FYI @hazrulakmal.
Question to the reviewers, especially @hazrulakmal: do we need to change the naming convention to something else to ensure we do not change the names - or their order - again, accidentally?
Depends on https://github.com/sktime/sktime/pull/5337, so this change should trigger the test that is failing on `main`.
=> &benheid [BUG] allow `alpha` and `coverage` to be passed again via metrics to `evaluate`

.github/workflows/test.yml
This PR simplifies the CI setup, by merging the windows CI step into the test matrix.
As a side effect, this removes the dependency on conda in the windows CI.
=> [MNT] simplified CI - merge windows CI step with test matrix

sktime/datatypes/_vectorize.py, sktime/datatypes/tests/test_vectorize.py
Part 1 of a sequence of PR to enable parallelization backends for any estimator that is hierarchical or multivariate via broadcast.
This adds the option to choose a `joblib` or `dask` based parallelization backend in `VectorizedDF.vectorize_est`, which is used to broadcast estimators across hierarchy levels or variables.
This PR also extends the test for `vectorize_est` to test the parallelization backends.
Part 2 then, later, needs to connect the parallelization to the relevant estimator base classes.
=> [ENH] `joblib` and `dask` backends in broadcasting of estimators in multivariate or hierarchical case - part 1, `VectorizedDF.vectorize_est`

sktime/datatypes/_vectorize.py, sktime/datatypes/tests/test_vectorize.py, sktime/forecasting/base/_base.py, sktime/forecasting/base/tests/test_base.py, sktime/transformations/base.py, sktime/transformations/tests/test_base.py
Part 2 of a sequence of PR to enable parallelization backends for any estimator that is hierarchical or multivariate via broadcast.
This PR adds the option to choose a `joblib` or `dask` based parallelization backend in forecaster and transformer base classes, which is used in case of hierarchical instance broadcasting or variable broadcasting.
This PR also adds tests for the backends in forecasters and transformers.
Depends on https://github.com/sktime/sktime/pull/5267 which introduces abstract parallelization in the brodcasting framework.
=> [ENH] `joblib` and `dask` backends in broadcasting of estimators in multivariate or hierarchical case - part 2, base class config

sktime/forecasting/trend/_stl_forecaster.py
Sets the tag to `False` if and only if at least one of the used forecaster has it as `False`, and `True` otherwise.
=> [BUG] fix `STLForecaster` tag `ignores-exogenous-X` to be correctly set for composites

doc-format, docs/source/developer_guide/continuous_integration.rst
Fixes #5308
This PR corrects the code block formatting for the `pre-commit install` command in the developer guide. The command was not properly formatted as a code block, which could cause confusion for readers. The command is now enclosed in a code block, making it clear that it's a command to be executed in the terminal.
=> [DOC] Correct code block formatting for pre-commit install command

sktime/dists_kernels/base/_delegate.py
Adds a delegator class for pairwise time series distances and kernels.
Tested indirectly through delegated distance in subsequent PR:
* https://github.com/sktime/sktime/pull/5348
* https://github.com/sktime/sktime/pull/5341
=> [ENH] delegator for pairwise time series distances and kernels

sktime/alignment/base.py
This adds a sensible default `_get_distance_matrix` for time series aligners as a default in `BaseAligner` - a 2x2 matrix with the distance off-diagonals. Users should override this when a multiple alignment is computed.
=> [ENH] sensible default `_get_distance_matrix` for time series aligners

sktime/tests/test_all_estimators.py, sktime/tests/test_switch.py
This PR widens the condition scope in incremental testing: estimators are now tested also if a module containing a parent class in `sktime` has changed, not only if the module containing the estimator itself has changed.
The test framework, with this change, would also discover issues like https://github.com/sktime/sktime/issues/5367, where changes are made to an adapter class.
This would also cover the case of a base class change, in this case all descendants are tested too.
=> [ENH] incremental testing to also test if any parent class in sktime has changed

sktime/alignment/dtw_numba.py
Fixes https://github.com/sktime/sktime/issues/5363 by replacing the list of `pd.Series` with a list of `pd.DataFrame`, which is a supported panel mtype.
=> [DOC] fix broken docstring example of `AlignerDtwNumba`

setup.cfg, sktime/forecasting/arch/_uarch.py, sktime/forecasting/tests/test_all_forecasters.py
Fixes #5349
Changes a if (check) condition in `_check_predict_proba` function of `sktime/forecasting/tests/test_all_forecasters.py` to preserve column name in univariate forecaster predictions.
Upon fixing this issue, `ARCH` doesn't require function `_predict_proba` as `BaseForecaster`'s `_predict_proba` is sufficient. Hence, removed that function.
A few tests are expecting name to be preserved even if it is `None`, [here](https://github.com/sktime/sktime/blob/12d2770c213382f1ee99bb05a03f19e7ab4cb5e6/sktime/utils/_testing/forecasting.py#L138). Thats why I didn't handle the `None` case separately. If the expected column name is `0` when original name is `None`, below code may be appropriate as recommended by @yarnabrina.
```
if isinstance(y_train, pd.Series) and y_train.name:
assert …
```
=> [BUG] Expected fix in `_check_predict_proba` #5349 

.all-contributorsrc, sktime/transformations/series/date.py, sktime/transformations/series/tests/test_date.py
Fixes #5155. 
This breaks apart the large if statement which creates the data objects for the tests into two classes consisting of pytest fixtures. These fixtures include the transformed data to be tested and the expected outputs.
N/A
Is the proposed reformatting an acceptable solution? In particular, the use of classes for storing the Multivariate and Univariate inputs and outputs.
N/A
N/A
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` …
=> [ENH] Refactor of `DateTimeFeatures` tests to `pytest` fixtures

pyproject.toml
Bumps the `numba` version bound to `<0.59`, allowing `0.58`.
This should be merged only if https://github.com/sktime/sktime/issues/5298 is resolved, or it will cause failures on `main`.
The tests are passing since no estimators are changed, instead the tests should be run on all estimator to ascertain compatibility.
=> [MNT] update numba requirement from <0.58,>=0.53 to >=0.53,<0.59""

sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_selection/_tune.py, sktime/forecasting/model_selection/tests/test_tune.py
0.24.0 release deprecations and change actions:
* in forecasting tuners, change of `tune_by_variable` default to `False`
* bump tracking todos
=> [MNT] 0.24.0 deprecations and change actions

.github/workflows/wheels.yml
This PR changes the release action back to an release after testing wheels.
This might be useful for changing the current workflow to one where all tests are run manually, or in CRON batches.
Reverts sktime/sktime#5265. Same as removing https://github.com/sktime/sktime/pull/5262 (was temporary)
=> Revert "[MNT] instant release action"

sktime/datasets/_single_problem_loaders.py, sktime/datasets/tests/test_single_problem_loaders.py
This PR adds an xfail to the UCR loader and the Monash loader - both retrieving benchmark data from the internet - in order to silence the sporadic failures described in bug reports #5460 and #5462.
Only a temporary measure, possibly also rectified by the CI refactor with a separate data testing element.
=> [MNT] xfail remote data loaders to silence sporadic failures

sktime/transformations/series/_clasp_numba.py
Fixes #5451.
Sometimes, the `exclusion_zone` array can contain indexes that are out of the range of `y_pred`. This causes a segmentation fault from numba when trying to access the elements of `y_pred` using `exclusion_zone`.
To fix this, any indexes that are outside the range of `y_pred` are removed from `exclusion_zone`.
No.
No, it doesn't look like there are any clasp specific tests in `sktime/transformations/series`? Should there be a test for this change?
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug …
=> [BUG] CLASP logic: remove indexes from exclusion zone that are out of range

sktime/transformations/panel/signature_based/tests/test_method.py
The test execution conditions for the estimator specific tests of `SignatureTransformer` were checking presence of `esig` rather than full environment compatibility.
This could lead to an unexpected test failure under the condition that `esig` was present but the more restrictive conditions required by `SignatureTransformer` were not satisfied.
This is fixed by checking the latter and not the former.
=> [BUG] fix test excepts for `SignatureTransformer`

CODEOWNERS, docs/source/api_reference/transformations.rst, sktime/transformations/series/scaledasinh.py
Implements the Hyperbolic Sine transformation and its inverse
Based on Ref. [1],  Hyperbolic sine transformation and its inverse can be useful in time series that exhibit spikes. ASinh transformation has two parameters known as "a" and "b" where “a” is the shift parameter and “b” is the scale parameter 
a = median(sample data)
b = median_abs_deviation(sample data) . 1.4826 [2] 
[1] Ziel F, Weron R. Day-ahead electricity price forecasting with high-dimensional structures: Univariate vs. multivariate modeling frameworks. Energy Economics. 2018 Feb 1;70:396-420.
[2] Uniejewski, B., Weron, R., Ziel, F., 2017. Variance stabilizing transformations for electricity spot price forecasting. IEEE Transactions on Power Systems, DOI: 10.1109/TPWRS.2017.2734563
No
Functionality of …
=> [ENH] Add Hyperbolic Sine transformation and its inverse (ScaledAsinhTransformer)

docs/source/api_reference/dists_kernels.rst, docs/source/api_reference/transformations.rst, sktime/dists_kernels/dtw/_dtw_tslearn.py, sktime/dists_kernels/signature_kernel.py
This PR makes some minor improvements to the API reference and fixes issues:
* making estimator mini-summaries consistent and meaningful
* removing `automodule` statements, as it would produce not a link but a confusing contextless abstract
=> [DOC] streamlining API reference, fixing minor issues

sktime/classification/deep_learning/mcdcnn.py
Fixes #4996
The fix is very simple.
The problem is that model.n_epochs is not passed to self.model_.fit in MCDCNNClassifier._fit (mcdcnn.py):
```
def _fit(self, X, y):
...
self.history = self.model_.fit(
X,
y_onehot,
epochs=self.n_epochs, **#<<<-----------------THIS LINS IS MISSING #**
batch_size=self.batch_size,
verbose=self.verbose,
callbacks=self.callbacks_,
)
return self
```
=> [BUG] fix missing epochs parameter in MCDCNNClassifier._fit (#4996)

sktime/split/base/_base_splitter.py
Adds a default implementation for `get_n_splits`, which simply calculates the splits and gets the length.
In consequence, fixes https://github.com/sktime/sktime/issues/5254.
I have also opened an issue for proper general testing of the issue that we are fixing here: https://github.com/sktime/sktime/issues/5411
=> [ENH] Sensible default for `BaseSplitter.get_n_splits`

sktime/transformations/series/detrend/mstl.py
This PR adds an inverse transform for the `MSTL` transformer, in line with the `STLTransformer`, which sums up any components from the decomposition.
Also updates the documentation, and in the process fixes https://github.com/sktime/sktime/issues/5454.
Regarding deprecation, the behaviour should be identical in all cases where no bug was present, i.e., identical indices seen in `fit` and `transform`.
=> [ENH] general inverse transform for `MSTL` transformer

sktime/forecasting/model_selection/_tune.py, sktime/forecasting/model_selection/tests/test_tune.py, sktime/utils/parallel.py
This PR adds parallel backend selection for forecasting tuners, using the `parallelize` utility module.
Towards https://github.com/sktime/sktime/issues/5380
Also makes the following changes:
* in tuners, deprecates some of the "backend parameters" for 0.26.0 in order to make the backend parameter interface consistent across the codebase.
* adds default fixtures for different parallel backend settings, also exported by the `utils.parallel` module
* tests that run the tuners with those parallelization settings
=> [ENH] parallel backend selection for forecasting tuners

sktime/utils/validation/_dependencies.py
This PR fixes a minor issue in one of the error messages in `_check_python_version`.
Example failure here: https://github.com/sktime/sktime/pull/5424#issuecomment-1774031258
=> [BUG] fix error message in `_check_python_version`

sktime/transformations/series/_clasp_numba.py
Closes #5476.
Sometimes the `ClaSPSegmentation` algorithm raises a value error in the `_compute_distances_iterative` method. This happens when `_compute_distances_iterative` attempts to use `np.argpartition` with a `kth` value which is larger than the length of the input array.
This PR checks if `k` is larger than the length of `dist` and if it is, it sets `k` to be the length of `dist` minus 1.
No.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the …
=> [BUG] in `ClaSPSegmentation`, deal with `k` when it is too large for `np.argpartition`

sktime/split/expandinggreedy.py
This PR addresses a `pandas` constructor deprecation message from `ExpandingGreedySplitter`, by explicitly specifying the `dtype` in the constructor.
=> [MNT] address `pandas` constructor deprecation message from `ExpandingGreedySplitter`

sktime/split/expandinggreedy.py
This PR adds logic to allow `float` `step_size` in `ExpandingGreedySplitter`.
Also makes minor changes:
* docstring formatting
* adds missing author credit for @davidgilbertson 
Questions for reviewers:
* I originally added this to help https://github.com/sktime/sktime/issues/5107, by later making `temporal_train_test_split` default to `ExpandingGreedySplitter` instances. Thi is no longer needed for #5107 though
* is there a more elegant algorithm for the fraction case along the lines of @davidgilbertson's neat algorithm for the integer case, perhaps @davidgilbertson can see this? Also, would you be fine with adding the `float` option?
Also FYI @BensHamza (splitters) and @hazrulakmal (for benchmarking and `temporal_train_test_split` connection).
=> [ENH] in `ExpandingGreedySplitter`, allow `float` `step_size`

sktime/forecasting/naive.py
This PR addresses warnings arising from testing `NaiveForecaster`, as sqrt-s of negative fh-indices are taken.
The reason for this was that the standard deviation formula was taking sqrt-s of the fh-index, so this is addressed by correcting the formula for in-sample values.
For this, the error term standard deviation is used with a multiplying factor of 1. This should be mathematically sensible, and finally silence the warning.
=> [ENH] in `NaiveForecaster`, add valid variance prediction for in-sample forecasts

sktime/utils/mlflow_sktime.py, sktime/utils/tests/test_mlflow_sktime_model_export.py, sktime/utils/validation/_dependencies.py
Fixes #5417
I believe the original `ModuleNotFoundError` message was not accurate for `mlflow` since the error it gave made it seem like `mlflow` can be installed in the soft-dependencies bundle. I've added a more accurate message that points the user to use `pip install sktime[mlflow]`. …
=> [ENH] in `mlflow` plugin, improve informativity of `ModuleNotFoundError` messages

sktime/forecasting/naive.py, sktime/transformations/series/impute.py, sktime/transformations/series/summarize.py
`pd.DataFrame.fillna` with `method` arg is deprecated and will be removed.
This PR addresses the deprecation by replacing `fillna` with `method` arg with suitable alternatives.
=> [MNT] address deprecation of `pd.DataFrame.fillna` with `method` arg

docs/source/api_reference/classification.rst, sktime/classification/deep_learning/__init__.py
Five deep learning classifiers were erroneously missing API reference entries and module exports.
This has been rectified.
=> [ENH] add missing exports and API reference entries for five deep learning classifiers

sktime/transformations/series/detrend/_deseasonalize.py
This PR updates the docstring of `STLTransformer` to correctly account for statements on inverse and pipelines.
See also discussion in https://github.com/sktime/sktime/issues/5454
=> [DOC] update docstring of `STLTransformer` to correct statements on inverse and pipelines

sktime/forecasting/compose/_reduce.py, sktime/forecasting/compose/tests/test_reduce_global.py
Fixes #5463  
Added
- the time zone info (if present) after the index range is calculated in `_get_shifted_window()` and `_predict_last_window()`
- a test for the bug
No
Yes
=> [BUG] fix predict function of `make reduction` (recursive, global) to work with tz aware data

sktime/utils/plotting.py, sktime/utils/tests/test_plotting.py
Fixes https://github.com/sktime/sktime/issues/5493.
The deeper reason was that the `plot_interval` logic seemed broken, it is unclear why it was working at all even in the case of 4 or more points. Possibly some fallback functionality in `numpy` which was kicking in, e.g., using the last indices if broadcast sizes do not match.
Also adds a test with the failure case from #5493.
=> [BUG] fix `plot_series` prediction interval plotting for 3 or less points in forecasting horizon

.github/workflows/test.yml, .github/workflows/validate_datasets.yml, .github/workflows/wheels.yml, Makefile, sktime/datasets/_single_problem_loaders.py, sktime/datasets/tests/test_datadownload.py, sktime/datasets/tests/test_single_problem_loaders.py
Replaces #5004
Depends on #5304
=> [MNT] Dataset downloader testing workflow

sktime/transformations/series/peak.py
This PR skips the downloader `load_solar` in doctests to avoid downloading data in doctests and keep download tests localized to the respective CI element.
See https://github.com/sktime/sktime/issues/5527#issuecomment-1793365055
=> [ENH] skip `load_solar` in doctests

Makefile
This PR excludes download tests the "no soft dependencies" CI element, as downloads are now tested in a regular cron.
Also prevents the current failure arising from
https://github.com/sktime/sktime/issues/5527
in PR CI.
=> [ENH] exclude downloads in "no soft dependencies" CI element

docs/source/api_reference/param_est.rst, sktime/param_est/stationarity/__init__.py, sktime/param_est/stationarity/_arch.py, sktime/param_est/stationarity/_statsmodels.py
Fixes some unreported issues with stationarity estimators:
* docstring issues, e.g., formatting, reference to wrong methods due to copy-paste error
* some estimators had the wrong sign, i.e., whether null or alternative meant stationarity. Instead of changing the docstring in those cases, I decided to fix the sign.
* renamed estimators from the `arch` package to avoid user assumption that the tests assume ARCH process. Instead, the docstring gives clear credit now.
Deprecation is not needed, as the affected estimators in the last point have not een released yet.
=> [ENH] fixed docstrings and signs for stationarity tests

sktime/transformations/series/fourier.py
Fixes #5512
See Issue #5512 for a description of the problem and the solution implemented in this PR.
For periodicity defined as a pandas period alias, a private method is added that takes the period alias and a datetime index, and returns per datetime the fraction of the period that has passed in the interval [0, 1).
No
All changed files :)
No
See here for …
=> [ENH] `FourierFeatures`: more period options - `pandas` period alias and from offset column

.github/workflows/wheels.yml
This PR simplifies the windows wheels test in the release workflow and brings it in line with the mac and linux workflows as much as possible.
Also avoids the `conda` error on python 3.12.
=> [MNT] in release workflow, simplify windows wheels test

sktime/classification/base.py, sktime/classification/tests/test_base.py, sktime/datatypes/__init__.py, sktime/datatypes/_check.py, sktime/datatypes/_panel/_check.py, sktime/regression/base.py, sktime/transformations/base.py
This PR improves error messages for input checks in base classes, an localizes the generation of informative error messages on how to improve and check inputs in the `datatypes` module.
In particular, this fixes https://github.com/sktime/sktime/issues/5506 by changing the error message generation to the improved logic.
Further changes:
* improved error mesages in forecasters, transformations
* `check_is_mtype` gets an option to return multiple error messages in same format as `check_is_scitype`, with a deprecation for this as the default if multiple `mtypes` to check against are passed.
=> [ENH] improved error messages for input checks in base classes

sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py
This PR adds a method `get_expected_pred_idx` to `ForecastingHorizon` which can be used to obtain the expected forecast index, including in the case of multi-index or multi-instance data.
This is the actual `pandas.Index` used for `pandas` based mtypes, or the "ideal" index if a non-`pandas` type is used.
=> [ENH] expected forecast prediction index utility in `ForecastingHorizon`

.github/workflows/test_all.yml, .github/workflows/test_base.yml, .github/workflows/test_code_quality.yml, .github/workflows/test_components.yml, .github/workflows/validate_datasets.yml, .github/workflows/validate_extras.yml
Related #5101, #5475
* this fixes the "lower coverage" issue by adding the `test_all` workflow, which tests everyting minus the module conditional tests and always runs
* now, if anything changes in `base`, it also runs all module jobs
=> [MNT] CI Modifications

sktime/forecasting/compose/tests/test_reduce_global.py
This PR fixes a faulty check for reduction forecasters' output, the current test checks against the wrong expectation.
As the test with the wrong expectation currently passes, this PR will cause it to fail.
The change in
https://github.com/sktime/sktime/pull/5539
should make it pass again.
The current state incorrectly expects `none` where the level name should e `"Period"`, in two places.
To keep coverage either way, one of the expcetation iss changed to the latter expectation `"Period"`, whereas in the other occurrence the data is changed to make the current expectation  `none` correct.
=> [ENH] fix index name check for reduction forecasters

sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py, sktime/forecasting/compose/_reduce.py
This PR refactors index generation in reducers to use the `ForecastingHorizon` method instead of custom functionality.
Also useful as a test for the former logic.
Depends on https://github.com/sktime/sktime/pull/5543 due to an incorrect test.
=> [ENH] refactor index generation in reducers to use `ForecastingHorizon` method

sktime/datatypes/_vectorize.py, sktime/forecasting/base/_base.py, sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_selection/_tune.py, sktime/transformations/base.py, sktime/utils/parallel.py
Adds support for custom `joblib` backends in the `sktime` unified parallelization interface. Fixes https://github.com/sktime/sktime/issues/5535.
It seems that using custom backends was previously possible via parameter passing, albeit not properly tested as a possibility.
This PR adds back the possibility via a `"joblib"` parallelization mechanism.
I would be thankful if you could suggest how to best test this, @smirngregHM - preferably without adding soft dependencies.
=> [ENH] support for custom `joblib` backends in parallelization

sktime/annotation/ggs.py
#5296 must be merged before this PR can.
Updates `GreedyGaussianSegmentation` to inherit from `BaseSerieAnnotator` following the `HMM` class as a guide.
No.
* Currently type check and conversion is done in the `_predict` method. It would be good to refactor this out into the `BaseSeriesAnnotator` class but I think that is a job for another PR.
* This PR makes no attempt to convert the `GGS` class to inherit from `BaseSeriesAnnotator` class. It would be good for this to be done but again I think this is a job for another PR.
No but I had to add the type conversions in the `_predict` method to get the `annotation` tests to pass locally.
This changes means that, similarly to the `HMM` class, the `fit` method has to be called before the `predict` method even though `fit` does not contain any …
=> [ENH] Change GGS to inherit from BaseSeriesAnnotator

sktime/alignment/utils/utils_align.py, sktime/classification/distance_based/_time_series_neighbors.py, sktime/datasets/tests/test_data_io.py, sktime/datasets/tests/test_readers_writers.py, sktime/datatypes/_check.py, sktime/datatypes/tests/test_check.py, sktime/datatypes/tests/test_utils.py, sktime/datatypes/tests/test_vectorize.py, sktime/forecasting/base/tests/test_base.py, sktime/forecasting/tests/test_all_forecasters.py, sktime/forecasting/tests/test_conformal.py, sktime/proba/tests/test_all_distrs.py, sktime/transformations/base.py, sktime/utils/_testing/tests/test_panel.py, sktime/utils/validation/forecasting.py
Fixes non reported warnings that are internally created due to missing parameters in call of `check_is_mtype`.
**Note** set the parameter to the old default that is working. Please prove if the `dict` argument is better. …
=> [MNT] set output format parameter in `sktime` internal `check_is_mtype` calls to silence deprecation warnings

sktime/datatypes/_panel/_examples.py
This PR makes the outputs of conversions of `pandas` based mtypes stricter with respect to their index types.
Apparently, on some OS/version combinations, index types can differ slightly, e.g., a `pd.Index` of integer elements not automatically being a `pd.RangeIndex`.
Changes:
* some examples have `pd.Index` subtypes changed so `pd.RangeIndex` is guaranteed throughout version and OS combinations.
Test coverage is in https://github.com/sktime/sktime/pull/5560.
=> [ENH] Uniformization of `pandas` index types in mtypes, of all versions

sktime/datatypes/_panel/_examples.py, sktime/utils/_testing/deep_equals.py
This PR improves error messaging in `deep_equals` and makes checks on `pandas` based indices stricter.
Changes:
* `dtypes` of `pd.DataFrame`-s are now checked explicitly
* providing a clearer return on `pd.DataFrame` `dtypes` no being equal
* `pd.Index` `dtypes` are now checked explicitly
* index equality check is slightly relaxed. `DataFrame.equals` may consider `MultiIndex` as unequal due to irrelevant typing in some `python` versions, so instead we now explicitly check equality in names, values
This should help diagnose the `dask` inconsistency in `VectorizedDF.reconstruct` return, I suspect it is the `dtype`.
Example of test failure (only on certain python versions) here: https://github.com/sktime/sktime/pull/5552
(update: this was due to `MultiIndex` type ambiguity, with the …
=> [ENH] `deep_equals` - clearer return on diffs from `dtypes` and `index`, relaxation of `MultiIndex` equality check

sktime/forecasting/conformal.py
Fixes #5569 
This PR is using a sparse matrix representation instead of directly a dataframe in `ConformalIntervals` to save the residuals. 
No
No
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorith …
=> [ENN] Improve memory efficiency of `ConformalIntervals` using sparse matrices

sktime/benchmarking/evaluation.py, sktime/benchmarking/tests/test_orchestration.py, sktime/datatypes/_panel/_convert.py, sktime/datatypes/_utilities.py, sktime/datatypes/tests/test_panel_converters.py, sktime/datatypes/tests/test_vectorize.py, sktime/forecasting/compose/tests/test_pipeline.py, sktime/forecasting/tests/test_naive.py, sktime/proba/base.py, sktime/transformations/compose/_ixtox.py, sktime/transformations/panel/interpolate.py, sktime/transformations/panel/padder.py, sktime/transformations/panel/reduce.py, sktime/transformations/panel/summarize/_extract.py, sktime/transformations/series/impute.py, sktime/transformations/series/outlier_detection.py, sktime/utils/pandas.py
This PR addresses various deprecation warnings from `pandas`:
* deprecation of integer `__getitem__` based `iloc` access of `DataFrame`, `Series`
* deprecation of `GroupBy.agg` with function arg
* deprecation of `applymap` methods
* deprecation of imputation `method` arg in favour of `ffill`, `bfill` methods
* deprecation of `is_period_dtype`
The changes should be downwards compatible due to historical duplication of functionality in `pandas`, except for:
* the change of `applymap` to `map` breaks below 2.1.0. For this reason, an adapter utility has been introduced which keeps downwards compatibility.
=> [MNT] addressing various `pandas` related deprecations

sktime/forecasting/conformal.py
Reverts sktime/sktime#5570
I found a bug introduced by this PR. Scipy sparse matrices' default value is zero and not none.  In Line 209, we are fetching the residuals of our residuals matrix and consider only values that are not Nan `resids = resids[~np.isnan(resids)]`. Due to the PR, the default values are not filtered anymore, and we are considering the zeros as normal residuals. This leads to too sharp intervals. 
I think the problem occurs if `sample_freq` is set in a way that not for all time steps a forecast is made. 
I see three possible fixes:
* Revert the PR
* Consider the zero as default value and filter for zeros. However, zero may also be a valid value. Thus, I think this would introduce an additional bug. 
* We store for which values residuals are calculated. Thus, we need …
=> Revert "[ENN] Improve memory efficiency of `ConformalIntervals` using sparse matrices"

sktime/forecasting/base/adapters/_fbprophet.py
This makes a minor change to code introduced in #5597 that prevents breakeage if `self.fit_kwargs` are not available in a descendant of the `_ProphetAdapter`, such as in the piecewise linear trend forecaster, in https://github.com/sktime/sktime/pull/5592
=> [ENH] `prophet` adapter - safer handling of `fit_kwargs`

sktime/transformations/series/func_transform.py
Relates to #5630
Small adjustment to `FunctionTransformer`'s docstring, related to changed made in #5630
dependency isolation, see …
=> [DOC] Adjust `FunctionTransformer`'s docstring

sktime/utils/tests/test_mlflow_sktime_model_export.py
`pytest.mark.skipif` supports specification of `reason`, and it was specified as `reaons` as a typo here:
https://github.com/sktime/sktime/blob/99a80dec85232817e2ff67b58a1165bdd0313bef/sktime/utils/tests/test_mlflow_sktime_model_export.py#L98
Ref. https://docs.pytest.org/en/stable/how-to/skipping.html#id1
=> [BUG] fixed typo in `pytest.mark.skipif`

sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py
Fixes https://github.com/sktime/sktime/issues/5584.
`tz` information can be lost in an intermediate step where the index is coerced to period.
The fix is to restore it later, in this case.
=> [ENH] fix loss of time zone attribute in `ForecastingHorizon.to_absolute`

sktime/transformations/panel/tsfresh.py
Adds a second test parameter set for `TSFreshRelevantFeatureExtractor`
Towards https://github.com/sktime/sktime/issues/3429
=> [ENH] second test parameter set for `TSFreshRelevantFeatureExtractor`

.all-contributorsrc, sktime/transformations/panel/tsfresh.py
Fixes the argument nomenclatutre mismatch that interfaces `sktime` with `tsfresh` that enables profiling ([`TSFreshFeatureExtractor`](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.transformations.panel.tsfresh.TSFreshFeatureExtractor.html)). Current fix keeps compatibility does not alter `sktime` signatures.
No
Functionality (enabling profiling and storing the profiling file) and backwards compatibility (no alterations in signatures for the `TSFreshFeatureExtractor` class.
No
No
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or …
=> [BUG] `TsFreshFeatureExtractor` - correct wrong forwarded parameter name `profiling`

sktime/classification/interval_based/_stsf.py, sktime/classification/interval_based/_tsf.py, sktime/param_est/stationarity/_arch.py
Towards #5643
Note: this does not handle the fact that `np.array` is not a type, and `np.ndarray` is. This is not changed as it is mentioned that way here, and may have recursive effects elsewhere:
https://github.com/sktime/sktime/blob/b999b1048e516de497dfd7dddec1e375b0139152/sktime/registry/_tags.py#L161
(and L138 as well)
=> [BUG] Fix typos in mtype tags `np.ndarray`, from erroneous `nd.array`

sktime/utils/plotting.py
fixes #5635 
Ensure that `plt.subfigures` is only called once and only if no ax is provided. 
No
=> [BUG] Fix multiple figures created by `plot_windows`

sktime/forecasting/compose/_reduce.py
Fixes and copmletes the docstring of the `YfromX` forecaster reducer:
* adds use of `skpro` forecasters as well-documented case
* fixes indentation and code font issues
=> [DOC] fix and complete `YfromX` docstring

sktime/datatypes/_adapter/dask_to_pd.py, sktime/datatypes/_examples.py, sktime/datatypes/_hierarchical/_check.py, sktime/datatypes/_hierarchical/_examples.py, sktime/datatypes/_panel/_check.py, sktime/datatypes/_panel/_examples.py, sktime/datatypes/_series/_check.py, sktime/datatypes/_series/_examples.py, sktime/datatypes/tests/test_check.py
This PR adds `n_features` and `feature_names` metadat field for time series mtypes - similar to the attributes of the same name in `sklearn`.
This will be useful for cleaner input/output queriability in a variety of places, and further `sklearn` compatibility.
Also makes following changes:
* docstring formatting in `get_examples`
* extends test `test_check_metadata_inference` to allow specification of keys not checked if mtype is lossy.
=> [ENH] `n_features` and `feature_names` metadata field for time series mtypes

examples/AA_datatypes_and_datasets.ipynb
This PR fixes a typo in the `AA_datatypes_and_datasets.ipynb` panel data loading example - the `set_index` call had the instance and time lable in the wrong sequence.
=> [DOC] fix typo in `AA_datatypes_and_datasets.ipynb` panel data loading example

sktime/registry/_scitype.py, sktime/registry/tests/test_scitype.py, sktime/registry/tests/test_tags.py
This PR fixes an unreported bug where `registry.scitype` would return strings even if `coerce_to_list=True`.
To ensure future coverage, a test is also added.
=> [BUG] fix `scitype` `coerce_to_list` parameter, add test coverage

sktime/forecasting/compose/__init__.py, sktime/forecasting/compose/_reduce.py
This PR adds `DirectReductionForecaster` as an export to `compose`, ensuring regular testing
The typo fix in the class' module ensures the test is also triggered by the diff testing.
Same as https://github.com/sktime/sktime/pull/5581 without refactor, as an intermediate step, or for testing and diagnostics.
=> [ENH] export and test `DirectReductionForecaster`

sktime/transformations/panel/rocket/_minirocket.py, sktime/transformations/panel/rocket/_minirocket_multivariate.py, sktime/transformations/panel/rocket/_minirocket_multivariate_variable.py, sktime/transformations/panel/rocket/_multirocket.py, sktime/transformations/panel/rocket/_multirocket_multivariate.py, sktime/transformations/panel/rocket/_rocket.py
Fixes https://github.com/sktime/sktime/issues/5606, by adding an explanation to the documentation on how fitted parameters of instances in fit and predict are linked.
=> [DOC] add explanation about fit/transform instance linking behaviour of rocket transformers

sktime/transformations/compose/_pipeline.py, sktime/transformations/tests/test_compose.py
Fixes https://github.com/sktime/sktime/issues/5624.
The output tag would not be correctly inferred if a series-to-panel transformer is followed by series-to-series.
This has been corrected.
Unfortunately, the solution is somewhat involved. I think this hints that we may want to incode the input/output type information differently, using number of dimensions or similar.
=> [ENH] Correct inference of `TransformerPipeline` output type tag

sktime/registry/_scitype.py, sktime/registry/tests/test_scitype.py, sktime/registry/tests/test_tags.py, sktime/tests/test_class_register.py, sktime/tests/test_switch.py, sktime/utils/estimator_checks.py
Currently, in the differential testing logic via `run_tests_for_class`, we do not cause a test to be run if the class has remained unchanged, but the covering test has changed.
To ensure we properly test changes in tests, I've extended the logic so suite tests for all estimators covered by them are always run if the test class itself changes.
Relies on https://github.com/sktime/sktime/pull/5574 for easy access to the test classes covering an estimator.
=> [ENH] conditional testing of objects - test if covering test class has changed

sktime/tests/test_all_estimators.py
This PR fixes two untracked issues:
* `test_multiprocessing_idempotent` would be skipped. A comment said that some issues were related to it, but there was no GitHub issue. This PR removes the skip, checking whether the problem is gone.
* `test_multiprocessing_idempotent` would also fail for forecasters with probabilistic capability, due to the output type not being comparable via the approx array comparison. The modified test now skips for `predict_proba` outputs.
The failures would also be thrown when using `check_estimator`, this was noticed by @benheid for `ConformalIntervals`.
=> [ENH] reactivate and fix `test_multiprocessing_idempotent`

sktime/registry/tests/test_lookup.py
This PR enables tag related registry tests for `splitter` and `clusterer` type, removing a skip from some time back where these objects did not have tags.
=> [ENH] enable tag related registry tests for `splitter` and `clusterer` type

sktime/registry/_scitype.py, sktime/registry/tests/test_scitype.py, sktime/registry/tests/test_tags.py, sktime/tests/test_class_register.py, sktime/tests/test_switch.py, sktime/utils/estimator_checks.py
This PR adds a test class register in the main `tests` folder, and refactors `check_estimator` test gathering to that central location.
This is in anticipation of:
* test gathering potentially across `python` packages, e.g., polymorphic pipelines with components across packages
* unified `check_estimator` interfaces across packages
* simplifying extension pattern when adding more scitypes
* logic for switching on tests for all affected estimators when test classes are changed
Depends on https://github.com/sktime/sktime/pull/5578 due to a bug in the `scitype` utility that needed to be fixed.
=> [ENH] test class register, refactor `check_estimator` test gathering to central location

sktime/split/__init__.py, sktime/split/cutoff.py, sktime/split/tests/test_cutoff.py
This PR adds a temporal splitter which is cutoff and forecasting horizon based, and anchors fh loc indices in a cutoff.
This may help with the `fit_predict` issue in https://github.com/sktime/sktime/pull/5562.
FYI @arnaujc91, @yarnabrina
=> [ENH] cutoff and forecasting horizon loc based splitter

sktime/forecasting/base/_base.py, sktime/forecasting/tests/test_all_forecasters.py
This PR adds an `X_pred` argument to `fit_predict`, which allows to pass different `X` to `predict`.
This should partially address https://github.com/sktime/sktime/issues/4839
=> [ENH] forecaster `fit_predict` with `X_pred` argument for `predict`

sktime/param_est/stationarity/_arch.py, sktime/registry/_tags.py
Fixes https://github.com/sktime/sktime/issues/5643,
related: https://github.com/sktime/sktime/pull/5645 - see discussion there on remaining locatios.
=> [BUG] consistent use of `np.ndarray` for mtype tags

sktime/forecasting/base/adapters/_statsmodels.py, sktime/forecasting/tests/test_exp_smoothing.py, sktime/forecasting/tests/test_theta.py
Fixes #5641 
Rather than convert to period just use the integer positions in `_StatsModelsAdapter`
No
=> [BUG] change index match to integer in `_StatsModelsAdapter` predict

sktime/tests/_config.py
Excepts two known failures from `test_multiprocessing_idempotent`, see #5658
=> [MNT] except known failing estimators from `test_multiprocessing_idempotent`

.github/workflows/wheels.yml
This PR changes the release action to an instant release.
Temporary until we have consolidated the release process so it is not delayed unduly by download failures or sporadic estimator fails.
Same as https://github.com/sktime/sktime/pull/5262 (was temporary)
=> [MNT] instant release action

docs/source/api_reference/transformations.rst, sktime/transformations/base.py, sktime/transformations/merger.py, sktime/transformations/tests/test_all_transformers.py
fixes #5350 
It implements a merger to create a single time series out of a panel. To enable it , it introduces Transformers that require Panels as input and transform them to Series. Thus the following adaption to base classes are needed:
* Determine the output scitype. Thus, in base.py `convert_output` an elif/else are added.
* In `_convert_output` of base.py, a check is added if the input conversion was executed based on incompatibilities to the scitype required by the algorithm or not. If due to incompatibilities, we assume that the output type of the algorithm should not be changed! Otherwise, we assume that this conversion is done because of the input data provided!
Moreover, the expected scitype for the tests is adapted to reflect the new kind of transformer!
No
* Is there a better …
=> [ENH] Add Merger Transformation

sktime/datatypes/_table/_check.py
This PR relaxes the `pandas` based `Table` mtype-s to also allow object `dtype`-s.
The reason for this is to allow programmatic support of type checking of `y` in time series classification and regression, and since the current implicitly defined interface supported object (e.g., string) `dtype`-s for classification outputs.
Also required for the multioutput extension in https://github.com/sktime/sktime/pull/5408.
=> [ENH] allow object `dtype`-s in `pandas` based `Table` mtype-s

sktime/forecasting/model_selection/__init__.py
This PR restores the old export location of `temporal_train_test_split`, in `forecasting.model_selection`.
This is following the rationale that it might be a popular import, therefore leaving the export as silent will prevent breakage in legacy code such as the blog post tested here: https://github.com/sktime/sktime/pull/5663
Also removes author credits from the respective `__init__` which are not accurate anymore since splitters moved to `split` (author credits moved there).
=> [MNT] restore old export location of `temporal_train_test_split`

sktime/forecasting/model_selection/__init__.py, sktime/split/slidingwindow.py
This PR restores the old export location of `ExpandingWindowSplitter` and `SlidingWindowSplitter`, in `forecasting.model_selection`.
This is following the rationale that it might be a popular import, therefore leaving the export as silent will prevent breakage in legacy code such as the blog post tested here: https://github.com/sktime/sktime/pull/5663
=> [MNT] restore old location to some splitters

sktime/transformations/base.py
Fixes https://github.com/sktime/sktime/issues/5606, by adding to the respective error message an explanation of:
* how fitted parameters of instances in fit and predict are linked
* how to use `FitInTransform` in TSC/TSR pipelines
This is in the base class, so it will show in all cases of instance-wise transformers that broadcast fit/transform, therefore also solving #5606 in a programmatic way.
=> [ENH] better explanation about fit/transform instance linking in instance-wise transformers in error messages, and pointer to common solution

pyproject.toml, sktime/classification/feature_based/_tsfresh_classifier.py
This fixes an unreported issue where internal feature columns in `TSFreshClassifier.predict` would sporadically be permuted.
This would result in an exception, or wrong predictions, depending on `sklearn` version.
=> [BUG] fix sporadic permutation of internal feature columns in `TSFreshClassifier.predict`

sktime/registry/_scitype.py, sktime/registry/tests/test_scitype.py
This PR fixes the `scitype` inteference utility for all combinations of `coerce_to_list`, `force_single_scitype`, and adds a generic test for the cases where the tag is a list (multiple/polymorphic), as well as when there is only one tag.
=> [BUG] fix scitype inference utility for all cases

README.md
This PR removes the outdated `sktime-dl` reference in `README.md`.
`sktime-dl` is superseded by `sktime` proper, since we introduced dependency management on the level of estimators.
Also, most, if not all, estimators from `sktime-dl` are obtainable via `sktime` directly.
Therefore, the reference is misleading and can be removed.
=> [ENH] remove outdated `sktime-dl` reference in `README.md`

sktime/transformations/tests/test_base.py
Bug https://github.com/sktime/skbase/issues/258 masked that the backend strings in transformer module's `test_base` were not updated with the backend interface deprecation: the string `"joblib"` should be `"multiprocessing"`.
This has been updated to reflect the correct backend strings.
The PR also adds `"dask"` as a tested backend, increasing coverage.
=> [BUG] fix backend strings in transformer `test_base`

docs/source/api_reference/forecasting.rst, docs/source/api_reference/transformations.rst
This PR adds the `ReducerTransform` and `DirectReductionForecaster` to the API reference, they were missing.
=> [DOC] add `ReducerTransform` and `DirectReductionForecaster` to API reference

sktime/forecasting/compose/_ensemble.py
Fixes https://github.com/sktime/sktime/issues/5701
Changes accommodate deprecation of `pandas.DataFrame.groupby(axis=1)` introduced in pandas 2.1.0. 
References: 
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html and https://github.com/pandas-dev/pandas/blob/d711b1d2ff9ee2c3faf0e118535d3d6218886a9d/pandas/core/frame.py#L9105-L9111
=> [MNT] changes pandas `groupby(axis=1)` in `EnsembleForecaster`

sktime/transformations/panel/rocket/_multirocket.py, sktime/transformations/panel/rocket/_multirocket_multivariate.py
The `__author__` field for `MultiRocket` and `MultiRocketMultivariate` was missing, hence authors would not be displayed in the estimator overview. This has been fixed (I took the authors from the `CODEOWNERS`).
FYI @ChangWeiTan @fstinner @angus924
=> [MNT] add missing `__author__` field for `MultiRocket` and `MultiRocketMultivariate`

sktime/classification/tests/test_all_classifiers.py
This PR fixes `test_multioutput` for genuinely multioutput classifiers.
The original test was missing a boolean negation on when to check vectorization.
=> [BUG] fix `test_multioutput` for genuinely multioutput classifiers

sktime/forecasting/model_selection/_tune.py
The type statement for the `forecaster` arguments in forecasting tuners was wrong, see discussion in https://github.com/sktime/sktime/discussions/5679.
This has been corrected, to correctly describe the status quo type expectation (forecaster interface compatible only, no sklearn regressors).
=> [DOC] correct type statement in forecasting tuner regarding `forecaster`

sktime/utils/_testing/deep_equals.py, sktime/utils/_testing/tests/test_deep_equals.py
This PR fixes an unreported bug where `deep_equals` would break on `np.array` with `dtype="object"`, this is due to the `equal_nan=True` setting in `np.array_equal` which will lead to an exception if dtype="object"`.
Also includes test cases covering this.
Required for https://github.com/sktime/sktime/pull/4596, as the TSC grid search will produce object typed arrays internally.
=> [BUG] fix `deep_equals` for `np.array` with `dtype="object"`

docs/source/api_reference/alignment.rst, docs/source/api_reference/param_est.rst, docs/source/api_reference/split.rst, sktime/param_est/stationarity/_statsmodels.py
This PR makes various minor improvements to the API reference docs:
* add missing reference to `all_estimators` in alignment
* fix broken link to `temporal_train_test_split` in the splitter docs
* remove superfluous line in preamble of parameter estimators list
* typo fixes
=> [DOC] various minor API reference improvements

sktime/utils/parallel.py
This PR fixes minor typos in an error message related to custom `joblib` backend selection.
=> [ENH] fixes for minor typos in error message related to custom `joblib` backend selection

sktime/performance_metrics/forecasting/probabilistic/_classes.py
This PR addresses the `DataFrame.groupby(axis=1)` deprecation in metric classes.
=> [ENH] addressing `DataFrame.groupby(axis=1)` deprecation in metric classes

sktime/base/_base.py, sktime/param_est/base.py
Relates to discussions had on #5630 
See https://github.com/sktime/sktime/pull/5630#discussion_r1429062635
dependency isolation, …
=> [ENH] Simplify `BaseEstimator._get_fitted_params()` and `BaseParamFitter` inheritance of that method

sktime/datatypes/_vectorize.py
This PR aims to decouple internal methods of `VectorizedDF` as much as possible from the internal data reference `self.X` and `self.X_multiindex`. Related to discussion in https://github.com/sktime/sktime/pull/5676
This is unfortunately not entirely possible, as the central `items` method needs access to data.
An open question is, how to reconcile this with a requirement that no data is present when pickling after `fit`.
=> [ENH] in `VectorizedDF`, partially decouple internal data store from methods

sktime/forecasting/base/tests/test_base.py, sktime/forecasting/model_selection/tests/test_tune.py, sktime/transformations/tests/test_base.py, sktime/utils/parallel.py
This PR refactors tests with parallelization backend fixtures to programmatic backend fixture lookup.
Where previously separate locations of backend fixtures were curated, they are now all pointed towards a single interface point, `sktime.utils.parallel._get_parallel_test_fixtures`.
=> [ENH] refactor tests with parallelization backend fixtures to programmatic backend fixture lookup

sktime/forecasting/model_selection/_tune.py
This PR improves clarity in describing `strategy="refit"` for forecasting tuners.
Inspired by discussion here: https://github.com/sktime/sktime/discussions/5704
=> [DOC] improve clarity in describing `strategy="refit"` in forecasting tuners' docstrings.

sktime/forecasting/base/_fh.py
This fixes an unreported bug where the `sort_time` argument of `ForecastingHorizon.get_expected_pred_idx` would behave erratically if th original time series was not sorted.
=> [BUG] fix `ForecastingHorizon.get_expected_pred_idx` `sort_time`

README.md, extension_templates/split.py, sktime/split/base/_base_splitter.py
This PR adds an extension template for time series splitters.
Minor additional changes:
* docstring formatting for splitters
* adding splitters as an object type in the table in the readme
=> [DOC] extension template for time series splitters

sktime/performance_metrics/forecasting/_classes.py, sktime/performance_metrics/forecasting/tests/test_metrics.py
Fixes https://github.com/sktime/sktime/issues/5715.
The issue with `sklearn` metrics is coming from their decorator which no longer allows inspection of admissible arguments via `python` native `sigature`.
Question for reviewers: is there an `sklearn` native way to inspect permissible signature, without reading private attriutes?
=> [BUG] Fix dynamic `make_forecasting_scorer` for newer `sklearn` metrics

docs/source/developer_guide/dependencies.rst
This updates the soft dependency handling guide for tests with current practice - which is class tag based depedency checking, as opposed to manually duplicating the soft dependency information.
=> [DOC] update soft dependency handling guide for tests with tag based dependency checking

sktime/datasets/_data_io.py, sktime/datasets/tests/test_data_io.py
Fixes #5591.
Ensures check_path is set as suggested by @fkiraly.
=> [BUG] fix `extract_path` arg in `sktime.datasets.load_UCR_UEA_dataset`

sktime/datatypes/tests/test_vectorize.py, sktime/forecasting/base/tests/test_base.py, sktime/forecasting/model_evaluation/tests/test_evaluate.py, sktime/utils/parallel.py
This PR continues refactoring locations where backend fixtures are used to retrieve them from the central location, `_get_parallel_test_fixtures`.
=> [ENH] further refactor parallelization backend test fixtures to use central location

sktime/forecasting/base/tests/test_base.py
This PR fixes an error on main arising from the parallelization backend test fixture refactor.
The tests did not pick it up due to the bug with `set_config` fixed in `scikit-base` 0.8.0, and `scikit-base` bound has not yet been upgraded on `main`.
=> [BUG] fix type error in parallelization backend test fixture refactor

sktime/forecasting/compose/_bagging.py
Fixes https://github.com/sktime/sktime/issues/5728 by removing the logic that copies `random_state` to components.
Also makes minor changes:
* docstring clarifications
* moving test-time-only imports into `get_test_params`
* internally, cloning now uses `scikit-base` `BaseObject.clone` instead of `sklearn` `clone`.
=> [BUG] in `BaggingForecaster`, fix `random_state` handling

CONTRIBUTORS.md
There have been multiple instances where new contributors accidentally updated `CONTRIBUTORS.md` instead of `all-contributorsrc` - since the former is auto-updated from the latter, this means their credit will be erased by accident if we do not catch this.
To reduce the risk of the same issue reoccurring, I added a comment at the top of `CONTRIBUTORS.md` that explains this.
=> [DOC] comment in `CONTRIBUTORS.md` that source file is `all-contributorsrc`

sktime/utils/_maint/_show_versions.py, sktime/utils/_maint/tests/test_show_versions.py
=> [BUG] handles `AttributeError` in `show_versions()` when dependency lacks `__version__`

sktime/forecasting/exp_smoothing.py
Skips failures in #5026 by removing test case triggering it - does not solve the bug.
Due to the bug, `ExponentialSmoothing`'s `.predict()` returns `NaN` sporadically, causing subsequent operations to fail since they expect finite values.
=> [BUG] skip sporadic test errors in `ExponentialSmoothing`

sktime/forecasting/trend/_polynomial_trend_forecaster.py, sktime/forecasting/trend/_trend_forecaster.py
This PR improves docstrings for `TrendForecaster` and `PolynomialTrendForecaster`:
* attributes listed
* explained type of `regressor_`
* formatting and typos
=> [DOC] improved docstring for `TrendForecaster` and `PolynomialTrendForecaster`

docs/source/get_involved/governance.rst
This PR updates the algorithm inclusion guide, changes are primarily of technical nature, due to last year's developments in dependency management on the level of estimators.
The decision making part is not changed.
Changes relate to:
* explaining that dependencies are managed on estimator level
* therefore additional options are available to power users, such as maintaining an estimator in a third party codebase. Dependency management within `sktime` is also more lenient due to depedency isolation.
* in consequence, first party companion packages like `sktime-dl` are no longer a primary means to manage soft dependencies, in first party code this is also addressed in the text. For third party code, no companion package is necessary either.
=> [DOC] updated algorithm inclusion guide

sktime/classification/interval_based/_tsf.py
Fixes https://github.com/sktime/sktime/issues/5740:
* corrects location for the configurable time series forest
* adds explanation on annother optionn, building the tsf from scratch
* formatting and typos
=> [DOC] improved docstring for `TimeSeriesForestClassifier`

sktime/forecasting/compose/tests/test_pipeline.py, sktime/transformations/base.py, sktime/transformations/series/feature_selection.py
This PR allows `BaseTransformer._transform` to return `None`, and adds a test that this plays well together with `ForecastingPipeline`.
The test case is the suggested example by @hliebert: https://github.com/sktime/sktime/discussions/5768#discussioncomment-8157485
=> &hliebert [ENH] allow `BaseTransformer._transform` to return `None`

sktime/transformations/series/summarize.py
This PR upgrades `SplitterSummarizer`, adding granular control of inner `fit`/`transform` input:
* add `fit_on` and `transform_on` argumennt that allows to specify the `X` that internally `fit` and `transform` are called on.
* deprecate `remember_data` - unintuitively named - in favour of the two new parameters. Deprecation is scheduled for 0.27.0.
=> [ENH] feature upgrade for `SplitterSummarizer` - granular control of inner `fit`/`transform` input

sktime/forecasting/model_evaluation/tests/test_evaluate.py
Fix `test_evaluate_error_score` to skip test of expected warning raised if the `joblib` backend is `"loky"` or `"multiprocessing"`. In these cases, no warnings are raised, this is a known issue: https://github.com/sktime/sktime/issues/5307
However, the change in the type of the `backend` test fixture has led to the skip having become ineffective. This PR restores the skip, and adds a skip for `"multiprocessing"`, which previously was not tested, but has the same problem.
=> [ENH] fix `test_evaluate_error_score` to skip test of expected warning raised if the `joblib` backend is `"loky"` or `"multiprocessing"`

.binder/Dockerfile
This changes the python version in the binder dockerfile to most recent 3.11.
Fixes https://github.com/sktime/sktime/issues/5761 - hopefully
=> [MNT] update python version in binder dockerfile to 3.11

docs/source/api_reference/transformations.rst
Fixes a consequential typo in the API reference - the scitype for transformers was wrong, at the top of the API reference page.
=> [DOC] fix `scitype` string of transformers in API ref

extension_templates/classification.py, extension_templates/clustering.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/forecasting.py, extension_templates/forecasting_simple.py, extension_templates/forecasting_supersimple.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py, extension_templates/transformer_simple.py, extension_templates/transformer_supersimple.py, sktime/base/_base.py, sktime/classification/base.py, sktime/clustering/base.py, sktime/dists_kernels/base/_base.py, sktime/forecasting/base/_base.py, sktime/param_est/base.py, sktime/performance_metrics/base/_base.py, sktime/proba/base.py, sktime/registry/_tags.py, sktime/regression/base.py, sktime/split/base/_base_splitter.py, sktime/transformations/base.py
Adds author and maintainer tags to registry and extension templates.
This implements, on the code base side, a proposal for the "tag based" approach discussed in issue https://github.com/sktime/sktime/issues/5746.
This also makes estimators directly searchable by author or maintainer.
However, none of the tags have currently been filled, this is pending discussion as it would be some work.
=> [ENH] author and maintainer tags

sktime/classification/distance_based/_shape_dtw.py, sktime/transformations/panel/dictionary_based/__init__.py, sktime/transformations/panel/dictionary_based/_paa.py, sktime/transformations/panel/dictionary_based/_sax.py, sktime/transformations/panel/dictionary_based/tests/test_paa.py, sktime/transformations/series/paa.py, sktime/transformations/series/sax.py
This PR adds instructions for a full rename/deprecation cycle for the new `SAX2` and `PAA2` transformers to replace `SAX` and `PAA` as primary implmentations. The new transformers are renamed to `SAX`, `PAA`, while the legacy implementations are renamed to `SAXlegacy`, `PAAlegacy`.
Implements https://github.com/sktime/sktime/issues/5778,
in detail:
* the future names are added as aliases to the current locations
* warning messages are displayed to any user constructing any of the estimators, with detailed change instructions. These messages can be turned off using `set_config`, as usual.
* this PR is released with 0.26.0
* at 0.27.0, the classes are renamed, and aliasing direction is switched. This will make the classes appear under their new names in `all_estimators` returns etc.
* at …
=> [MNT] change cycle for making `SAX2` and `PAA2` primary implementation renamed to `SAX`, `PAA`

docs/source/api_reference/forecasting.rst, sktime/forecasting/compose/__init__.py, sktime/forecasting/compose/_ignore_x.py, sktime/forecasting/compose/tests/test_ignorex.py
This PR adds `IgnoreX`, a forecasting compositor that allows a user to control whether exogenous data is ignored.
As indirectly requestd by @hliebert in https://github.com/sktime/sktime/discussions/5768
=> [ENH] forecasting compositor to ignore exogenous data

sktime/classification/deep_learning/base.py, sktime/classification/interval_based/_tsf.py
`sklearn 1.4.0` compatibility patches:
* address rename of `sparse` to `sparse_output` in `OneHotEncoder`
* `TimeSeriesForestClassifier` fix of breakage due to `sklearn` parent inspecting non-existent `self.criterion`
=> [ENH] `sklearn 1.4.0` compatibility patches

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/forecasting.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py, sktime/forecasting/base/_base.py, sktime/proba/base.py
This PR improves formatting of the tag section in extension templates, especially around the packaging header.
=> [DOC] improved formatting of tag section in extension templates

CODEOWNERS, docs/source/get_involved/governance.rst
This PR finishes the migration of algorithm author and maintainer information from `CODEOWNERS` to estimator tags.
As discussed in https://github.com/sktime/sktime/issues/5746, the information is also keyed more granularly, with `authors` tag keeping track of significant code contribution credits, while `maintainers` tracks the current active maintainer(s) according to the role specified in the governance doc.
The information previously present in `CODEOWNERS` has been moved completely to estimator tags, possibly reconciled with inconsistencies with `__authors__` attributes of the module, or commit history.
Barring accidental data entry error, the information should now be fully migrated via the following PR:
https://github.com/sktime/sktime/pull/5800 …
=> [MNT] remove maintainer information from `CODEOWNERS` in favour of estimator tags

sktime/performance_metrics/forecasting/_classes.py, sktime/performance_metrics/tests/test_metrics_classes.py
This PR adds the option to parallelize forecasting performance metrics via `set_config`.
The method is simply passing on the config to `vectorize_est`, if set.
Tests are added. Docstrings do not need to be added, as apprently the option is already inherited from `BaseObject` (mistakenly before this PR, but now correctly).
=> [ENH] parallelization support and config for forecasting performance metrics

pyproject.toml
This PR temorarily bounds `scikit-base<0.7.0` for the 0.25.1 release, to be reverted for 0.26.0.
This is in order to sync the MINOR bump of `scikit-base` with that of `sktime`.
=> [MNT] temporary bounding `scikit-base<0.7.0` (status quo 0.25.0) for 0.25.1 release

pyproject.toml
Update: I think the bugfixes in 0.7.0 are very localized but important, so I'll bump the bound for 0.25.1 after all.
---
Reverts sktime/sktime#5824, to be released with the 0.26.0 release, to ensure core dependencies bump minor version bounds in sync with `sktime` (to avoid downstream instability).
=> [MNT] revert temporary bounding of `scikit-base<0.7.0` to `scikit-base<0.8.0`

extension_templates/forecasting.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py
This PR adds missing documentation on PEP 440 format specification for the `python_dependencies` tag in some extension templates.
=> [DOC] add missing documentation on PEP 440 format specification for `python_dependencies` tag in extension templates

sktime/classification/deep_learning/rnn.py, sktime/classification/early_classification/_probability_threshold.py, sktime/datatypes/_check.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_selection/__init__.py, sktime/regression/deep_learning/rnn.py, sktime/utils/_testing/deep_equals.py, sktime/utils/deep_equals/__init__.py
Carries out deprecations and change actions scheduled for 0.26.0:
* finish deprecation of num_epochs inn RNN classifier and regressor
* in `check_is_mtype`, change default of `msg_return_dict` to `"dict"`
* in forecast benchmark `evaluate`, remove `kwargs`
* bump deprecation/change checks scheduled for 0.26.0 to 0.27.0
=> [MNT] 0.26.0 deprecations and change actions

sktime/forecasting/compose/_ignore_x.py
`IgnoreX` breaks even when wrapping forecasters that do not require `fh` in `.fit()`
No.
N/A
No.
Why is this the default behaviour in `BaseForecaster`?
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#alg …
=> [BUG] fix tag handling in `IgnoreX`

pyproject.toml
This PR bounds `moto<5.0.0` in `mlflow` tests to circumvent https://github.com/sktime/sktime/issues/5855
=> [MNT] bound `moto<5.0.0` in `mlflow` tests

pyproject.toml, sktime/utils/tests/test_mlflow_sktime_model_export.py
=> [MNT] [BUG] fix moto breaking change by using different mocking methods depending on version

sktime/registry/_scitype.py, sktime/transformations/base.py, sktime/transformations/bootstrap/_mbb.py, sktime/transformations/compose/_featureunion.py, sktime/transformations/tests/test_compose.py
This PR uniformizes coercion of `sklearn` transformers in transformation dunders across the codebase, syntactically and architecturally.
* coercion to `sktime` was missing in the `+` (`FeatureUnion`) dunder, while present in all others
* checks were too restrictive in some cases where the downstream code would have been able to coerce, dunder checks were relaxed to let `sklearn` estimators pass.
* `sktime` type checks were using inheritance rather than tags, which may be problematic for polymorphic estimators. This has been addressed by using the `scitype` utility rather than inheritance check.
A test has been added for coercion in the `+` (`FeatureUnion`) dunder, the remainder should be covered by current tests.
Also contains a minor fix in the test file: the test …
=> [ENH] in transformer dunders, uniformize coercion of `sklearn` transformers

sktime/benchmarking/evaluation.py, sktime/transformations/panel/catch22wrapper.py, sktime/transformations/panel/summarize/_extract.py, sktime/transformations/panel/tests/test_interpolate.py
This PR addresses some warnings from `pandas` deprecations:
* change in behaviour of `__getitem__` with `int`, replaced by `iloc` - this fixes https://github.com/sktime/sktime/issues/5881 amongst others
* change in behaviour when `pd.concat` is called on empty `pd.DataFrame`
=> [MNT] address some `pandas` deprecations

docs/source/changelog.rst, docs/source/developer_guide/deprecation.rst
This PR adds more details to the deprecation manual for simple pararmeter changes and deprecations, in the form of step-wise recipes.
This should help developers with spelling out the steps to carry out in detail.
=> [DOC] recipes for simple parameter change and deprecation management

sktime/utils/tests/test_mlflow_sktime_model_export.py
Fixes #5859
`mlflow` tests were missing the skip markers despite using estimators like `AutoARIMA` and `CNNClassifier` that have soft dependencies. I've added `pytest.mark.skipif` decorators on top of each fixture/test that make use of either of these estimators.
None
I'm not particularly fond of cases where I find myself copy-pasting any amount of code. I can appreciate the modularity such unit tests provide but I was wondering if we could instead use classes (one for mlflow-only test, mlflow-arima tests and mlflow-tensorflow tests).
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or …
=> [MNT] Skip `mlflow` tests when soft-dependencies are absent

sktime/forecasting/base/_base.py, sktime/transformations/base.py
This PR improves specificity of some error messages in forecasters and transformations:
* `BaseForecaster` input checks now concretely list non-compliances with allowed mtypes, and make a reference to the class name.
* `BaseTransformer` input checks now make reference to the class name (non-compliances were already listed).
* error message in `_most_complex_scitype` of `BaseForecaster` and ``BaseTransformer` now makes reference to class name and found scitypes.
=> [ENH] Improved specificity of some error messages in forecasters and transformations

docs/source/api_reference/transformations.rst
Fixes the dead link of DropNA in API reference (https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.transformations.series.dropna.DropNA.html)
=> [BUG] fixing broken link to `DropNA` in API reference

docs/source/api_reference/forecasting.rst, sktime/forecasting/bats.py, sktime/forecasting/statsforecast.py, sktime/forecasting/tbats.py
Towards #4643 
This PR adds an interface to the `AutoTBATS` model provided in `statsforecast`, and expose to users as `StatsForecastAutoTBATS`.
Other than that, it also updates outdated links for `StatsForecastAutoCES`, `StatsForecastAutoETS` and `StatsForecastAutoTBATS`.
=> [ENH] statsforecast AutoTBATS direct interface estimator

docs/source/api_reference/forecasting.rst, sktime/forecasting/arima/__init__.py, sktime/forecasting/arima/_pmdarima.py, sktime/forecasting/arima/_statsmodels.py, sktime/forecasting/statsmodels_arima.py
No issue created for this PR so far. We wanted to implement the `ARIMA` forecast from `statsmodels` library.
Implement `ARIMA` forecast from `statsmodels` library
No tests added besides the tests run for ALL forecasters. …
=> [ENH] interface to `ARIMA` from `statsmodels` library

docs/source/conf.py
This PR replaces the somewhat manual scraping of information in the current estimator overview table by use of estimator tags.
Minor change: also addresses `pandas` deprecation related to `pd.concat`.
=> [DOC] use tags for estimator overview

docs/source/api_reference/forecasting.rst
Fixes a broken link in the forecasting API ref: `ARDL`
=> [DOC] fix `ARDL` API reference

sktime/pipeline/pipeline.py, sktime/pipeline/step.py, sktime/pipeline/tests/regression_tests/test_pipeline_regression.py
Fix pipeline.predict if inner X are derrived by y by not emptying the buffer of the y dummy step.
Fixes #5830 
Avoid to empty the buffer if no new data is arriving during `predict` call. 
No …
=> [BUG] Empty dummy step's buffer only if new data arrive

sktime/forecasting/compose/_fallback.py, sktime/forecasting/compose/tests/test_fallback.py
Addresses: https://github.com/sktime/sktime/issues/5835
Gives `FallbackForecaster` the option of using `forecaster.predict_interval()` when all forecasters have this capability. Raises and exception if at least one forecaster does not have `predict_interval` enabled.
No
Yes
See …
=> [ENH] `FallbackForecaster` predict_interval

sktime/forecasting/base/_delegate.py, sktime/forecasting/compose/_grouped.py, sktime/forecasting/compose/_ignore_x.py, sktime/forecasting/compose/_multiplexer.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_selection/_tune.py, sktime/forecasting/stream/_update.py, sktime/param_est/plugin/_forecaster.py
This PR:
* cetralizes logic for safe cloning of delegator tags in `_DelegatedForecaster`, previously in a array of individual descendants
* excepts packaging tags such as `"authors"` and `"python_depedencies"` from cloning (this type of tag did not exist in its current form when most descendant logic was implemented originally)
The refactor ensures that the logic has to be updated only in one location.
From a design perspective, one might consider localizing `set_delegated_tags` in `_DelegatedForecaster.__init__` and call `super().__init__` after, however that has the danger of not being downwards compatible, since `_DelegatedForecaster` currently has no `__init__`.
Related discussion https://github.com/sktime/sktime/pull/5843 as brought up by @tpvasconcelos in the context of `IgnoreX` …
=> [ENH] centralize logic for safe clone of delegator tags - forecasting

docs/source/conf.py
This PR adds hyperlinks to the GitHub IDs in author and maintainer fields in the estimator table.
=> [DOC] add GitHub ID hyperlinks in estimator table

.github/workflows/test_all.yml
This PR fixes https://github.com/sktime/sktime/issues/5794, by simply disabling pre-commit tests.
The rational is, better a full test without pre-commit, than a completely useless test.
Once we find out how to execute `pre-commit` on parts of the repo, it is easy to add as part of `code_quality`.
Again, this interim solution is better than waiting for that uncertain day and only then start running CRON tests.
=> [MNT] fix failing CRON "test all" workflow

docs/source/developer_guide/deprecation.rst
This PR splits the current deprecation recipe example into two, and adds more details.
FYI @yarnabrina, I think your example was quite nice, but it combined two of the "base recipes" (changing default value, changing name), so is probably going to be confusing to a new developer. It is better if any examples match one of the recipes 1:1. I think it also was not entirely in line with the recipe (e.g., use of `None` vs string `"deprecated"`).
Ultimately, I split it into two 1:1 examples for the two base recipes that the current example was composed of.
Also fixes some indentation issues which made the recipes format strangely.
=> [DOC] improved deprecation recipes

.github/actions/test-base/action.yml, .github/actions/test-component/action.yml, .github/workflows/test.yml
Currently quite a few of our actions are outdated, and they are throwing lots of deprecation warnings.
These should have been updated by Dependabot, but they may have been overridden by merge changes. This PR updates them to latest versions.
=> [MNT] update versions of several actions

examples/AA_datatypes_and_datasets.ipynb
Reference Issues/PRs
Fixes issues #5878 
What does this implement/fix? Explain your changes.
I have addressed the typo in the structure convention. Instead of 'monotonous,' it now correctly states 'monotonic.' I made this adjustment in the section detailing the structure convention for time series objects, specifically in the line: 'obj.index must be monotonous, and one of... I have push just the correct file this time.
Does your contribution introduce a new dependency? If yes, which one?
No
What should a reviewer concentrate their feedback on?
Did you add any tests for the change?
no
Any other comments?
no
PR checklist
For new estimators
dependency isolation, see the [estimator dependencies guide]
=> [DOC] Typo in documentation, fixed monotonous to monotonic 

sktime/forecasting/compose/_fallback.py, sktime/forecasting/compose/tests/test_fallback.py
-Issue: https://github.com/sktime/sktime/issues/5897
-Additional discussion: https://github.com/sktime/sktime/pull/5847
We've introduced a `nan_predict_policy` within the `FallbackForecaster` class to handle NaN values in forecaster predictions. This policy defaults to "ignore" and can be set to "raise", which will actively check for NaN values in the prediction output and raise an exception if any are detected, or "warn", which will warn the user if any values are detected. This enhancement is aimed at improving the robustness and reliability of the forecasting process, especially when integrating transformations like BoxCox with ARIMA forecasters.
No new dependencies.
- Correctness of the NaN detection and exception raising mechanism.
- Adhering to existing `sktime` design standards.
- …
=> [ENH] Add nan policy handler for FallbackForecaster #5897

sktime/classification/distance_based/_time_series_neighbors.py, sktime/utils/profiling.py
This PR adds code to `KNeighborsTimeSeriesClassifier` that passes a callable to the internal sklearn estimator to avoid oom errors when precomputing the distance matrix, trading off memory efficiency with compute efficiency.
Adds the following algorithms - with test coverage - to `KNeighborsTimeSeriesClassifier`:
* `ball_tree`
* `brute_incr` - brute force, but distances are not all precomputed
These strategies also allow for unequal length time series given internal adapter encoding.
Removes `kd_tree` from the docstring which did not work previously, and cannot be interfaced, as `sklearn` does not allow this to be called together with a custom distance.
Potentially fixes https://github.com/sktime/sktime/issues/5914, and fixes #2774
=> [ENH] k-nearest neighbors classifier: support for non-brute algorithms and non-precomputed mode to improve memory efficiency

sktime/forecasting/model_selection/_tune.py
This PR moves `ForecastingSkoptSearchCV` to the abstract parallelization backend.
This resolves a dependent problem, where, due to inheritance on `BaseGridSerachCV`, the estimator prevents the deprecation action in 0.27.0 of removing the `n_jobs` argument.
=> [ENH] move `ForecastingSkoptSearchCV` to abstract parallelization backend

sktime/datatypes/_utilities.py, sktime/datatypes/tests/test_utils.py, sktime/forecasting/base/_base.py, sktime/forecasting/base/tests/test_base.py, sktime/forecasting/squaring_residuals.py, sktime/forecasting/tests/test_exp_smoothing.py
N/A
Found a bug when fitting panel-style models where the panels have a frequency attribute.
Changed the base (:/) to check fh only on the inner, non-vectorized, loop. Also, added a check, with the freq check turned off, when it is vectorized since when fh is supplied only in predict it seems to be written to self and expects something there in other tests
```python
from sktime.datasets import load_airline
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
import pandas as pd
ind = pd.date_range(
start="1960-01-01", periods=len(y.index), freq="H", name="datetime"
)
y = pd.DataFrame(y.values, index=ind, columns=["passengers"])
y = y.set_index([y.index.hour.rename("hour"), y.index]).sort_index()
assert y.loc[0].index.freq == pd.Timedelta("1D"), "Expected …
```
=> [BUG] `BaseForecaster` - move `check_fh` to inner loop if vectorized

sktime/forecasting/base/_base.py
Adds fixes for `pandas 2.2.X` compatibility:
* ensures index sorting in `update_predict` - previously, this was automatic, but now has to be enforced due to behaviour change of `pd.concat`.
=> [MNT] `pandas 2.2.X` compatibility fixes

.github/workflows/test.yml
This PR adds a job so that changes outside `sktime` folder, e.g. changes in docs/templates/examples do not trigger unit tests.
=> [MNT] avoid running unit tests in CI for documentation/template/etc. changes

docs/source/developer_guide/deprecation.rst
This PR fixes some odd formatting in the deprecation timeline example.
=> [DOC] fix odd formatting in deprecation timeline example

docs/source/glossary.rst, sktime/forecasting/base/_base.py, sktime/registry/_lookup.py
This PR makes improvements around the documentation of data container types and forecasting docstrings:
* glossary items for mtype, scitype, pointers to lookup, extension templates
* forecasting docstrings have been reworked: clarified requirements, cleaned up docstrings, consistency
* removed the obsolete restriction arising from univariate/multivariate in forecasting docstrings, simplifying these quite a bit (this is no longer a restriction since quite a while, since we introduced broadcasting across variables)
Critical review would be appreciated, e.g., whether this makes things easier to understand for newcomers and current users.
=> [DOC] improved glossary and forecasting docstrings

sktime/transformations/base.py
Improves output type checking error messages in `BaseTransformer.transform`, using idiomatic `check_is_error_msg`.
Related: https://github.com/sktime/sktime/issues/5867
=> [ENH] improved output type checking error messages in `BaseTransformer.transform`

sktime/classification/dictionary_based/_boss.py, sktime/performance_metrics/forecasting/tests/test_metrics.py, sktime/transformations/bootstrap/_mbb.py
This PR addresess some minor deprecations:
* move of `delayed` from `sklearn.utils.fixes` to `sklearn.utils.parallel`
* change in behaviour of `pandas.DataFrame.groupby` with length 1 `level`
* deprecation of `squared` arg in `sklearn` metrics
=> [MNT] address some upcoming deprecations

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/early_classification.py
Minor PR updating extension templates:
* remove type annotations, some of these were not compatible with lower python versions in the support range
* add the preamble on docstring and authors variable on top in those templates where these were missing
=> [DOC] remove type annotations in extension templates

extension_templates/transformer.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/tests/test_pipeline.py, sktime/registry/_tags.py, sktime/transformations/base.py, sktime/transformations/compose/_column.py, sktime/transformations/compose/_ytox.py
Fixes #5975, see there for description of the edge case bug where `X` is `None`, but passing to transformers is valid.
Changes included:
* added tag `requires_X` for transformers, because passing `X` always causes problems with other examples. This is turned off for, e.g., `YfromX`.
* replaced custom scitype inference utility in `_pipeline.py` module with the central entry point in `registry` (that was created later)
* better docstring formatting in `TransformedTargetForecaster` and `ForecastingPipeline`
=> & albahhar [ENH] in `ForecastingPipeline`, allow `None` `X` to be passed to transformers

docs/source/api_reference/forecasting.rst, pyproject.toml, sktime/forecasting/base/adapters/__init__.py, sktime/forecasting/base/adapters/_neuralforecast.py, sktime/forecasting/neuralforecast.py, sktime/forecasting/tests/test_neuralforecast.py
Adapter class to `neuralforecast` from `Nixtla` and concrete estimator for `RNN`.
Notes for reviewers (not in any particular order)
1. `neuralforecast` supports 3 types of exogenous features: static (constant over time), historical (unknown for prediction horizon) and future (known for prediction horizon). I felt the static type has no predictive capability if models are trained per series, and as far as I know, sktime will not be able to support historical type for framework compatibilities. Hence in this first draft of adaptation, I have added support for only future type.
2. `neuralforecast` has the capability of directly supporting panel/hierarchical datasets directly. I am not sure how to take benefit of that in sktime, so have not used it in this first draft. If it's easy enough to …
=> [ENH] Add neuralforecast adapter and rnn forecaster

sktime/transformations/series/feature_selection.py
The bullet point for the " feature-importance" is not properly rendered. I have added blank line before and after the bullet point list.
Fixes #5993
The bullet point for the " feature-importance" in feature_selection.py is not properly rendered. I have added blank line before and after the bullet point list.
No
No …
=> [DOC] format docstrings in `feature_selection.py` correctly

docs/source/api_reference/param_est.rst
This PR adds the missing `PluginParamsTransformer` to the API reference
=> [ENH] add missing `PluginParamsTransformer` to API reference

docs/source/get_involved/code_of_conduct.rst
This updates the contact links in the main code of conduct - this was inconsistent with the "roles" page.
The code of conduct itself is not changed.
Changes:
* email updated to reflect use of `sktime.net` domain
* added @marrov as listed as a member - this has been done a year ago on the "roles" page, but by accident omitted on the CoC page itself
* added option to contact via `discord`, as that is faster
Further changes: typo fixes; clarifying one instance of significance threshold
=> [DOC] update contact links in code of conduct

docs/source/index.rst
This PR puts a box with key links to 2024 summer programme participation on the `sktime.net` landing page:
* application to internhsips and mentoring
* contribution to managed workstreams (sponsoring and time commitments)
=> [DOC] 2024 summer programme links on `sktime.net` landing page

sktime/transformations/series/fourier.py
Fixes #5932
I added blank lines and line blocks to properly create the sp_list description, as required by the reStructuredText syntax.
No
No
No
- [ x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.
=> [DOC] Added blank lines to properly render `FourierFeatures` docstring, `sp_list` (#5932)

sktime/datatypes/_panel/_convert.py
This PR modifies the conversion from `pd-multiindex` to `df-list` mtype to use `Index.unique` instead of `set`.
As this is more idiomatic, it should be less error prone across `pandas` versions.
A possible fix for https://github.com/sktime/sktime/issues/5988, based on a guess what the issue could be.
=> [ENH] use `Index.unique` instead of `set` in conversion from `pd-multiindex` to `df-list` mtype

CODEOWNERS, docs/source/changelog.rst, docs/source/developer_guide/deprecation.rst, docs/source/get_involved/governance.rst, docs/source/glossary.rst, sktime/classification/interval_based/_tsf.py, sktime/forecasting/base/_delegate.py, sktime/forecasting/ltsf.py, sktime/tests/test_switch.py, sktime/utils/deep_equals/_deep_equals.py
The 4 releases in 2024 had wrong dates in changelog. This PR fixes those, and also run codespell and typos for some other spelling mistakes.
=> [MNT] Fix typos in changelog

.all-contributorsrc, sktime/regression/base.py, sktime/regression/tests/test_all_regressors.py
Fixes #6018
Remove non-existing `normalize` parameter for `r2_score` in `sktime.regression.base` class : `BaseRegressor` method : `score`.
No.
This PR does not solve another issue which is not directly linked, but should be noted.
With `test_x,  test_y  = load_UCR_UEA_dataset(name=data, split="test")`
```
model.score(test_x, test_y)
```
Will throw error :
<details>
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 model.score(test_x, test_y)
File [~/Development/sktime-dev/sktime/sktime/regression/base.py:302](http://localhost:18888/lab/tree/sktime/sktime/sktime/regression/base.py#line=301), in BaseRegressor.score(self, X, y, multioutput)
298 from …
```
=> [BUG] fix `BaseRegressor.score` method failing with `sklearn.metrics r2_score got an unexpected keyword argument 'normalize'`

docs/source/api_reference/regression.rst, sktime/regression/deep_learning/__init__.py, sktime/regression/deep_learning/cntc.py, sktime/regression/deep_learning/inceptiontime.py, sktime/regression/deep_learning/macnn.py, sktime/tests/_config.py
Part of https://github.com/sktime/sktime/issues/3351. See also https://github.com/sktime/sktime/pull/3365
Migrated CNTC, InceptionTime, and MACNN regressors to sktime from sktime-dl
None
None …
=> [ENH] Migrate DL regressors from sktime-dl: CNTC, InceptionTime, MACNN

sktime/classification/model_selection/_tune.py, sktime/forecasting/compose/tests/test_multiplex.py, sktime/forecasting/model_evaluation/__init__.py, sktime/forecasting/model_evaluation/_functions.py
Fixes various minor typos:
* docstring typos
* author credits: `model_evaluation` was missing credits of @hazrulakmal; module `__init__` should have no authors variable
=> [DOC] fix various typos

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/early_classification.py, extension_templates/forecasting.py, extension_templates/forecasting_simple.py, extension_templates/forecasting_supersimple.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py, extension_templates/transformer_simple.py, extension_templates/transformer_supersimple.py
This PR adds further clarification regarding immutability of `self`-params in the extension templates, including recipes on handling defaults and estimators (the latter only in "non-simple" extension templates).
=> [DOC] clarification regarding immutability of `self`-params in extension templates

docs/source/api_reference/forecasting.rst, sktime/forecasting/neuralforecast.py, sktime/forecasting/tests/test_neuralforecast.py
Sktime already has an adapter for `neuralforecast` which only implements `RNN` model. RNN's suffer from problems like gradient vanishing while training, So I it's good to have LSTM model implemented that works better than RNN for time-series forecasting. 
Here is a demo of LSTM implemented in sktime using neuralforecast [notebook](https://colab.research.google.com/drive/1R9z5HS4uRpzVuVYKMHoB-q3-osWgHyD_?usp=sharing)
=> [ENH] `neuralforecast` based LSTM model

sktime/forecasting/model_evaluation/tests/test_evaluate.py
This PR silences the sporadic failure on `main` related to #5959, until the bug is respolve.
Does *not* resolve #5959, just silences the sporadic failure.
=> [MNT] silence sporadic failure in `test_evaluate_error_score`

sktime/transformations/series/detrend/tests/test_mstl.py
Closes #6083, resolves #5458.
This PR adds a test file for the [MSTL](https://github.com/sktime/sktime/blob/main/sktime/transformations/series/detrend/mstl.py) class. Currently, all it intends to do is test whether [MSTL](https://github.com/sktime/sktime/blob/main/sktime/transformations/series/detrend/mstl.py)'s `transform` returns the correct components when `return_components` is set to True during initialization.
If it would be beneficial, I could probably expand the testing script to test MSTL in other scenarios (like we do for `_detrender` and `_deseasonalizer`). From @fkiraly's last comment in #5458, I thought this would be the most immediately helpful and nice-to-have test.
There's just one method in my code right now so it should be quick to review. This is my first PR here and …
=> Add a `test_mstl` module checking if `transform` returns desired components

sktime/transformations/panel/catch22.py
This PR corrects the deprecation action timing for `Catch22` changes, it moves instructions to the release manager from 0.28.0 to 0.29.0.
This is because changes will be released with 0.27.1 (not 0.27.0), so for a full minor cycle the earliest time of breaking change can be 0.29.0 after a full cycle of warnings.
=> [MNT] correct deprecation action timing for `Catch22` changes

docs/source/api_reference/transformations.rst, sktime/transformations/series/detrend/__init__.py, sktime/transformations/series/detrend/mstl.py
Fixes #6085.
`MSTL` import has been added to `sktime/transformations/series/detrend/__init__.py`.
```py
from sktime.transformations.series.detrend.mstl import MSTL
from sktime.transformations.series.detrend import MSTL
```
This change does not require a deprecation message as it is supported downwards and "don't break user code without forewarning".
=> [ENH] Adds `MSTL` import statement in `detrend`

.github/workflows/update_contributors.yml
Currently, the `update-contributors` workflow - which updates `CONTRIBUTORS.md` if `.all-contributorsrc` is updated - triggers a job targeting any branch where that is the case.
This happens for PR branches, where this is intended behaviour, but also for `main`, where the update job fails due to branch protection.
This PR means to remove the second condition, which triggers unintended behaviour, and only leave the first one that triggers the intended behaviour.
=> [MNT] run `update-contributors` workflow only on PR

docs/source/developer_guide.rst, docs/source/get_involved/contributing.rst
Fixes: #6162
Changed the channel reference from #contributors to #lobby in the sktime documentation to accurately reflect the Discord server setup. This ensures that new developers receive correct instructions on how to introduce themselves and engage with the community.
=> [DOC] corrected Discord channel mention in developer guide

sktime/forecasting/compose/_fallback.py
By accident, I rediscovered an earlier discussion on what is now `FallbackForecaster` in https://github.com/sktime/sktime/issues/3838.
In it, @rikstarmans implemented and posted code of an almost functional prototype, but never made a pull request to `sktime`.
In consequence, I think @rikstarmans should be credited with (co-)authorship, but not listed as a maintainer of `FallbackForecaster` - this PR adds @rikstarmans as an author.
FYI @ninedigits
=> [DOC] add credit to @rikstarmans in `FallbackForecaster`

.all-contributorsrc, sktime/regression/deep_learning/mlp.py
Added examples to docstrings in  sktime.regression.deep_learning.mlp.py for MLPRegressor. 
No
No
dependency isolation, see the …
=> [DOC] Added an example to MLPRegressor #4264 

sktime/networks/rnn.py
Implemented the standard 'get_test_params' class method with the appropriate docstring and applicable parameters.
Added a couple test params for `RNNNetwork` contributing towards #3429. One test param that covers the default set and another that covers the 'units' parameter.
One thing I noticed when going through the docstring for the `RNNNetwork` class is that there seems to be a missing reference [1] inside.
This is my first pull request ever so please leave me some feedback! :) 
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting …
=> [ENH] added test params to `RNNNetwork` on 3429

sktime/tests/_config.py
This PR adds temporary skips to sporadically failing tests for `ShapeletTransformPyts` until the underlying bug is resolved, see #6171.
=> [MNT] temporary skip sporadically failing tests for `ShapeletTransformPyts`

sktime/annotation/base/_base.py
Closes #5305.
This PR documents the `int_label` option in the `BaseSeriesAnnotator` class. This option is used in the the greedy gaussian segmentation model and the hidden markov model.
No. …
=> [DOC] in `BaseSeriesAnnotator`, document the `int_label` option

sktime/classification/deep_learning/base.py, sktime/classification/deep_learning/cnn.py, sktime/classification/deep_learning/cntc.py, sktime/classification/deep_learning/fcn.py, sktime/classification/deep_learning/inceptiontime.py, sktime/classification/deep_learning/lstmfcn.py, sktime/classification/deep_learning/macnn.py, sktime/classification/deep_learning/mcdcnn.py, sktime/classification/deep_learning/mlp.py, sktime/classification/deep_learning/resnet.py, sktime/classification/deep_learning/rnn.py, sktime/classification/deep_learning/tapnet.py, sktime/regression/deep_learning/base.py, sktime/regression/deep_learning/cnn.py, sktime/regression/deep_learning/cntc.py, sktime/regression/deep_learning/fcn.py, sktime/regression/deep_learning/inceptiontime.py, sktime/regression/deep_learning/lstmfcn.py, sktime/regression/deep_learning/macnn.py, sktime/regression/deep_learning/mcdcnn.py, sktime/regression/deep_learning/mlp.py, sktime/regression/deep_learning/resnet.py, sktime/regression/deep_learning/rnn.py, sktime/regression/deep_learning/tapnet.py
Some of the current deep learning classifiers on `main` had unreported bugs in their `__init__` logic and were not tested.
This was due to `BaseDeepClassifier` and `BaseDeepRegressor` having `__init__` args and defaults, for `batch_size` (both) and `random_state` (only `BaseDeepClassifer`).
If `super().__init__()` was called from the child class without passing these parameters, they would be overwritten by the defaults. Most existing classes did not pass these on, so were getting their defaults overwritten, unless they overwrote them again after that in their own `__init__`.
Further, some regressors were passing parameters that the super's `__init__` did not actually have, crashing upon construction - which was not noticed, as someone had added these classes to the `tests._config` …
=> [BUG] fix `super` calls in deep learning classifiers and regressors

sktime/regression/deep_learning/inceptiontime.py, sktime/tests/_config.py
Fixes an unreported network construction bug in `InceptionTimeRegressor`.
A `self.n_classes_` attribute was used internally, which neither the estimator nor the network had.
Previously undetedted since the estimator was excepted from testing, see https://github.com/sktime/sktime/pull/6138
=> [BUG] fix network construction in `InceptionTimeRegressor`

build_tools/check_backticks.py, sktime/classification/dictionary_based/_boss.py, sktime/classification/dictionary_based/_muse.py, sktime/classification/dictionary_based/_weasel.py, sktime/classification/feature_based/_catch22_classifier.py, sktime/clustering/k_means/_k_means_tslearn.py, sktime/clustering/kernel_k_means.py, sktime/dists_kernels/gak.py, sktime/transformations/series/detrend/_deseasonalize.py
This PR is related to this work here: https://github.com/sktime/sktime/pull/6023
It creates a python script in `build_tools` that can be run to list out all the files and incorrect uses of `backticks` in the docstrings.
- checkout the regex expressions used in function: `find_invalid_backtick_text`
- I am not sure how the output should look like, I have attached a snapshot below in comments.
If this tool is accepted we can use this to fix all the remaining invalid `backtick` uses and can later be converted to a pre-commit tool.
=> [MNT] create build tool to check invalid backticks

.github/workflows/update_contributors.yml
Reverts sktime/sktime#6133
I think this does not work - not sure why the job fails on PR.
=> Revert "[MNT] run `update-contributors` workflow only on PR"

sktime/datatypes/_table/_registry.py
While refactoring `datatypes`, noticed some minor inconsistencies in the registry short descriptions of mtypes. Fixed in this PR.
=>  [DOC] minor clarifications in mtype descriptions

pyproject.toml
`temporian` is currently causing install failures on `main`, likely due to version 0.8.0 released today.
This PR adds a bound `temporian<0.8.0` to `pyproject.toml`.
FYI @ianspektor, @achoum
=> [MNT] bound `temporian<0.8.0`

docs/source/api_reference/forecasting.rst, sktime/forecasting/conditional_invertible_neural_network.py, sktime/networks/cinn.py
This PR prepares the change cycle for renaming `cINNForecaster` to `CINNForecaster` completing the steps for release v0.28.0 in #6120
- todos on top of class definition
- warning message in class initialization
- alias line added with a todo in the bottom of the file
I have tried to mimic this implementation https://github.com/sktime/sktime/pull/5799
The todos lines with release versions and warning message should be considered.
=> [MNT] initialize change cycle (0.28.0) for renaming `cINNForecaster` to `CINNForecaster`

sktime/transformations/compose/_featureunion.py, sktime/transformations/tests/test_compose.py
This PR fixes #6077, by correcting the output type tag inference as suggested by @fspinna.
Also adds the MRE from #6077 as a test.
Currently, the tags are copied from the first component instance in the feature union - I'm unsure what should happen in case the tags are unequal for the members of the feature union.
=> &fspinna [BUG] fix `FeatureUnion` for primitive outputs

.all-contributorsrc, sktime/forecasting/exp_smoothing.py
While exploring #6175, realized that the default parameter for `method` in Exponential Smoothing should be `SLSQP`. This also affects statsmodels documentation and there is already an [open PR](https://github.com/statsmodels/statsmodels/pull/9129) in their repo to fix this.
Changes `method='L-BFGS-B'` to `method='SLSQP'`.
No
See [statsmodels default](https://github.com/statsmodels/statsmodels/blob/192670b31c9069b247b0901d66013853e2ca47b7/statsmodels/tsa/holtwinters/model.py#L1142C1-L1142C55)
N/A
N/A
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. …
=> [DOC] ExponentialSmoothing default method change from L-BFGS-B to SLSQP

docs/source/api_reference/regression.rst
This PR fixes some missing exports in the time series regression API reference, of deep learning regressors.
=> [DOC] fix missing exports in time series regression API ref

sktime/datasets/_readers_writers/arff.py, sktime/datasets/_readers_writers/long.py, sktime/datasets/_readers_writers/ts.py, sktime/datasets/_readers_writers/tsf.py, sktime/datasets/_readers_writers/tsv.py, sktime/datasets/_readers_writers/utils.py
Fixes #2576 
I've created a function which takes two parameters (path, suffix). If the path does not have the specified file extension, the funciton appends it(suffix) to the path. (It basically eleminates the need of adding specified file ending for data loaders)
No
See here for …
=> [ENH] automatic inference of file ending in data loaders for single file types

sktime/forecasting/base/_base.py
The default for `BaseForecaster.predict_var` in a case where `predict_proba` was implemented was erroneous - this is fixed.
Discovered - and covered - via the upgrade of `BaggingForecaster` in #6052
=> [BUG] fix `BaseForecaster.predict_var` default if `predict_proba` is implemented

sktime/registry/_lookup.py
This PR removes a spurious line from `all_estimators` - the line had no effect.
=> [ENH] remove unnecessary line in `all_estimators`

docs/source/get_involved/code_of_conduct.rst
This PR adds more "don't do this" examples to the code of conduct, from the python software foundation CoC.
The examples added (copied from PSF) primarily target emergent patterns of social media harassment and cyberbullying, as well as "unwanted attention" type harassment.
=> [DOC] add more examples to CoC from python software foundation CoC

docs/source/_static/js/dynamic_table.js
Fixes #5495
I identified the location of the Js search function. It was written with jQuery which I was not familiar with. I just rewrote it in vanilla Js and the problem was fixed. 
This is very basic so it may not but the most right or efficient. I am going to look further into the documentation and implement some other enhancements for the estimator overview in particular and the docs in general. Then I may find out why the jQuery didn't work or draw up some other solutions.
=> [BUG] search function for estimator overview not working

.github/workflows/update_contributors.yml, .github/workflows/wheels.yml
Fixes #6181.
This implement ensures that `Update Contributors` does not run on `main`. It also makes sure `build wheels` only triggers when `release` is triggered and and `Update Contributors` is completed.
Not yet, but I am considering to add based on feedback and possible merge
I think the workflow is too tightly woven together, and can be broken down further to ensure seamlessness.
=> &duydl [MNT] Ensure Update Contributors does not run on main

sktime/clustering/k_means/_k_means_tslearn.py
- Introduce two test parameter sets for ``TimeSeriesKMeansTslearn`` in the ``get_test_params`` function.
- Reference Issues
Towards : #3429 
- Tests passed: pytest sktime\clustering\tests\test_k_means.py
=> Add new test parameter sets for ``TimeSeriesKMeansTslearn``

sktime/classification/deep_learning/base.py
This PR makes a minor correction to correct deprecation versions stated in the `BaseDeepClassifier` docstring
=> [DOC] correct deprecation versions in `BaseDeepClassifier` docstring

.github/PULL_REQUEST_TEMPLATE.md, docs/source/developer_guide/add_estimators.rst, examples/01_forecasting.ipynb, examples/02_classification.ipynb, examples/03_transformers.ipynb
Maintainers/owners of estimators are now tracked in the `maintainers` tag of the estimator, and no longer in `CODEOWNERS`.
This had been updated in various places, but a few locatoins had been missed:
* the PR template
* a few jupyter notebook tutorials
* the developer guide
This PR updates these locations with a updated pointers to the tags.
=> [DOC] update maintainer tag information in docs and PR template

README.md
Add Hall-of-Fame section, fixes #3716 
The Hall-of-Fame section is added after (How-to-get-involved)
No
The code written for keeping track of contributions to the repository.
Not Yet …
=> [DOC] Add hall-of-fame widget to README (Added the Hall-of-fame section) #3716 

sktime/transformations/panel/_shapelet_transform_numba.py
Improved numerical stability by setting a tolerance threshold for standard deviation calculation in shapelet transform. This change from use_std = std != 0 to use_std = std > 1e-8 prevents potential NaN values by avoiding division by extremely small numbers, addressing issues related to the precision limits of floating-point arithmetic.
This PR addresses the NaN issue discussed in [#4073](https://github.com/sktime/sktime/issues/4073). By introducing a tolerance threshold for the standard deviation calculation, it aims to resolve the NaN values encountered in certain cases.
Enhances the `_online_shapelet_distance` function's robustness by introducing a tolerance threshold (`1e-8`) for the standard deviation (`std`) calculation, ensuring numerical stability and preventing NaN values in …
=> [BUG] Update `_shapelet_transform_numba.py` to improve numerical stability

sktime/tests/_config.py
This PR skips some of the sporadic failures on main, see https://github.com/sktime/sktime/issues/6201
=> [MNT] temporary skip for some sporadic failures on `main`

docs/source/api_reference/transformations.rst, sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_selection/__init__.py, sktime/forecasting/model_selection/_tune.py, sktime/forecasting/trend/_pwl_trend_forecaster.py, sktime/forecasting/trend/tests/test_pwl_trend.py, sktime/transformations/panel/catch22wrapper.py, sktime/transformations/panel/dictionary_based/__init__.py, sktime/transformations/panel/dictionary_based/_paa.py, sktime/transformations/panel/dictionary_based/_sax.py, sktime/transformations/series/paa.py, sktime/transformations/series/sax.py, sktime/transformations/series/tests/test_paa.py, sktime/transformations/series/tests/test_sax.py, sktime/utils/_testing/deep_equals.py, sktime/utils/deep_equals/__init__.py
Carries out deprecations and change actions scheduled for 0.28.0:
* removed `n_jobs` parameter in `Catch22Wrapper`
* in `ProphetPiecewiseLinearTrendForecaster`, switch seasonality defaults to False
* finalize rename cycle for `PAA`, `SAX`
* bump deprecation/change checks scheduled for 0.28.0 to 0.29.0
=> [MNT] 0.28.0 deprecations and change actions

docs/source/installation.rst
This PR updates the installation instructions on `conda` soft dependencies.
It changes the `catch22` specific instruction, which is also outdated (see #6227), to a more general reference to packages not available on `conda`. FYI @royiavital.
=> [MNT] update installation instructions on `conda` soft dependencies

sktime/proba/empirical.py
This PR extends the `Empirical` distribution to be able to represent distributions over hierarchical data frames. Required for the probabilistic mode of bootstrap/bagging forecaster.
=> [ENH] extend `Empirical` distribution to hierarchical data

sktime/forecasting/tests/test_varmax.py
This PR skips the tests failing with memouts since recently as described in https://github.com/sktime/sktime/issues/6260, until the issue has been diagnosed and fixed.
=> [MNT] temporary skip for failure #6260

sktime/datatypes/_examples.py
This PR makes `get_examples` safer against side effects on the data fixtures, by adding a `deepcopy` at the end.
This should prevent issues like in https://github.com/sktime/sktime/pull/6253#pullrequestreview-1983193029 from occurring in the future.
=> [ENH] make `get_examples` side effect safe via `deepcopy`

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/forecasting.py, extension_templates/forecasting_simple.py, extension_templates/forecasting_supersimple.py, extension_templates/split.py, extension_templates/transformer.py, extension_templates/transformer_simple.py, extension_templates/transformer_supersimple.py
This PR adds instructions to extension templates to credit authors of 3rd party estimators in interface classes when writing a direct interface, as opposed to `sktime` native estimators.
This is accompanying discussion in https://github.com/sktime/sktime/issues/5938, as a proposed change.
This PR does not add author credits that would be missing based on this policy, that would happen in separate PR after discussion in #5938 is concluded.
=> [DOC] `authors` tag - extension template instructions to credit 3rd party interfaced authors

sktime/utils/mlflow_sktime.py
It seems the fix #6282 caused another issue - I believe the reason is that `dask` removed `pyyaml` as a dependency.
Consequently, the `import yaml` statement in the mlflow module now fails, post #6282. Unclear why the tests did not recognize this.
The fix should be this: import `yaml` only if `mlflow` is present.
=> [MNT] fix isolation of `mlflow` soft dependencies

sktime/proba/mixture.py
Related to issue #4518
Moves mixture distribution from `skpro` into `sktime`.
No
Facing a issue while testing, I have tested the distribution in my own terminal.
when i tried **pytest ./sktime**  , i got this issue.
Does installing TensorRT is a solution but i see it tries to install different version of tensorflow. Any recommendation here is much appreciated.
No
No
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, …
=> [ENH] mixture distribution

sktime/classification/distance_based/_time_series_neighbors_tslearn.py, sktime/clustering/k_means/_k_means_tslearn.py, sktime/clustering/k_shapes.py, sktime/clustering/kernel_k_means.py, sktime/dists_kernels/ctw.py, sktime/dists_kernels/dtw/_dtw_tslearn.py, sktime/dists_kernels/gak.py, sktime/dists_kernels/lcss.py
With increased visibility of the authors field in the docs (e.g., in the reworked [estimator overview](https://www.sktime.net/en/latest/estimator_overview.html)), we should make sure it properly reflects contribution. Also see #5938.
This adds upstream authors to the author fields of interfaced estimators from `tslearn` - based on best guesses inferred from author strings and commit history.
FYI @rtavenar, @yanncabanes, @chusloj, @danisodu. Please let us know if we are missing anything or anyone.
Please feel free to claim maintainer role for any of the algorithms if you want.
=> [DOC] author credits to `tslearn` authors

sktime/classification/distance_based/_time_series_neighbors_pyts.py, sktime/transformations/panel/rocket/_rocket_pyts.py, sktime/transformations/panel/shapelet_transform/_shapelet_transform_pyts.py
With increased visibility of the authors field in the docs (e.g., in the reworked [estimator overview](https://www.sktime.net/en/latest/estimator_overview.html)), we should make sure it properly reflects contribution. Also see #5938.
This adds upstream authors to the author fields of interfaced estimators from `pyts` - based on best guesses inferred from author strings and commit history.
FYI @johannfaouzi. Please let us know if we are missing anything or anyone.
Please feel free to claim maintainer role for any of the algorithms if you want.
=> [DOC] author credits to `pyts` authors

sktime/forecasting/tbats.py
This adds one test parameter set to the `TBATS` forecaster to cover the doc example.
=> [ENH] TBATS test parameters to cover doc example

.all-contributorsrc
Add myself as a maintenance contributor as was kindly invited by @fkiraly here: https://github.com/sktime/sktime/issues/6304#issuecomment-2060979554
=> [MNT] add `slavik57` as a maintenance contributor for fixing `conda-forge` `sktime-all-extras 0.28.0` release

.all-contributorsrc, sktime/transformations/series/summarize.py, sktime/transformations/series/tests/test_window_summarizer.py
"In this implementation, within the _window_feature function, if the summarizer is a callable function, it will perform a rolling operation and apply the custom function. However, in the backfill stage, which the previous author set up to use 'Z' for backfilling, the custom function is not applied.
No …
=> [BUG] Fix backfill of custom function in window_feature

sktime/proba/laplace.py
Fixes an unreported bug: the variance method `var` of the `Laplace` distribution was returning scale parameter divided by $\sqrt{2}$. However, instead, the scale parameter should be multiplied by $\sqrt{2}$.
=> [BUG] fix `var` of `Laplace` distribution

.github/workflows/test.yml, .github/workflows/test_all.yml, .github/workflows/test_base.yml, .github/workflows/test_datasets.yml, .github/workflows/test_module.yml, .github/workflows/test_other.yml, .github/workflows/wheels.yml
This PR moves Mac based GHA runners consistently to `macos-13`.
`macos-latest` is failing with python 3.8 and 3.9 recently, and `macos-14` = `macos-latest` has half the memory of `macos-13`.
=> [MNT] set GHA macos runner consistently to `macos-13`

sktime/transformations/bootstrap/_tsbootstrap.py
Fixes an unreported bug where `TSBootstrapAdapter` would always return `RangeIndex` for the bootstrapped time series.
This should default to the same index as `X` seen in `_transform`.
=> [BUG] fixed indexing of return in `TSBootstrapAdapter`

sktime/clustering/dbscan.py, sktime/dists_kernels/dtw/_dtw_sktime.py, sktime/dists_kernels/edit_dist.py
`TimeSeriesDBSCAN` does not set its tags correctly if one of the `numba` based distance in `sktime` is used. In this case, it cannot support unequal length time series, and the corresponding tag needs to be set.
Similarly, the tags for some of the `numba` distances were set incorrectly, which is now corrected as well.
=> [BUG] fix dependent tags of `TimeSeriesDBSCAN`

docs/source/api_reference/transformations.rst, sktime/transformations/panel/catch22wrapper.py
With increased visibility of the authors field in the docs (e.g., in the reworked [estimator overview](https://www.sktime.net/en/latest/estimator_overview.html)), we should make sure it properly reflects contribution. Also see #5938.
This adds upstream authors to the author field of the `pycatch22` facing transformation, and gives clearer credit to `pycatch22` in the docstring by naming it.
It also appears that the estimator was never added to the public documentation page, and only the copy/reimplementation was visible there - I apologize for that, this dates back to old history of `sktime`, and was certainly not intentional on my part.
The author credits add @benfulcher and @jmoo2880. The maintainer tag had @benfulcher, so based on recent contribution activity I added @jmoo2880. Please …
=> [DOC] author credits to `pycatch22` authors, fix missing documentation page

sktime/transformations/series/adapt.py
This PR makes `TabularToSeriesAdaptor` compatible with `sklearn` transformers that accept only `y`, e.g., `LabelEncoder`.
If provided with such a transformer, it plugs in the outer `X` to the inner `y`, along the lines of the a suggested design resolution at the root of the problem in `sklearn`, discussed in https://github.com/sktime/sktime/issues/5867.
Towards https://github.com/sktime/sktime/issues/5867
FYI @yarnabrina
Question: do you know of a transformer that has (a) only `y`, and (b) accepts float input? This is to ensure we can test it with the default framework, which currently does not make distinctions in input types.
=> [ENH] make `TabularToSeriesAdaptor` compatible with `sklearn` transformers that accept only `y`, e.g., `LabelEncoder`

.all-contributorsrc, sktime/transformations/series/augmenter.py
Adds to https://github.com/sktime/sktime/issues/4264
Added examples to docstrings in `WhiteNoiseAugmenter`
No
No
No
No
dependency …
=> [DOC] Added an example to WhiteNoiseAugmenter #4264 

sktime/proba/empirical.py
The `Empirical` distribution would produce `pd.Index` of tuples instead of `pd.MultiIndex` in some methods, causing failures in https://github.com/sktime/sktime/pull/6052.
This PR fixes that.
In light of the current refactor in `skpro` which will see the `Empirical` reworked, I think it is sufficient to test indirectly via #6052 for onw.
=> [ENH] fix `Empirical` index to be `pd.MultiIndex` for hierarchical data index

sktime/transformations/bootstrap/tests/__init__.py, sktime/transformations/series/detrend/_deseasonalize.py, sktime/transformations/series/detrend/tests/test_deseasonalise.py
This PR fixes `STLTransformer.inverse_transform` for the univariate case.
An attribute was accessed that did not exist.
Related to https://github.com/sktime/sktime/issues/6337 but not identical, unreported.
It needs to be investigated why suite tests did not catch this, for now I have added a manual test.
Makes minor improvements to files touched:
* fixes minor typo
* moves fixture generation inside test functions to avoid data generation on module load
=> [BUG] Fix `STLTransformer.inverse_transform` for univariate case

sktime/tests/_config.py
Skips tests for the `VARMAX` forecaster until #6344 is resolved.
=> [MNT] skip `VARMAX` until sporadic failures are resolved

docs/source/api_reference/forecasting.rst, sktime/forecasting/conditional_invertible_neural_network.py, sktime/networks/cinn.py
This PR completes step 2 of change cycle for renaming cINNForecaster to CINNForecaster completing the steps for release v0.29.0 in https://github.com/sktime/sktime/issues/6120
- renames the classes
- updates deprecation warning
=> [MNT] change cycle (0.29.0) for renaming `cINNForecaster` to `CINNForecaster`

pyproject.toml, sktime/classification/deep_learning/base.py, sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_selection/__init__.py, sktime/forecasting/model_selection/_tune.py, sktime/regression/deep_learning/base.py, sktime/transformations/panel/catch22.py, sktime/utils/_testing/deep_equals.py, sktime/utils/deep_equals/__init__.py
Carries out deprecations and change actions scheduled for 0.29.0:
* removed `n_jobs` parameter in `Catch22`
* in deep learning based classifiers and regressors, change default for `legacy_method` in `save` to `False`
* intermediate stage rename cycle for `cINNForecaster` to `CINNForecaster`
* added lower bound `scikit-base>=0.6.1`, schedule removal of legacy `deep_equals` for 0.30.0
* bump deprecation/change checks scheduled for 0.29.0 to 0.30.0
=> [MNT] 0.29.0 deprecations and change actions

sktime/tests/test_switch.py, sktime/tests/tests/__init__.py, sktime/tests/tests/test_test_utils.py, sktime/utils/git_diff.py
Towards https://github.com/sktime/sktime/issues/6344.
Speeds up test collection by `lru_cache`-ing all test switch utilities called from `run_test_for_class`.
This gets test collection time for the classification module to 5 seconds, compared to historical test times:
* 0.22.0 - 12 sec for 301 tests
* 0.24.0 - 11 sec for 294 tests
* in 0.24.2, parent classes were included in diff check
* 0.25.0 - 38 sec for 355 tests
* 0.26.0 - 38 sec for 355 tests
* in 0.26.1, the condition on dep change in `pyproject` was added
* 0.27.0 - 56 sec for 363 tests
* 0.28.1 - 72 sec for 246 tests
* this PR: 5 sec for 246 tests
(timings from `python -m pytest sktime/classification -n0 --collect-only`)
For all of `sktime`, the test collection time is down to 40sec for me locally, from >20 minutes.
=> [MNT] speed up test collection - cache differential testing switch utilities

sktime/tests/_config.py
This PR adds temporary skips for estimators involved in timeouts, see #6344, until the problem is fully diagnosed and addressed.
=> [MNT] temporary skip of estimators involved in timeouts #6344

sktime/base/_base.py
This PR adds a warning, raised by any instantiated `sktime` estimator under python 3.8.
It announces dropping of support for 3.8 at version 0.30.0, and adds release manager instructions on handling the warning.
Towards https://github.com/sktime/sktime/issues/5791
=> [MNT] `python 3.8` End-of-life and `sktime` support drop warning

sktime/tests/_config.py
Also skips tests for `pmdarima` `ARIMA`, in relation to #6344
=> [MNT] temporary skip tests for `ARIMA` in relation to #6344

docs/source/changelog.rst, sktime/base/_base.py
This PR places the EOL notice in the 0.29.0 changelog more prominently.
=> [DOC] prominent placement of 3.8 EOL in changelog

.github/workflows/wheels.yml
Removes test step from the release action - temporary to allow quick release.
Issue #6344 causes mac-13 to run longer than 6 hours and then time out - there are no known failures, just too long runtimes at the moment.
To be reverted.
=> [MNT] instant release action - temporary

sktime/tests/tests/test_test_utils.py
This fixes an unreported bug pointed out by @yarnabrina in the test `test_run_test_for_class`, in the check for the logic of `run_test_for_class` returning an attribution of its test yes/no flag to a reason.
If `ONLY_CHANGED_MODULES` flag is `False` and all estimator dependencies are present, the reason returned should be `True_run_always`, but the test checks incorrectly for another positive reason.
This is fixed - a bug with the test, not with `run_test_for_class` - as it did not take into account properly the combination of `ONLY_CHANGED_MODULES = False` and all dependencies present, which in our CI occurs only in `test_all`.
=> [BUG] fix `test_run_test_for_class` logic check if `ONLY_CHANGED_MODULES` flag is `False` and all estimator dependencies are present

README.md
This updates the meetup time in the README to the current, 13 UTC slot.
=> [DOC] update meetup time to new 1pm slot

sktime/forecasting/statsforecast.py
This PR adds some minor enhancements in `StatsForecastAutoTBATS`:
1. supports new arguments added in newer `statsforecast` to control box cox parameter range for automated selection
2. updates existing test parameters with use of more arguments for higher coverage
3. removes internal use of deprecated `seasonal_periods` parameter instead of consistent `season_length` parameter -> this is not a breaking change as user interface is unchanged
=> [MNT] maintenance changes for AutoTBATS

pyproject.toml
Carries out @benheid's suggestion to fix #6445
=> [MNT] bound `transformers<4.41.0`

sktime/tests/tests/test_test_utils.py
The `test_run_test_for_class` test logic was erroneous in case the class with dependency was changed.
This is due to an accidental variable overwrite, `run_no_dep` being overwritten with the value from the test class with dependencies.
Spotted through failure in https://github.com/sktime/skpro/pull/343, which changed the "class with dependencies" example used in `skpro`.
=> [BUG] fix `test_run_test_for_class` test logic

sktime/performance_metrics/forecasting/_coerce.py, sktime/performance_metrics/forecasting/tests/test_metrics.py
This PR allows metric classes to be called with `multilevel` arg in all cases, if the series is not hierarchical. Previously, this would crash the metric.
This PR changes behaviour in this degenerate case so a single-entry `pd.DataFrame` is returned.
Fixes https://github.com/sktime/sktime/issues/6413
=> [BUG] allow metric classes to be called with `multilevel` arg if series is not hierarchical

sktime/utils/plotting.py
This PR adds a formal explanation to the docstring of `plot_calibration`, of what is being plotted.
=> [DOC] `plot_calibration` docstring - formal explanation of the plot

docs/source/developer_guide/deprecation.rst
This PR adds a preamble to the "deprecation policy" document in the developer guide, explaining why we need a deprecation policy, and high-level principles from which the policy elements are derived.
This should hopefully provide a better degree of illustration and explanation to new developers that we onboard.
A review by new developers (e.g., summer mentees) is especially welcome, as this is written for you.
=> [DOC] high-level explanation of deprecation policy principles

sktime/performance_metrics/forecasting/probabilistic/__init__.py, sktime/performance_metrics/forecasting/probabilistic/_classes.py, sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py
Interval width metric for interval forecasts, as requeste by @benHeid.
=> [ENH] Interval width (sharpness) metric

sktime/utils/git_diff.py
If an `lru_cache`-d function returns a mutable object, and that object is later muted, the cached function wlil continue returning the muted - incorrect - return.
This PR fixes the one instance in the code base where this issue could arise.
=> [ENH] make `get_packages_with_changed_specs` safe to mutation of return

sktime/classification/ensemble/_bagging.py
Fixes https://github.com/sktime/sktime/issues/6427.
The problem was that `_predict_proba` did simply forget to subset columns of `X`.
The bug was not detected as the base classifier used in tests was `DummyClassifier`, which ignores `X`, and hence misses the failures in column subsetting of `X` entirely.
To cover the bug, the classifier was replaced by `SummaryClassifier.`.
=> [BUG] fix `BaggingClassifier` for column subsampling case

docs/source/developer_guide/testing_framework.rst
Minor change to the developer guide on the test framework, adds an explicit explanation on how `get_test_params` provides the test fixtures to the test classes.
=> [DOC] explanation of `get_test_params` in test framework example

sktime/classification/dictionary_based/_boss.py, sktime/classification/dictionary_based/tests/test_boss.py, sktime/classification/distance_based/_proximity_forest.py
Towards https://github.com/sktime/sktime/issues/6431.
Fixes `ProximityForest`, tree, stump, and `IndividualBOSS` returning `y` of different type in `predict`.
The `IndividualBOSS` was coercing to `object` which  was turned of.
The proximity classifiers had `_predict` being copy-paste of the default `_predict` which was fixed in https://github.com/sktime/sktime/pull/6430. The fix is deduplication, so the `_predict` defaults to the fixed parent classes' predict.
Tested via https://github.com/sktime/sktime/pull/6428
=> [BUG] fix `ProximityForest`, tree, stump, and `IndividualBOSS` returning `y` of different type in `predict`

sktime/classification/base.py
This fixes one of the bugs reported in https://github.com/sktime/sktime/issues/6427, namely the default `_predict` in `BaseClassifier` always returning integer labels, even if the original labels were not integers.
This would cause all classifiers that did not have a custom `_predict` implemented - a few composites, among them `BaggingClassifier` - to always predict integers, even if the `y` seen in `fit` was of another type.
The fix is simple, adding a missing application of the memorized integer-to-class dictionary.
Test coverage is through https://github.com/sktime/sktime/pull/6428.
=> [BUG] fix classifier default `_predict` returning integer labels always, even if `fit` `y` was not integer

sktime/classification/base.py, sktime/classification/dictionary_based/_boss.py, sktime/classification/dictionary_based/tests/test_boss.py, sktime/classification/distance_based/_proximity_forest.py, sktime/classification/tests/test_all_classifiers.py
This PR extends the suite test `test_classifier_on_unit_test_data` to test that `y` of object or str dtype `y` leads to correct labels on `predict` outputs.
Covers second bug in https://github.com/sktime/sktime/issues/6427, namely the example returning integer labels instead of string labels - but does not fix the bug.
It is hence expected that the test will detect bug #6427.
Depends on the following PR which fix newly covered bugs:
* #6430
* https://github.com/sktime/sktime/pull/6432
=> [ENH] test classifiers on str dtype `y`, ensure `predict` returns same type and labels

.all-contributorsrc, examples/AA_datatypes_and_datasets.ipynb
NA
There was a mistake in the description of the capabilities of the  `"np.ndarray"` mtype. As the example shows, it is capable to represent multivariate series.
No
Proof read :)
NA
NA …
=> [DOC] fixed wrong sentence in the documentation

docs/source/api_reference/performance_metrics.rst, sktime/performance_metrics/forecasting/probabilistic/__init__.py, sktime/performance_metrics/forecasting/probabilistic/_classes.py
This PR adds the unsigned area under the calibration curve as a metric for distribution forecasts.
FYI @benHeid, @astrogilda.
=> [ENH] unsigned area under the calibration curve metric for distribution forecasts

sktime/registry/_lookup.py
Adds a doctest skip for the `all_estimators` example.
This is to avoid running the retrieval method three times, the same functionality is already covered in `test_lookup`.
Also, the test should fail, because the printout is not tested against, so it is odd that it does not fail on `main` currently.
=> [MNT] skip doctest for `all_estimators`

sktime/classification/base.py, sktime/regression/base.py, sktime/regression/tests/test_all_regressors.py
Makes some minor changes to ensure `sklearn 1.5.0` compatibility.
* relaxes tests for return of `BaseRegressor.score`, which uses `sklearn` metrics internally. `sklearn` regression metrics now seem to return `float` instead of `np.floating`. To ensure this is can be in line with `sklearn` type on all versions, the test is relaxed to allow for both. I do not think stricter tests are needed, as `np.floating` behaves like `float` for all practical purposes.
* fixes an unreported bug where `BaseClassifier.score`, in some instances, returned an 1D `np.ndarray` and not a float by default
=> [ENH] `sklearn 1.5.0` compatibility patch

sktime/datatypes/_panel/_check.py, sktime/datatypes/tests/test_utils.py, sktime/performance_metrics/forecasting/probabilistic/_classes.py, sktime/proba/mixture.py, sktime/transformations/panel/channel_selection.py, sktime/transformations/panel/reduce.py, sktime/transformations/series/binning.py, sktime/transformations/series/peak.py, sktime/transformations/series/vmd/_vmdpy.py
This PR addresses various warnings in the code, related to deprecated features or mathematical computations.
Deprecations:
* addressed deprecation of `pd.DataFrame.groupby(axis=1)` in multiple locations
* address changed signature of `groupby` for length 1 `level` parameter
* address changed default of `observed` in `groupby`
* fixed import of `sktime` `train_test_split` from deprecated location
* addressed change in behaviour of `pd.concat` on empty `DataFrame`
Computations:
* fixed unsafe division in `channel_selection.py`
* fixed unsafe weighted average in `vmdpy`
=> [MNT] address various deprecation and computation warnings

sktime/classification/deep_learning/cnn.py, sktime/regression/deep_learning/cnn.py
This PR adds `filter_sizes` and `padding` parameters to `CNNClassifier` and `CNNRegressor`, and ensures these are passed on to `CNNNetwork`.
Fixes https://github.com/sktime/sktime/issues/6436.
=> [BUG] in `CNNClassifier` and `CNNRegressor`, ensure `filter_sizes` and `padding` is passed on

sktime/transformations/base.py
Improves the formatting of transformation docstrings, and references to mtypes/scitypes, consistnet with current docstrings of forecasters.
Also clarifies the impact of the `requires_y` tag on whether `y` is required.
=> [DOC] improved formatting of transformation docstrings

sktime/base/_base_panel.py, sktime/classification/base.py
This fixes an unreported bug where `BaseClassifier.fit_predict` and `fit_predict_proba` would not work for `pd-multiindex` mtype.
The failure is due to `cv.split` being called on a multi-index, which applies to `iloc` range index instead of the first `loc` index component of the multi-index.
Test coverage is added through the scenario in PR https://github.com/sktime/sktime/pull/6374 which covers both `pd-multiindex` as well as the three-class case.
This PR also de-duplicates the `_fit_predict_boilerplate` method of `BaseClassifier` with `BasePanelMixin`.
=> [BUG] fix `BaseClassifier.fit_predict` and `fit_predict_proba` for `pd-multiindex` mtype

sktime/transformations/series/tests/test_differencer.py
Removes `Prophet` as an example of an exogeneous forecaster from `test_differencer_cutoff`.
This has multiple advantages, runtime, and removal of an unnecessary dependency in the test.
It also allows to diagnose https://github.com/sktime/sktime/issues/6487 - if this still fails, then `Prophet` is not the culprit, and we have found a simpler example for the bug #6487.
If it no longer fails, we know there´s something specific about `Prophet`, possibly an interaction.
=> [ENH] remove `Prophet` from `test_differencer_cutoff`

sktime/utils/plotting.py
1. sktime.utils.plot_series() now handles xticks following matplotlib defaults. (Fixes https://github.com/sktime/sktime/issues/5895) As a result fig,ax objects returned by plot_series() can be used correctly by matplotlib. See accompanying pdf for details including some before and after plot comparisons. (section 3 in the pdf)
2. Fixed (or enhanced) sktime.utils.plot_series() so that it can plot multiple coverage levels if present in the pred_interval multiindex. (section 5 in the pdf)
[PullRequestNotes.pdf](https://github.com/sktime/sktime/files/15298401/PullRequestNotes.pdf)
=> [ENH], [BUG] utils/plotting.py: change plot_series() to use matplotlib conventions; enhance plot_interval()

sktime/forecasting/base/_fh.py
`pandas` has once more changed their interfaces and `ForecastingHorizon` breaks with `2Y` and other frequencies, see https://github.com/sktime/sktime/issues/6499.
This fix moves internal use of `freq` to objects, from strings, which fixes the issue in a backwards compatible manner without changing any of the public interfaces.
=> [ENH] compatibility of `ForecastingHorizon` with `pandas` `freq` `2Y` on `pandas 2.2.0` and above

sktime/forecasting/base/tests/test_fh.py
Adds more extensive test cases for `ForecastingHorizon`  `pandas 2.2.X` compatibility, failure case #6499.
=> [ENH] add test case for `ForecastingHorizon`  `pandas 2.2.X` compatibility, failure case #6499

sktime/utils/plotting.py
1. `sktime.utils.plot_series` now handles `xticks` following `matplotlib` defaults. (Fixes https://github.com/sktime/sktime/issues/5895) As a result fig,ax objects returned by `plot_series` can be used correctly by matplotlib. See accompanying pdf for details including some before and after plot comparisons. (section 3 in the pdf)
2. Fixed (or enhanced) sktime.utils.plot_series() so that it can plot multiple coverage levels if present in the pred_interval multiindex. (section 5 in the pdf)
[PullRequestNotes.pdf](https://github.com/sktime/sktime/files/15298401/PullRequestNotes.pdf)
Fixes issues highlighted in revert https://github.com/sktime/sktime/pull/6498 as follows:
`markersize = 4` changed to `s = 4` in call for `matplotlib` scatter plot
=> [ENH], [BUG] utils/plotting.py: change `plot_series` to use `matplotlib` conventions; enhance `plot_interval`

.github/workflows/wheels.yml
Removes the pre-release test run until we have solved the sporadic timeouts, #6344.
For 0.29.1, the `test_all` workflow has already run, so coverage is ensured..
=> [MNT] fast release

sktime/forecasting/pykan_forecaster.py
This PR fixes #6505 if default parameters are passed.
The issue was a mistake that led to accessing the public instead of the private coerced `_grid` attribute.
=> [BUG] fix `PyKANForecaster` default params

sktime/classification/deep_learning/lstmfcn.py, sktime/regression/deep_learning/lstmfcn.py, sktime/tests/_config.py, sktime/tests/test_all_estimators.py
Fixes check_estimator for #6153 and partially solves it.
It corrects the `test_fit_does_not_overwrite_hyper_params` by replacing the `callback = []` to `callback = None` as originally referenced.
| Before Fix  | After Fix |
| ------------- | ------------- |
| ![image](https://github.com/sktime/sktime/assets/38614120/0318c7fe-26cb-49a4-8a10-10efcbe6e377)  |![image](https://github.com/sktime/sktime/assets/38614120/9a6fc3a8-09f0-448f-a736-6a3420eb4af6) |
| ![image](https://github.com/sktime/sktime/assets/38614120/0c1a2351-8486-4111-8d23-f1d624bf147f) | ![image](https://github.com/sktime/sktime/assets/38614120/8d30c67a-5a8e-451b-9e92-6347c2916c72)  |
Furthermore, to make sure that other code wasn't compromised I ran 2 more `check_estimator`
| Before Fix  | After Fix |
| ------------- | …
=> [BUG] Resolve `LSTMFCNClassifier` and `LSTMFCNRegressor` changing `callback` parameter 

sktime/forecasting/conditional_invertible_neural_network.py, sktime/networks/cinn.py
This completes step 3 of change cycle for renaming cINNForecaster to CINNForecaster, completing the steps for release v0.30.0 in #6120
* remove aliases altogether
* remove deprecation warning
=> [MNT] final change cycle (0.30.0) for renaming `cINNForecaster` to `CINNForecaster`

pyproject.toml
There are multiple instances of direct imports by `joblib` without isolation, and it never causes problem as it is a dependency of `scikit-learn`. It has always been so and unlikely to change in future, so moving it to core dependencies to avoid conda linting warnings.
=> [MNT] added joblib as core dependency

sktime/utils/plotting.py
This PR prevents external imports upon import of `sktime.utils`.
This has an impact on initialization performance of `sktime` and test collection, as otherwise external dependencies such as `numpy`, `pandas`, are imported whenever `utils.estimator_checks` or `utils.dependencies` is loaded. This happens repeatedly upon `pytest` call, making the tests less performant than they could be.
Imports were caused by imports from the `plotting` module` directly in `__init__`, which are now isolate inside the methods to prevent imports upon use of test functionality.
The same issue was also present for `sktime` init, i.e., the package proper, as it imports `show_versions` which in turn imported `utils` (as its root location).
=> [MNT] isolate `utils` module init and `sktime` init from external imports

sktime/tests/test_switch.py, sktime/utils/git_diff.py
This PR updates the `is_module_changed` utility to be valid when querying directories, and adds a new test switch `run_test_module_changed` which also takes `ONLY_CHANGED_MODULES` into account.
This will be useful for conditional testing, e.g., #6517 or the `pykalman` fork.
=> [ENH] upgrade `is_module_changed` test utility for paths

sktime/distances/_distance.py, sktime/distances/tests/test_distance_alignment_path.py, sktime/distances/tests/test_distance_correctness.py, sktime/distances/tests/test_lower_bounding.py, sktime/distances/tests/test_numba_distance_parameters.py, sktime/distances/tests/test_numba_distances.py, sktime/distances/tests/test_pairwise_distances.py, sktime/tests/test_switch.py, sktime/utils/git_diff.py
This PR adds a switch that runs tests in the `distances` module only if it has changed. This will have a substantial impact on the test times, as this module adds up to lengthy testing.
Depends on https://github.com/sktime/sktime/pull/6518.
This PR *will* run tests in the `distances` module, as it has changed by virtue of introducing the pytest conditional testing decorators.
=> [MNT] run tests in `distances` module only if it has changed

sktime/split/tests/test_cutoff.py, sktime/split/tests/test_expandingcutoff.py, sktime/split/tests/test_expandinggreedy.py, sktime/split/tests/test_expandingwindow.py, sktime/split/tests/test_sameloc.py, sktime/split/tests/test_singlewindow.py, sktime/split/tests/test_slidingwindow.py, sktime/split/tests/test_split.py, sktime/split/tests/test_temporaltraintest.py
Decorates all low-level tests in the `split` module to be executed only if the tested estimators have changed.
Towards #2890.
=> [MNT] differential testing for `split` module

sktime/libs/README.md, sktime/libs/pykalman/__init__.py, sktime/libs/vmdpy/README.md, sktime/libs/vmdpy/__init__.py, sktime/libs/vmdpy/tests/__init__.py, sktime/libs/vmdpy/tests/test_readme_example.py, sktime/libs/vmdpy/vmdpy.py, sktime/transformations/series/tests/test_vmd.py, sktime/transformations/series/vmd.py, sktime/transformations/series/vmd/__init__.py, sktime/transformations/series/vmd/tests/__init__.py
Cleans up folder structure and documentation for onboard libs `pykalman` and `vmdpy`.
* adds missing license statement and package preamble for `pykalman`
* moves `vmdpy` to public module in `sktime.libs` folder
* flatten structure of `vmd` module in `transformation` after removal of nested package contents
* adds `README` to `libs` folder and `vmdpy`
* add tests folder for `vmdpy` (currently only readme example)
The changes in `vmdpy` and `transformations` do not require deprecation, as no public interfaces change.
=> [MNT] reorganization of onboard libs - `pykalman`, `vmdpy`

sktime/transformations/series/difference.py
Fixes #6480 by making the copy explicit. 
Make the copy explicit so that the warning is not shown. 
No
dependency isolation, see …
=> [BUG] in `Differencer`, make explicit clone to avoid `SettingWithCopyWarning`

sktime/benchmarking/evaluation.py, sktime/benchmarking/tests/test_TSCStrategy.py, sktime/benchmarking/tests/test_benchmarks.py, sktime/benchmarking/tests/test_evaluator.py, sktime/benchmarking/tests/test_experiments.py, sktime/benchmarking/tests/test_forecasting.py, sktime/benchmarking/tests/test_orchestration.py, sktime/benchmarking/tests/test_tasks.py
This PR adds differential testing decorators to the benchmarking module.
It also removes conditional skips based on the soft dependency `kotsu`, which is no longer used.
Towards #2890.
=> [MNT] enable differential testing in `benchmarking` module

sktime/forecasting/compose/tests/test_multiplex.py, sktime/forecasting/compose/tests/test_pipeline.py, sktime/forecasting/compose/tests/test_reduce.py, sktime/forecasting/compose/tests/test_reduce_global.py
This PR:
* simplifies tests in the `forecasting.compose.tests` module, by removing estimators with soft dependencies, and using fast forecasters in testing the framework
* adds differential testing for all tests in the module
Towards #2890.
=> [ENH] simplify and add differential testing to `forecasting.compose.tests` module

sktime/forecasting/tests/test_all_forecasters.py
Reverts parts of https://github.com/sktime/sktime/pull/6233 which cause `check_estimator` based tests in third party libraries to be always skipped.
This is due to `QuickTester.run_tests` propagating the skip conditoin up, affecting the entire test in the 3rd party package instead of just a single `sktime` test.
FYI @YelenaYY
=> [BUG] revert `pytest.skip` change from #6233

docs/source/api_reference/tags.rst
This PR fixes minor typos in the tags API reference text.
=> [DOC] fix minor typos in tags API reference

sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py
Fixes https://github.com/sktime/sktime/issues/6572 by patching over what seems like a `pandas` bug, using a try/except.
=> [BUG] patch over `pandas 2.2.X` issue in `freq` timestamp/period round trip conversion for period start timestamps such as `"MonthBegin"`

sktime/base/_panel/knn.py, sktime/classification/distance_based/_time_series_neighbors.py, sktime/dists_kernels/base/adapters/__init__.py, sktime/dists_kernels/base/adapters/_sklearn.py, sktime/regression/distance_based/_time_series_neighbors.py
This PR further refactors and deduplicates knn classifier and regressor.
* changes mixin to a callable distance adapter which can be passed to `sklearn`
* moves duplicative `_distance` function to distance adapter
* decouples distance adapter from assuming `self` attributes being set to explicit pass via constructor
* simplifies inheritance structure of knn classifier, regressor
The distance adapter - in particular uncoupling - ensures that it can be used more broadly across distance based estimators and adapters towards `sklearn` compatible estimators in the future.
=> [ENH] further refactor of knn classifier and regressor

sktime/forecasting/base/tests/test_base.py, sktime/forecasting/base/tests/test_base_bugs.py, sktime/forecasting/base/tests/test_fh.py
This PR adds differential testing and makes minor improvements to `forecasting.base` tests:
* replaces `ARIMA` with a faster and internal alternative
* refactors fixture generation
=> [MNT] differential testing and minor improvements to `forecasting.base` tests

sktime/performance_metrics/forecasting/probabilistic/__init__.py, sktime/performance_metrics/forecasting/probabilistic/_classes.py, sktime/performance_metrics/forecasting/probabilistic/tests/test_distr_metrics.py, sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py, sktime/performance_metrics/forecasting/tests/test_metrics.py, sktime/performance_metrics/tests/test_metrics_classes.py, sktime/performance_metrics/tests/test_numpy_metrics.py, sktime/performance_metrics/tests/test_performance_metrics_forecasting.py, sktime/performance_metrics/tests/test_segmentation_metrics.py
This PR adds differential testing for `performance_metrics` module.
Runs tests in the module iff any file within is changed.
Relies on https://github.com/sktime/sktime/pull/6617 to avoid merge conflicts.
=> [MNT] differential testing for `performance_metrics` module

docs/source/developer_guide/add_estimators.rst, sktime/utils/estimator_checks.py, sktime/utils/tests/test_check_estimator.py
This PR adds a `paramterize_with_checks` decorator utility for granular test setup of API compliance tests in 2nd/3rd party libraries.
It is a `pytest` decorator, inspired by [the `sklearn` utility of the same name](https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.parametrize_with_checks.html#sklearn.utils.estimator_checks.parametrize_with_checks).
Maintainers of third party libraries can use this with the following pattern to set up tests granular by test name:
```python
@parametrize_with_checks([NaiveForecaster, ExponentialSmoothing])
def test_sktime_compatible_estimators(obj, test_name):
check_estimator(obj, tests_to_run=test_name, raise_exceptions=True)
```
Supports both classes and instances, and all object types supported by `check_estimator`.
In case …
=> [ENH] `parametrize_with_checks` utility for granular API compliance test setup in 2nd/3rd party libraries

sktime/tests/_config.py
This PR aims to skip a few tests during the CI workflow for known and existing bugs to sporadic behaviour for `ProximityForest` and `ProximityTree`. For reference - see #6637.
In this PR we are planning to skip `test_multiprocessing_idempotent` and `test_classifier_output` for `ProximityForest` and `test_fit_idempotent` for `ProximityTree`. 
Hopefully that allows the CI workflows to pass successfully
=> [MNT] update tests._config to skip various tests for Proximity Forest and Proximity Tree

.all-contributorsrc
Re: pykalman utils.py PR 107  
https://github.com/pykalman/pykalman/pull/107
contributed to the python 3.11 compatibility upgrade for `pykalman`:
replaced deprecated `inspect.getargspec` by `inspect.getfullargspec `
=> [MNT] credit doberbauer for pykalman python 3.11 compatibility fix

sktime/datatypes/tests/test_convert.py, sktime/datatypes/tests/test_convert_to.py, sktime/utils/deep_equals/_deep_equals.py
The  `deep_equals` plugin for `scipy` `csr_matrix` is not compatible with the latest version `1.14`.
This PR changes the logic so it is.
Also ensures key locations in `sktime.datatypes` are tested if `deep_equals` plugins in `sktime` change.
=> [MNT] `scipy` `1.14.0` compatibility for `deep_equals` plugin for `csr_matrix`

sktime/utils/dependencies/_dependencies.py
After https://github.com/sktime/sktime/pull/6355, the `suppress_import_stdout` argument of `_check_soft_dependencies` no longer has any effect.
It is hence scheduled for deprecation with the 0.32.0 release.
=> [MNT] deprecate unused `_check_soft_dependencies` argument `suppress_import_stdout`

docs/source/roadmap.rst, docs/source/roadmap_2021.rst
I noticed that the roadmap documentation page still showed the 2021 roadmap - this is because since then planning moved to hackmd/wikis and then to issues, and apparently we forgot about that page.
To make management of the roadmap easier in the future and avoid forgetting about it in the docs, I've replaced the 2021 roadmap page with a link to issues tagged "roadmap". This will direct visitors of the docs to the place where the roadmap is actually being developed.
=> [DOC] rst roadmap documentation page stale since 2021 - replace by correct links to recent roadmaps

sktime/transformations/compose/_featureunion.py
Fixes #6678 by ensuring that the `requires_X` and `requires_y` tags are correctly set for `FeatureUnion`, based on component tags:
* `requires_X` is True if and only if *at least one* transformer in the pipeline requires `X` per `requires_X`
* `requires_y` is True if and only if *at least one* transformer in the pipeline requires `y` per `requires_y`
=> [BUG] ensure correct setting of `requires_X` and `requires_y` tag for `FeatureUnion`

sktime/transformations/compose/_pipeline.py, sktime/transformations/tests/test_compose.py
Fixes #6674 by ensuring that the `requires_X` and `requires_y` tags are correctly set for `TransformerPipeline`, based on component tags:
* `requires_X` is True if and only the *first* transformer in the pipeline requires `X`. This in particular should resolve #6674.
* `requires_y` is True if and only if *at least one* transformer in the pipeline requires `y`.
=> [BUG] ensure correct setting of `requires_X` and `requires_y` tag for `TransformerPipeline`

sktime/base/adapters/_pyts.py, sktime/base/adapters/_tslearn.py
The parameter forward refactor introduced a bug in `pyts` and `tslearn` adapters, where the direcation of forwarding was wrong - from the `self` to the wrapped estimator.
This is fixed, and should be merged quickly before release as the fixed bug has not been released yet.
=> [BUG] Fix bug in fitted parameter override in `pyts` and `tslearn` adapters

sktime/forecasting/arima/_pmdarima.py, sktime/forecasting/arima/_statsmodels.py, sktime/forecasting/sarimax.py, sktime/forecasting/var.py
This PR clarifies the different ARIMA estimators in the code base, and adds author credits for upstream.
Most confusingly, it seems there are two (S)ARIMA(X) models in `statsmodels`, both by the same set of authors, one inheriting from the other - `ARIMA` and `SARIMAX`. Unlike the naming implies, these are both (S)ARIMA(X) models.
I have no idea what is going on and neither the `statsmodels` docs nor the code base are illuminating on a superficial glance, so I am just adding clearer pointers that explain to the user what they are getting.
Also adds upstream sets of authors for credit, for `statsmodels` and `pmdarima` ARIMA models.
FYI @arnaujc91, or @yarnabrina (interface authors), do you know?
=> [DOC] clarify docs on ARIMA estimators, add author credits for upstream

sktime/transformations/panel/padder.py
This fixes dropped column names in `PaddingTransformer`, for some rare circumstanes.
This does not entirely fix, but is related to, #6679. See longer discussion there on the specific circumstances.
=> [BUG] partial fix for dropped column names in `PaddingTransformer`

sktime/forecasting/compose/_pipeline.py
Fixes https://github.com/sktime/sktime/issues/6678, which resulted in `y` set erroneously to `None` in `ForecastingPipeline`
=> [BUG] fix passing of `y` in `ForecastingPipeline`

sktime/forecasting/tests/test_interval_wrappers.py
This PR skips the failing test `test_wrapper_series_mtype` on the `gluonts` mtype `gluonts_ListDataset_series`.
This needs to be fixed, but is skipped to enable the release.
=> [MNT] skip failing test `test_wrapper_series_mtype` on `gluonts` datatype

.github/workflows/wheels.yml
Insta-release action for 0.30.2, 0.31.0 - temporary and should be reverted.
Most release jobs finish with success, but one or two always gets stuck and times out. We should really diagnose what is wrong here, the ones that run have decent test time.
=> [MNT] insta-release action for 0.30.2, 0.31.0

sktime/forecasting/base/adapters/_fbprophet.py, sktime/forecasting/trend/_pwl_trend_forecaster.py
Temporary silencing of issue https://github.com/sktime/sktime/issues/6720, `prophet` incompatibility with `numpy<2`.
=> [MNT] bound `prophet` based forecasters to `numpy<2` due to incompatibility of `prophet`

sktime/utils/dependencies/_dependencies.py
This PR refactors and fixes some silent bugs in the environment checker utiliits.
Refactor:
* checking of presence of individual packages and their versions is now factored out and `lru_cache`-d into a utility `_get_pkg_version`. This avoids checking presence or version of the same package twice.
* multiplied boilerplate for raising exception, warning, or nothing based on `severity` args is factored out into a single private method, `_raise_at_severity`
Bugfix:
* the refactor of `_raise_at_severity` has revealed that for multiple functions, the return in the case of `severity="warning"` was incorrect (`True` even if the package was missing or incompatible). This is not a serious bug as that case was no longer used in the code base. Either way, it is now fixed.
=> [ENH] refactor and bugfixes for environment checker utilities

sktime/forecasting/base/_fh.py, sktime/utils/datetime.py, sktime/utils/warnings.py
This PR adds suppressions for aggressive `freq` related warnings from `pandas 2.2`, as reported in https://github.com/sktime/sktime/issues/6694 (fixes #6694)
See https://github.com/sktime/sktime/issues/6245 for more permanent solutions
=> [MNT] suppress aggressive `freq` related warnings from `pandas 2.2`

.all-contributorsrc, sktime/transformations/hierarchical/aggregate.py
Fixes part of #3429.
Adds second test parameter to `Aggregator` transformation
No
No
=> [ENH] add second test params dict to Aggregator

pyproject.toml
https://github.com/sktime/sktime/issues/6766
https://github.com/sktime/sktime/issues/6291
While trying to reproduce #6291 , I installed `tbats` with Python 3.12 and it ran.
Note: The version of tbats on PyPI uses `setup.py` to declare requirements, and it does not list any constraints on versions there.
No
No …
=> [BUG] Remove tbats python version constraint

sktime/registry/_tags.py
Attempts to fix #6747
Minor formatting change to the docstring rst table for scitype_transform_input.
No
Seeing if the table renders correctly
No
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm …
=> [BUG] fix transformers type table in API referece in accordance with sphinx guidelines

docs/source/installation.rst
None
- add apostrophes to make dev install cross-platform (doesn't work on ~Mac~ `zsh` without apostrophes)
- Add indent before "install options" bullets to fix formatting
No
No
Issue with apostrophes was discovered at SciPy sprint
=> [DOC] Modify editable install to make cross-platform

sktime/transformations/panel/truncation.py
Added an example to the documentation for trunctransformer, and clarified the wording a bit.
Nope.
Does the example work? Is it a clearer description?
No new test functions, since it's just documentation, but I did test that the example works
I'm at SciPy 2024 learning about contributing to open source! …
=> [DOC] TruncationTransformer New Example

sktime/annotation/base/_base.py, sktime/annotation/tests/test_clasp.py
Closes #6741.
The `predict_segments` method was failing for change point detection algorithm because it was calling `segments_to_change_points` not `change_points_to_segments`.
No
No but it highlights the need for better annotation module tests. I will open a related issue.
The original issue contained a minimal example demonstrating the bug. This is now fixed.
```python
from sktime.annotation.clasp import ClaSPSegmentation
from sktime.datasets import load_gun_point_segmentation                                                                                                                                   from sktime.tests.test_switch import run_test_for_class
ts, period_size, cps = load_gun_point_segmentation()
clasp = ClaSPSegmentation(period_size, n_cps=1)
clasp.fit(ts)
segments = …
```
=> [BUG] Fix bug when predicting segments from clasp change point annotator

sktime/datatypes/_panel/_check.py
the check_pdmultiindex_panel error message now prints the names of columns if there are any of object type.
=> [ENH] `check_pdmultiindex_panel` to return names of invalid `object` columns if there are any

sktime/annotation/eagglo.py, sktime/benchmarking/_base_kotsu.py, sktime/benchmarking/_lib_mini_kotsu/registration.py, sktime/benchmarking/benchmarks.py, sktime/benchmarking/forecasting.py, sktime/benchmarking/tests/test_benchmarks.py, sktime/clustering/k_means/_k_means.py, sktime/clustering/k_medoids.py, sktime/clustering/metrics/averaging/_averaging.py, sktime/clustering/partitioning/_lloyds.py, sktime/clustering/tests/test_lloyds.py, sktime/datatypes/_panel/_convert.py, sktime/distances/_ddtw.py, sktime/distances/_distance.py, sktime/distances/_numba_utils.py, sktime/distances/_resolve_metric.py, sktime/distances/base/_base.py, sktime/distances/base/_types.py, sktime/distances/tests/_shared_tests.py, sktime/distances/tests/_utils.py, sktime/distances/tests/test_numba_distance_parameters.py, sktime/distances/tests/test_numba_distances.py, sktime/distances/tests/test_pairwise_distances.py, sktime/forecasting/compose/_skforecast_reduce.py, sktime/utils/_testing/_conditional_fixtures.py
As per official [documentation](https://docs.python.org/3.9/library/typing.html#typing.Callable), `typing.Callable` is deprecated in favour of `collections.abc.Callable`. This PR makes the corresponding changes in the imports, plus one fix single extra formatting issue in `sktime/datatypes/_panel/_convert.py`.
=> [MNT] Update `Callable` import from `typing` to `collections.abc`

sktime/transformations/series/adapt.py
This adds two features to `TabularToSeriesAdaptor`:
* passing `pandas`-like type with column names retained - fixes #6680
* allowing global pooling, i.e., passing pooled samples from all series to the `sklearn` transformer
=> [ENH] `pandas` inner type and global pooling for `TabularToSeriesAdaptor`

sktime/utils/dependencies/_dependencies.py
This PR switches out the current logic in the dependency checking module for retrieving installed package versions:
* all installed packages and their versions are queried only once and are cached, preventing additional runtime for any repeated checks
* the internal logic uses `importlib.metadata.distributions` directly
* as a consequence, package aliases and the install name are no longer needed, so given this we could even deprecate the respective tags (which are regularly leading to developer confusion)
The idea for this PR was contibuted by @dinobektesevic (using `pip`, but this is now using `importlib` instead)
=> [MNT] improved environment package version check

sktime/forecasting/base/adapters/_pytorchforecasting.py, sktime/forecasting/pytorchforecasting.py
This PR fixes incorrect setting of the `python_dependencies` tag on `PytorchForecastingTFT` and `PytorchForecastingNBeats` in branch main (was using the import name, not the pypi package name)
=> [BUG] correct dependency tag for `pytorch-forecasting` forecasters: rename `pytorch_forecasting` to correct package name `pytorch-forecasting`

sktime/datatypes/_convert.py
Fix Several type check warnings reported by Pyre@Google, which were outdated after code modifications.
1. update the argument `to_type` in function `convert` from `str` to `Union[str, List[str]]`, since it could be str or list of str after commit 0094f868c2930ceb3f246972dd34d15348469809
2. update the argument `as_scitype` in function `convert` from `str` to `Optional[str]`, since it could be str or None after commit 105ad4c4411fefbdc8ad587727f666a41a47ad1c 
3. update the argument `store_behaviour` in function `convert` from `str` to `Optional[str]`, since it could be str or None after commit b02a98b55c30b9fee3ab82af4c2636b03472022
4. update the argument `to_type` in function `convert_to` from `str` to `Union[str, List[str]]`, since it could be str or list of str after commit …
=> [MNT] updates and fixes to type hints

docs/source/api_reference/tags.rst
This small PR adds a cross-reference to the estimator search at the start of the tags API reference.
=> &yarnabrina [DOC] cross-reference estimator search from tags API reference

pyproject.toml
Latest pykan versions are causing to fail some test cases for pykan that affects the CI for all workflows. This PR bounds the versions to `pykan<0.2.2,>=0.2`, ensuring stable working of `PyKANForecaster` and not blocking other workflows.
=> [MNT] downgrade pykan version to <0.2.2

sktime/datatypes/tests/test_convert.py
So far, converter framework tests in `datatypes` were run only between mtypes without soft dependencies.
This PR switches the setting to cover all types, including those requiring soft dependencies, for soft dependencies present in the given environment.
=> [ENH] converter framework tests in `datatypes` to cover all types, including those requiring soft dependencies

sktime/datatypes/_adapter/gluonts.py, sktime/datatypes/_adapter/tests/test_gluonts.py, sktime/datatypes/_panel/_check.py, sktime/datatypes/_panel/_examples.py, sktime/datatypes/_series/_check.py, sktime/datatypes/_series/_convert.py, sktime/datatypes/_series/_examples.py, sktime/datatypes/tests/test_convert.py, sktime/forecasting/tests/test_interval_wrappers.py
This implements support for the GluonTS PandasDataset object as an sktime series scitype, and adds conversion functions to convert pd.DataFrame to a GluonTS PandasDataset. 
In addition, it fixes some prior GluonTS code and now enforces the test_interval_wrappers function!
Depends on https://github.com/sktime/sktime/pull/6838
GluonTS, but that was added prior already
A reviewer should focus on the sktime/datatypes/_adapter/gluonts.py file for the new changes
No, I had already defined tests in a prior PR
Assists with the #6659 PR.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving …
=> [ENH] Added support for GluonTS PandasDataset as a series scitype

sktime/datatypes/_series/_convert.py
Fixes a type inconsistency in conversion `pandas` to `xarray` based `Series`.
On windows - and only on windows - integer types may be converted to `int32` instead of `int64`.
=> [BUG] fix type inconsistency in conversion `pandas` to `xarray` based `Series`

sktime/transformations/base.py, sktime/transformations/series/detrend/mstl.py, sktime/transformations/series/detrend/tests/test_mstl.py
Fixes https://github.com/sktime/sktime/issues/6397, and more generally ensures that `MSTL` can be used in forecasting pipelines as expected. Also improves documentation, and fixes some unreported bugs in `MSTL`.
* `return_components` would not return components that sum to the original as expected. This has been fixed. I also consider the fact that the return in the case `return_components=True` included "transformed", which is "trend" plus "residual", a bug, since unexpected by the user.
* The docstring was incorrect in describing the components that were actually returned, in the case where `periods` were passed - not three components with seasonal components summed up, but seasonal components individually.
* `inverse_transform` did not work. This was also masked by the boilerplate …
=> [BUG] fix `MSTL` inverse transform and use in forecasting pipeline

sktime/transformations/base.py, sktime/transformations/panel/dictionary_based/_sfa.py, sktime/transformations/panel/dictionary_based/_sfa_fast.py
This PR makes the new access points for `self._is_vectorized` in `BaseTransformer` more defensive, by using `getattr` with a default instead of direct attribute access. The changes were introduced in https://github.com/sktime/sktime/pull/6825 to fix a bug with vectorization ov `inverse_transform`.
As @Abhay-Lejith has pointed out, the `SFA` transformer is failing as it overrides `fit` but not `transform` (see https://github.com/sktime/sktime/actions/runs/10147989805/job/28060326703?pr=6732).
This is not something an estimator should do, as it breaks the API extension pattern, but in case downstream users copied this pattern, at least they will not be impacted.
Also makes some minor changes to `SFA` transformer (setting the attribute in `fit`), and `SFAfast` (docstring formatting).
=> [ENH] making `self._is_vectorized` access more defensive in `BaseTransformer`

sktime/transformations/series/fourier.py
This PR clarifies the docstring of `FourierFeatures` about handling of the original columns. Previously, this was not too clear from the preamble, and only became evident after looking at all parameters.
This addition is to prevent the confusion in https://github.com/sktime/sktime/issues/6674 - when the transformer is used in isolation, a user might expect the original columns to be retained. However, by default, the columns are dropped, to ensure the expected behaviour when used as part of a pipeline.
FYI @kdekker-private, let me know if this seems clearer now.
=> [DOC] clarify column handling in docstring of `FourierFeatures`

sktime/libs/README.md, sktime/utils/git_diff.py
This PR resolves diacritics being decoded on windows and raises a decode error(`'charmap' codec can't decode byte 0x9d in position 3519: character maps to <undefined>`). Added the parameter to enforce encoding inside the `subprocess.check_output` function call.
=> [MNT] Resolve the issue with diacritics failing to be decoded on Windows

sktime/forecasting/autots.py
This PR enables by tag the passing of multivariate data to `AutoTS`.
This does not change any internal logic, it's just a check whether passing of multivariate data was disabled by mistake.
=> [ENH] enable multivariate data passed to `autots` interface

pyproject.toml
Mr-SEQL versions 0.0.3 and 0.0.4 was released on Aug 2, and it breaks the sktime interface conformance tests, see https://github.com/sktime/sktime/issues/6880
This PR restricts mrseql to <0.0.3 until the underlying issue is fixed.
=> [MNT] restrict failing Mr-SEQL version

sktime/forecasting/pykan_forecaster.py
Fixes some `pykan` related imports and dependency checks.
* `_check_soft_dependencies` to use correct PEP 440 specifier
* removed dependencies alias from the `pykan` based forecaster
There are failures on main which are also fixed by this.
=> [MNT] Fix `pykan` import and dependency checks

sktime/forecasting/model_evaluation/_functions.py
This PR fixes docstring formatting of forecasting `evaluate`, which has some odd indentations in places where line breaks are intended.
=> [DOC] fix docstring formatting of `evaluate`

sktime/utils/git_diff.py
This PR makes `pyproject.toml` parsing for differential testing more robust against non-package relevant changes, e.g., if a line is added that is not a valid package requirement string, such as in a case where `pyproject.toml` is changed outside the dependency specifications block.
Currently, this leads to an exception in `_get_packages_with_changed_specs`.
With the change, no exception is raised, as it is caught and considered a non-package related line.
=> [MNT] make `pyproject.toml` parsing for differential testing more robust against non-package relevant changes

build_tools/nb_json_formatter.py
This PR adds a formatter for jupyter notebook json in build tools, used for cleaning up the jupyter notebooks in https://github.com/sktime/sktime/pull/6847.
Question: is there sth in `ruff` that we could use as part of precommits, with similar or equal functionality? FYI @fnhirwa.
=> [ENH] formatter for jupyter notebook json in build tools

sktime/tests/test_switch.py
This PR syncs differential testing utilities with `skpro` anticipating a joint refactor to `skbase`.
Counterpart of https://github.com/sktime/skpro/pull/434.
Contains only minor changes in `sktime.tests.test_switch`, making variable naming and docstrings less `sktime` specific.
=> [MNT] sync differential testing utilities with `skpro`

sktime/utils/dependencies/_dependencies.py
Currently, `_check_soft_dependencies` behaves unexpectedly for post and pre versions of patch releases, for requirements and/or actuals such as `"my_pkg=2.3.4.post0"`.
This PR fixes the utility for that case, and adds a flag that determines whether pre/post identifiers should be ignored consistently.
This should also fix the current CI failures due to `matplotlib` `post` versions.
=> [BUG] fix `_check_soft_dependencies` for post and pre versions of patch versions

docs/source/index.rst
This PR adds a link pointing to an info page with voter and candidate registration for the upcoming council elections (deadline Sep 22) to the landing page of the webpage.
=> [DOC] add elections link on landing page

docs/source/developer_guide/git_workflow.rst
This PR makes two updates to the git workflow guide page in the developer guide:
* adds details on keeping chained branches up-to-date
* fixes the header sizes, which were the wrong way round
=> [DOC] git workflow guide - chained branches, fixing header fonts

sktime/annotation/bs.py, sktime/annotation/tests/test_bs.py
Related to #6481.
Implements binary segmentation as described in WILD BINARY SEGMENTATION FOR MULTIPLE
CHANGE-POINT DETECTION (https://arxiv.org/pdf/1411.0858).
Yes, added tests for the algorithm in `test_bs.py`. …
=> [ENH] Add binary segmentation annotator for change point detection

build_tools/changelog.py
This PR fixes a bug in the changelog utility, namely the termination condition to retrieve all merged PR since the last release.
The bug manifests as less PR being retrieved than merged.
The reason for this is the termination condition: the script retrieves PR, sorted by "updated at", until a PR is encountered that was merged before the release.
This terminates too early, in all cases where a merged PR before the last release gets updated so it ends up more recent than the last page that contains merged PR after the last release. The subsequent pages of PRs are incorrectly cut off then.
The fix is simple, the termination condition should be when a PR is encountered whose latest *update* was before the last release. Since PR are ordered by when the latest update was, this ensures that all …
=> [BUG] changelog utility: fix termination condition to retrieve merged PR

sktime/transformations/series/tests/test_time_since.py
Reverts an erroneous instance of a `pandas` deprecation fix related to `"M"` and `"ME"` frequencies.
=> [MNT] revert an erroneous instance of `pandas` deprecation fix

.github/actions/test-component/action.yml, .github/workflows/test.yml, .github/workflows/test_all.yml, .github/workflows/test_other.yml
This PR fixes the failures to https://github.com/sktime/sktime/commit/2819f431badebe3930cc6683ae7995c8442f940d
The path should be updated in workflow files as the script was moved to `.github`
=> [MNT] Update the path to script to fix #6926

sktime/transformations/panel/catch22.py
This PR fixes handling of `numpy` integers in refactored `Catch22` transformation for feature names, these would previously raise an error.
=> [BUG] fix handling of `numpy` integers in refactored `Catch22` transformation

sktime/utils/_estimator_html_repr.py, sktime/utils/tests/test_estimator_html_repr.py
This PR makes the version retrieval for the html repr safer and more flexible, by replacing a relative import with an import that uses the doc source attribute as a reference instead.
=> [ENH] in estimator html repr, make version retrieval safer and more flexible

sktime/forecasting/tests/test_all_forecasters.py
This PR fixes `test_global_forecasting_tag` to incorporate classes that are not inherited by `_BaseGlobalForecaster` rather inherit a class that inherits this. Current behaviour does not detect that the estimator supports global forecasting if it does not directly inherit `_BaseGlobalForecaster` and the global tests are not executed.
Problem was identified in https://github.com/sktime/sktime/pull/6928 where `LTSFLinearForecaster` inherits `BaseDeepNetworkPyTorch` which inherits `_BaseGlobalForecaster` and global capability could not be detected during tests.
=> [ENH] improve test_global_forecasting_tag

sktime/forecasting/compose/_reduce.py, sktime/forecasting/tests/test_all_forecasters.py
This PR removes a number of now superfluous try-excepts in forecasting API test suite `TestAllForecasters`, dating from a time where the interface was less unified, and calls with tag mismatches could lead more often to `NotImplementedError`.
* exogenous data can now always be passed, even if not used
* proba methods can always be called and raise an informative exception
* in-sample forecasts can always be called and raise an informative exception
=> [ENH] remove now superfluous try-excepts in forecasting API test suite

sktime/base/_base.py
`numba` used to be incompatible with `numpy 2`, requiring us to dynamically set estimator specific version bounds.
This PR removes the flag, as `numba` seems to be compatible with `numpy 2` now.
=> [MNT] remove `numpy 2` incompatibility flag from `numba` based estimators

sktime/base/_base.py, sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/base/_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/_reduce.py, sktime/forecasting/model_selection/__init__.py, sktime/utils/dependencies/_dependencies.py
Carries out deprecations and change actions scheduled for 0.32.0:
* remove `suppress_import_stdout` argument in `_check_soft_dependencies`
* bump deprecation/change checks scheduled for 0.32.0 to 0.33.0
=> [MNT] 0.32.0 deprecations and change actions

sktime/forecasting/base/tests/test_fh.py, sktime/forecasting/tests/test_varmax.py
This PR handles some remaining `pandas` related deprecation warnings:
* `"M"` and `"ME"` freqenties
* time delta `unit` argument
=> [MNT] handle more `pandas` deprecations

sktime/transformations/base.py
I noticed this bug while working on #6650. `Xt_msg` should be `dict`, not `list` (`Xt_msg.items` is called immediately afterwards).
=> [BUG] Fix Xt_msg type in tranformations.base

.pre-commit-config.yaml
Simple maintenance PR
1. `pre-commit autoupdate` -> bumped `ruff`
2. `pre-commit run --all-files` -> made no changes -> indicates all files on `main` are well formatted
=> [MNT] update versions of `pre-commit` hooks

.github/workflows/test.yml, pyproject.toml, sktime/forecasting/compose/_reduce.py, sktime/forecasting/compose/tests/test_reduce.py
`make_reduction` type inference breaks for non-sklearn estimators that follow the interface but do not inherit from `sklearn` `BaseEstimator`, e.g., `CatBoostRegressor`.
This is due to an accidental raise on such estimators, fixed by this PR.
=> [BUG] fix `make_reduction` type inference for non-sklearn estimators

sktime/base/_base.py, sktime/forecasting/compose/_pipeline.py
This PR adds a `numpy 2` incompatibility flag to the `pmdarima` dependency. The aim is to address https://github.com/sktime/sktime/issues/6975
This will result in test skips, but also raising an error message for users of `pmdarima` estimators with `numpy 2`.
My major concern is that the failure (a) does not seem to have appeared until recently, and (b) it is localized to a custom test and not the contract tests of `pmdarima` based estimators.
So, we may be breaking working code, say, if the `numpy 2` incompatibility of `pmdarima` is only localized or sporadic.
=> [MNT] add `numpy 2` incompatibility flag to `pmdarima` dependency

sktime/tests/test_softdeps.py
The `test_softdep_error` dependency handling check would incorrectly fail if only the environment marker tag was not satisfied, this is an unreported bug apparent in the CI of https://github.com/sktime/sktime/pull/6571 - the first onboard estimator using the `env_marker` tag.
This bug does not impact `check_estimator`, i.e., external API checks, as this is a separate test.
The reason for the failure was that the error message raised in the case that only the marker is mismatched was not caught as one of multiple potential, expected error messages, this has been fixed.
=> [BUG] fix `test_softdep_error` dependency handling check if environment marker tag is not satisfied

docs/source/api_reference/datasets.rst, sktime/datasets/__init__.py, sktime/datasets/_hierarchical_demo.py, sktime/datasets/tests/test_hierarchical_demo.py, sktime/datasets/tests/test_loaders.py
This PR adds the hierarchical sales toydata generator, which has now been used in many workshops, to the `datasets` module.
The generator was originally written by @marrov.
=> marrov [ENH] Hierarchical sales toydata generator from workshops

sktime/benchmarking/forecasting.py, sktime/forecasting/model_evaluation/_functions.py
Fixes #6964 
Checks if the parameter `y` is an instance of tuple. if yes it unpacks the tuple into two variables y and X …
=> [BUG] ForecastingBenchmark giving an error when the dataloader returns the tuple (y, X)

pyproject.toml
It appears that the maintainer of `tsbootstrap` is planning a narrowing of dependency bounds of multiple packages. This is likely going to cause dependency conflicts and problematic resolutions.
See https://github.com/astrogilda/tsbootstrap/pull/165
To prevent issues from reaching users, I propose to remove `tsbootstrap` from public facing dependency sets.
The interfaces will still be tested through the `all_extras_pandas2` set, although that may also be impacted by the changes.
=> [MNT] remove `tsbootstrap` dependency from public dependency sets

docs/source/api_reference/tags.rst, docs/source/developer_guide/dependencies.rst
This PR updates the soft dependency handling guide for estimators with:
* links to packaging tag API reference
* removal of the requirement to populate the dependency alias tag
=> [DOC] update soft dependency handling guide for estimators

sktime/utils/dependencies/_dependencies.py
This fixes https://github.com/sktime/sktime/issues/6987, i.e., all environment checks in case multiple distributions of a package are present in an environment.
This situation may arise for instance in deployment setups with a base environment that has a certain version, that is overridden by a more recent version in a virtual environment, e.g., on databricks.
In this case, present code returns the version of the *first* occurrence of the package in `sys.path`, but the *last* occurrence is the one that gets imported when doing `from package import something`.
The fix uses an idea of @toandaominh1997: instead of parsing the result of `distributions` for package names and versions, we just parse it for package names, and obtain the version from the `importlib.metadata.version` method. In …
=> &toandaominh1997 [BUG] fix dependency checkers in case of multiple distributions available in environment, e.g., on databricks

sktime/forecasting/prophetverse.py, sktime/utils/dependencies/__init__.py, sktime/utils/dependencies/_placeholder.py
This adds a placeholder record decorator for easy addition of external estimators to the index data records discoverable by the estimator overview or `all_estimators`.
It also replaces the current ad-hoc decorator for `Prophetverse` with this more general decorator.
=> [ENH] placeholder record decorator

sktime/forecasting/base/adapters/_fbprophet.py, sktime/forecasting/tests/test_prophet.py
This PR introduces a minor change in fbprophet adapter, flattening an array to get first value instead of calling `[0][0]` twice.
Fixes #6982 
Prophet().fit(y).get_fitted_params() was raising error if the the dataframe `y` contained a series with only constant values.
No
No, but could add if needed
=> [BUG] - Fix Prophet `_get_fitted_params `error when the timeseries is constant

examples/AA_datatypes_and_datasets.ipynb, sktime/datatypes/_panel/_convert.py, sktime/datatypes/_panel/_examples.py
This PR fixes the `nested_univ` converter, to return the index name of series nested in the dataframe. 
Fixes #7025
=> [BUG] Fix `nested_univ` converter inconsistent handling of index level names

sktime/forecasting/compose/_pipeline.py
This PR makes fixes to the `TransformedTargetForecaster` docstring, which had some small but consequential typos in the formalism.
=> [DOC] fixes to `TransformedTargetForecaster` docstring

sktime/clustering/k_means/_k_means.py, sktime/clustering/k_medoids.py, sktime/clustering/partitioning/__init__.py, sktime/clustering/partitioning/_lloyds.py, sktime/clustering/tests/test_lloyds.py, sktime/tests/_config.py
This renames the base class `TimeSeriesLloyds` to `BaseTimeSeriesLloyds`, as the test framework interprets classes that are not private and not starting as `Base` as concrete, leading `TimeSeriesLloyds` to be collected and fail tests.
Also removes the test skips for the class.
=> [MNT] rename base class `TimeSeriesLloyds` to `BaseTimeSeriesLloyds`

sktime/utils/numba/general.py, sktime/utils/numba/njit.py, sktime/utils/numba/stats.py
This PR removes module level `numba` import warnings which could be erroneously raised in some crawling cases or by import chains.
The modules are not locations that a user would normally import from, making this change a net improvement in my opinion, as most raises would be erroneus or uninformative.
=> [MNT] remove module level `numba` import warnings

sktime/classification/feature_based/_signature_classifier.py
It appears that `esig` is incompatible with `numpy 2`. See #7023.
This adds `numpy 2` bounds to the respective estimators.
=> [MNT] `esig` based estimators: add `numpy<2` bound

sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/tests/test_pipeline.py
The html display for `TransformedTargetForecaster` is failing since #6930, if estimators are passed as a list instead of list of tuples.
This is fixed by using the attribute that always returns a list of tuples. A test is also added.
=> [BUG] fix html display for `TransformedTargetForecaster` and `ForecastingPipeline`

sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/tests/test_forecastx.py
This PR fixes the issue that caused the `update` method to fail by getting the new values for `X` depending on the forecaster parameters when calling the update method.
fixes https://github.com/sktime/sktime/issues/6724
=> [BUG] Fix `ForecastX.update` when the `forecaster_X_exogeneous` is set to `"complement"`

sktime/performance_metrics/annotation/metrics.py, sktime/performance_metrics/tests/test_annotation_metrics.py
Closes #7031.
Implements the padded F1 score metric. This is a metric for evaluating the quality for predicted change points. The metric is described in this paper https://arxiv.org/pdf/2003.06222.
Yes
I have called this padded F1 score since it pads the true labels to be more forgiving of the predictions. Is anyone aware of another more appropriate name for this?
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, …
=> [ENH] Add padded f1 score for evaluating change point detection algorithms

docs/source/api_reference/transformations.rst
This PR splits the long list of transformation pipeline components, in the API reference, into sensible subcategories, for better user experience.
=> [DOC] split list of transformation pipeline components into subcategories

sktime/forecasting/pytorchforecasting.py
See also https://github.com/jdb78/pytorch-forecasting/issues/1632
I tried to reduce the load for the runner by reducing the batch size in the PyTorch forecasting models and reduced the model size of the TFT.
In my opinion, this PR is successful if in multiple runs, the CI is not crashing because of HEAP errors and crashed runners...
=> [MNT] Try to reduce load for the runners

sktime/datasets/_fpp3_loaders.py, sktime/datasets/tests/test_datadownload.py
FPP3 datasets are loaded from CRAN, using fixed URLs. CRAN updated two of the three URLs used by _fpp3_loaders.py. This PR updates the URLs accordingly (otherwise the functionality is broken.)
A reviewer can run the following code to test the change, if desired. 
```
import matplotlib.pyplot as plt
from sktime.datasets import load_fpp3
from sktime.utils.plotting import plot_series
y = load_fpp3('aus_production')['Beer']
fig, ax = plot_series(y)
plt.show()
```
=> URLs changed on CRAN; updated _fpp3_loaders.py accordingly

sktime/tests/test_all_estimators.py
This changes the `test_inheritance` contract to:
* check base class inheritance only based on registered scitypes strings occurring in `object_type`
* no longer require a certain number of mid level base classes to be present (no longer: at least one, and at most two, and two only if from a special list)
This also addresses four cases that had required special treatment, three of which already had one-off exception treatment in the test, contributing to a contract consisting more of exceptions than the rule in terms of code:
* the global forecaster extension by @XinyuWuu
* the polymorphic `Pipeline` by @benHeid 
* the legacy transformation mixins
* the `skchange` package of @tveten which includes extensions with new base classes and scitypes
Comments and feedback appreciated, especially …
=> [ENH] change `test_inheritance` to be more lenient to framework level extensions

pyproject.toml
With the 1.1.0 release, `pytorch-forecasting` supports python 3.12.
This Pr:
* removes the <3.11 restriction for `pytorch-forecasting`
* adds upper bound `<1.2.0`
=> [MNT] remove <3.11 restriction for `pytorch-forecasting`, add upper bound

docs/source/changelog.rst
This corrects some incorrect bounds mentioned in 0.33.0 changelog, changing the bounds in the changelog to the correct ones, as in the `pyproject.toml`.
=> [DOC] correct incorrect bounds mentioned in 0.33.0 changelog

sktime/forecasting/theta.py
I noticed that the parameter `initial_level` was not covered in the test paramater selections of `ThetaForecaster`.
This PR adds one more parameter set in `get_test_params`, so we also test a non-default for `inital_level`.
=> [ENH] `ThetaForecaster` - add one more parameter set

sktime/utils/retrieval.py, sktime/utils/tests/test_retrieval.py
This PR adds general retrieval utilities for all functions or classes in a module - this will be needed for a refactor of the `datatypes` module. Includes tests.
=> [ENH] retrieval utilities for all functions or classes in a module

docs/source/about/team.rst, docs/source/get_involved/governance.rst
This PR adds the four new core developers to the "team" page: @geetu040, @fnhirwa, @pranavvp16, @XinyuWuu.
Also:
* makes some formatting related changes - broken bullet point display, alphabetic ordering
* removes two core developers who have been inactive for a longer time: @chrisholder, @freddyaboulton
=> [DOC] update core developers on team page, formatting

sktime/transformations/series/tests/test_temporian.py
This adds a temporary skip (`xfail`) to the `temporian` related failure of `test_complex_function` until #7040 is resolved
=> [MNT] temporarily skip `temporian` related failure of `test_complex_function` until #7040 is resolved

sktime/transformations/series/difference.py, sktime/transformations/series/tests/test_differencer.py
This PR fixes the bug with `drop_na` reported in #7076, and further issues that arise when `transform` is called on data different from `fit`.
Adds tests covering the change:
* the example from #7076
* test cases where `fit` and `transform` indices are different
=> [BUG] fix `drop_na` and update mode of `Differencer` transformation

sktime/forecasting/base/_base.py
Forecasters probabilistic forecasts would fail if only `_predict_var` was implemented, as the dispatching logic was not correctly worked out. The bug was undetected and unreported, as #6424 seems to add the first such example.
I thought it was, but it was correct only in `sdkpro`. This PR fixes the issue by copying the same logic from `skpro` `BaseProbaRegressor`.
The PR and estimator in https://github.com/sktime/sktime/pull/6424 can be seen as a test. Fixes #7145.
=> [BUG] fix probabilistic forecasts if only `_predict_var` is implemented

sktime/forecasting/tests/test_all_forecasters.py
Presently, `test_pred_int_tag`, does not take into account `_predict_var` if implemented - this PR adds that to the logic.
=> [ENH] add `_predict_var` in `test_pred_int_tag`

sktime/datatypes/_alignment/__init__.py, sktime/datatypes/_alignment/_examples.py, sktime/datatypes/_base/__init__.py, sktime/datatypes/_base/_base.py, sktime/datatypes/_examples.py, sktime/datatypes/_hierarchical/__init__.py, sktime/datatypes/_hierarchical/_examples.py, sktime/datatypes/_panel/__init__.py, sktime/datatypes/_panel/_examples.py, sktime/datatypes/_proba/__init__.py, sktime/datatypes/_proba/_examples.py, sktime/datatypes/_series/__init__.py, sktime/datatypes/_series/_examples.py, sktime/datatypes/_table/__init__.py, sktime/datatypes/_table/_examples.py, sktime/utils/retrieval.py
Refactors the example fixtures in the `datatypes` module along the lines of https://github.com/sktime/skpro/pull/458:
* a base class for datatype examples, `BaseExample`, to replace the more ad-hoc dictionary design
* a complete refactor of all `_example` submodules to this interface
* a full refactor of the public framework module with `get_example` logic, in `datatypes`, to allow extensibility with this design
Beyond the refactor, sets the `polars` requirements for the `polars` data examples to `polars>=1.0`, and adds `pyarrow` as a requirement, consistent with the status quo in `skpro`.
Closes #7128, as it addresses the issue both from an isolation perspective, as well as the missing argument perspective.
=> [ENH] refactor `datatypes` example fixtures to `BaseObject` classes

sktime/forecasting/compose/_bagging.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/_reduce.py, sktime/registry/__init__.py, sktime/registry/_scitype.py, sktime/registry/tests/test_scitype.py, sktime/transformations/base.py, sktime/transformations/compose/_transformif.py, sktime/utils/_testing/estimator_checks.py, sktime/utils/_testing/scenarios_classification.py, sktime/utils/_testing/scenarios_clustering.py, sktime/utils/_testing/scenarios_forecasting.py
Alternative to #7137 #7136 #7135
Introduces a new method `is_scitype`, which checks if an estimator has the same scitype as at least one of the elements from a list of strings, `scitypes`
No
Are the missing instances where `is_scitype` should be used
See here for further details …
=> [ENH] `is_scitype` utility for scitype checking, improve support of estimators with multiple object types

sktime/forecasting/reconcile.py, sktime/forecasting/tests/test_reconcile.py
#7107 and  #4767
Adds a parameter `total` to the reconciler forecaster which when False returns the dataframe without the dunder (__total) levels
=> [BUG] Adding a parameter to `reconciler forecaster` to return a dataframe without the dunder levels

README.md
Inspired by the `pytorch-forecasting` box at the top of the README, replaces the wasteful top row which only contained the word "Overview" with three links to key locations on the sktime documentation page - user docs, tutorials, changelog.
=> [DOC] add quicklinks at top of README box

sktime/transformations/panel/signature_based/_signature_method.py
From `test-all`, `SignatureTransformer` is incompatible with `numpy 2`, this PR restricts it to `numpy<2`, similar to `SignatureClassifier` which uses it under the hood.
Closes #7023, as it is seems the `esig` package is no longer maintained.
=> [MNT] bound `SignatureTransformer` to `numpy<2`

docs/source/index.rst
This removes the 2024 elections registration news item from the landing page, as elections registration for voters and candidates has ended on Sep 22, see https://github.com/sktime/elections
=> [DOC] remove 2024 elections registration news item

sktime/forecasting/base/adapters/_pytorchforecasting.py
This PR removes the hard coded python version bound from `pytorch-forecasting` based estimators
=> [MNT] remove python version bound from `pytorch-forecasting` based estimators

extension_templates/classification.py, extension_templates/clustering.py
This PR removes references to `nested_univ` from the classification and clustering extension templates. Reason, this mtype is semi-deprecated and not recommended.
=> [DOC] remove references to `nested_univ` from extension templates

.github/workflows/test.yml, examples/01c_forecasting_hierarchical_global.ipynb
Split part of https://github.com/sktime/sktime/pull/6628, removes `pytorch-forecasting` install from jupyter notebook, instead moves it to the CI.
=> XinyuWuu [MNT] remove ptf install from example notebook

sktime/datasets/tests/test_datadownload.py
Addresses the isolation in #7177, but does not resolve the testing issue.
Skip the test `load_fpp3` if the package `rdata` is not installed
=> [BUG] skip the test `load_fpp3` if rdata is not installed

sktime/transformations/panel/hog1d.py
This PR adds a get_test_params method to the HOG1D Transformer class. The test `sktime.tests.test_all_estimators.TestAllObjects.test_get_test_params_coverage` was failing because of it missing.
=> [ENH] HOG1D Transformer add new test parameter set to `get_test_params`

.all-contributorsrc, sktime/transformations/panel/padder.py
This PR adds an example to the docstring of `PaddingTransformer`.
As discussed in #4264.
Initial contribution at PyData Paris 2024 sprint.
=> [DOC] add docstring example for `PaddingTransformer`

sktime/transformations/series/filter.py
This Pr adds a docstring example to the `Filter` transformer.
Towards #4264.
Demo issue for pydata Paris 2024.
=> [DOC] add docstring example to `Filter` transformer

sktime/datatypes/_adapter/polars.py
Changed the way to calculate the number of actual features to solve performance issues #7134
Fixes #7134 
I have updated the way to calculate the number of actual features in the LazyFrame to improve performance. The previous method raised performance warnings during execution, particularly when determining the width of a LazyFrame. I have replaced the line:
```python
metadata["n_features"] = obj.width - len(index_cols)
metadata["n_features"] = obj.collect_schema().len() - len(index_cols)
```
This change avoids the costly operation of resolving the schema and thus addresses the performance warnings.
No, this change does not introduce any new dependencies.
The effectiveness of the new method for calculating the number of features.
Ensure that performance warnings no longer occur when …
=> [ENH] Fix polars `PerformanceWarning` when object is of type `polars.LazyFrame`

sktime/transformations/series/theta.py
This PR adds the get_test_params method to the ThetaLinesTransformer class, providing standardized parameter settings for testing.
What does this implement/fix? Explain your changes.
This change implements the get_test_params method, which returns a list of dictionaries containing test parameters for the  ThetaLinesTransformer. This will facilitate easier testing and validation of the transformer’s functionality.
Does your contribution introduce a new dependency? If yes, which one?
No new dependencies were introduced.
What should a reviewer concentrate their feedback on?
The implementation of the get_test_params method
The clarity of the parameter settings provided for testing
Did you add any tests for the change?
Yes, relevant tests have been added to ensure the functionality of …
=> [ENH] Added get_test_params in ThetaLinesTransformer 

docs/source/developer_guide.rst, docs/source/installation.rst
This PR deduplicates and clarifies the install instructions for `sktime`.
* deduplicates the instructions with the Git setup page
* deduplicates two sections on developer install
* removes ambiguous instrutions that lead to a non-editable install
* adds quotation marks for all install commands to ensure compatibility with all OS
* adds warning on liability or cost when using commercial conda distributions like Anaconda
=> [DOC] clearer install instructions

sktime/forecasting/tests/test_timesfm.py, sktime/forecasting/timesfm_forecaster.py, sktime/transformations/compose/_logger.py, sktime/utils/singleton.py, sktime/utils/tests/test_singleton.py
This PR ensures that `timesfm` zero-shot model instances are not repeatedly loaded into memory for same configurations and repo IDs.
This is ensured by wrapping the `timesfm` package facing constructor in a multiton pattern, with key uniquely determined by configuration and repo ID.
Depends on the multiton pattern decorator refactor in #7203.
Closes #7201.
Also adds a test that ensures that the tests on `TimesFMForecaster` are run in the linux/3.10 combination.
=> [ENH] cached `timesfm` instance in case of repeated use

sktime/forecasting/darts.py, sktime/tests/_config.py
this pr fixes the failure of the `DartsLinearRegression` which was failing instead of raising a warning.
it adds `message` to be passed correctly instead of using `message` as a keyword argument.
Also skipping tests for `DartsXGBModel` as it causes timeout errors as reported in https://github.com/sktime/sktime/pull/7110
fixes https://github.com/sktime/sktime/issues/7224
=> [BUG] Fix `DartsLinearRegression` failing instead of giving a warning

sktime/forecasting/squaring_residuals.py
Python 3.13 compabitiliy update for `SquaringResiduals`.
The `eval` statements in the estimator seem not compatible with 3.13 - they are replaced by equivalent `getattr` statements instead.
=> [ENH] python 3.13 compatibility - `SquaringResiduals`

sktime/registry/_craft.py, sktime/registry/tests/test_craft.py
This PR makes the `eval` and `locals` calls in `craft` python 3.13 compatible.
Also adds further tests for `craft` to ensure better coverage if soft dependencies are not present.
=> [ENH] python 3.13 compatibility - `craft`

sktime/classification/distance_based/_time_series_neighbors.py, sktime/regression/distance_based/_time_series_neighbors.py
Improves docstrings for `sktime` native k-nearest neighbours classifier and regressor, with a focus on explaining the use of `sktime` distances to handle multivariate and unequal index cases.
Inspired by #7232
=> [DOC] improved docstrings for k-nearest neighbours classifier and regressor

sktime/transformations/series/augmenter.py
I have added the missing import statements in ReverseAugmenter docstring example to make it easy for user to quickly copy and paste the example to test it out. This fix was in accordance with the issue #4400.
=> [DOC] added missing import statements in ReverseAugmenter docstring example

sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py
Fixes #7170 
Use `Period` instead of `PeriodIndex` for performing mathematical operations
no
add a unit test 
dependency …
=> [BUG] fix ForecastingHorizon `to_absolute` wiht multiple frequencies

sktime/forecasting/reconcile.py, sktime/forecasting/tests/test_reconcile.py
The test `test_reconcilerforecaster_return_totals` would sporadically fail due to singular matrices.
This is due to the length of the time series - 12 - being equal to the number of time series, which can result in near-singular matrices due to the random generation.
Reducing the number of time series should substantially lower the probability of this, as done in this PR.
=> [BUG] fix singular matrices in `test_reconcilerforecaster_return_totals`

pyproject.toml
This PR adds `skchange` to soft dependency sets:
* `all_extras`
* `all_extras_pandas2`
* `annotation`
This PR also:
* removes `skchange` from the `binder` dependency set
* adds a new soft dependency set `detection` which is identical to `annotation`.
=> [MNT] add `skchange` to extras

sktime/annotation/base/_base.py, sktime/base/_base.py, sktime/classification/early_classification/_probability_threshold.py, sktime/forecasting/base/_fh.py, sktime/forecasting/base/tests/test_fh.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/model_selection/__init__.py, sktime/forecasting/model_selection/_tune.py
Carries out deprecations and change actions scheduled for 0.34.0:
* remove internal `self.task` and `self.learning_type` from `BaseSeriesAnnotator`
* remove python 3.8 EOL warnings, as python 3.8 has now reached EOL
* bump deprecation/change checks scheduled for 0.33.0 to 0.34.0
=> [MNT] 0.34.0 deprecations and change actions

sktime/classification/deep_learning/cntc.py, sktime/regression/deep_learning/cntc.py, sktime/tests/_config.py
Fixed #6467, by fixing input formatting.
=> [ENH] fix input shape in `CNTCClassifier` and `CNTCRegressor`

docs/source/changelog.rst
Makes minor changes to the changelog, 0.33.2:
* better explanation of the new scoring parameters `alpha` and `coverage`
* typo fixes
=> [DOC] fix typos in changelog, better explanation of scoring parameters

sktime/transformations/series/dropna.py
This PR fixes some part of issue #4400 
This PR adds an example to the docstring of the `DropNA` class in `sktime/transformations/series/dropna.py`. The example demonstrates how to use the `DropNA` transformer, including necessary imports and a sample usage scenario.
No, this change does not introduce any new dependencies.
- The clarity and correctness of the added example in the docstring
- Whether the example adequately demonstrates the usage of the `DropNA` transformer
No new tests were added as this is a documentation change.
This change aims to improve the usability of the `DropNA` transformer by providing a clear, executable example in its docstring.
- Not applicable as this is not a new estimator.
=> [DOC] add docstring example for `DropNA`

sktime/libs/README.md
This PR adds `uni2ts` in the list of sktime vendor packages in `sktime/libs/README.md`
=> [DOC] Add uni2ts in libs/README.md

docs/source/api_reference/detection.rst
Fixes #7371 
Added Binary Segmentation Estimator in `docs/source/api_reference/detection.rst`
=> [DOC] Add Binary Segmentation Estimator to API reference

docs/source/api_reference/clustering.rst
This PR adds a sub-division of the existing categories in the API reference for clustering, and the missing DBSCAN algorithm.
=> [DOC] categories for clustering algorithms in API reference

docs/source/api_reference/data_format.rst, sktime/datatypes/_table/_base.py, sktime/datatypes/_table/_check.py
Fixes some issues with the new API reference for data formats:
* adds missing `Table` scitype - broken link
* fixes missing mtype entries
=> [DOC] fixes to the mtype API reference

sktime/registry/_base_classes.py, sktime/registry/_lookup.py
This refactors `_check_estimator_types` to use the new record class interface, removing the need to construct a full lookup of base classes, reducing coupling in the process.
=> [ENH] refactor `_check_estimator_types` to use record class interface

examples/01c_forecasting_hierarchical_global.ipynb, examples/AA_datatypes_and_datasets.ipynb, sktime/datatypes/_panel/_check.py
This PR fixes multiple duplications of the word "correspond", replacing "correspond correspond" by simply "correspond".
I am surprised there were so many in the code base (nine), perhaps this is case of copy-paste proliferation.
=> [DOC] fix duplications of the word "correspond"

sktime/forecasting/croston.py
Fixes #6675 
`Croston` does not use exogenous features passed in `X` in different methods, and the value of `ignores-exogeneous-X` tag should be `True`. It was incorrectly set as `False`, and this PR addresses that.
=> [BUG] rectify `ignores-exogeneous-X` tag value in `Croston`

.all-contributorsrc, sktime/transformations/series/holiday/_holidayfeats.py
When looking at HolidayFeatures API documentation, there's no mention of module loading path. Only after looking to source I found it. When giving examples I would expect imports too.
no
Nothing really
No. But I not sure that sktime's documentation is tested. I saw plugin to docs - doctests, but it needs to be run, not only included into conf.py. 
No
- [x ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. …
=> [DOC] Add import location to HolidayFeatures docs

sktime/forecasting/compose/_ensemble.py, sktime/forecasting/online_learning/_online_ensemble.py
Resolves #7407. 
A common use case with ML estimators is to create an ensemble estimator with N replicates of the same estimator. This PR facilitates this use case.
Previously, an ensemble forecaster was created via EnsembleForecaster( forecasters, ... ), with forecasters being a list of 2-tuples [(str1, estimator1), ..., (strN, estimatorN)]. This is a bit tedious if many of the estimators are identical.
This PR allows each tuple to be either of the form (str, estimator) (as before) or (str, estimator, count). This latter form says to create count replicates of the estimator.
=> [ENH] `EnsembleForecaster` option to specify multiple copies of same forecaster easily

sktime/base/_meta.py, sktime/forecasting/compose/_ensemble.py
This PR combines a refactor with a fix:
* brings `_HeterogeousMetaEstimator._check_estimator` to parity with `scikit-base`
* fixes issues with `EnsembleForecaster.__init__` introduced in https://github.com/sktime/sktime/pull/7424
The two are combined due to small footprint and dependency.
=> [ENH] parity of `_HeterogenousMetaEstimator._check_estimator` with `skbase` and fixes in `EnsembleForecaster.__init__`

sktime/forecasting/neuralforecast.py
Adds learning rate scheduler related arguments in existing RNN and LSTM estimators from `neuralforecast`.
=> [ENH] Add new arguments to neuralforecast rnn and lstm

sktime/annotation/tests/test_all_annotators.py, sktime/utils/_testing/annotation.py
This PR renames the private `make_annotation_problem` to `make_detection_problem`, in line with the current rename rework of hte module, see https://github.com/sktime/sktime/issues/7295.
This utility is entirely private and used only in testing, so no deprecation is needed.
=> [ENH] rename private `make_annotation_problem` to `make_detection_problem`

sktime/annotation/bs.py, sktime/annotation/hmm_learn/base.py, sktime/detection/base/_base.py, sktime/registry/_tags.py, sktime/tests/test_all_estimators.py
This PR makes minor improvements to the `BaseDetector` class:
* extension of existing capability tags to detector
* addition of `capability:update` tag for offline vs online detection
* boilerplate code to skip `_fit` and `_update` if `fit_is_empty` tag is set
* fix incorrect value of `fit_is_empty` tag in `hmmlearn` estimators
Besides the above, an explicit error message is added in `TestAllEstimators`, closely related to testing tag vailidity of tags such as the above.
=> [ENH] minor improvements to `BaseDetector`

sktime/utils/tests/test_check_estimator.py
The tests for `check_estimator` would fail with uninformative error, as the dict would contain `Exception` descendants in case of failure and not - as a subroutine assumed - strings starting with `FAIL` or similar.
This PR fixes this failure case and ensures the failure condition is clearly handled.
=> [BUG] fix `check_estimator` test in case of failure

sktime/detection/base/_base.py, sktime/detection/tests/test_base.py
This PR fixes the logic in `BaseDetector.change_points_to_segments` which was off and returning odd results, even failing if `start` was not set.
Fixes the call in `predict_segments` which was assuming `loc` rather than `iloc` indexing.
Adds tests for `change_points_to_segments`.
=> [BUG] fix `BaseDetector.change_points_to_segments`

sktime/tests/_config.py, sktime/transformations/panel/compose.py
In accordance with issue #7431, I have updated `get_test_params` method for `ColumnTransformer` to ensure 2 parameter tests sets.
=> [ENH] added test parameter set for ColumnTransformer

.github/workflows/test_all.yml, .github/workflows/test_module.yml, .github/workflows/test_other.yml
With the full transfer of tests from `annotation` to `detection`, the CI for the `detection` alias `annotation` module should be pointed to the `detection` module.
This PR carries out that change of pointer.
=> [MNT] `detection` module - move CI from `annotation` module

examples/07_detection_anomaly_changepoints.ipynb
This PR renames `Capa` to `CAPA` in the detection notebook, following the same rename in `skchange`.
=> [ENH] `skchange` rename of `Capa` to `CAPA`

sktime/detection/compose/_pipeline.py, sktime/detection/lof.py, sktime/tests/_config.py
This PR fixes the API incompatibility of the `SubLOF` detector - this is crucial as it was used as a component in other detector test casess such as the `DetectorPipeline`.
Consequently, this PR re-enables tests of `SubLOF` and also `DetectorPipeline`. Fixes #7415.
=> [ENH] fix API incompatibility of `SubLOF` detector

sktime/detection/compose/_as_transform.py, sktime/detection/compose/_pipeline.py
This PR makes minor updates to the `DetectorPipeline` and `DetectorAsTransformer` inner calls docstrings, to use the module `detectors`, and the term "detection" instead of "annotation".
Also changes the names of some private methods - no deprecation required, as these are private.
=> [ENH] update `DetectorPipeline` and `DetectorAsTransformer` inner calls and docstrings

sktime/performance_metrics/forecasting/_classes.py
Improves formatting of forecasting metric docstrings concerning the `multilevel` and `multioutput` parameters.
=> [DOC] improve formatting of forecasting metrics

pyproject.toml
It seems that the new minor version of `peft` is causing the problems in https://github.com/sktime/sktime/issues/7492.
This PR adds an upper bound on `peft` that prevents this newer version, 0.14.0, from being installed.
Not a conclusive fix for #7492, but should ensure stability of dependencies until fixed.
=> [MNT] bound `peft<0.14.0`

sktime/forecasting/hf_transformers_forecaster.py, sktime/forecasting/ttm.py
Addressing the CI failures observed in #7488
> RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback): cannot import name 'EncoderDecoderCache' from 'transformers' (/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/transformers/init.py)
=> [MNT] remove top level import of transformers

sktime/forecasting/compose/_skforecast_reduce.py
Towards #7451
As outlined in https://github.com/sktime/sktime/issues/7451#issuecomment-2506334247, this PR restricts `SkforecastAutoreg` to `skforecast<0.14`. There will be no user visible changes for the time being since skforecast is bounded in pyproject.toml similarly so far.
=> [MNT] add upper bound to skforecast autoreg adapter

sktime/utils/_estimator_html_repr.py
This PR addresses the issue raised about encoding scheme when parsing html files on traditional Chinese windows systems, we are supposed to pass the `encoding` argument  to the open function to enforce `ute-8`
closes https://github.com/sktime/sktime/issues/7479
=> [BUG] Fix codec error on traditional Chinese Windows systems

sktime/detection/adapters/_pyod.py, sktime/detection/bs.py, sktime/detection/clasp.py, sktime/detection/clust.py, sktime/detection/compose/_pipeline.py, sktime/detection/eagglo.py, sktime/detection/ggs.py, sktime/detection/hmm.py, sktime/detection/hmm_learn/base.py, sktime/detection/lof.py, sktime/detection/stray.py
This PR populates the author and maintainer tags of estimators in the detection module that predate the major rework - these did not have the tags properly populated.
Tags are populated from commit history and/or author fields on module level.
=> [ENH] detection module rework - populate author and maintainer tags

sktime/base/_meta.py, sktime/classification/compose/_pipeline.py, sktime/clustering/compose/_pipeline.py, sktime/dists_kernels/compose.py, sktime/forecasting/compose/_grouped.py, sktime/forecasting/compose/_pipeline.py, sktime/forecasting/compose/_transform_select_forecaster.py, sktime/param_est/compose/_pipeline.py, sktime/registry/_tags.py, sktime/regression/compose/_pipeline.py, sktime/transformations/compose/_column.py, sktime/transformations/compose/_featureunion.py
Implements #7222 
Fixes #7152 
- update `sk_visual_block` method of `_HeterogenousMetaestimator` to be based on the `visual_block_kind` tag
- add `visual_block_kind` to tags registry
- add new `_steps` and `steps_` properties to:
- `ParamFitterPipeline`
- `PwTrafoPanelPipeline`
- `RegressorPipeline`
- `ClassifierPipeline`
- `ClustererPipeline`
- `PwTrafoPanelPipeline`
- `GroupbyCategoryForecaster` 
- `Permute`
- change `FeatureUnion`'s visual_block_kind tag to parallel and update `_steps_attr` to correct format (an iterable of (name: str, estimator) tuples)
- update `_steps_attr` of `GroupbyCategoryForecaster` and `TransformSelectForecaster` to point to default (the steps properties). Change their `visual_block_kind` tag to parallel.
- update `_steps_attr` of ColumnEnsembleTransformer …
=> [ENH] html display of estimators - tag and consistent handling of via `_steps_attr` in `HeterogenousMetaEstimator` descendants

sktime/registry/_base_classes.py, sktime/tests/test_class_register.py
This PR moves the test class registry to the type registry, reducing the number of extension points by one if a new scitype is added.
Fixes https://github.com/sktime/sktime/issues/7493.
As a side effect, also reduces the number of deprecation points for defunct scitypes such as `series-annotator` by one - the release manager notes have been updated to take this into account as well.
=> [ENH] Refactor test class registry to type records

sktime/forecasting/base/_meta.py, sktime/forecasting/compose/_hierarchy_ensemble.py, sktime/forecasting/compose/tests/test_hierarchy_ensemble.py
This PR fixes the `get_fitted_params` not yielding access to component forecasters in some descendants of `_HeterogenousEnsembleForecaster` descendants.
The reason was that the `_steps_fitted_attr` was not set, likely because `get_fitted_params` was introduced after some of the affected forecasters.
This is now fixed - also fixes https://github.com/sktime/sktime/issues/7418
=> [BUG] fix `get_fitted_params` access to wrapped estimators in `_HeterogenousEnsembleForecaster` descendants

sktime/classification/deep_learning/cnn.py, sktime/classification/deep_learning/cntc.py, sktime/classification/deep_learning/fcn.py, sktime/classification/deep_learning/lstmfcn.py, sktime/classification/deep_learning/mcdcnn.py, sktime/classification/deep_learning/mlp.py, sktime/classification/deep_learning/resnet.py, sktime/networks/cnn.py, sktime/networks/fcn.py, sktime/networks/inceptiontime.py, sktime/networks/mcdcnn.py, sktime/networks/mlp.py, sktime/networks/resnet.py, sktime/regression/deep_learning/cnn.py, sktime/regression/deep_learning/cntc.py, sktime/regression/deep_learning/fcn.py, sktime/regression/deep_learning/inceptiontime.py, sktime/regression/deep_learning/mcdcnn.py, sktime/regression/deep_learning/mlp.py, sktime/regression/deep_learning/resnet.py
Upon reviewing https://github.com/sktime/sktime/issues/7453, I noticed that a lot of code in the TSC module was copied from dl-4-tsc - without giving clear credit to @hfawaz, e.g., not mentioning them in the authors tag fields.
This has been rectified by:
* adding @hfawaz as the first author to the `authors` tag
* moving the reference to dl-4-tsc to the top of the estimator card
FYI @skinan
=> [DOC] add proper credits to hfawaz and dl-4-tsc in various time series classifiers

sktime/detection/_datatypes/__init__.py, sktime/detection/_datatypes/_check.py, sktime/detection/tests/test_all_detectors.py
This PR refactors the checks for detector outputs from `TestAllDetectors` to a separate module, `detection._datatypes`.
This is in order to introduce a data checker layer similra to `datatypes`, without fully integrating with the `datatypes` machinery yet - as we will probably reuse the utilities inside `BaseDetector` before that.
=> [ENH] refactor checks for detector outputs into separate module

sktime/detection/_datatypes/_convert.py, sktime/detection/_datatypes/_examples.py, sktime/detection/_datatypes/test/__init__.py, sktime/detection/_datatypes/test/test_convert.py, sktime/performance_metrics/detection/_base.py, sktime/performance_metrics/detection/tests/test_base.py
Currently, detection metrics can accept segments or point event detections, as determined by the `"scitype:y"` tag.
Currently, if a metric is given the other type, it fails.
This PR adds conversion between the two types with, in my opinion, sensible choices to use in detection metrics - so all metrics can now be provided with point or segment detections.
Under the hood, this uses new `datatypes`-like functionality in the `detection` module - optimally, mid-term this gets refactored to deduplicate with the converters in `BaseDetector`, or moved to `sktime.datatypes` as an mtype.
However, for the time being, it seemed more sensible to add new code, as the conversions required for metrics are not exactly those in the base class.
=> [ENH] Detection metrics - coercion to detection type in boilerplate

sktime/tests/test_softdeps.py, sktime/utils/_testing/tests/test_check_imports.py, sktime/utils/dependencies/_dependencies.py
Syncs the dependency checker utilities with `scikit-base`, in anticipation of a refactor deduplication.
=> [ENH] sync dependency checkers with `scikit-base`

docs/source/api_reference/tags.rst, sktime/registry/_tags.py
This PR adds documentation for the new `visual_block_kind` tag introduced in https://github.com/sktime/sktime/pull/7233 by @mateuszkasprowicz, in the API reference for developers.
Probably by accident, the tag was added to the list of tags scheduled for deprecation in the tag registry, from where it has also been removed.
=> [DOC] document new `visual_block_kind` tag

sktime/transformations/panel/catch22.py
Adds missing docstrings for functions under [catch22.py](https://github.com/sktime/sktime/blob/main/sktime/transformations/panel/catch22.py). Came across this when reading about Catch22 Transformer. …
=> [DOC] Add missing docstring for functions in `/transformations/panel/catch22.py`

sktime/registry/_base_classes.py, sktime/registry/_lookup.py
This PR changes `all_estimators` retrieval to be entierly tag based.
Previously, retrieval and indexing used class inheritance to determine the type of an estimator. This has now been completely changed to using tag based retrieval, via the `object_type` tag that all estimators in `sktime` possess.
Advantages:
* more idiomatic, minimizing API points for retrieval
* there are less cached lists of retrieved classes internally
=> [ENH] change `all_estimators` retrieval to be entirely tag based

sktime/datatypes/_adapter/gluonts.py, sktime/datatypes/_adapter/tests/test_gluonts.py, sktime/datatypes/_panel/_check.py
Fix #7551 
I've added a general set of checks  under `_check` function for the `PanelGluontsList` class. Have not updated the docstring if this is required.
Feedback on the general implementation of code and any other requirements.
See here for further details on the [algorithm …
=> [ENH] Remove `gluonts dependency` in `gluonts_ListDataset_panel` mtype

sktime/transformations/panel/tsfresh.py
Temporary fix for https://github.com/sktime/sktime/issues/7600 - bounds `scipy<1.15` on the `tsfresh` based estimators.
This is only temporary and should be reverted after a proper fix.
=> [MNT] `tsfresh` estimators - temporary bound on `scipy`

sktime/classification/sklearn/_rotation_forest.py, sktime/classification/sklearn/tests/test_rotation_forest.py
Fixes #7022 
The `RotationForest` estimator is now inherited from `ClassifierMixin` and the test for `sklearn` compatibility - `parametrize_with_checks` has also been added in `test_rotation_forest.py`. …
=> [ENH] add `sklearn` compliance to `RotationForest`

sktime/forecasting/auto_reg.py
Fixes #7653 
The [AutoREG documentation](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.auto_reg.AutoREG.html) included arguments such as endog and exog that are not present in the model and have been removed .
No
See here for further details on …
=> [DOC] AutoREG docstring includes non-existent arguments #7653

sktime/forecasting/hf_transformers_forecaster.py, sktime/forecasting/ttm.py
Description:
This update (Fixes #7644) modifies the code to ensure that the y_test dataset is only created when validation_split is not None. If validation_split is None, no y_test dataset is created, and it is not passed to the Trainer. This change optimizes resource usage and eliminates unnecessary processing when validation data is not required.
Key Changes:
Added a conditional check to create y_test only when validation_split is provided.
Ensured that y_test is excluded from being passed to the Trainer when validation_split is None.
=> [ENH] Validation split fix issue 7644

sktime/forecasting/pytorchforecasting.py
Add missing brackets required to select columns "c0" and "c1". Single brackets were used previously, which results in the following error: 
KeyError: ('c0', 'c1')
This simply fixes a bug in the example code in the documentation which couldn't be run if copy-pasting the code directly.  …
=> [BUG] Fix typo in example code in documentation requiring double brackets to slice dataframe.

sktime/performance_metrics/forecasting/_classes.py, sktime/performance_metrics/forecasting/tests/test_all_metrics_forecasting.py
Closes #6813 
Adds a class parameter to dispatch between `evaluate` and `evaluate_by_index`, if `__call__` is called.
=> [ENH] Forecasting metrics dispatch of `__call__` to `evaluate` vs `evaluate_by_index`

sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_evaluation/tests/test_evaluate.py
Fixes #7636 
This draft PR enhances the `evaluate` function in sktime to optionally return fitted models for each fold in the cross-validation. This is implemented through a new `return_model` parameter which, when set to `True`, adds a `fitted_forecaster` column to the results DataFrame containing the fitted forecaster for each fold.
The enhancement is useful for:
- Analyzing model behavior across different folds
- Reusing fitted models from specific folds for further analysis or prediction
- Debugging model performance variations between folds
Changes made:
1. Added `return_model` parameter to `evaluate` function (default=False)
2. Modified `_get_column_order_and_datatype` to include fitted model column
3. Updated `_evaluate_window` to store fitted models in results
4. Added …
=> [ENH] forecasting `evaluate`: new `return_model` parameter to return fitted estimator states

sktime/detection/lof.py
Fixes part of #7652 Ensured that `_fit` etc have lower case `y`
Fixed the typo `Y` to `y` in `SubLOF`.
No
Tests
No, Verified and removed existing warnings.
Before:
After: …
=> Fixed [BUG] in #7652 Ensured that `_fit` etc have lower case `y`

.all-contributorsrc, sktime/forecasting/timesfm_forecaster.py
- Fixes #7209.
As discussed in #7209, this PR enhances the `TimesFMForecaster` by setting automatic defaults for `context_len` and `horizon_len`:
- `horizon_len`: Defaults to `fh-max` if not explicitly specified.  
- `context_len`: Defaults to the smallest multiple of `input_patch_len` exceeding `len(y)`.  
Explicitly specified values still override these defaults. 
Moreover, calculated values are stored in `self.horizon_len_` and `self.context_len_`.  
N/A
Yes, tests have been added in `get_test_params` to cover default and overridden values, including broadcasting.
N/A
=> [ENH] Set `context_len` and `horizon_len` per default in `TimesFMForecaster`

sktime/clustering/base.py, sktime/clustering/tests/test_all_clusterers.py
This PR makes minor improvements to the clusterer base class:
* the base class is modified to not override the `n_clusters` attribute if it was already set in the child class - this could lead to hard-to-diagnose errors, especially since this is not described in the extension guide.
* the pytest regex to check univariate clustering algorithms was incorrect - this did not cause issues until now as all clusterers were multivariate.
=> [ENH] improvements to clusterer base class and tests

sktime/registry/_lookup.py
Fixes https://github.com/sktime/sktime/issues/7716 by excluding the fallback module containing `Normal` from retrieval by `all_estimators`.
=> [BUG] fixing spurious retrieval of fallback `Normal` distribution

docs/source/api_reference/performance_metrics.rst
This PR adds a proper API reference for the new detection metrics (based on `skbase` class design).
Already includes a link for the windowed F1 score, which will become visible only after merging https://github.com/sktime/sktime/pull/7628.
=> [DOC] API reference for detection metrics

sktime/transformations/panel/shapelet_transform/tests/test_shapelet_transform.py
Temporary skip of `test_st_on_unit_test` to silence https://github.com/sktime/sktime/issues/7725 in tests until fixed.
=> [MNT] temporary skip of `test_st_on_unit_test`

docs/source/api_reference/forecasting.rst, sktime/forecasting/compose/_grouped.py, sktime/forecasting/compose/_transform_select_forecaster.py
This improves the summary and docstring for the grouped/clustering forecaster compositors, in order to enhance clarity about what they are doing, and findability given that it also clarifies the one-sentence summary in the API docs.
=> [DOC] improved docstring for grouped/clustering forecaster compositors

sktime/registry/_lookup.py, sktime/registry/tests/test_lookup.py
Fixes https://github.com/sktime/sktime/issues/7664
The exact failure condition: `all_estimators` would ignore the type specified via `estimator_types` if `filter_tags` was also provided, in a case where all tags filtered for were available in multiple scitypes.
The reason was the internal translation code that translated the `estimator_types` argument to a `filter_tags` argument or `object_types` in `scikit-base` `all_objects`.
This has now been fixed, and a test has been added to cover https://github.com/sktime/sktime/issues/7664.
An existing test for estimator type plus tag filter was present, but it did not trigger the condition as the tag used did not occur outside forecasters. This test has been extended to also use the tag triggering #7664, `handles-missing-data`.
The test framework …
=> [BUG] fix `all_estimators` lookup in case a tag is used that is not scitype specific

.all-contributorsrc, pyproject.toml
Add platform_machine constraint to prevent temporian installation on aarch64.
No, only updates existing temporian dependency constraints.
See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintai …
=> [BUG] fix: add aarch64 installation constraint for temporian

docs/source/api_reference/param_est.rst, sktime/param_est/lag.py, sktime/param_est/tests/test_lag.py
Solves part 2 of #4578
A parameter estimator was added to estimate the best set of lags an AutoREG model should use to achieve the best results.
Addition of private functions to _fit, I did not notice any other implementation where there were private functions created inside _fit and I want to ensure that it is right to do so. I also tried using soft dependencies the way that are supposed to be used but I'd still request a check to ensure I used them correctly.
Added a test to check if my implementation matches that of statsmodels (without exog).
dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).
=> [ENH] Implemented statmodels' `ar_select_order`

sktime/transformations/base.py, sktime/transformations/tests/test_base.py
Fixes https://github.com/sktime/sktime/issues/6417.
The fix is not passing a `y` of mismatching scitype to the inner methods of transformations.
The reason for the bug #6417 was that, in classification or regression pipelines, a `Table` `y` would be passed on to sensible choices of transformers in a pipeline that could optionally take a `Series` `y`, causing an exception, while the user expectation would be that that `y` is not used.
The case where there is this mismatch with user expectation is a quite specialized combination case:
* a transformation is used that can use `y` but does not need to
* that `y`, when passed, must have scitype `Series`
* that is, equivalently in terms of tags: `requires_y = False` and `scitype:transform-labels = Series`
* the transformation is used in a …
=> [BUG] in transformers, do not pass `y` to inner in case of scitype mismatch

sktime/networks/macnn.py, sktime/tests/_config.py
Fixes part of issue #6153
MACNNClassifier, MACNNRegressor - fail all tests with ValueError: A KerasTensor cannot be used as input to a TensorFlow function.
No
tests
No, passed all the existing test cases …
=> [BUG] fix bugs in `MACNNClassifier`, `MACNNRegressor`

sktime/datatypes/_alignment/__init__.py, sktime/datatypes/_alignment/_base.py, sktime/datatypes/_alignment/_check.py, sktime/datatypes/_alignment/_examples.py, sktime/datatypes/_check.py, sktime/datatypes/_proba/__init__.py, sktime/datatypes/_proba/_base.py, sktime/datatypes/_proba/_check.py
Completes the refactor of `datatypes` `_check` modules by refactoring the `Alignment` and `Proba` modules completely to the `scikit-base` patterns.
Also reformats the docstrings of public methods in the `datatypes` libary to render correctly.
=> [ENH] refactor `Alignment` and `Proba` datatypes to `scikit-base` records

pyproject.toml
Raises the `scikit-learn` bound to `<1.7.0`, for release with `sktime 0.36.0`.
=> [MNT] raise `scikit-learn` bound to `<1.7.0`

sktime/transformations/tests/test_pipeline.py
Fixes some incompatibilities with `sklearn 1.6.X`:
* `test_FeatureUnion_pipeline` was testing compatibility of classifier pipelines with `sklearn` components. This is no longer supported as `sktime` has transitioned to own components, and `sklearn` made compositors more restrictive with the "metadata routing" mechanism. The test is therefore changed to `xfail` (not removed to have a reference for potential pipeline redesigns).
=> [ENH] `sklearn 1.6.X` compatibility patch

sktime/forecasting/moirai_forecaster.py, sktime/forecasting/rbf_forecaster.py, sktime/libs/uni2ts/moirai_module.py, sktime/transformations/series/subsequence_extraction.py
This PR fixes some faulty instances of core and soft dependency handling.
* Use of deprecated `package_import_alias`
* `warning` raised in `rbf_forecaster.py`
* private import in `subsequence_extraction.py`
=> [MNT] fix some faulty instances of dependency handling

sktime/forecasting/tests/test_all_forecasters.py
Fixes #7787 by removing the parent `_ProbalisticPredictionCheck` from `TestAllForecasters` and `TestAllGlobalForecasters`, and replacing `self` calls to parent methods with function calls.
=> [MNT] fix failing `TestAllForecasters` test collection due to `pytest` inheritance bug

sktime/forecasting/compose/_ensemble.py
This PR fixes the (str, forecaster, count) parametrization for `EnsembleForecaster`. Fixes https://github.com/sktime/sktime/issues/7784
It is strange why the tests did not pick this up, if I run `check_estimator` it breaks.
=> [BUG] fix (str, forecaster, count) parametrization for `EnsembleForecaster`

sktime/detection/base/_base.py, sktime/transformations/series/adapt.py, sktime/utils/adapters/_safe_call.py, sktime/utils/tests/test_retrieval.py
This PR refactors some code for safe argument passing to functions with unknown signature into a new module `sktime.utils.adapter._safe_call`.
The collection of functions is used in two key locations:
* interface contracts with unstable interfaces, e.g., the `sklearn` transformer public API contract
* extension contracts, particularly in the case where we add new arguments to inner extension contracts, for ensuring downwards compatibility (to prior to the added argument), or where we want to have a variable extension contract.
Test coverage for the functions is given through their use through `TabularToSeriesAdaptor`, except `_safe_call` which will be useful in https://github.com/sktime/sktime/pull/7737.
=> [ENH] private utilities for safe argument passing to function with unknown signature

docs/source/api_reference/data_format.rst, docs/source/glossary.rst
Fixes a numbor of minor issues in the documentation related to tata types, e.g., broken links, references, and typos.
=> [DOC] minor fixes to data types documentation

sktime/forecasting/base/adapters/_statsmodels.py
This PR fixes the inconsistency in variable `name` for the `statsmodels` adapter.
The reason for the inconsistency was that the metadata `varnames` was replacing `None` `name` with `0`, so playing back the latter in `_predict` would change the `name` attribute of the `pd.Series`.
The fix plays back the name as seen in `_fit`, after remembering it.
Fixes #7825
=> [BUG] fix `statsmodels` adapter variable name for `pd.Series`

sktime/forecasting/enbpi.py
Fixes https://github.com/sktime/sktime/issues/7645
A simple fix in the example docstrings of EnbPIForecaster
Solves :
- Module Import error
- Specifies the range for the Forcasting Horizon
The example provided in the [Docs](https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.enbpi.EnbPIForecaster.html) would produce errors.
@fkiraly Kindly review this PR, thanks!!
=> [DOC] update enbpi docstrings

sktime/tests/_config.py
This PR fixes fix `test_excluded_tests_by_test` for the `HFTransformersForecaster`.
The reason for the failure is parallel PRs which changed test parameters of `HFTransformersForecaster`.
=> [ENH] fix `test_excluded_tests_by_test` for `HFTransformersForecaster`

sktime/distances/_wdtw_numba.py
This PR fixes an out-of-bounds error in `ProximityStump` and WDTW.
The error is due to a sporadic out-of-bounds where, in the WDTW distance, weights of form w(abs(i-j)) are copmuted, with w a pre-allocated weight vector. The pre-allocation size takes only the possible range of i into account, but not the range of j.
This is fixed.
=> [BUG] fix sporadic out-of-bounds error in `ProximityStump` and WDTW

sktime/tests/tests/test_test_utils.py
This PR improves, and fixes, the test `test_excluded_tests_by_test`, whose sole purpose it is to remind contributors actioning one of the estimtaors in https://github.com/sktime/sktime/issues/3429 to remove the test skip from the estimator.
* the condition is changed so the test triggers only in this scenario, and not when a new estimator is added that does not have enough test parameter sets. Currently the intended condition and the latter as well trigger a failure, and these triggers correspond to the two "subset" relationships of the set equality. Removing one removes the undesired trigger condition.
* The error message is updated to be clearer and more actionable to contributors.
=> [ENH] improve condition and error message in `test_excluded_tests_by_test`

sktime/benchmarking/_lib_mini_kotsu/run.py, sktime/benchmarking/benchmarks.py
This PR changes `BaseBenchmark` to make the write to `csv` file in `run` to be optional.
If no path is provided to `run` - the new default - the results data frame is returned without hard drive operation. Previously, a string had to be provided without default.
=> [ENH] benchmarking: make write to `csv` file optional

sktime/transformations/series/summarize.py, sktime/transformations/series/tests/test_summarize.py, sktime/utils/tests/test_warnings.py, sktime/utils/warnings.py
The `_custom_showwarning` method in `sktime/utils/warnings.py` causes infinite recursion when handling certain warnings (e.g., pandas `LossySetitemError`), resulting in a `RecursionError: maximum recursion depth exceeded`. Additionally, in `sktime/transformations/series/summarize.py`, the line `func_dict.loc[:, "window"] = func_dict["window"].astype("object")` throws a `LossySetitemError` in pandas 2.x due to incompatible type coercion.
This issue was identified while using PyCaret with sktime, where tests failed with a crash in a joblib worker due to a `PicklingError` caused by excessive recursion.
- Modified the `_custom_showwarning` method in the `_SuppressWarningPattern` class to add a guard against recursion using an `_in_warning` flag, while preserving delegation to …
=> [BUG] Fix infinite recursion in `_SuppressWarningPattern` and `LossySetitemError` in `SummaryTransformer`

sktime/param_est/base.py, sktime/param_est/compose/_func_fitter.py, sktime/param_est/lag.py, sktime/param_est/seasonality.py, sktime/param_est/stationarity/_arch.py, sktime/param_est/stationarity/_statsmodels.py, sktime/utils/_testing/scenarios_param_est.py
As an unreported bug in the test framework, one of the data scenarios was not passed to parameter estimators.
This masked a number of bugs which this PR also fixes:
* `StationarityZivotAndrews` test examples had too large parameters for the test data
* `StationarityKPSS` docstring claimed `regression` options which did not exist
* `FunctionParamFitter` pickling tests would not work for lambda expressions - tests have been replaced by bound functions
* `SeasonalityACFqstat` had an indexing bug (1 vs 0 based indexing)
* `SeasonalityPeriodogram` would break if it found no seasonality
* `ARLagOrderSelector` overrode the wrong fitted parameter method, `get_fitted_params` (rather than the private one)
=> [BUG] fix parameter estimator missing univariate scenario and masked bugs

sktime/tests/_config.py
Related: https://github.com/sktime/sktime/issues/7921
Skips the failing test until resolved or diagnosed.
=> [BUG] skip `RocketClassifier` expected output test until resolved

sktime/forecasting/compose/_reduce.py, sktime/utils/multiindex.py
Fixes #7926 
The method `asfreq` was being called with multiindex dataframes. In addition, the construction of `y_pred` wasn't considering the timeseries instances.
=> [BUG] Fix RecursiveReductionForecaster failing test_hierarchical_with_exogeneous

sktime/forecasting/base/_fh.py, sktime/utils/datetime.py, sktime/utils/warnings.py
Ensures a new context manager is generated each time for use, for the `pandas 2.2` related warning context manager used in https://github.com/sktime/sktime/issues/7906
Does not solve the race condition, but makes the context manager safer.
=> [BUG] safer context manager for `pandas 2.2` warning suppression

sktime/tests/test_switch.py, sktime/tests/tests/test_test_utils.py
This PR tries to cover some blind spots in the testing framework.
It triggers differential tests for estimators and object where previously they would not have been triggered, namely if one of the three key framework modules changes: `datatypes`, `tests`, and `utils`.
This condition is added to the `run_test_for_class` switch.
=> [ENH] trigger differential tests if core framework modules change

sktime/utils/parallel.py
This PR clarifies assumptions on function `fun` in `utils.parallel.parallelize`, in the docstring.
=> [DOC] clarify assumptions on function `fun` in `utils.parallel.parallelize`

docs/source/developer_guide/add_estimators.rst
Fixes a minor typo in `add_estimators.rst`
=> [DOC] minor typo fix in `add_estimators.rst`

sktime/base/_base.py, sktime/forecasting/base/adapters/_pmdarima.py, sktime/forecasting/base/adapters/_tbats.py, sktime/registry/tests/test_craft.py
Half a year ago, we added the method `_handle_numpy2_softdeps` to handle dependencies that were not `numpy 2` compatible, but did not advertise that bound in their package dep bounds. The method was intended to be temporary, until packages move to declare their `numpy` bounds properly, or become compatible with `numpy 2`.
Most soft dependencies have moved to `numpy 2` compatibility, but `pmdarima` has not, and perhaps will not put this in their dependency bounds - it is the only such dependency remaining.
This PR removes the temporary utility and moves the bound into the `pmdarima` adapter.
=> [ENH] remove `numpy 2` dependency handler from `BaseObject`

sktime/tests/_config.py
Skips the failing tests of `MCDCNNClassifier` temporarily until fixed, see #6465 and #7958
=> [MNT] temporary skip of `MCDCNNClassifier` failing tests

.github/workflows/test.yml, .github/workflows/wheels.yml
Moves the release to trusted publishers.
All secrets have been removed from the repo.
=> [MNT] move release to trusted publishers

sktime/tests/_config.py
Temporary skip of `VARMAX` tests due to sporadic timeout, see #7965
=> [MNT] temporary skip of `VARMAX` tests due to timeout

sktime/forecasting/compose/_grouped.py, sktime/forecasting/compose/_transform_select_forecaster.py
This PR adds the possibility to pass a clusterer to `GroupByCategoryForecaster`.
It also looks like the `GroupByCategoryForecaster` is mostly a copy of `TransformSelectForecaster`, so I do not quite understand what happened here.
In any case, I've tried to sync the classes as much as possible, with various features that have since been added to `TransformSelectForecaster`.
=> [ENH] add clusterer use to `GroupByCategoryForecaster` and docstrings

sktime/forecasting/model_evaluation/_functions.py
This PR speeds up forecasting `evaluate` benchmark input checks, by minimizing the amount of checks and metadata computations required.
=> [ENH] speed up forecasting `evaluate` benchmark input checks

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/detection.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/early_classification.py, extension_templates/forecasting.py, extension_templates/forecasting_simple.py, extension_templates/forecasting_supersimple.py, extension_templates/metric_detection.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py, extension_templates/transformer_simple.py, extension_templates/transformer_supersimple.py
This PR contains some improvements to the extension templates:
* corrected docstring template to be compliant with numpydoc
* simplified parameters to three examples - without default, with default and primitive-valued, with mutable default and estimator-valued
* added link to tags API reference
=> [DOC] extension templates improvements

sktime/forecasting/base/_base.py, sktime/tests/test_all_estimators.py
In the "by-module" tests, the following condition could lead to unexpected failure:
something changes in two top level modules, and one of them is a `forecasting` estimator with a valid, non-standard `predict_proba` method - or one of the framework module.
The problem is that this combined change will lead to `TestAllEstimators` being executed in the non-forecasting cluster of tests, attempting to call `predict_proba` of the forecaster.
This requires `skpro` for representation of distributions, which is not installed in the non-forecasting test VM, producing an exception.
The change ensures that the test for `predict_proba` is not run if `skpro` is not present - it is present in the forecasting tests which will always run.
=> [ENH] in tests, handle soft dependency in `BaseForecaster.predict_proba` on `skpro`

sktime/clustering/kvisibility.py
Fixes the missing `python_dependencies` tag in `TimeSeriesKVisibility`.
Previoulsly masked due to the bug fixed in https://github.com/sktime/sktime/pull/7971.
=> [BUG] `TimeSeriesKVisibility` - fix missing `python_dependencies` tag

sktime/clustering/tests/test_all_clusterers.py
This PR fixes the broken clustering tests in `TestAllClusterers` detected via https://github.com/sktime/sktime/pull/7971:
* `test_clusterer_output` was using the `n_classes` attribute instead of `n_clusters`, probably due to copy-paste error from classification.
=> [BUG] fix broken clustering tests in `TestAllClusterers`

sktime/tests/_config.py
This PR skips the `pytorch-forecasting` estimators temporarily until the bug in #7997 is resolved.
=> [MNT] temporary skip of `pytorch-forecasting` tests until resolution of #7997

sktime/forecasting/compose/_hierarchy_ensemble.py
Fixes test case failing for `HierarchyEnsembleForecaster`, found as part of #7971.
Test error that this pull request addresses:
`AssertionError('Estimator HierarchyEnsembleForecaster should not change or mutate  the parameter default from PolynomialTrendForecaster() to PolynomialTrendForecaster() during fit.')`
In most places, the `default` forecaster is cloned, but the clone step was ommitted in one location. This pull request rectifies that.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus …
=> [BUG] Fix `HierarchyEnsembleForecaster` test failure

sktime/base/_meta.py, sktime/forecasting/base/_meta.py, sktime/forecasting/compose/_column_ensemble.py, sktime/forecasting/compose/_ensemble.py, sktime/forecasting/compose/_hierarchy_ensemble.py, sktime/forecasting/compose/_stack.py, sktime/forecasting/online_learning/_online_ensemble.py
`_HeterogenousEnsembleForecaster` parameter inspection did not work as intended as the initial coercion to name/estimator pairs was buggy. This is fixed
=> [BUG] fix `_HeterogenousEnsembleForecaster` parameter inspection

sktime/forecasting/base/_meta.py, sktime/forecasting/compose/_ensemble.py, sktime/forecasting/compose/_stack.py, sktime/forecasting/online_learning/_online_ensemble.py
`_HeterogenousMetaForecaster` descendants would have a bug where the `forecasters_` attribute was populated by `_fit_forecasters` with a list of forecasters, not with the expected list of (name, estimator) pairs.
This impacted `get_fitted_params` and general usage, this should now be fixed.
=> [BUG] fix `_HeterogenousMetaForecaster` handling of `forecasters_`

sktime/tests/_config.py
Temporarily skips `STDBSCAN` clusterer, until #7994 is resolved.
=> [MNT] temporary skip of `STDBSCAN` clusterer

sktime/registry/_tags.py
This PR improves the API reference for the `python_dependencies` tag.
It adds:
* examples with explanation
* information on how to specify logical "or", assumes https://github.com/sktime/sktime/pull/7943 to be merged
=> [DOC] improved API reference for `python_dependencies` tag

sktime/tests/test_switch.py, sktime/utils/dependencies/_dependencies.py
This PR fixes `_check_estimator_deps` in the disjunction case, as it would interpret a simple disjunction as a conjunction.
=> [BUG] fix `_check_estimator_deps` in disjunction case

sktime/classification/sklearn/_rotation_forest.py
Fixes the `RotationForest` docstring to be a valid example for tabular classifiers. Fixes https://github.com/sktime/sktime/issues/7974
=> [DOC] fix `RotationForest` docstring example

sktime/transformations/base.py, sktime/transformations/tests/test_base.py
In a combination of cases the `Series`-to-`Primitives` transformer would not correctly handle the output data and drop the last index element unexpectedly. This would happen if:
* a `Series`-to-`Primitives` transformer
* supports `Panel` and `Hierarchical` data natively
* and is passed a hierarchical `pd.DataFrame` to `fit_transform`
This is one of the root causes of https://github.com/sktime/sktime/issues/8012, fixes https://github.com/sktime/sktime/issues/8038
The fix is to catch the condition exactly. The reason for the failure is that we need to deal with two cases separately:
* vectorization causes a new level of "all-zeroes" to appear. This happens exactly if a `Series` is vectorized, because this would result in an abstract "zero-level index", i.e., just a vector without index. …
=> [BUG] fix `Series`-to-`Primitives` transformer output index for hierarchical data

sktime/clustering/base.py, sktime/clustering/tests/test_all_clusterers.py
Fix failing tests for SklearnClustererPipeline, TimeSeriesDBSCAN, and ClustererPipeline tracked in #8026. Bugs discovered via #7971.
Updated the default implementation of predict_proba for clusterers to return an array of shape (n_instances, n_clusters). This is the intended shape, but the implementation was instead returning an array of shape (n_samples, n_clusters).
Also updated the tests to allow for instances to not be assigned to any cluster (indicated by cluster -1). This means that the probability assigned for each instance may be less than 1.
No
No. This is covered by existing tests.
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - …
=> [BUG] Fix failing tests for SklearnClustererPipeline, TimeSeriesDBSCAN, ClustererPipeline

sktime/tests/test_all_estimators.py, sktime/utils/estimator_checks.py
This PR adds verbose output to `check_estimator`, informing the user on passed and failed tests, if `raise_exceptions=True`.
As the utility immediately raises on failure, the output needs to be conditioned directly on try/except of execution of the individual tests, hence a `verbose` parameter is added in `QuickTester.run_tests` to achieve this result.
The default in `run_tests` is `verbose=False`, and it is invoked with `verbose=True`, iff `check_estimator` args are `raise_exceptions=True` and `verbose=True` (where `verbose=True` and `raise_exceptions=False` are the defaults of `check_estimator`).
Fixes https://github.com/sktime/sktime/issues/8046.
FYI @jgyasu, would appreciate review and usage feedback.
=> [ENH] `check_estimator` verbose output on passed and failed tests if `raise_exceptions=True`

sktime/transformations/series/tests/test_kalman_filter.py
Using unsymmetric or indefinite matrices break Kalman filter math and may result to random "division by zero" -type errors inside the libraries.
@NoaWegerhoff
=> [ENH] Use valid covariance matrices in Kalman filter unit tests

sktime/clustering/compose/_as_transform.py, sktime/utils/_testing/scenarios_transformers.py
Fixes small bug introduced in #8013. See also #8012, #8036, #8005.
`ClustererAsTransformer` fails when applied to hierarchical data:
```python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.clustering.compose._as_transform import ClustererAsTransformer
from sktime.clustering.dbscan import TimeSeriesDBSCAN
y_h  = _make_hierarchical()
model = ClustererAsTransformer(TimeSeriesDBSCAN.create_test_instance())
y_pred = model.fit_transform(y_h) # KeyError: ('h0_0', 'h1_0')
```
This was introduced in the clean up phase of #8013, and missed due to hierarchical tests not running on transformers. The commit that introduced the bug has been reversed.
Hierarchical tests have also been enabled for transformers.
Yes - Hierarchical tests have been enabled for transformers …
=> [BUG] Hierarchical data passed to `ClustererAsTransformer` fails

sktime/transformations/tests/test_base.py
In https://github.com/sktime/sktime/pull/8053, we shortened the hierarchical transformation scenarios to ensure quicker runtime.
However, this caused the hard-coded expected length in some tests to fail.
This is now fixed by using the input length instead, programmatically fixing the impacted output length tests for hierarchical transformations.
=> [BUG] fix expected output length tests for hierarchical transformations

sktime/registry/_tags.py
This minor PR fixes a few broken glossary refs in the tag API reference.
=> [DOC] fix a few broken glossary refs

sktime/tests/test_all_estimators.py
`BaseForecaster.predict_proba` depends on `skpro`, which can cause "`skpro` not present" exceptions in `TestAllEstimators` run on a forecaster when called in an environment that does not contain `skpro`.
In the current CI this happens only in the rare case when forecasters are collected in a non-forecaster CI batch, it still should be handled as these are unexpected failures.
=> [ENH] handle `BaseForecaster.predict_proba` `skpro` dependency in `TestAllEstimators`

docs/source/changelog.rst, sktime/performance_metrics/detection/_randindex.py, sktime/transformations/series/outlier_detection.py
This PR addresses the following deprecation warnings from `pandas`:
* deprecation of `is_interval_dtype`
* deprecation of certain write-on-slice cases
=> [ENH] address some `pandas` deprecation warnings

pyproject.toml
`pytorch-forecasting` 1.3.0 has been released recently, with 3.13 support and bugfixes. We should increase the bound and merge after tests pass.
=> [MNT] increase `pytorch-forecasting` bound

sktime/forecasting/compose/_reduce.py
This PR carries out a minor refactor to improve code clarity in the `make_reduce` code tree.
The refactor moves two sizeable if/else branches into their own functions, which clarifies which variables are used in which branch.
The result is troubling, as for instance `transformers` and `fh`, `windows_identical` are not used in both branches.
=> [ENH] reducer - minor code clarity refactor

sktime/tests/_config.py
This PR adds a temporary skip for `TimeSeriesKvisibility` until known failures are fixed. See #8026 and #8072
=> [MNT] temporary skip for `TimeSeriesKvisibility` until fix of known failures

sktime/transformations/base.py, sktime/transformations/merger.py, sktime/transformations/tests/test_all_transformers.py
Fixes failing tests for `Merger` tracked in #8026.
Merger is the only transformer that converts Panel data to Series. In fact it is the only estimator with tag `{"scitype:transform-input": "Panel"}`. When this was implemented, the hierarchical case was not considered. This PR adds that support to fix the failing tests.
This PR also fixes a bug when `stride == 0`. The issue here was that in changing from numpy3d to ndarray, the order of instances and time points was not accounted for in this case.
No
Tests already enabled, e.g. test_fit_transform_output[Merger-0-TransformerFitTransformHierarchicalUnivariate]
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common …
=> [BUG] Allow `Merger` to work on hierarchical inputs

sktime/transformations/panel/compose.py
Fixes `ColumnConcatenator` errors tracked in #8026.
Sets the index correctly when hierarchical data is provided. Previously only one level of the hierarchical index was retained.
No
Tests already cover this behaviour - previously masked due to hierarchical tests not enabled.
See …
=> [Bug] Handle hierarchical input types in ColumnConcatenator correctly

sktime/networks/macnn.py
See error in CI pipeline: [test_save_estimators_to_file](https://github.com/sktime/sktime/actions/runs/14115519712/job/39553508329?pr=7603)
Removes the keras module from the pickled objects and replaces backend.mean by AveragePooling
=> [BUG] Fix serialization errors in tests of `MACNNClassifier`

sktime/performance_metrics/forecasting/_coerce.py
This PR ensures that scalar forecasting metric outputs are coerced to `float`, rather than `np.float64` or `np.int64`.
Important question: what should be the expectation here?
The doctests apparently expect a python float.
For discussion, see https://github.com/sktime/sktime/issues/8075.
Fixes https://github.com/sktime/sktime/issues/8075
=> [ENH] coerce scalar forecasting metric outputs to `float`

sktime/tests/_config.py
PR to temporarily remove RecursiveReductionForecaster (RRF) from unit tests
This will be fixed in #7380 but, since the RRF is causing time-out errors in CIs, this is kind of urgent at the moment. #7380 should re-add this estimator to the tests.
=> [MNT] Temporarily remove RecursiveReductionForecaster from unit tests

sktime/tests/_config.py
The early classifier `TEASER` fails `test_multiprocessing_idempotent` with the error below - this is due to different output API.
The test is skipped until the tests have been adapted, the skip is added to the existing skips of this nature.
```
FAILED sktime/tests/test_all_estimators.py::TestAllEstimators::test_multiprocessing_idempotent[TEASER-ClassifierFitPredictThreeClasses-predict_proba] - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 5) + inhomogeneous part.
```
=> [MNT] skip early classifier `TEASER` in `test_multiprocessing_idempotent`

sktime/transformations/tests/test_check_estimator.py
Temporary skip for `test_transformation_can_return_new_instances` until https://github.com/sktime/sktime/issues/8084 is resolved.
=> [MNT] skip `test_transformation_can_return_new_instances` until resolution of #8084

sktime/transformations/tests/test_check_estimator.py
The estimator _TransformChangeNInstances, which was created for test purposes, was not correctly handling hierarchical scenarious that were just re-activated.
Fixes #8084
=> [BUG] Make _TransformChangeNInstances capable of handling hierarchical test scenarios

.all-contributorsrc, sktime/libs/vmdpy/vmdpy.py, sktime/transformations/series/tests/test_vmd.py, sktime/transformations/series/vmd.py
Fixes #6602 
- The VMD module would discard the last sample when given an odd length sequence. 
- The math has been updated to handle odd length sequences based on [this comment](https://github.com/sktime/sktime/issues/6602#issuecomment-2168141677). Now the VMD module handles odd length sequences properly.
- VMD transformer used the hack of duplicating the last sample to achieve an even length sequence, this is no longer necessary and has been removed.
- A test to check the preservation of odd / even sequence length has been added. 
No.
- Quality of test cases.
Yes, to check odd/even length preservation at the VMD transformer.
Credit goes to Zachery Lorch for providing the core of the fix in the comment linked above. Their name has been added to the module's credits and as the co-author …
=> &LorchZachery [BUG] Fix VMD odd length data returns even length decomposition

sktime/performance_metrics/forecasting/_coerce.py, sktime/performance_metrics/forecasting/tests/test_all_metrics_forecasting.py
Fixes https://github.com/sktime/sktime/issues/8082
This PR updates the test case in `TestAllForecastingPtMetrics` to strictly check that forecasting metrics return a **Python `np.float64`** instead of allowing any float types (`float`, etc.).  
- Updated the assertion in `test_metric_output_direct`:  
```python
if isinstance(multioutput, np.ndarray) or multioutput == "uniform_average":
assert all(type(x) is np.float64 for x in res.values())  # Ensures strict Python float
```
=> [ENH] Ensure Forecasting Metrics Return `np.float64`

sktime/transformations/tests/test_check_estimator.py
In a previous PR (#8092), I forgot to remove a line that was forcing the execution of a specific test.
Related to #8092
Remove the line that wasn't supposed to be there
=> [MNT] Remove debugging line from test_check_estimator

sktime/forecasting/pykan_forecaster.py
The `PyKANForecaster` seems to require `matplotlib` now as one of its dependencies, see failure below:
```
FAILED sktime/tests/test_all_estimators.py::TestAllEstimators::test_fit_idempotent[PyKANForecaster-2-ForecasterFitPredictMultivariateNoX-predict] - ModuleNotFoundError: No module named 'matplotlib'
```
This is likely bad dependency management on the part of the package maintainers - `matplotlib` is a plotting and not a modelling package - but it cannot be helped as the import is somewhere on module level, so it is a de-facto dependency now.
We need to keep track and add the dependency requirement, or the estimator will break for users.
=> [MNT] update `PyKANForecaster` dependency set

sktime/regression/deep_learning/cntc.py
Some tests failed due to a wrong output shape of the `CNTCRegressor`. See: https://github.com/sktime/sktime/actions/runs/14181530236/job/39737203338
Squeeze the last dimension of the CNTCRegressor
=> [BUG] squeeze output of `CNTCRegressor`

pyproject.toml
This PR increases the `tensorflow` bound to `<2.20`.
Fixes https://github.com/sktime/sktime/issues/8058
=> [MNT] increase `tensorflow` bound to `<2.20`

sktime/tests/_config.py
Removes the `CNTCRegressor` parameter test skip, after a second set of test parameters has been added.
=> [MNT] remove `CNTCRegressor` parameter test skip

sktime/base/_base.py, sktime/base/_meta.py, sktime/registry/_scitype.py, sktime/registry/_scitype_coercion.py, sktime/registry/tests/test_scitype.py
This PR refactors the `scitype` detection logic to include `sklearn` scitypes.
The `scitype` method can now return sklearn scitypes such as `"regressor_tabular"` or `"classifier_tabular"`
In addition, the meta-estimator clone logic is relaxed so that `sklearn` types are also natively supported.
=> [ENH] refactor `scitype` detection logic and meta-estimator clone logic to include `sklearn` estimator types

sktime/tests/_config.py
Skips failing tests from https://github.com/sktime/sktime/issues/8135 until fixed.
=> [MNT] temporarily skip `ESRNNForecaster`  failing tests

sktime/performance_metrics/detection/__init__.py, sktime/performance_metrics/detection/_ts_auprc.py
The class is not working and failing tests. It is removed for now, from public exports
=> [MNT] remove `TimeSeriesAUPRC` from exports and docs

sktime/forecasting/compose/_pipeline.py, sktime/registry/_scitype_coercion.py
This PR adds automatic transformer coercion in forecasting pipelines, and removes the need for manual transformer coercions such as of `sklearn` estimators through `TabularToTransformAdaptor`.
This is achieved through use of the `registry._scitype_coercion` module, which also has minor updates and bugfixes in this PR.
=> [ENH] automatic transformer coercion in explicit forecasting pipeline specification syntax

sktime/tests/_config.py
temporary skip for `SCINetForecaster` until https://github.com/sktime/sktime/issues/7871 is resolved
=> [MNT] temporary skip `SCINetForecaster`

pyproject.toml
This PR removes `tsbootstrap` soft dependency from the `all_extras_pandas2` dependency set.
This should have happened in https://github.com/sktime/sktime/pull/6966 - due to pinned dependencies - but by accident did not happen in the `pandas 2` dependency set.
=> {MNT] remove `tsbootstrap` soft dependency from `all_extras_pandas2` dependency set

sktime/forecasting/vecm.py
This PR skips the `VECM` docstring test example due to a `pandas 1` incompatibility in the `pandas` data container used.
=> [MNT] skip `VECM` doctest due to `pandas 1` incompatibility

sktime/utils/parallel.py
Skips the `ray` parallelization fixtures until https://github.com/sktime/sktime/issues/8149 is resolved.
=> [MNT] skip tests with `ray` parallelization fixtures

sktime/utils/dependencies/_safe_import.py, sktime/utils/dependencies/tests/test_safe_import.py
Fixes #8181 
This PR allows `_safe_import` to create mock objects if it encounters an `ImportError` or `AttributeError` exception.
=> [BUG] Stop Importing Modules if Raised an Exception in `_safe_import`

sktime/utils/parallel.py
https://github.com/sktime/sktime/pull/8188 accidentally introduced a failure in the test fixture generating utility `_get_parallel_test_fixtures`, which leads to failures in all parallelization backend related tests.
This PR fixes that.
Since this is purely in the test framework, I do not think we need to release a hotfix.
=> [BUG] fix accidental failure in fixture generating utility `_get_parallel_test_fixtures`,

sktime/performance_metrics/forecasting/probabilistic/_classes.py, sktime/utils/plotting.py
Most probabilistic forecasting metrics were lacking a proper mathematical documentation in the docstring.
This PR adds that documentation, to the docstrings of probabilistic forecasting metrics where it was missing - towards https://github.com/sktime/sktime/issues/4303.
=> [DOC] mathematical reference for probabilistic forecasting metrics

sktime/libs/_aws_fortuna_enbpi/enbpi.py
I found a bug in the `EnbPI` class that we picked up from fortuna. It was in the `init` by which if a user selected "median" as the aggregation function, this was incorrect assigned to `_aggregation_fun` instead of `aggregation_fun`. The `_aggregation_fun` is never used in the code. See below:
```python
if aggregation_fun == "mean":
self.aggregation_fun = lambda x: np.mean(x, 0)
elif aggregation_fun == "median":
self._aggregation_fun = lambda x: np.median(x, 0)
```
The obvious quick fix is to drop the leading underscore.
=> [FIX] Fix aggregation function assignment in EnbPI class

sktime/benchmarking/_benchmarking_dataclasses.py, sktime/benchmarking/forecasting.py, sktime/forecasting/model_evaluation/_functions.py, sktime/forecasting/model_evaluation/tests/test_evaluate.py
Towards #8063 
* Enables the usage of SlidingWindowSplitter etc. as cv when being in global mode.
* Enables the usage of Temporal splitting the instance split that is used for testing. This avoids temporal data leakage across different time series.
* Add test for testing the behaviour of the temporal splitting
The interface is a bit complicated. Not sure, how this can be solved, or if someone has a better idea.
=> [ENH] Add temporal global split to evaluate

sktime/detection/skchange_aseg/capa.py, sktime/detection/skchange_aseg/circular_binseg.py, sktime/detection/skchange_aseg/mvcapa.py, sktime/detection/skchange_aseg/statthreshold.py, sktime/detection/skchange_cp/moving_window.py, sktime/detection/skchange_cp/pelt.py, sktime/detection/skchange_cp/seeded_binseg.py, sktime/utils/dependencies/_placeholder.py
This PR updates `_placeholder_record` to allow mirroring of mulitple upstream locations, which are checked in sequence.
The direct use case is recent breaking changes of import locations in `skchange`, moving public import locations of individual estimators one level up.
In order to maintain compatibility with both newer and older locations, the new `_placeholder_record` is used with the pattern `[new_location, old_location]`.
FYI @tveten, are these the correct new import locations? Also, for your convenience, here is the deprecation/change policy we are using:
https://www.sktime.net/en/stable/developer_guide/deprecation.html
It would be great if you would add some testing for integrity of the import locations in `skchange`!
=> [ENH] `_placeholder_record` to allow mirroring of multiple locations, update of `skchange` import locations

sktime/split/expandinggreedy.py, sktime/split/slidinggreedy.py, sktime/split/tests/test_expandinggreedy.py, sktime/split/tests/test_slidinggreedy.py
Fixes #8198 and fixes #8199 
This PR adds:
- Missing `fh` init in SlidingGreedySplittter
- Proper `fh` handling when `test_size` is `float` for both greedy splitters
- Fixes inexact type hints in ExpandingGreedySplitter
- Adds tests for `fh` handling in both splitters
No
- If the side-effect of setting `fh` on `split()` is a bad pattern
- If initialising `fh` differently based on the type of `test_size` is a bad pattern
- The correctness of the tests
Yes, previously the greedy splitters did not check `fh` handling and now both have a test to cover this.
=> [BUG] Fix `fh` handling in greedy splitters

sktime/pipeline/pipeline.py
There's a typo in `Pipeline`'s constructor in a multi-line string leading to this:
This PR fixes it, making formatting of that line consistent with how spaces are enabled in adjacent lines.
=> [DOC] Add missing space to `Pipeline` constructor warning

sktime/forecasting/compose/tests/test_reduce.py
This fixes some bugs in recursive reduction tests, where instead of `assert` statements there were `return` statements or simply no statements, thus resulting in no check where there should have been one.
FYI @PranavBhatP, it would be appreciated if you could review this since you created these tests in #7770.
=> [BUG] fix recursive reduction tests

sktime/performance_metrics/forecasting/_msep.py
This changes `MeanSquaredErrorPercentage` to be positive if the denominator - the mean of ground truth samples - is negative.
This also solves an unreported sporadic bug in rarer cases when, on the test data, said denominator is negative, and the square root is computed via `square_root=True`.
I do not consider this a breaking change, since sound usage should happen only if the average is indeed a positive number - and since the "lower is better" tag was set to `True`.
=> [ENH] enforce `MeanSquaredErrorPercentage` to be positive

sktime/forecasting/compose/_skforecast_reduce.py, sktime/forecasting/compose/tests/test_skforecast_reduce.py
Fixes : #8206 
Changes Made: 
Fixed Typo
- Fixed a typo in parameter documentation: corrected `"fucntion"` to `"function"`.
Enhancements
- Added support for the `store_in_sample_residuals` parameter in the `SkforecastRecursive` class
- Introduced the parameter in the `__init__` method with a default value of `False`.
- Stored it as an instance attribute.
- Passed it to the `ForecasterRecursive` constructor.
=> [ENH] SkforecastRecursive - support in-sample predict_quantiles

docs/source/conf.py
The table on [Estimator Overview](https://www.sktime.net/en/stable/estimator_overview.html) page does not have the filter for `"capability:predict_proba"` currently. This PR adds it.
=> [ENH] Add `predict_proba` tag for classifier to estimator overview table

sktime/transformations/hierarchical/aggregate.py, sktime/transformations/hierarchical/tests/test_aggregate.py
Fixes #7614 
* Add `__init__` argument to activate `inverse_transform`, for backward compatibility
* Fix the inverse transform so that it does not fail when a given level does not have aggregated value
Is the name of the argument good?
Yes
This PR should be merged before #7697
=> [BUG] Fix Aggregator inverse_transform being skipped

sktime/performance_metrics/forecasting/probabilistic/_classes.py, sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py
=> [BUG] Fix boundary equality in `EmpiricalCoverage`

sktime/benchmarking/benchmarks.py
=> [BUG] Fix `"kkwargs"` typo in `ForecastingBenchmark`

sktime/datasets/_single_problem_loaders.py
There are two utility functions for loading TSC datasets in `sktime`, `_load_dataset` and `_load_provided_dataset`. The former is for the datasets that need to be downloaded and latter is for the datasets that are shipped with sktime. 
For example, `load_arrow_head` uses `_load_provided_dataset` but loaders like `load_gun_point`, `load_osuleaf` and others use `_load_dataset` even though they are shipped with sktime by default. Thus, it leads to redundant dataset downloads. This PR fixes it.
=> [ENH] Use `sktime` Provided Dataset in `TSC` Dataset Loaders

sktime/base/_base.py, sktime/forecasting/base/tests/test_base.py, sktime/forecasting/compose/_transform_select_forecaster.py, sktime/forecasting/enbpi.py, sktime/param_est/plugin/_forecaster.py, sktime/param_est/plugin/_transformer.py, sktime/registry/_lookup.py, sktime/tests/test_softdeps.py, sktime/transformations/base.py, sktime/transformations/tests/test_compose.py
This PR replaces all-tags retrieval via `get_tags` by single-tag retrieval where possible. This is better as it does not trigger, for instance, warning messages about deprecated tags.
It also adds the name of the package to the tag aliaser class.
=> [ENH] avoid all-tags retrieval, add package name to tag aliaser

sktime/forecasting/compose/_bagging.py, sktime/transformations/bootstrap/_mbb.py
Minor improvements to `MovingBlockBootstrapTransformer`:
* faster test cases
* improved docstring with more visible defaults
=> [ENH] faster `MovingBlockBootstrapTransformer` tests, improved docstring

sktime/forecasting/compose/_bagging.py, sktime/forecasting/naive/_naive.py, sktime/transformations/panel/tsfresh.py
This PR removes some unstable estimators with sporadic failures, and long runtimes, from the core testing set:
* `BaggingForecaster` - sporadic failures
* `NaiveVariance` - runs long
* the `tsfresh` transformations - runs long
=> [ENH] remove some unstable and long running estimators from the core testing set

sktime/classification/sklearn/_rotation_forest.py, sktime/classification/sklearn/tests/test_all_classifiers.py
Fixes https://github.com/sktime/sktime/issues/8265 - the reason was that `base_estimator` was not written to `self._base_estimator` when a non-standard one was provided.
Adds the failure case to the test.
=> [BUG] fix `RotationForest` for a custom `base_estimator`

pyproject.toml
Reverts the `joblib` bound to `joblib<1.6`, this should be increased with 0.38.0 and not with 0.37.1.
=> [MNT] revert `joblib` bound to `joblib<1.6`

pyproject.toml
increase `joblib` bound to `joblib<1.7`, to be released with 0.38.0
=> [MNT] increase `joblib` bound to `joblib<1.7`

sktime/datasets/_single_problem_loaders.py, sktime/datasets/forecasting/macroeconomic.py, sktime/forecasting/base/adapters/_tbats.py, sktime/param_est/seasonality.py
The newly erleased `scipy 1.16` has removed some private utilities which were imported by a number of time series packages.
This PR adds a bound `scipy<1.16` to those estimators, and a todo check for release managers to check compatibility at next minor release.
=> [MNT] add `scipy<1.16` bounds to incompatible estimators

.github/workflows/test.yml, .github/workflows/test_all.yml, .github/workflows/test_base.yml, .github/workflows/test_datasets.yml, .github/workflows/test_module.yml, .github/workflows/test_other.yml
This PR implements ARM64 architecture support across all GitHub Actions workflow files by adding `ubuntu-22.04-arm` runners. The change enables testing on ARM-based infrastructure providing comprehensive platform coverage for sktime's CI pipeline.
Modified workflow files:
- test.yml
- test_all.yml
- test_base.yml
- test_datasets.yml
- test_module.yml
- test_other.yml
No new dependencies are introduced. This change only affects the CI infrastructure by adding ARM-based runners to existing workflows.
Reviewers should focus on:
- Impact on overall CI execution time across all workflows 
- Verification that all tests pass consistently on ARM architecture
- Assessment of any potential increase in resource usage [**Check** [**Usage Limit**](https://github.com/sktime/sktime/pull/7695)]
The key …
=> [MNT] CI: Add ubuntu-22.04-arm runners to enhance arm aarch64 architecture testing and maintenance

.github/workflows/test.yml
This changes "needs" of the mlflow jobs in CI and ensures those are skipped if both `sktime/` and `pyproject.toml` are not modified.
=> [MNT] Skip mlflow test jobs if sktime folder or pyproject.toml is untouched

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/clustering.py, extension_templates/detection.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/early_classification.py, extension_templates/forecasting.py, extension_templates/forecasting_global_supersimple.py, extension_templates/forecasting_simple.py, extension_templates/forecasting_supersimple.py, extension_templates/metric_detection.py, extension_templates/param_est.py, extension_templates/split.py, extension_templates/transformer.py, extension_templates/transformer_simple.py, extension_templates/transformer_supersimple.py
This PR makes a small consistent change across all extension templates, improving clarity of language in reference to the methods that need to be implemented.
=> [DOC] use clearer language in extension template preamble

pyproject.toml
Add aarch64 platform_machine constraint to prevent esig and ts2vg installation on aarch64.
No, only updates existing esig and ts2vg dependency constraints on aarch64. …
=> [MNT] fix: add aarch64 installation constraint for esig and ts2vg

docs/source/api_reference/forecasting.rst, sktime/forecasting/greykite.py
`GreykiteForecaster` was missing from the API reference, this PR adds it
=> [ENH] add missing API reference for `GreykiteForecaster`

sktime/libs/chronos/chronos.py, sktime/libs/chronos/chronos_bolt.py, sktime/libs/granite_ttm/configuration_tinytimemixer.py, sktime/libs/granite_ttm/modeling_tinytimemixer.py, sktime/libs/timemoe/timemoe.py, sktime/libs/timemoe/timemoe_config.py, sktime/libs/timemoe/ts_generation_mixin.py, sktime/libs/timesfm/patched_decoder.py, sktime/libs/timesfm/timesfm.py
This PR replaces unsafe imports from `torch` and `transformers` with the `_safe_import` pattern.
Also changes the imports of `ModelOutput` to point to `transformers.utils.ModelOutput` which is the current and historically stable location.
Fixes https://github.com/sktime/sktime/issues/8469
=> [MNT] replace unsafe imports from `torch` and `transformers` with `_safe_import` pattern

sktime/libs/chronos/chronos_bolt.py, sktime/libs/granite_ttm/modeling_tinytimemixer.py
Fixes #8482, fixes #8486.
Rolling the `transformers 4.53` compatibility patch accidentally removed type annotations from `ModelOutput` children in `ChronosForecaster` and `TinyTimeMixerFoercaster` - rendering them failing.
This was not spotted by tests due to human error. This PR fixes the problem, and releasing a hotfix (after a test run) should limit the impact of the problem.
=> [BUG] fix accidental removal of dataclass type in `ChronosForecaster` and `TinyTimeMixerForecaster`

sktime/classification/foundation_models/momentfm.py, sktime/forecasting/chronos.py, sktime/tests/_config.py
This PR moves the test skip configuration for all estimators with their own VM to the tags of said estimators.
This is necessary to ensure that the correct tests are skipped in those VM tests.
=> [ENH] move test skips to estimators for estimators with their own VM

sktime/classification/deep_learning/tapnet.py, sktime/tests/_config.py
* #8515 
This PR implements part of issue #8515 by migrating `TapNetClassifier` test skip configurations from the central tests._config.py file to the estimator's own tags.
=> [ENH] Move TapNetClassifier test skip config from tests._config to estimator tags.

sktime/tests/test_all_estimators.py
There is a typo in `test_all_estimators`, this PR corrects it.
=> [DOC] A typo in `test_all_estimators`

sktime/utils/dependencies/_dependencies.py
This PR adds a note on what to use between the import name and package name with `_check_soft_dependencies`. Users who aren't familiar with the PEP convention, might find it confusing.
See discussion thread here: [https://discord.com/channels/1075852648688930887/1392760533870051398](https://discord.com/channels/1075852648688930887/1392760533870051398)
=> [DOC] Note about package names in `_check_soft_dependencies`

sktime/forecasting/base/_base.py
Currently, `BaseForecaster.predict_proba` will raise an exception if `skpro` is not present, and the `_predict_proba` is not the default.
The intention of this is to give users feedback about requiring `skpro` for non-default implementations of `predict_proba`.
However, this condition is too strict, as some `predict_proba` implementations, including the default, do not require `skpro`.
Important cases which raise exceptions but would not need to are composites where `predict_proba` is simply looped through.
This PR ensures that an exception is raised only if the `_predict_proba` call causes an exception, under the current exception condition, and if we additionally (new) encounter an `ImportError`.
Tested via https://github.com/sktime/sktime/pull/8553
=> [ENH] loosen condition for `skpro` dependency exception in `BaseForecaster.predict_proba`

docs/source/api_reference/transformations.rst
Fixes broken API reference of `ColumnSelect` and missing `IndexSubset` in the "composition" section of the transformers API reference.
=> [DOC] fix broken API reference of `ColumnSelect` and `IndexSubset`

sktime/classification/deep_learning/resnet.py, sktime/tests/_config.py
[ENH] move test skip config from tests._config to estimator tags #8515
This PR implements part of issue https://github.com/sktime/sktime/issues/8515 by migrating ResNetClassifier test skip configurations from the central tests._config.py file to the estimator's own tags.
=> [ENH] Move Test Skip config for `ResNetClassifier`

sktime/forecasting/chronos.py
This PR removes internal broadcasting in `ChronosForecaster` in favour of programmatic broadcasting.
This also fixes the unreported issue of not being able to pass unequal length hierarchical data to the forecaster.
=> [ENH] remove internal broadcasting in `ChronosForecaster` in favour of programmatic broadcasting

sktime/registry/_tags.py
Makes minor improvements to formatting and clarity in `python_dependencies` tag description
=> [DOC] improve formatting and clarity in `python_dependencies` tag description

docs/source/developer_guide/dependencies.rst
This PR adds documentation for handling module-level soft dependency imports in sktime. The existing developer guide explains how to manage soft dependencies within estimators, but does not cover scenarios where optional dependencies need to be imported at the module level.
To address this, I have added a new section titled "Module-level soft dependency imports" under dependencies.rst. It provides clear usage patterns for using _check_soft_dependencies before importing optional modules directly. Example code snippets are included to demonstrate both severity-based checks and conditional imports.
=> &fkiraly [DOC] Add guide for module-level soft dependency imports (#7690)

.github/workflows/test.yml, pyproject.toml
Reduces dependencies in notebook CI to avoid failures in https://github.com/sktime/sktime/pull/8584, or being stuck on very old versions of packages.
Creates a new developer dependency set `notebooks` meant to be comprised of aminimal set of dependencies for running all notebooks.
=> [MNT] separate dependency set for notebooks, reduce dependencies in notebook CI

sktime/registry/_craft.py, sktime/registry/tests/test_craft.py
This PR fixes an unreported bug, namely that the `deps` dependency inspection utility would fail if an estimator in the spec contained a disjunction dependency, for instance, `DartsXGBRegressor`.
This PR fixes the bug by ensuring that disjunctive statements are resolved by picking the first element, to result in one of multiple possible choices for dependencies.
One could add a feature to return a disjunctive dependency, but doing this by default would violate the implicit contract that the return of `deps` results in a list of PEP 440 dependency specifier str (not a disjunction, possibly).
=> [BUG] ensure `deps` dependency inspection is compatible with disjunctions in estimator dependency tags

.github/workflows/test.yml, examples/07_detection_anomaly_changepoints.ipynb, sktime/detection/skchange_aseg/capa.py
updates the notebook CI python version to 3.11.
Also fixes a broken import from newer `skchange` version, by redirecting it to the stable `sktime` import location.
=> [MNT] update notebook CI python version to 3.11

sktime/classification/sklearn/tests/test_all_classifiers.py
This PR broadens the run condition for `sklearn` compatible classifiers in `classification.sklearn` - all are run if anything in the module changes.
This is safer as the module has interdependencies.
=> [ENH] ensure that any change in `classification.sklearn` triggers the classification tests

.github/scripts/install_osx_dependencies.sh, .github/workflows/test.yml
This PR aims to update the macos runners in `test_vms` to use `macos-latest` and also updates `install_osx_dependencies.sh` bash script in github to dynamically setup the runner based on Intel or ARM macs
relates to macos fix for global forecasters pr #8331
=> [MNT] Update test_vms to use `macos-latest` in CI and configure osx setup in github scripts to dynamically install dependencies

pyproject.toml
The `temporian` packages looks unmaintained - hence I suggest removing it from the recommended `transformations` depset, to avoid indirect bounds on packages arising from it.
Link to repo: https://github.com/google/temporian
The estimator can be tested in a separate environment once the respective PR is merged.
=> [MNT] remove unmaintained (?) package `temporian` from recommended `transformations` depset

sktime/performance_metrics/forecasting/_common.py, sktime/performance_metrics/forecasting/_functions.py, sktime/performance_metrics/forecasting/_mape.py, sktime/performance_metrics/forecasting/_mse.py
Changes the `MeanAbsolutePercentageError` parent to `BaseForecastingErrorMetric`, from `BaseForecastingErrorMetricFunc`.
Since MAPE is a mean loss, the default `_evaluate` will do the same as the function imported.
As part of this:
* refactors by moving common internal functions `_percentage_error` and `_relative_error` to a `_common` module.
* exposes `relative_to` and `eps` as parameters in the metric
This is an architectural improvement since it makes the class self contained, and avoids dependence on the external function.
Also deduplicates multioutput handling in MAPE and MSE.
=> [ENH] change `MeanAbsolutePercentageError` parent to `BaseForecastingErrorMetric`

docs/source/get_involved/governance.rst
This PR fixes some broken links on the "decision making" page:
* link to all-contributors specification (the .org URL is no longer extant)
* link to the estimator implementation guide
=> [DOC] fix some broken links on the "decision making" page

.github/workflows/test.yml
This PR reorders CI steps to minimize expected runtime, by moving quick steps ahead to gate slow or long running steps.
Important changes:
* notebook runs are now gated behind a new step `detect-notebooks-change`
* `test-nosoftdeps` is gated behind `test-devdeps`
* `detect-changed-classes` is gated behind `detect-package-change`
=> [MNT] reorder CI steps to minimize expected runtime

sktime/forecasting/compose/_reduce.py, sktime/forecasting/compose/tests/test_reduce.py
Fixes #8601 
Makes it so that the created frequencies will always be created at the start of the frequency instead of at the end. 
No
Yes. Functionally identical to the "test_recursive_reduction_with_X" in the test_reduce file, but the data has a PeriodIndex with frequency "2M" instead of being numbered. 
- [ x ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get …
=> [BUG] RRF sometimes creates the wrong PeriodIndex when the frequency is higher than 1

docs/source/api_reference/tags.rst, sktime/registry/_tags.py
Documents the forecasting metrics tags and adds them to the tags API.
=> [DOC] document metric tags in the tags API

.all-contributorsrc, sktime/classification/deep_learning/cntc.py, sktime/tests/_config.py
Fixes #8659 
This change fixes a problem, which occurred when you've provided CNTC with callbacks arguments.
Should I add a test? If so where? There doesn't seem to be any tests for cntc.py.
See here for [full badge reference](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)
See here for further details on the [algorithm …
=> [BUG] CNTCClassifier throws error when you provide callbacks.

sktime/classification/deep_learning/fcn.py, sktime/tests/_config.py
Moved the skip test configuration for FCNClassifier to the estimator's _tags as for issue 8515.
- Removed FCNClassifier from `EXCLUDED_TESTS` in `_config.py`
- Added `tests:skip_by_name` tag in `FCNClassifier` class
Towards #8515
See here for [full badge reference](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)
See here for …
=> [ENH]  Move FCNClassifier test skip rule to estimator tag

sktime/utils/tests/test_parallelize.py
Fixes #8619 
I have implemented a test for `parallelize` where I am running a simple for loop and checking if the results are as expected and ensuring that `backend_params` is not being mutated.
No, it does not.
=> [ENH] tests for `parallelize` backend abstraction utility

sktime/forecasting/chronos.py, sktime/forecasting/naive/_naive.py, sktime/forecasting/residual_booster.py
Closes #8581 
This PR implements a new wrapper forecaster, `ResidualBoostingForecaster`, which enables exogenous variable support for forecasters that do not natively handle exogenous inputs (`X`).
It works by combining:
- A base forecaster, trained on the target series alone, and
- A residual forecaster, trained to predict and correct the base model’s residuals using exogenous features.
This reduction approach mirrors the residual modeling trick used in AutoGluon Chronos-Bolt for enabling exogenous support, and makes it easy to augment univariate forecasters without changing their internals.
- Correctness and clarity of the core `_fit` and `_predict` implementation
- Whether the wrapper logic properly handles in-sample residual computation
- Adherence to sktime's style and testing …
=> [ENH] Residual Booster Forecaster

docs/source/api_reference/forecasting.rst, sktime/tests/test_all_estimators.py
Adds the `ResidualBoostingForecaster` from https://github.com/sktime/sktime/pull/8582 to the API reference.
=> [DOC] add `ResidualBoostingForecaster` to the API reference

.github/workflows/test.yml
Small change to update macos-runners in `test-full` to use `macos-latest` @fkiraly
=> [MNT] Upgrade CI to set `test-full` to use `macos-latest` runners

.github/workflows/test.yml
Partially reverts https://github.com/sktime/sktime/pull/7715 for `test-cython-estimators` job, since this apparently prevents `mysqm` from building.
=> [MNT] partial revert of #7715 for `test-cython-estimators` job.

pyproject.toml, sktime/classification/feature_based/_signature_classifier.py, sktime/classification/tests/_classification_test_reproduction.py, sktime/tests/_config.py, sktime/tests/test_softdeps.py, sktime/transformations/panel/signature_based/_compute.py, sktime/transformations/panel/signature_based/_signature_method.py
The `esig` package is sporadically maintained and currently pinned in soft dependency sets, which restricts versions and may cause future degradation.
This PR removes these dependencies and adds the `"tests:vm"` tag to `esig` based estimators.
Also contains minor changes:
* second test parameter sets for aforementioned estimators
* fills `"tests:libs"` tag with correct internal dependencies
* widens bounds for `esig` based estimtors due to release of 1.0.0
=> [ENH] remove `esig` soft dependency and move `esig` based estimators to own test VM

docs/source/api_reference/split.rst, sktime/forecasting/model_evaluation/_functions.py, sktime/split/__init__.py, sktime/split/base/_common.py, sktime/split/fh.py, sktime/split/temporal_train_test_split.py, sktime/split/tests/test_temporaltraintest.py
Adds a `ForecastingHorizon` based splitter, similar to the behaviour of `temporal_train_test_split` if `fh` is passed.
Also makes `temporal_train_test_split` to point to that splitter instead of the legacy function `_split_by_fh`, which is removed.
This also fixes https://github.com/sktime/sktime/issues/8700 and fixes https://github.com/sktime/sktime/issues/4968
=> [ENH] `ForecastingHorizon` based splitter

README.md, docs/source/api_reference/tags.rst, sktime/registry/_tags.py
Minor fixes to documentation:
* correct python versions in README
* correct tag documentation
* add reference higher up to `all_estimators` in tag API reference
=> [DOC] minor fixes to documentation

sktime/classification/model_evaluation/_functions.py
Fixes an unreported bug where the `backend` and `backend_params` in TSC `evaluate` were being ignored.
FYI @jgyasu
=> [BUG] fix `backend` and `backend_params` in TSC `evaluate` being ignored

sktime/classification/model_evaluation/tests/test_evaluate.py
Fixes #8703
I have modified the test file `classification/model_evaluation/tests/test_evaluate.py` to test all parallelization backends for the classification evaluate function.
1. Imported the `_get_parallel_test_fixtures` utility, which provides a list of available parallel backend configurations.
2. Used this utility to create a `BACKENDS` list containing these configurations.
3. Parameterized the existing `test_evaluate_parallel_backend` test by adding the `@pytest.mark.parametrize("backend", BACKENDS)` decorator.
- Correctness of the Parameterization
- Consistency with Existing Patterns
How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - …
=> [ENH] add tests for TSC `evaluate` parallelization backends 

sktime/forecasting/ttm.py
Fixes #8732 
The current PR aims to resolve the unexpected `dict` object that's printed out during `TinyTimeMixerForecaster`'s doctest, causing `sktime`'s remote CI to fail. The root problem arises from two major factors: 
An unexpected dictionary object that's printed out like so: 
```
{'train_runtime': 0.2049, 'train_samples_per_second': 195.186, 'train_steps_per_second': 48.797, 'train_loss': 19674936.0, 'epoch': 10.0}
```
which is outputted from `transformers`'s Trainer class. 
and a `TinyTimeMixerForecaster` configuration information that looks like so: 
```
TinyTimeMixerForecaster(config={'context_length': 8, 'prediction_length': 2},
fit_strategy='full', model_path=None,
training_args={'max_steps': 10,
'output_dir': 'test_output',
'per_device_train_batch_size': 4,
'report_to': …
```
=> [BUG] suppressing `dict` while running TTM doctest

sktime/utils/dependencies/_safe_import.py, sktime/utils/dependencies/tests/test_safe_import.py
Fixes an unreported bug in `_safe_import` when importing package and `pkg_name` is not `None` - in this case, the import would always result in a mock, because the `importlib` statement was referring to the `pkg_name` and not to `obj_name` which would have been the correct import name.
A test to prevent regression has also been added.
=> [BUG] fix bug in `_safe_import` when importing package and `pkg_name` is not `None`

sktime/forecasting/compose/_reduce.py, sktime/transformations/series/lag.py
fixes the `DirectReductionForecaster` failure on newer `pandas`, arising from attempting to `shift` a regular `pd.DatetimeIndex`.
The fix needs to be applied in the `Lag` transformer, used internally.
=> [BUG] fix `DirectReductionForecaster` failure on newer `pandas`

.github/workflows/test.yml, .github/workflows/test_all.yml, .github/workflows/test_base.yml, .github/workflows/test_datasets.yml, .github/workflows/test_module.yml, .github/workflows/test_other.yml, .github/workflows/wheels.yml, README.md, docs/source/get_started.rst, docs/source/installation.rst, pyproject.toml
Removes 3.9 from supported versions, and changes any CI jobs depending on 3.9 to 3.11.
Should be released with 0.39.0.
=> [MNT] python 3.9 end-of-life

sktime/datatypes/_hierarchical/_base.py, sktime/datatypes/_panel/_base.py, sktime/datatypes/_series/_base.py, sktime/datatypes/_table/_base.py
This PR adds a full documentation of the `Hierarchical` and `Table` object types, and improves the description of other scitypes `Panel` and `Series`.
=> [DOC] better documentation of time series scitypes, full mathematical documentation of `Hierarchical` and `Table` type

sktime/performance_metrics/forecasting/_functions.py, sktime/utils/stats.py
forks `scikit-learn` `_weighted_percentage` to ensure compatibility with newer versions of `scikit-learn`.
The private utility was used in some forecasting metrics, and has a breaking change in a newer `scikit-learn` version..
=> [ENH] `sklearn` compatibility - fork `scikit-learn` `_weighted_percentage`

sktime/datasets/forecasting/hierarchical_sales_toydata.py
fixes the `HierarchicalToyData` dataset `n_instances` tag value, there are 4 time series, so the value should be 4.
=> [BUG] fix `HierarchicalToyData` dataset `n_instances` tag value

sktime/classification/early_classification/tests/test_teaser.py
Recent `numba` versions seem to affect the outputs of the `TEASER` estimator, although only minimally - still, causing failures in the exact output tests (e.g., accuracy from 73% to 70%).
This PR relaxes the conditions on the tests.
=> [ENH] relax tests for `TEASER` estimator

pyproject.toml
removes `python<3.13` bound in some dependency sets for `numba`.
This only removes a restriction in explicit install commands - previously, `sktime` could already be installed with `numba`, but the tests for `numba` did not run on `python 3.13`.
=> [MNT] remove `python<3.13` bound in some dependency sets for `numba`

sktime/tests/test_all_estimators.py
There have been a few cases where signatures of placeholder records have diverged from upstream packages due to changes in the upstream package, see for example discussion in https://github.com/sktime/sktime/pull/8792.
This PR adds a test that checks placeholder against upstream signature, to avoid this situation in the future - or at least become alerted to it.
=> [ENH] test for consistency of placeholder record signatures

sktime/base/_base.py, sktime/base/tests/test_tagaliaser.py
For 0.39.0, makes fixes in tag deprecation logic, to behave as follows. Assume a setting where `"old_tag"` is renamed to `"new_tag"`.
If `"new_tag"` is queried and `"old_tag"` is set, retrieves `"old_tag"`. This is to not break third party estimators that set `"old_tag"`.
If `"new_tag"` is queried and `"old_tag"` is not set, retrieves `"new_tag"`.
If `"old_tag"` is queried and `"old_tag"` is not set, and `"new_tag"` is set, retrieves `"new_tag"`. Also raises a warning, since this is a case where the user queries the tag.
If `"old_tag"` is queried and `"old_tag"` is set, retrieves `"old_tag"`, and also raises a warning.
Previously, `"new_tag"` would be retrieved it `"new_tag"` was present - this would break estimators that still had only `"old_tag"` set, but not `"new_tag"`. With the …
=> [ENH] fixes to tag deprecation logic

extension_templates/alignment.py, extension_templates/classification.py, extension_templates/detection.py, extension_templates/dist_kern_panel.py, extension_templates/dist_kern_tab.py, extension_templates/early_classification.py, extension_templates/split.py, sktime/base/_base.py, sktime/forecasting/greykite.py, sktime/forecasting/hf_momentfm_forecaster.py, sktime/forecasting/patch_tst.py, sktime/tests/test_all_estimators.py, sktime/transformations/hierarchical/squeeze_hierarchy.py
In order to help third party extension developers, this PR adds a clause to the "valid tags" tests that checks if deprecated tags are being used.
While https://github.com/sktime/sktime/pull/8845 ensures that estimators continue working, for users of third party estimation developers, this PR ensures that conformance tests start failing with a useful error message.
Also makes the following changes:
* fixes `TagAliaserMixin.set_tags` logic which was faulty
* changes some deprecated tag to post-deprecation tags that were missed
=> [ENH] tag deprecation test extension to warn third party developers of deprecated tags

.github/workflows/test.yml
Fixes #8912
`set-output` is deprecated.
Fixed by following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
No
No
See here for [full badge reference](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md) …
=> [MNT] fix `set-output` deprecation in github-actions

.github/actions/test-component/action.yml, .github/workflows/test.yml, .github/workflows/test_datasets.yml
Makes two changes to the CI tests:
* redirects the `matplotplib` backend on windows to silent
* adding prints for the python dependencies in jobs where this was still missing
=> [MNT] in tests, set `matplotlib` silent backend and print python deps

sktime/classification/dictionary_based/_boss.py, sktime/tests/_config.py
#3429
Adds "feature_selection" = "chi2" to first test parameter creating a second one
No
That parameter makes sense 
No
No
=> [ENH] `BOSSEnsemble` second set of test parameters
